package com.samlscope.runner.cases;

import static org.junit.jupiter.api.Assertions.*;
import com.samlscope.core.plan.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.metadata.MetadataService;
import com.samlscope.saml.normal.*;
import java.net.URI;
import java.nio.file.Path;
import java.security.cert.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.w3c.dom.Element;

class MetadataCertificateRuntimeEvidenceTest {
    @TempDir Path data;
    private static final String RUN="run_0123456789ABCDEFGHJKMNPQRS",PLAN="plan_0123456789ABCDEFGHJKMNPQRS",DS="http://www.w3.org/2000/09/xmldsig#",REV="urn:samlscope:test:certificate-revocation";
    @Test void approvedCertificateConditionsRequireActualCriticalIssuerAndSignedRevocationOriginals()throws Exception {
        for(var token:List.of("control","certificate-critical-extension","certificate-unknown-ca","certificate-revoked")){
            var peer=fixture(token);var certificate=certificate(peer);assertDoesNotThrow(()->MetadataCertificateRuntimeEvidence.validateCondition(data,token,peer,certificate));
            if(token.equals("certificate-revoked")){
                var crl=(Element)peer.getElementsByTagNameNS(REV,"CRL").item(0);byte[] raw=Base64.getMimeDecoder().decode(crl.getTextContent());raw[raw.length-1]^=1;crl.setTextContent(Base64.getEncoder().encodeToString(raw));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateCondition(data,token,peer,certificate));
            }
        }
        var normal=fixture("control");var certificate=certificate(normal);assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateCondition(data,"certificate-critical-extension",normal,certificate));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateCondition(data,"certificate-unknown-ca",normal,certificate));
    }
    @Test void unreachableRequiresBothActualCrlAndOcspExtensionsAndNativeNetworkOriginals()throws Exception {
        var peer=fixture("certificate-revocation-unreachable");var c=certificate(peer);var crl=MetadataCertificateRuntimeEvidence.extensionUris(c.getExtensionValue("2.5.29.31"));var ocsp=MetadataCertificateRuntimeEvidence.extensionUris(c.getExtensionValue("1.3.6.1.5.5.7.1.1"));assertEquals(1,crl.size());assertEquals(1,ocsp.size());assertTrue(crl.iterator().next().endsWith("/unavailable.crl"));assertTrue(ocsp.iterator().next().endsWith("/unavailable.ocsp"));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateCondition(data,"certificate-revocation-unreachable",peer,c));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.extensionUris(new byte[]{4,10,0}));
    }
    @Test void validSignedButDifferentAuthenticationSemanticsCannotBecomeCertificateViolation()throws Exception {
        var clock=Clock.fixed(Instant.parse("2026-10-02T00:00:00Z"),ZoneOffset.UTC);var key=new FilePlanKeyStore(data.resolve("other-keys"),clock).getOrCreate(PLAN);var destination=URI.create("http://target.example/sso");var acs=URI.create("http://suite.example/acs");String fixture="control-normal",entity="http://suite.example/p/"+PLAN,action=com.samlscope.core.caseexec.ActionIds.derive(RUN,MetadataCertificateRuntimeProbeTestCase.CASE,"await-fixture-"+fixture,0);var raw=new SamlSignedRequestFactory().build(SamlSignedRequestFactory.Fixture.VALID,"_"+action,destination,entity,acs,clock.instant(),key);assertDoesNotThrow(()->MetadataCertificateRuntimeEvidence.validateRequestBytes(RUN,fixture,raw,destination,entity,acs,key));
        for(var attribute:List.of("ForceAuthn","IsPassive")){var document=SecureXml.parse(raw);var request=document.getDocumentElement();var signature=request.getElementsByTagNameNS(DS,"Signature").item(0);request.removeChild(signature);request.setAttribute(attribute,"1");new XmlSigner().sign(request,key,(Element)request.getElementsByTagNameNS("urn:oasis:names:tc:SAML:2.0:protocol","NameIDPolicy").item(0));assertTrue(new XmlSignatureVerifier().hasValidEnvelopedSignature(request,key.certificate()));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateRequestBytes(RUN,fixture,SecureXml.serialize(document),destination,entity,acs,key));}
        var changed=new SamlSignedRequestFactory().build(SamlSignedRequestFactory.Fixture.VALID,"_other-action",destination,entity,acs,clock.instant(),key);assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.validateRequestBytes(RUN,fixture,changed,destination,entity,acs,key));
    }
    @Test void certificateRefusalRequiresNativePkixCauseOriginalBoundToSameRequestAndCertificate()throws Exception {
        data=data.toRealPath(); // @TempDir may use macOS /var; production requires canonical non-symlink parents.
        var cert=certificate(fixture("certificate-unknown-ca"));var factory=CertificateFactory.getInstance("X.509");var parameters=new PKIXParameters(Set.of(new TrustAnchor(certificate(fixture("control")),null)));parameters.setRevocationEnabled(false);
        var failure=assertThrows(CertPathValidatorException.class,()->CertPathValidator.getInstance("PKIX").validate(factory.generateCertPath(List.of(cert)),parameters));assertEquals(PKIXReason.NO_TRUST_ANCHOR,failure.getReason());
        byte[] request="signed request original validated by outer reader".getBytes(java.nio.charset.StandardCharsets.UTF_8);String requestId="_native",target="0".repeat(64),digest=hash(cert.getEncoded());var begin=Instant.parse("2026-10-02T00:00:00Z");var end=begin.plusSeconds(1);var writer=new java.io.StringWriter();writer.append("request_id="+requestId+"\nrequest_sha256="+hash(request)+"\ncertificate_sha256="+digest+"\nreason=NO_TRUST_ANCHOR\n");failure.printStackTrace(new java.io.PrintWriter(writer));byte[] trace=writer.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);java.nio.file.Files.write(data.resolve("native-exception.txt"),trace);
        var codec=new com.samlscope.store.JsonCodec();var cause=codec.mapper().createObjectNode();cause.put("schema","samlscope-native-certpath-operation-failure-v1").put("source","native-selected-pkix-trust-engine").put("algorithm","PKIX").put("trustEngineBean","shibboleth.PKIXSignatureTrustEngine").put("runId",RUN).put("targetMetadataSha256",target).put("requestId",requestId).put("requestSha256",hash(request)).put("certificateSha256",digest).put("nativeTimestamp",begin.toString()).put("exceptionClass",failure.getClass().getName()).put("reason","NO_TRUST_ANCHOR").put("exceptionTraceFile","native-exception.txt").put("exceptionTraceSha256",hash(trace));
        var exchange=codec.mapper().createObjectNode().put("certificateCheckFailureFile","cause.json");java.nio.file.Files.write(data.resolve("cause.json"),codec.mapper().writeValueAsBytes(cause));assertTrue(MetadataCertificateRuntimeEvidence.nativeCertificateCause(data,exchange,"certificate-unknown-ca","shibboleth.PKIXSignatureTrustEngine",RUN,target,requestId,request,cert,begin,end));
        assertFalse(MetadataCertificateRuntimeEvidence.nativeCertificateCause(data,exchange,"certificate-unknown-ca","shibboleth.ExplicitKeySignatureTrustEngine",RUN,target,requestId,request,cert,begin,end));assertFalse(MetadataCertificateRuntimeEvidence.nativeCertificateCause(data,codec.mapper().createObjectNode(),"certificate-unknown-ca","shibboleth.PKIXSignatureTrustEngine",RUN,target,requestId,request,cert,begin,end));
        for(var field:List.of("requestId","certificateSha256","exceptionTraceSha256","reason")){var changed=cause.deepCopy();changed.put(field,"forged");java.nio.file.Files.write(data.resolve("cause.json"),codec.mapper().writeValueAsBytes(changed));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.nativeCertificateCause(data,exchange,"certificate-unknown-ca","shibboleth.PKIXSignatureTrustEngine",RUN,target,requestId,request,cert,begin,end));}
        // A declared reason plus matching hash is insufficient without a real native exception stack.
        byte[] fake=("request_id="+requestId+"\nrequest_sha256="+hash(request)+"\ncertificate_sha256="+digest+"\nreason=NO_TRUST_ANCHOR\n").getBytes(java.nio.charset.StandardCharsets.UTF_8);java.nio.file.Files.write(data.resolve("native-exception.txt"),fake);cause.put("exceptionTraceSha256",hash(fake));java.nio.file.Files.write(data.resolve("cause.json"),codec.mapper().writeValueAsBytes(cause));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.nativeCertificateCause(data,exchange,"certificate-unknown-ca","shibboleth.PKIXSignatureTrustEngine",RUN,target,requestId,request,cert,begin,end));
    }
    @Test void redactedRuntimeRequiresImmutableContainerMountOriginalForTheExactEpochIdentity()throws Exception{
        data=data.toRealPath();var codec=new com.samlscope.store.JsonCodec();String image="sha256:3c1b1fa64c58258aefc9e38d4ae60e9f0340731318a472110ea56ce88c18a11a";var snapshot=codec.mapper().createObjectNode().put("Id","native-container").put("Image",image);snapshot.putObject("Config");snapshot.putObject("State").put("Running",true).put("StartedAt","2026-10-02T00:00:00Z");java.nio.file.Files.write(data.resolve("native-start.json"),codec.mapper().writeValueAsBytes(codec.mapper().createArrayNode().add(snapshot)));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.runtime(data,"native-start.json"));
        var nativeRaw=codec.mapper().createObjectNode().put("Id","native-container").put("Image",image);nativeRaw.putArray("Mounts");byte[] bytes=codec.mapper().writeValueAsBytes(nativeRaw);java.nio.file.Files.write(data.resolve("mounts.json"),bytes);var capture=codec.mapper().createObjectNode().put("schema","samlscope-immutable-container-mounts-capture-v1").put("source","native-docker-inspect-readback").put("hostStartedAt","2026-10-02T00:00:01Z").put("hostCompletedAt","2026-10-02T00:00:02Z").put("originalFile","mounts.json").put("originalSha256",hash(bytes)).put("productConfigurationWrites",0).put("protocolSubmissions",0).put("credentialPosts",0);capture.putArray("command").add("docker").add("inspect").add("--format").add("{\"Id\":{{json .Id}},\"Image\":{{json .Image}},\"Mounts\":{{json .Mounts}}}").add("samlscope-reference-shibboleth");java.nio.file.Files.write(data.resolve("target-container-mounts-capture.json"),codec.mapper().writeValueAsBytes(capture));assertEquals("native-container|"+image+"|2026-10-02T00:00:00Z",MetadataCertificateRuntimeEvidence.runtime(data,"native-start.json"));
        for(var field:List.of("Id","Image","Mounts")){var changed=nativeRaw.deepCopy();if(field.equals("Mounts"))changed.withArray("Mounts").addObject().put("Type","bind");else changed.put(field,"other");var altered=codec.mapper().writeValueAsBytes(changed);java.nio.file.Files.write(data.resolve("mounts.json"),altered);capture.put("originalSha256",hash(altered));java.nio.file.Files.write(data.resolve("target-container-mounts-capture.json"),codec.mapper().writeValueAsBytes(capture));assertThrows(Exception.class,()->MetadataCertificateRuntimeEvidence.runtime(data,"native-start.json"));}
    }
    private static String hash(byte[] raw)throws Exception{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(raw));}
    private Element fixture(String token){var clock=Clock.fixed(Instant.parse("2026-10-02T00:00:00Z"),ZoneOffset.UTC);var keys=new FilePlanKeyStore(data.resolve("keys"),clock);var plan=new TestPlan(PLAN,"certificate",com.samlscope.core.profile.FunctionalProfile.METADATA_IDP,new TestPlan.Target(TargetKind.IDP,"http://target.example/idp",new TestPlan.MetadataSource(MetadataSourceKind.URL,"http://target.example/metadata")),MetadataDeliveryKind.HTTP_URL,Map.of(),new TestPlan.Parameters(180,30,"reference",TestPlan.RequestSigningMode.REQUIRED),TestPlan.Interaction.defaults(),clock.instant(),clock.instant());return SecureXml.parse(new MetadataService(URI.create("http://suite.example"),keys,new XmlSigner(),clock).generatePolling(plan,MetadataService.Variant.parse(token),RUN)).getDocumentElement();}
    private X509Certificate certificate(Element peer)throws Exception{return (X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(((Element)peer.getElementsByTagNameNS("urn:oasis:names:tc:SAML:2.0:metadata","SPSSODescriptor").item(0)).getElementsByTagNameNS(DS,"X509Certificate").item(0).getTextContent())));}
}
