package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.runner.DefaultCaseContext;
import com.samlscope.core.evaluation.Outcome;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.time.Clock;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

class ShibbolethSelfContainedTrustEvidenceFileTest {
    @TempDir Path temp;
    private static final String RUN="run_4RK6H7SCP540PGAAVVPRPP5YKZ";
    private ObjectNode path(boolean calibration){return new JsonCodec().mapper().createObjectNode().put("selectedPath",calibration?"developer-instrumented-additional-anchor":"stock-native-signature-encryption").put("counterfactualCalibrationOnly",calibration);}
    private ObjectNode nativeControl(){return new JsonCodec().mapper().createObjectNode().put("stockNativeSignatureAccepted",true).put("stockAdditionalTrustInputSupplied",false).put("emptyExternalAnchorsAccepted",false).put("samePublicAnchorSuppliedAccepted",true).put("otherPublicAnchorSuppliedAccepted",false);}
    @Test void nativeExtraAnchorControlCannotBecomeProductFindingByReceipt(){assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateSelectedPath(path(true),false));assertTrue(ShibbolethSelfContainedTrustEvidenceFile.validateSelectedPath(path(true),true));assertFalse(ShibbolethSelfContainedTrustEvidenceFile.validateSelectedPath(path(false),false));}
    @Test void calibrationFlagMustMatchConsumerPath(){var n=path(false).put("counterfactualCalibrationOnly",true);assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateSelectedPath(n,true));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateSelectedPath(path(false).put("selectedPath","unknown"),true));}
    @Test void samePublicAnchorPositiveAndOtherPeerNegativeAreBothRequired(){ShibbolethSelfContainedTrustEvidenceFile.validateNativeControl(nativeControl());for(String field:List.of("samePublicAnchorSuppliedAccepted","stockNativeSignatureAccepted"))assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateNativeControl(nativeControl().put(field,false)));for(String field:List.of("emptyExternalAnchorsAccepted","otherPublicAnchorSuppliedAccepted","stockAdditionalTrustInputSupplied"))assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateNativeControl(nativeControl().put(field,true)));}
    @Test void bareBooleanStringsNeverSubstituteNativeControl(){for(String field:List.of("stockNativeSignatureAccepted","samePublicAnchorSuppliedAccepted","otherPublicAnchorSuppliedAccepted"))assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateNativeControl(nativeControl().put(field,"true")));}
    @Test void failedOrUnremovedNativeDiagnosticCannotQualify(){var n=new JsonCodec().mapper().createObjectNode().put("nativeCompilerCalls",1).put("nativePublicJavaCalls",2).put("temporarySourceRemoved",true);for(String k:List.of("productSettings","protocol","credentialPosts","productRestarts","personOperations"))n.put(k,0);ShibbolethSelfContainedTrustEvidenceFile.validateCosts(n);assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateCosts(n.deepCopy().put("temporarySourceRemoved",false)));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateCosts(n.deepCopy().put("credentialPosts",1)));}
    @Test void partialSidecarOwnsReceiptAndFailsClosed()throws Exception{var leaf=leaf();Files.createDirectories(temp.resolve(RUN+".shibboleth-trust"));assertTrue(leaf.exists(RUN));assertEquals(Outcome.NOT_VERIFIED,leaf.evaluate(context()).outcome());}
    @Test void symlinkOwnedReceiptIsNeverRead()throws Exception{Path publicFile=temp.resolve("public.json");Files.writeString(publicFile,"{}");Files.createSymbolicLink(temp.resolve(RUN+".shibboleth-trust.json"),publicFile);var leaf=leaf();assertTrue(leaf.exists(RUN));assertEquals(Outcome.NOT_VERIFIED,leaf.evaluate(context()).outcome());}
    @Test void malformedDirectoryReceiptDoesNotEnableObserverFallback()throws Exception{Files.createDirectory(temp.resolve(RUN+".shibboleth-trust.json"));var leaf=leaf();assertTrue(leaf.exists(RUN));assertEquals(Outcome.NOT_VERIFIED,leaf.evaluate(context()).outcome());assertFalse(leaf.exists("../../outside"));}
    @Test void nativeScopeMustBracketActualHttpWithinItsOwnEpoch(){var m=new JsonCodec().mapper();var epoch=m.createObjectNode().put("startedAt","2026-10-03T09:00:00Z").put("completedAt","2026-10-03T09:01:00Z");epoch.putArray("exchanges").addObject().putArray("nativeHttp").addObject().put("startedAt","2026-10-03T09:00:20Z").put("completedAt","2026-10-03T09:00:40Z");var before=m.createObjectNode().put("recordedAt","2026-10-03T09:00:10Z");var after=m.createObjectNode().put("recordedAt","2026-10-03T09:00:50Z");ShibbolethSelfContainedTrustEvidenceFile.validateScopeWindow(before,epoch,"before");ShibbolethSelfContainedTrustEvidenceFile.validateScopeWindow(after,epoch,"after");assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateScopeWindow(before.deepCopy().put("recordedAt","2026-10-03T09:00:30Z"),epoch,"before"));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateScopeWindow(after.deepCopy().put("recordedAt","2026-10-03T09:00:30Z"),epoch,"after"));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateScopeWindow(before.deepCopy().put("recordedAt","2026-10-03T08:59:59Z"),epoch,"before"));}
    @Test void changedNativeTrustSelectionOrAdditionalPropertySourceDoesNotQualify(){var n=new JsonCodec().mapper().createObjectNode().put("idp.trust.signatures","shibboleth.ExplicitKeySignatureTrustEngine");ShibbolethSelfContainedTrustEvidenceFile.validateSelectedProperties(n);for(var mutant:List.of(n.deepCopy().put("idp.trust.signatures","shibboleth.PKIXSignatureTrustEngine"),n.deepCopy().put("idp.additionalProperties","/unknown.properties"),n.deepCopy().put("idp.service.relyingparty.resources","/custom.xml")))assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateSelectedProperties(mutant));}
    @Test void auditRestorationAllowsOnlyRecordedRestartOfSameNativeIdentity(){var m=new JsonCodec().mapper();var start=m.createObjectNode().put("id","native-id").put("image","native-image").put("running",true).put("startedAt","2026-10-03T09:00:00Z");start.putArray("mounts").addObject().put("Destination","/opt/reference-idp").put("Source","/public/reference");ShibbolethSelfContainedTrustEvidenceFile.validateRuntimeIdentity(start,start,start,false);var restored=start.deepCopy().put("startedAt","2026-10-03T09:10:00Z");ShibbolethSelfContainedTrustEvidenceFile.validateRuntimeIdentity(start,start,restored,true);assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateRuntimeIdentity(start,start,restored,false));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateRuntimeIdentity(start,start,restored.deepCopy().put("image","other"),true));assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateRuntimeIdentity(start,restored,restored,true));}
    @Test void roleAndTrustBundlesMustDescribeTheSameNativeEpoch(){var m=new JsonCodec().mapper();var trust=m.createObjectNode().put("id","native-id").put("image","native-image").put("running",true).put("startedAt","2026-10-03T09:00:00Z");var role=m.createArrayNode();var nativeRuntime=role.addObject().put("Id","native-id").put("Image","native-image");nativeRuntime.putObject("State").put("Running",true).put("StartedAt","2026-10-03T09:00:00Z");ShibbolethSelfContainedTrustEvidenceFile.validateRoleRuntime(trust,role);for(String key:List.of("id","image","startedAt")){var changed=trust.deepCopy().put(key,key.equals("startedAt")?"2026-10-03T08:00:00Z":"foreign");assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateRoleRuntime(changed,role));}assertThrows(IllegalArgumentException.class,()->ShibbolethSelfContainedTrustEvidenceFile.validateRoleRuntime(trust.deepCopy().put("running",false),role));}
    private ShibbolethSelfContainedTrustEvidenceFile leaf(){return new ShibbolethSelfContainedTrustEvidenceFile(temp,temp.resolve("signer"),e->{throw new AssertionError("malformed proof must not request content");},r->{throw new AssertionError("malformed proof must not read metadata");},(r,v)->{throw new AssertionError("malformed proof must not read keys");});}
    private DefaultCaseContext context(){var transcript=new TranscriptRecorder(){public List<TranscriptEntry>list(String r){return List.of();}public TranscriptEntry record(TranscriptInput i){throw new AssertionError("no send");}public TranscriptEntry updateSamlAnalysis(String r,String i,Map<String,Object>s){throw new AssertionError("no mutation");}};return new DefaultCaseContext(RUN,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,transcript,true);}
}
