package com.samlscope.runner.cases;

import static org.junit.jupiter.api.Assertions.*;
import com.samlscope.core.evaluation.Outcome;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.w3c.dom.Element;

/** Signed real SOAP objects, not status labels, establish the participant failure. */
class ShibbolethNativeSloContinuationEvidenceTest {
    static final String RUN="run_00000000000000000000000000",PLAN="plan_00000000000000000000000000",ENTITY="http://localhost:18080/p/"+PLAN,
        TARGET="http://localhost:18280/idp/shibboleth",P="urn:oasis:names:tc:SAML:2.0:protocol",A="urn:oasis:names:tc:SAML:2.0:assertion",
        SOAP="http://schemas.xmlsoap.org/soap/envelope/",SUCCESS="urn:oasis:names:tc:SAML:2.0:status:Success",RESPONDER="urn:oasis:names:tc:SAML:2.0:status:Responder",
        PREP="tx_00000000000000000000000000",SHA="a".repeat(64);
    static final Instant NOW=Instant.parse("2026-10-03T21:00:00Z");
    @TempDir Path directory;
    private PlanCredentials suite,target;
    private int next;
    private void keys(){if(suite==null){var clock=Clock.fixed(NOW,ZoneOffset.UTC);suite=new FilePlanKeyStore(directory.resolve("suite"),clock).getOrCreate(PLAN);target=new FilePlanKeyStore(directory.resolve("target"),clock).getOrCreate(PLAN);}}
    private ShibbolethNativeSloContinuationEvidence.SoapMessage message(String type,String id,String responseTo,String issuer,String dest,String status,int seconds,Direction direction,String trial,String label){
        keys();var d=SecureXml.newDocument();var root=d.createElementNS(P,"samlp:"+type);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:samlp",P);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:saml",A);
        root.setAttribute("ID",id);root.setAttribute("Version","2.0");root.setAttribute("IssueInstant",NOW.plusSeconds(seconds).toString());if(!dest.isBlank())root.setAttribute("Destination",dest);if(responseTo!=null)root.setAttribute("InResponseTo",responseTo);d.appendChild(root);
        var is=d.createElementNS(A,"saml:Issuer");is.setTextContent(issuer);root.appendChild(is);
        if("LogoutResponse".equals(type)){var s=d.createElementNS(P,"samlp:Status");var code=d.createElementNS(P,"samlp:StatusCode");code.setAttribute("Value",status);s.appendChild(code);root.appendChild(s);}
        else{var n=d.createElementNS(A,"saml:NameID");n.setTextContent("public-test-principal");root.appendChild(n);var i=d.createElementNS(P,"samlp:SessionIndex");i.setTextContent("public-test-session");root.appendChild(i);}
        new XmlSigner().sign(root,issuer.equals(TARGET)?target:suite,(Element)root.getFirstChild().getNextSibling());
        byte[] decoded=SecureXml.serialize(d);var envelope=SecureXml.newDocument();var e=envelope.createElementNS(SOAP,"soap:Envelope");e.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:soap",SOAP);envelope.appendChild(e);var b=envelope.createElementNS(SOAP,"soap:Body");e.appendChild(b);b.appendChild(envelope.importNode(root,true));byte[] raw=SecureXml.serialize(envelope);
        var summary=new LinkedHashMap<String,Object>();summary.put("type",type);summary.put("transport","SOAP");
        if(label!=null){summary.put("propagationFixture","error-v2");summary.put("propagationMode","failure".equals(trial)?"first-arrival":"all-success");summary.put("propagationOrdinal",seconds/2);summary.put("propagationTrial",trial);summary.put("propagationParticipant",label);summary.put("preparedMetadataRef",PREP);summary.put("preparedMetadataSha256",SHA);
            if("LogoutResponse".equals(type)){summary.put("producerBoundary","soapResponse-return");summary.put("responseStatus",status);}}
        else if(direction==Direction.OUTBOUND){summary.remove("transport");summary.put("kind","LOGOUT_PROBE");summary.put("probe_transport","direct-soap");summary.put("action_id",id.substring(1));}
        String url=dest,correlation=responseTo;if(label==null&&direction==Direction.OUTBOUND)correlation=id.substring(1);
        if(label==null&&direction==Direction.INBOUND){summary.remove("transport");summary.put("type","SloProbeHttpResponse");summary.put("probe_transport","direct-soap");summary.put("saml_message","LogoutResponse");correlation=responseTo.substring(1);url="http://localhost:18280/idp/profile/SAML2/SOAP/SLO";}
        String tx="tx_"+String.format("%026d",++next);var entry=new TranscriptEntry(tx,RUN,direction,NOW.plusSeconds(seconds),correlation,"POST",url,"LogoutResponse".equals(type)?200:null,Map.of(),"transcripts/"+RUN+"/"+tx+".body",raw.length,"transcripts/"+RUN+"/"+tx+".saml.xml",decoded.length,"text/xml",java.net.URI.create(url).getRawQuery(),summary);
        return ShibbolethNativeSloContinuationEvidence.message(entry,decoded,raw,RUN);
    }
    private String endpoint(String label,String trial){return ENTITY+"/sp/slo/soap?run="+RUN+"&propagation=error-v2&participant="+label+"&trial="+trial+"&mode="+("failure".equals(trial)?"first-arrival":"all-success");}
    private Map<String,Element> peers(String trial){keys();var p=new LinkedHashMap<String,Element>();for(var label:List.of("primary","fail","remain","remain2")){
        String url="primary".equals(label)?ENTITY+"/sp/slo/soap":endpoint(label,trial);
        String xml="<md:EntityDescriptor xmlns:md='urn:oasis:names:tc:SAML:2.0:metadata' entityID='"+ENTITY+(label.equals("primary")?"":"/sp-"+label)+"'><md:SPSSODescriptor><md:SingleLogoutService Binding='urn:oasis:names:tc:SAML:2.0:bindings:SOAP' Location='"+url.replace("&","&amp;")+"'/></md:SPSSODescriptor></md:EntityDescriptor>";
        p.put(label,SecureXml.parse(xml.getBytes(StandardCharsets.UTF_8)).getDocumentElement());}return p;}
    private record Fixture(String trial,Map<String,Element> peers,ShibbolethNativeSloContinuationEvidence.SoapMessage origin,ShibbolethNativeSloContinuationEvidence.SoapMessage result,List<ShibbolethNativeSloContinuationEvidence.Participant> participants){}
    private Fixture fixture(String trial){return fixture(trial,List.of("fail","remain","remain2"));}
    private Fixture fixture(String trial,List<String> order){keys();String originId="_"+ShibbolethNativeSloContinuationEvidence.originActionId(RUN,trial);var origin=message("LogoutRequest",originId,null,ENTITY,"http://localhost:18280/idp/profile/SAML2/SOAP/SLO",null,1,Direction.OUTBOUND,trial,null);
        var rows=new ArrayList<ShibbolethNativeSloContinuationEvidence.Participant>();int sec=2;
        for(var label:order){var q=message("LogoutRequest","_q_"+label,null,TARGET,endpoint(label,trial),null,sec++,Direction.INBOUND,trial,label);
            var a=message("LogoutResponse","_a_"+label,"_q_"+label,ENTITY+"/sp-"+label,"http://localhost:18280/idp/profile/SAML2/SOAP/SLO","failure".equals(trial)&&rows.isEmpty()?RESPONDER:SUCCESS,sec++,Direction.OUTBOUND,trial,label);rows.add(new ShibbolethNativeSloContinuationEvidence.Participant(label,q,a));}
        var finalResponse=message("LogoutResponse","_final",originId,TARGET,ENTITY+"/sp/slo/soap",SUCCESS,9,Direction.INBOUND,trial,null);finalResponse=summary(finalResponse,"request_transcript",origin.entry().id());return new Fixture(trial,peers(trial),origin,finalResponse,rows);}
    private void verify(Fixture f){ShibbolethNativeSloContinuationEvidence.validateTrial(RUN,f.trial,ENTITY,TARGET,PREP,SHA,f.peers,f.origin,f.result,f.participants,List.of(suite.certificate()),List.of(target.certificate()));}
    private Fixture changed(Fixture f,int index,ShibbolethNativeSloContinuationEvidence.Participant p){var rows=new ArrayList<>(f.participants);rows.set(index,p);return new Fixture(f.trial,f.peers,f.origin,f.result,rows);}
    private ShibbolethNativeSloContinuationEvidence.SoapMessage summary(ShibbolethNativeSloContinuationEvidence.SoapMessage m,String key,Object value){var e=m.entry();var s=new LinkedHashMap<>(e.samlSummary());s.put(key,value);return new ShibbolethNativeSloContinuationEvidence.SoapMessage(new TranscriptEntry(e.id(),e.runId(),e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),e.decodedSamlRef(),e.decodedSamlBytes(),e.contentType(),e.rawQuery(),s),m.xml());}
    @Test void signedResponderThenBothRemainingResponsesClosesFailureTrial(){verify(fixture("failure"));}

    @Test void firstVerifiedArrivalGetsErrorRegardlessOfParticipantLabel(){verify(fixture("failure",List.of("remain2","fail","remain")));}
    @Test void forgedFirstArrivalModeAndOrdinalCannotOverrideActualOrder(){var f=fixture("failure");var p=f.participants.getFirst();
        for(var field:List.of("propagationMode","propagationOrdinal"))assertThrows(IllegalArgumentException.class,()->verify(changed(f,0,new ShibbolethNativeSloContinuationEvidence.Participant(p.label(),summary(p.request(),field,field.equals("propagationMode")?"all-success":2),p.response()))));}
    @Test void signedPartialProtocolWithoutAuthoritativeTerminalSetStaysUnverified(){var f=fixture("failure");var operation=ShibbolethNativeSloContinuationEvidence.inspectTrial(RUN,f.trial,ENTITY,TARGET,PREP,SHA,f.peers,f.origin,f.result,f.participants.subList(0,1),List.of(suite.certificate()),List.of(target.certificate()));
        assertEquals(Outcome.NOT_VERIFIED,SloContinuationProof.computeOutcome(operation));assertEquals(Set.of("remain","remain2"),operation.terminalRemaining());}
    @Test void allSuccessControlStillAnswersExactlyThreeDifferentParticipants(){verify(fixture("all-success"));}
    @Test void missingRemainingOrResponseDoesNotProveContinuation(){var f=fixture("failure");assertThrows(IllegalArgumentException.class,()->verify(new Fixture(f.trial,f.peers,f.origin,f.result,f.participants.subList(0,2))));}
    @Test void fakeMarkerCannotTurnARealSamlSuccessIntoFailure(){var f=fixture("failure");var p=f.participants.getFirst();var a=message("LogoutResponse","_a_fail","_q_fail",ENTITY+"/sp-fail","http://localhost:18280/idp/profile/SAML2/SOAP/SLO",SUCCESS,3,Direction.OUTBOUND,"failure","fail");assertThrows(IllegalArgumentException.class,()->verify(changed(f,0,new ShibbolethNativeSloContinuationEvidence.Participant("fail",p.request(),summary(a,"responseStatus",RESPONDER)))));}
    @Test void wrongActualSamlErrorStatusIsNotTheApprovedResponder(){var f=fixture("failure");var p=f.participants.getFirst();var a=message("LogoutResponse","_a_fail","_q_fail",ENTITY+"/sp-fail","http://localhost:18280/idp/profile/SAML2/SOAP/SLO","urn:oasis:names:tc:SAML:2.0:status:Requester",3,Direction.OUTBOUND,"failure","fail");assertThrows(IllegalArgumentException.class,()->verify(changed(f,0,new ShibbolethNativeSloContinuationEvidence.Participant("fail",p.request(),a))));}
    @Test void missingActualProducerBoundaryCannotClaimIssuedFailure(){var f=fixture("failure");var p=f.participants.getFirst();assertThrows(IllegalArgumentException.class,()->verify(changed(f,0,new ShibbolethNativeSloContinuationEvidence.Participant("fail",p.request(),summary(p.response(),"producerBoundary","consume-arrival")))));}
    @Test void parallelDispatchBeforeFailureResponseIsNotContinuation(){var f=fixture("failure");var p=f.participants.get(1);var q=message("LogoutRequest","_q_remain",null,TARGET,endpoint("remain","failure"),null,2,Direction.INBOUND,"failure","remain");assertThrows(IllegalArgumentException.class,()->verify(changed(f,1,new ShibbolethNativeSloContinuationEvidence.Participant("remain",q,p.response()))));}
    @Test void sameParticipantRetryCannotReplaceAnotherRemainingPeer(){var f=fixture("failure");var first=f.participants.getFirst();assertThrows(IllegalArgumentException.class,()->verify(changed(f,2,new ShibbolethNativeSloContinuationEvidence.Participant("fail",first.request(),first.response()))));}
    @Test void differentPreparationTrialOrReferenceCannotBeStitched(){var f=fixture("failure");var p=f.participants.get(1);for(var key:List.of("propagationTrial","preparedMetadataRef","preparedMetadataSha256"))assertThrows(IllegalArgumentException.class,()->verify(changed(f,1,new ShibbolethNativeSloContinuationEvidence.Participant("remain",summary(p.request(),key,"foreign"),p.response()))));}
    @Test void responseToAnotherRequestOrOriginOperationIsUnproven(){var f=fixture("failure");var p=f.participants.get(1);var a=message("LogoutResponse","_other","_q_foreign",ENTITY+"/sp-remain","http://localhost:18280/idp/profile/SAML2/SOAP/SLO",SUCCESS,5,Direction.OUTBOUND,"failure","remain");assertThrows(IllegalArgumentException.class,()->verify(changed(f,1,new ShibbolethNativeSloContinuationEvidence.Participant("remain",p.request(),a))));
        var r=message("LogoutResponse","_final_other","_other_origin",TARGET,ENTITY+"/sp/slo/soap",SUCCESS,9,Direction.INBOUND,"failure",null);assertThrows(IllegalArgumentException.class,()->verify(new Fixture(f.trial,f.peers,f.origin,r,f.participants)));}
    @Test void duplicateMessageIdsAndEventsAfterFinalCannotComplete(){var f=fixture("failure");var p=f.participants.get(2);var q=message("LogoutRequest","_q_fail",null,TARGET,endpoint("remain2","failure"),null,6,Direction.INBOUND,"failure","remain2");assertThrows(IllegalArgumentException.class,()->verify(changed(f,2,new ShibbolethNativeSloContinuationEvidence.Participant("remain2",q,p.response()))));
        var a=message("LogoutResponse","_a_remain2","_q_remain2",ENTITY+"/sp-remain2","http://localhost:18280/idp/profile/SAML2/SOAP/SLO",SUCCESS,10,Direction.OUTBOUND,"failure","remain2");assertThrows(IllegalArgumentException.class,()->verify(changed(f,2,new ShibbolethNativeSloContinuationEvidence.Participant("remain2",p.request(),a))));}
    @Test void originalSignedResponseCannotBeRewrittenOrGivenAnotherIssuer(){var f=fixture("failure");var p=f.participants.get(1);p.response().xml().setAttribute("InResponseTo","_q_fail");var altered=f;assertThrows(IllegalArgumentException.class,()->verify(altered));
        f=fixture("failure");p=f.participants.get(1);var a=message("LogoutResponse","_a_remain","_q_remain",ENTITY+"/sp-remain2","http://localhost:18280/idp/profile/SAML2/SOAP/SLO",SUCCESS,5,Direction.OUTBOUND,"failure","remain");var finalF=f;var finalP=p;assertThrows(IllegalArgumentException.class,()->verify(changed(finalF,1,new ShibbolethNativeSloContinuationEvidence.Participant("remain",finalP.request(),a))));}
    @Test void foreignRunAndNestedOrAdditionalSoapBodiesAreRejected(){var f=fixture("failure");var m=f.participants.getFirst().request();byte[] inner=SecureXml.serialize(m.xml().getOwnerDocument());assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.message(m.entry(),inner,inner,"run_11111111111111111111111111"));
        var body=("<soap:Envelope xmlns:soap='"+SOAP+"'><soap:Body><x/><x/></soap:Body></soap:Envelope>").getBytes(StandardCharsets.UTF_8);assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.message(m.entry(),inner,body,RUN));}
    @Test void ownedPartialAndSymlinkNeverFallsBackToOldObserver()throws Exception{var r=new ShibbolethNativeSloContinuationEvidence(directory,e->null,x->new byte[0],x->Optional.empty());assertFalse(r.exists(RUN));Files.createDirectory(directory.resolve(RUN));assertTrue(r.exists(RUN));
        var transcript=new TranscriptRecorder(){public List<TranscriptEntry> list(String run){return List.of();}public TranscriptEntry record(TranscriptInput i){throw new AssertionError();}public TranscriptEntry updateSamlAnalysis(String id,String c,Map<String,Object>s){throw new AssertionError();}};
        var context=new com.samlscope.runner.DefaultCaseContext(RUN,com.samlscope.core.plan.TargetRole.IDP,Clock.fixed(NOW,ZoneOffset.UTC),com.samlscope.core.plan.TestPlan.Parameters.defaults(),com.samlscope.core.plan.TestPlan.Interaction.defaults(),com.samlscope.core.run.Reachability.CONFIRMED,transcript,true);
        assertEquals(Outcome.NOT_VERIFIED,r.read(context,ShibbolethNativeSloContinuationEvidence.CASE).orElseThrow().outcome());Files.delete(directory.resolve(RUN));Files.createSymbolicLink(directory.resolve(RUN),directory.resolve("suite"));assertTrue(r.exists(RUN));assertEquals(Outcome.NOT_VERIFIED,r.read(context,ShibbolethNativeSloContinuationEvidence.CASE).orElseThrow().outcome());}
    @Test void changedNativeTargetMetadataCannotClaimExactRestoration(){byte[] original="original native published metadata".getBytes(StandardCharsets.UTF_8),configured="same Run configured publication".getBytes(StandardCharsets.UTF_8);ShibbolethNativeSloContinuationEvidence.validateRestorationBytes(original,original,configured,configured);assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.validateRestorationBytes(original,configured,configured,configured));}
    @Test void configuredPublicationFromAnotherSnapshotCannotResolveThisRun(){byte[] original="original".getBytes(StandardCharsets.UTF_8),configured="configured".getBytes(StandardCharsets.UTF_8),foreign="different Run snapshot".getBytes(StandardCharsets.UTF_8);assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.validateRestorationBytes(original,original,configured,foreign));}
    @Test void actualSenderSummaryAndAbsentOptionalFinalDestinationRemainBound(){var f=fixture("failure");var r=message("LogoutResponse","_final_no_destination",f.origin.xml().getAttribute("ID"),TARGET,"",SUCCESS,9,Direction.INBOUND,"failure",null);r=summary(r,"request_transcript",f.origin.entry().id());verify(new Fixture(f.trial,f.peers,f.origin,r,f.participants));var bad=summary(r,"saml_message","Response");assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.message(bad.entry(),SecureXml.serialize(bad.xml().getOwnerDocument()),SecureXml.serialize(bad.xml().getOwnerDocument()),RUN));}
    @Test void actualSenderOriginActionAndResponseTranscriptCannotNameAnotherOperation(){var f=fixture("failure");for(var key:List.of("action_id","kind")){var origin=summary(f.origin,key,"foreign");assertThrows(IllegalArgumentException.class,()->verify(new Fixture(f.trial,f.peers,origin,f.result,f.participants)));}var wrong=summary(f.result,"request_transcript","tx_11111111111111111111111111");assertThrows(IllegalArgumentException.class,()->verify(new Fixture(f.trial,f.peers,f.origin,wrong,f.participants)));}
    private Element metadata(String expiry,String certificate,String location,String extra){return SecureXml.parse(("<md:EntityDescriptor xmlns:md='urn:oasis:names:tc:SAML:2.0:metadata' xmlns:ds='http://www.w3.org/2000/09/xmldsig#' xmlns:x='urn:foreign' entityID='"+ENTITY+"' validUntil='"+expiry+"' "+extra+"><md:SPSSODescriptor protocolSupportEnumeration='urn:oasis:names:tc:SAML:2.0:protocol'><md:KeyDescriptor use='signing'><ds:KeyInfo><ds:X509Data><ds:X509Certificate>"+certificate+"</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleLogoutService Binding='urn:oasis:names:tc:SAML:2.0:bindings:SOAP' Location='"+location+"'/></md:SPSSODescriptor></md:EntityDescriptor>").getBytes(StandardCharsets.UTF_8)).getDocumentElement();}
    @Test void nativeMetadataIndentationCertificateWrappingAndMillisProjectionPreserveMeaning(){
        var compact=metadata("2026-10-17T20:42:08.624009633Z","AQIDBA==",ENTITY+"/sp/slo/soap","");
        var nativeXml=new String(SecureXml.serialize(compact.getOwnerDocument()),StandardCharsets.UTF_8).replace("><",">\n  <").replace(".624009633Z",".624Z").replace("AQIDBA==","AQID\nBA==");
        var nativeElement=SecureXml.parse(nativeXml.getBytes(StandardCharsets.UTF_8)).getDocumentElement();
        assertEquals(ShibbolethNativeSloContinuationEvidence.metadataView(compact),ShibbolethNativeSloContinuationEvidence.metadataView(nativeElement));
        assertNotEquals(ShibbolethNativeSloContinuationEvidence.view(compact),ShibbolethNativeSloContinuationEvidence.view(nativeElement));
    }
    @Test void nativeMetadataProjectionDoesNotHideChangedEndpointOrCertificateDer(){
        var original=metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/soap","");String expected=ShibbolethNativeSloContinuationEvidence.metadataView(original);
        assertNotEquals(expected,ShibbolethNativeSloContinuationEvidence.metadataView(metadata("2026-10-17T20:42:08.624Z","AQIDBQ==",ENTITY+"/sp/slo/soap","")));
        assertNotEquals(expected,ShibbolethNativeSloContinuationEvidence.metadataView(metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/foreign","")));
        assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.metadataView(metadata("2026-10-17T20:42:08.624Z","AQID!BA==",ENTITY+"/sp/slo/soap","")));
    }
    @Test void metadataExpiryProjectionHasNoArbitraryToleranceAndRetainsSubstantiveText(){
        var original=metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/soap","");
        assertNotEquals(ShibbolethNativeSloContinuationEvidence.metadataView(original),ShibbolethNativeSloContinuationEvidence.metadataView(metadata("2026-10-17T20:42:08.625Z","AQIDBA==",ENTITY+"/sp/slo/soap","")));
        var changed=metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/soap","");changed.appendChild(changed.getOwnerDocument().createTextNode("meaningful"));
        assertNotEquals(ShibbolethNativeSloContinuationEvidence.metadataView(original),ShibbolethNativeSloContinuationEvidence.metadataView(changed));
    }
    @Test void metadataProjectionRetainsAllUnnamespacedAndForeignAttributes(){
        var original=metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/soap","ID='_original' marker='exact'");String expected=ShibbolethNativeSloContinuationEvidence.metadataView(original);
        for(String attrs:List.of("ID='_foreign' marker='exact'","ID='_original'","ID='_original' x:marker='exact'"))
            assertNotEquals(expected,ShibbolethNativeSloContinuationEvidence.metadataView(metadata("2026-10-17T20:42:08.624Z","AQIDBA==",ENTITY+"/sp/slo/soap",attrs)));
    }
    private Map<String,byte[]> stockFlows(){var m=new LinkedHashMap<String,byte[]>();for(String n:ShibbolethNativeSloContinuationEvidence.STOCK_AUTHN_FLOWS)m.put("/opt/reference-idp/flows/authn/conditions/"+n,("<flow id='"+n+"'/>").getBytes(StandardCharsets.UTF_8));return m;}
    @Test void exactlyFourByteBoundStockAuthnConditionFlowsAreNotSloOverrides(){var stock=stockFlows();byte[] inventory=(String.join("\n",stock.keySet())+"\n/opt/reference-idp/views/logout.vm\n").getBytes(StandardCharsets.UTF_8);ShibbolethNativeSloContinuationEvidence.validateFlowOverrides(inventory,stock,stock);var missing=new LinkedHashMap<>(stock);missing.remove(missing.keySet().iterator().next());assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.validateFlowOverrides(inventory,missing,stock));}
    @Test void changedStockFlowUnknownAuthnAndSloOverridesRemainUnproven(){var stock=stockFlows();String inventory=String.join("\n",stock.keySet())+"\n";var altered=new LinkedHashMap<>(stock);altered.put(altered.keySet().iterator().next(),"<flow id='changed'/>".getBytes(StandardCharsets.UTF_8));assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.validateFlowOverrides(inventory.getBytes(StandardCharsets.UTF_8),altered,stock));for(String path:List.of("/opt/reference-idp/flows/authn/conditions/unknown.xml","/opt/reference-idp/flows/saml/saml2/slo-back-flow.xml","/opt/reference-idp/edit-webapp/WEB-INF/lib/override.jar","/opt/reference-idp/flows/authn/conditions/../conditions-flow.xml"))assertThrows(IllegalArgumentException.class,()->ShibbolethNativeSloContinuationEvidence.validateFlowOverrides((inventory+path+"\n").getBytes(StandardCharsets.UTF_8),stock,stock));}
}
