package com.samlscope.runner.cases;
import static org.junit.jupiter.api.Assertions.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.store.JsonCodec;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import org.junit.jupiter.api.io.TempDir;

class SimpleSamlPhpSelfContainedTrustEvidenceFileTest {
    private static final JsonCodec JSON=new JsonCodec();
    static ObjectNode trust() throws Exception{return (ObjectNode)JSON.mapper().readTree("{\"metadataSigningCertificateSha256\":\"abc\",\"stockNativeSignatureAccepted\":true,\"stockAdditionalTrustInputSupplied\":false,\"mutant\":{\"mathematicalSignatureAccepted\":true,\"additionalTrustInputRequired\":true,\"additionalTrustInputSupplied\":false,\"rejected\":true,\"exceptionClass\":\"RuntimeException\",\"exceptionMessage\":\"ExternalTrustInputRequired:abc\",\"acceptedWithSamePublicAnchorSupplied\":true,\"counterfactualCalibrationOnly\":true}}");}
    @Test void nativeExtraAnchorRequiresSameCertificateCausalDifferentialNotALabel()throws Exception{var n=trust();assertDoesNotThrow(()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateStock(n));assertDoesNotThrow(()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateAdditionalTrustTrace(n));for(String field:new String[]{"mathematicalSignatureAccepted","additionalTrustInputRequired","rejected","acceptedWithSamePublicAnchorSupplied","counterfactualCalibrationOnly"}){var bad=n.deepCopy();((ObjectNode)bad.path("mutant")).put(field,false);assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateAdditionalTrustTrace(bad));}var wrong=n.deepCopy();((ObjectNode)wrong.path("mutant")).put("exceptionMessage","ExternalTrustInputRequired:other");assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateAdditionalTrustTrace(wrong));}
    @Test void externallySuppliedAnchorOrInvalidStockSignatureCannotProveSelfContainedTrust()throws Exception{var n=trust();n.put("stockAdditionalTrustInputSupplied",true);assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateStock(n));n.put("stockAdditionalTrustInputSupplied",false).put("stockNativeSignatureAccepted",false);assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateStock(n));}
    @Test void encryptionPolicyIsAllowedButSharedSecretRemoteTrustAndHmacAreNot()throws Exception{var sp=(ObjectNode)JSON.mapper().readTree("{\"keys\":[{}],\"validate.authnrequest\":true,\"assertion.encryption\":true}");assertDoesNotThrow(()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateTrustInputs(sp));for(String field:new String[]{"sharedkey","truststore","remote.trust","signature.callback","hmac_key","certData"}){var bad=sp.deepCopy();bad.put(field,"extra");assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateTrustInputs(bad));}}
    @Test void flippingReceiptSelectionCannotTurnUnchangedStockResultIntoViolation()throws Exception{var stock=trust();stock.remove("mutant");stock.set("selectedConsumer",JSON.mapper().readTree("{\"path\":\"stock-native-signature-encryption\",\"accepted\":true,\"additionalTrustInputRequired\":false,\"additionalTrustInputSupplied\":false}"));assertDoesNotThrow(()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateSelectedConsumer(stock,"stock-native-signature-encryption",false));assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateSelectedConsumer(stock,"developer-instrumented-additional-anchor",true));((ObjectNode)stock.path("selectedConsumer")).put("path","developer-instrumented-additional-anchor");assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateSelectedConsumer(stock,"developer-instrumented-additional-anchor",true));}
    @Test void selectedInvocationBindsActualArgvRawInputsOutputSourceAndUnchangedContainer(@TempDir Path temp)throws Exception{
        var folder=temp.toRealPath();var old=JSON.mapper().readTree("[{\"Id\":\"same-container\",\"Image\":\"same-image\"}]");Files.write(folder.resolve("target-container-inspect-start.json"),JSON.mapper().writeValueAsBytes(old));
        var costs=(ObjectNode)JSON.mapper().readTree("{\"attempts\":[{\"selectedPath\":\"stock-native-signature-encryption\",\"exitCode\":0,\"sourceSha256\":\"x\",\"inputSha256\":\"input\",\"outputSha256\":\"output\",\"startedAt\":\"2026-10-02T00:00:00Z\",\"completedAt\":\"2026-10-02T00:00:01Z\",\"command\":[\"docker\",\"exec\",\"-i\",\"samlscope-reference-ssp\",\"php\",\"/tmp/self-contained-trust-123456abcdef.php\"]},{\"selectedPath\":\"developer-instrumented-additional-anchor\"}],\"nativeContainerBefore\":{\"Id\":\"same-container\",\"Image\":\"same-image\",\"State\":{\"Running\":true}},\"nativeContainerAfter\":{\"Id\":\"same-container\",\"Image\":\"same-image\",\"State\":{\"Running\":true}}}");((ObjectNode)costs.path("attempts").get(0)).put("sourceSha256",SimpleSamlPhpSelfContainedTrustEvidenceFile.PRODUCER);
        assertDoesNotThrow(()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateInvocation(costs,"stock-native-signature-encryption","input","output",JSON.mapper().createObjectNode(),folder));
        for(String field:new String[]{"sourceSha256","inputSha256","outputSha256"}){var bad=costs.deepCopy();((ObjectNode)bad.path("attempts").get(0)).put(field,"foreign");assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateInvocation(bad,"stock-native-signature-encryption","input","output",JSON.mapper().createObjectNode(),folder));}
        var bad=costs.deepCopy();((ObjectNode)bad.path("nativeContainerAfter")).put("Id","foreign");assertThrows(IllegalArgumentException.class,()->SimpleSamlPhpSelfContainedTrustEvidenceFile.validateInvocation(bad,"stock-native-signature-encryption","input","output",JSON.mapper().createObjectNode(),folder));
    }
}

