package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.XmlSignatureVerifier;
import com.samlscope.saml.normal.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.zip.ZipFile;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.html.HTML;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;
import org.w3c.dom.Element;

/**
 * Original native metadata import and request-bound consent rendering. Native admission refusal
 * is distinct from SAML rejection. URI storage, an image load failure, and browser blocking do
 * not prove nonuse. The URL counterexample is the native policy anchor rendered for the user.
 */
final class KeycloakNativeUiConsumerEvidence {
 static final String LOGO="IIP-MD05-f9-idp-01",URL="IIP-MD05-fh-idp-01";
 static final List<String> VARIANTS=variants();
 private static final String MD="urn:oasis:names:tc:SAML:2.0:metadata",UI="urn:oasis:names:tc:SAML:metadata:ui",DS="http://www.w3.org/2000/09/xmldsig#",P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",XML="http://www.w3.org/XML/1998/namespace";
 private static final String TARGET="http://localhost:18180/realms/samlscope",ADMIN="http://localhost:18180/admin/realms/samlscope",SERVICES="213c45bb357e0881ead8284f12308e3c9fd8e09e7f0b6ec816f95f8b0921bea9",THEMES="a89cbd82fa30951224262aaf5326f6239e1217224678d69cfac3d3fd1b493407";
 private static final ObjectMapper JSON=new ObjectMapper();
 private static final Map<String,String> CLASSES=Map.of(
  "org/keycloak/protocol/saml/EntityDescriptorDescriptionConverter.class","f12ac7fc23ddaec03f2b0d61c47368dae8038b478a4972a66d0ff7f3415de4ec",
  "org/keycloak/forms/login/freemarker/model/ClientBean.class","ef9a20e5d87881efefa547c416cb4502774ef4a8ff3b69f6816c50bbff958093",
  "org/keycloak/forms/login/freemarker/model/OAuthGrantBean.class","ec5a9f478b99d2d46b5bbcb4581e6bccb2298d355c09f8b3df1b5b28d5ac18fe",
  "org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.class","166c279f5408e203a3e5ada8d996a1dc8326068ea188cbd20e63f5d3786b5dc3",
  "org/keycloak/validation/DefaultClientValidationProvider.class","93c2f39ecefbf85667b7969fd51f14012d251c5bcd771fe45c151630646b2d43");
 private static final Map<String,String> TEMPLATES=Map.of(
  "theme/base/login/login-oauth-grant.ftl","2b879a1228b542fcdf6949feddbee996b2f609f35d55dc933eeb063612dde746",
  "theme/keycloak.v2/login/login-oauth-grant.ftl","855c74189b438c5ae2950aef9a196de92772ffa0871e34ed5b24a64500a5396c",
  "theme/keycloak.v2/login/theme.properties","f5032f39aabb1e0dc940564937263fb0dfb99c534ec0a1f92dea6c4baf0e03e2",
  "theme/keycloak/login/theme.properties","f0e83d4d0961df9c78e585e971a560487a2d986138ddc9adcbd89d0ee96ff66b");
 private final Path directory;private final TranscriptContentReader content;
 KeycloakNativeUiConsumerEvidence(Path directory,TranscriptContentReader content){this.directory=directory.toAbsolutePath().normalize();this.content=content;}
 private Path receipt(String run){return directory.resolve(run+".keycloak-ui-consumer.json");}
 boolean exists(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&Files.exists(receipt(run),LinkOption.NOFOLLOW_LINKS);}
 private static List<String> variants(){var out=new ArrayList<>(List.of("control","ui-consumer-logo-localized","ui-consumer-logo-fallback"));for(var element:List.of("logo","information","privacy"))for(var scheme:List.of("http","https","data","javascript","file"))out.add("ui-url-"+element+"-"+scheme);return List.copyOf(out);}
 private record Original(TranscriptEntry entry,JsonNode json){}
 private Original original(JsonNode ref,String run,String hash,String peer,String kind,Map<String,TranscriptEntry> entries,List<EvidenceRef> evidence)throws Exception{
  String id=text(ref,"reference");require(id.matches("tx_[0-9A-HJKMNP-TV-Z]{26}"));var e=entries.get(id);require(e!=null&&e.direction()==Direction.INBOUND&&run.equals(e.runId()));
  var raw=content.readDecodedSaml(e);require(raw!=null&&raw.length==e.decodedSamlBytes()&&sha(raw).equals(text(ref,"sha256")));var v=JSON.readTree(raw);
  require("samlscope-keycloak-native-ui-original-v1".equals(text(v,"schema"))&&run.equals(text(v,"runId"))&&hash.equals(text(v,"targetMetadataSha256"))&&peer.equals(text(v,"peerEntityId"))&&kind.equals(text(v,"kind"))&&!Instant.parse(text(v,"recordedAt")).isAfter(e.timestamp()));
  evidence.add(new EvidenceRef("transcript",e.id()));return new Original(e,v);
 }
 Optional<CaseOutcome> read(CaseContext context,byte[] targetRaw,String id){
  if(!Set.of(LOGO,URL).contains(id)||!exists(context.runId()))return Optional.empty();
  String stage="receipt";var evidence=new ArrayList<EvidenceRef>();
  try{
   require(context.transcriptComplete());var file=receipt(context.runId());var bytes=safe(file,262144);var receipt=JSON.readTree(bytes);String hash=sha(targetRaw),peer=text(receipt,"peerEntityId");var target=SecureXml.parse(targetRaw).getDocumentElement();
   require("samlscope-keycloak-native-ui-consumer-v1".equals(text(receipt,"schema"))&&context.runId().equals(text(receipt,"runId"))&&"native-ui-consumer-matrix".equals(text(receipt,"campaignId"))&&hash.equals(text(receipt,"targetMetadataSha256"))&&TARGET.equals(text(receipt,"targetEntityId"))&&TARGET.equals(target.getAttribute("entityID"))&&peer.matches("http://localhost:18080/p/plan_[0-9A-HJKMNP-TV-Z]{26}"));
   var entries=new LinkedHashMap<String,TranscriptEntry>();for(var e:context.transcript().list(context.runId()))require(context.runId().equals(e.runId())&&entries.put(e.id(),e)==null);
   var restore=receipt.path("restoration");require(restore.path("restored").isBoolean()&&restore.path("restored").asBoolean());
   var before=original(restore.path("before"),context.runId(),hash,peer,"client-inventory",entries,evidence);var after=original(restore.path("after"),context.runId(),hash,peer,"client-inventory",entries,evidence);
   var scopeBefore=original(restore.path("scopeBefore"),context.runId(),hash,peer,"native-scope",entries,evidence);var scopeAfter=original(restore.path("scopeAfter"),context.runId(),hash,peer,"native-scope",entries,evidence);
   require(before.json().path("clients").isArray()&&before.json().path("clients").isEmpty()&&before.json().path("clients").equals(after.json().path("clients")));
   for(String field:List.of("runtime","realm","clientPolicies","sourceJarSha256"))require(scopeBefore.json().path(field).equals(scopeAfter.json().path(field)));
   stage="native-operative-source";verifyScope(scopeBefore.json());verifySource(context.runId());
   var accepted=new ArrayList<String>();for(var v:VARIANTS)if(!Set.of("ui-url-logo-javascript","ui-url-privacy-data","ui-url-privacy-javascript").contains(v))accepted.add(v);
   var collected=MetadataAlgorithmEvidence.collect(accepted,context,content,targetRaw);require(collected.issues().isEmpty()&&collected.exchanges().size()==accepted.size());
   var exchanges=new HashMap<String,MetadataAlgorithmEvidence.Exchange>();for(var ex:collected.exchanges())require(exchanges.put(ex.variant(),ex)==null);var members=receipt.path("members");require(members.isArray()&&members.size()==VARIANTS.size());
   var logoSamples=new ArrayList<UiLogoComparison.Sample>();var logoStable=new HashSet<String>();var clientIds=new HashSet<String>();var requestsUsed=new HashSet<String>();Instant last=scopeBefore.entry().timestamp();int browserIndex=0;var urlUses=new ArrayList<String>();
   for(int i=0;i<VARIANTS.size();i++){
    var member=members.get(i);String variant=text(member,"variant");require(VARIANTS.get(i).equals(variant));stage="fixture-"+variant;
    var prepared=entries.values().stream().filter(e->e.direction()==Direction.OUTBOUND&&"MetadataPrepared".equals(e.samlSummary().get("type"))&&variant.equals(e.samlSummary().get("variant"))).toList();require(prepared.size()==1);var e=prepared.getFirst();var raw=content.readDecodedSaml(e);
    require(e.timestamp().isAfter(last)&&sha(raw).equals(text(member,"fixtureSha256"))&&sha(raw).equals(e.samlSummary().get("metadataSha256"))&&"PREPARED".equals(e.samlSummary().get("delivery"))&&Integer.valueOf(200).equals(e.status()));
    var fetch=entries.get(String.valueOf(e.samlSummary().get("fetchTranscriptId")));require(fetch!=null&&fetch.direction()==Direction.INBOUND&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&variant.equals(fetch.samlSummary().get("variant"))&&Integer.valueOf(200).equals(fetch.status())&&fetch.id().equals(e.correlationId())&&Objects.equals(fetch.url(),e.url())&&!fetch.timestamp().isAfter(e.timestamp()));
    var metadata=SecureXml.parse(raw).getDocumentElement();require(MD.equals(metadata.getNamespaceURI())&&"EntityDescriptor".equals(metadata.getLocalName())&&peer.equals(metadata.getAttribute("entityID"))&&SamlSchemaValidation.isValid(metadata,SamlSchemaValidation.SchemaKind.METADATA));verifySignature(metadata);
    evidence.add(new EvidenceRef("transcript",fetch.id()));evidence.add(new EvidenceRef("transcript",e.id()));
    var converted=original(member.path("converter"),context.runId(),hash,peer,"converter",entries,evidence);var applied=original(member.path("application"),context.runId(),hash,peer,"ui-prerequisite-application",entries,evidence);var restored=original(member.path("restoration"),context.runId(),hash,peer,"client-inventory",entries,evidence);
    for(var v:List.of(converted,applied))require(variant.equals(text(v.json(),"variant"))&&sha(raw).equals(text(v.json(),"fixtureSha256")));
    require(converted.entry().timestamp().isAfter(e.timestamp())&&applied.entry().timestamp().isAfter(converted.entry().timestamp())&&restored.entry().timestamp().isAfter(applied.entry().timestamp())&&variant.equals(text(restored.json(),"variant"))&&restored.json().path("clients").equals(before.json().path("clients")));
    var conversion=nativeResponse(converted,"POST",ADMIN+"/client-description-converter",200,e.timestamp());require(sha(raw).equals(text(converted.json().path("native"),"requestSha256"))&&peer.equals(text(conversion,"clientId"))&&"saml".equals(text(conversion,"protocol"))&&!conversion.has("consentRequired"));
    var attributes=conversion.path("attributes");require(attributes.isObject()&&!attributes.has("saml.metadataDescriptorUrl")&&!attributes.has("saml.useMetadataDescriptorUrl")&&"true".equals(text(attributes,"saml.client.signature")));
    require(sha(JSON.writeValueAsBytes(conversion)).equals(text(applied.json(),"converterSha256"))&&applied.json().path("consentRequired").isBoolean()&&applied.json().path("consentRequired").asBoolean());var recipe=(ObjectNode)conversion.deepCopy();recipe.put("consentRequired",true);require(sha(JSON.writeValueAsBytes(recipe)).equals(text(applied.json().path("native"),"requestSha256")));
    String candidate=verifyUiInput(metadata,variant,attributes);stage="native-application-"+variant;
    if(!accepted.contains(variant)){
     require("rejected".equals(text(member,"nativeAdmission"))&&!member.has("persisted")&&!member.has("browser"));var error=nativeResponse(applied,"POST",ADMIN+"/clients",400,converted.entry().timestamp());require(error.equals(member.path("rejection"))&&"invalid_input".equals(text(error,"error"))&&((variant.contains("logo")?"Logo":"Policy")+" URL uses an illegal scheme").equals(text(error,"error_description")));require(member.path("orchestrationOnlyContinue").asBoolean());
     // No browser request or target protocol result is inferred for a native admission refusal.
     require(entries.values().stream().noneMatch(t->t.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(t.samlSummary().get("type"))&&variant.equals(t.samlSummary().get("variant"))));
    }else{
     require("accepted".equals(text(member,"nativeAdmission")));nativeResponse(applied,"POST",ADMIN+"/clients",201,converted.entry().timestamp());
     var persisted=original(member.path("persisted"),context.runId(),hash,peer,"operative-client",entries,evidence);var browser=original(member.path("browser"),context.runId(),hash,peer,"native-browser-ui",entries,evidence);require(persisted.entry().timestamp().isAfter(applied.entry().timestamp())&&browser.entry().timestamp().isAfter(persisted.entry().timestamp())&&restored.entry().timestamp().isAfter(browser.entry().timestamp()));
     for(var v:List.of(persisted,browser))require(variant.equals(text(v.json(),"variant"))&&sha(raw).equals(text(v.json(),"fixtureSha256")));var saved=persisted.json().path("client");verifyClient(conversion,saved,peer);require(clientIds.add(text(saved,"id")));
     var ex=exchanges.get(variant);require(ex!=null);var request=entries.get(ex.evidence().get(2).reference());var response=entries.get(ex.evidence().get(3).reference());require(requestsUsed.add(request.id())&&request.timestamp().isAfter(persisted.entry().timestamp())&&response.timestamp().isBefore(browser.entry().timestamp()));
     require(Instant.parse(text(browser.json().path("observation"),"startedAt")).isAfter(persisted.entry().timestamp()));verifyBrowser(context,variant,++browserIndex,browser,request,response,metadata,saved,entries,candidate);evidence.addAll(ex.evidence());
     var observed=browser.json().path("observation");if(variant.startsWith("ui-consumer-logo-")){
      var info=one(one(one(metadata,MD,"SPSSODescriptor"),MD,"Extensions"),UI,"UIInfo");var logos=children(info,UI,"Logo");var neutral=logos.stream().filter(n->!n.hasAttributeNS(XML,"lang")).findFirst().orElseThrow();var localized=logos.stream().filter(n->n.hasAttributeNS(XML,"lang")).findFirst().orElseThrow();
      String selected=observed.path("consent").path("images").get(0).path("src").asText();var selection=selected.equals(neutral.getTextContent())?UiLogoComparison.Selection.DEFAULT:selected.equals(localized.getTextContent())?UiLogoComparison.Selection.LOCALIZED:UiLogoComparison.Selection.UNOBSERVED;
      String fixed=sha(JSON.writeValueAsBytes(fixedLogo(metadata,variant,context.runId())));logoStable.add(fixed);var stable=sha((fixed+JSON.writeValueAsString(scopeBefore.json().path("realm"))+THEMES+SERVICES+"en-US:single-campaign-Chrome:fresh-context:kc-page-title-img").getBytes(StandardCharsets.UTF_8));
      logoSamples.add(new UiLogoComparison.Sample(context.runId(),peer,variant.endsWith("localized")?UiLogoComparison.Condition.PREFERRED_AVAILABLE:UiLogoComparison.Condition.PREFERRED_UNAVAILABLE,stable,sha(raw),sha(image(neutral.getTextContent())),sha(image(localized.getTextContent())),request.timestamp(),Instant.parse(text(observed.path("consent"),"recordedAt")),selection,List.of(new EvidenceRef("transcript",fetch.id()),new EvidenceRef("transcript",e.id()),new EvidenceRef("transcript",request.id()),new EvidenceRef("browser-observation",browser.entry().id()))));
     }
     if(variant.startsWith("ui-url-privacy-")){var links=observed.path("consent").path("policyLinks");if(links.size()==1&&Set.of("file","javascript").contains(java.net.URI.create(candidate).getScheme()))urlUses.add(variant.substring("ui-url-".length()));}
    }
    last=restored.entry().timestamp();
   }
   require(before.entry().timestamp().isBefore(scopeBefore.entry().timestamp())&&after.entry().timestamp().isAfter(last)&&scopeAfter.entry().timestamp().isAfter(after.entry().timestamp())&&sha(bytes).equals(sha(safe(file,262144))));
   evidence.add(new EvidenceRef("native-ui-policy",context.runId()+".keycloak-ui-consumer.json#"+sha(bytes)));
   if(LOGO.equals(id)){require(logoStable.size()==1);var result=UiLogoComparison.evaluate(logoSamples,List.of());return Optional.of(new CaseOutcome(result.outcome(),result.notVerifiedReason(),result.reasonCode(),result.reasonMessageKey(),evidence.stream().distinct().toList(),details(result.details(),"native-consent-logo-language-fallback",browserIndex,urlUses)));}
   require(urlUses.equals(List.of("privacy-file")));return Optional.of(new CaseOutcome(Outcome.VIOLATED,null,"browser.ui-url.disallowed-scheme-used","browser.ui-url.disallowed-scheme-used",evidence.stream().distinct().toList(),details(Map.of("disallowed_scheme_uses",urlUses),"native-consent-policy-anchor",browserIndex,urlUses)));
  }catch(Exception unproven){return Optional.of(new CaseOutcome(Outcome.NOT_VERIFIED,"native_ui_consumer_unproven","browser.ui-native-consumer.evidence-incomplete","browser.ui-native-consumer.evidence-incomplete",List.of(),Map.of("evidence_issue",stage)));}
 }
 private static Map<String,Object> details(Map<String,Object> base,String scope,int browsers,List<String> forbidden){var result=new LinkedHashMap<String,Object>(base);result.put("product","keycloak");result.put("proof_scope",scope);result.put("native_originals_verified",true);result.put("restoration_verified",true);result.put("native_source_and_theme_verified",true);result.put("native_fixture_members",VARIANTS);result.put("native_browser_successes",browsers);result.put("native_admission_refusals",3);result.put("disallowed_scheme_uses",forbidden);return Map.copyOf(result);}
 private static JsonNode nativeResponse(Original original,String method,String url,int status,Instant after)throws Exception{
  var v=original.json().path("native");require(method.equals(text(v,"method"))&&url.equals(text(v,"url"))&&v.path("status").isInt()&&v.path("status").asInt()==status);Instant start=Instant.parse(text(v,"startedAt")),end=Instant.parse(text(v,"finishedAt"));require(!start.isBefore(after)&&!end.isBefore(start)&&!end.isAfter(original.entry().timestamp()));
  var raw=Base64.getDecoder().decode(v.path("responseBase64").asText());require(sha(raw).equals(text(v,"responseSha256")));return raw.length==0?JSON.createObjectNode():JSON.readTree(raw);
 }
 private static void verifyScope(JsonNode v){var runtime=v.path("runtime");require(runtime.path("running").asBoolean()&&"sha256:9d1f1b2b7261ff53c66cb1092dfcdc34a5fb77e81f9e6a6e75b8b6a795de8067".equals(text(runtime,"image"))&&text(runtime,"version").startsWith("Keycloak 26.7.2\n")&&text(runtime,"containerId").matches("[a-f0-9]{64}"));Instant.parse(text(runtime,"startedAt"));
  var realm=v.path("realm");require("samlscope".equals(text(realm,"realm"))&&realm.path("enabled").asBoolean()&&realm.has("loginTheme")&&realm.path("loginTheme").isNull()&&realm.has("defaultLocale")&&realm.path("defaultLocale").isNull()&&realm.path("internationalizationEnabled").isBoolean()&&!realm.path("internationalizationEnabled").asBoolean());require(v.at("/clientPolicies/policies/policies").isArray()&&v.at("/clientPolicies/policies/policies").isEmpty()&&v.at("/clientPolicies/profiles/profiles").isArray()&&v.at("/clientPolicies/profiles/profiles").isEmpty()&&SERVICES.equals(text(v.path("sourceJarSha256"),"services"))&&THEMES.equals(text(v.path("sourceJarSha256"),"themes")));
 }
 private void verifySource(String run)throws Exception{var root=directory.resolve(run+".keycloak-ui-consumer");for(var jar:List.of("native-services.jar","native-themes.jar")){var path=root.resolve(jar);var raw=safe(path,33554432);require(sha(raw).equals(jar.contains("services")?SERVICES:THEMES));try(var zip=new ZipFile(path.toFile())){for(var pin:(jar.contains("services")?CLASSES:TEMPLATES).entrySet()){var entry=zip.getEntry(pin.getKey());require(entry!=null);try(var in=zip.getInputStream(entry)){require(sha(in.readNBytes(1048577)).equals(pin.getValue()));}}}}}
 private byte[] safe(Path path,long maximum)throws Exception{require(path.normalize().startsWith(directory)&&Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)&&Files.size(path)>0&&Files.size(path)<=maximum);for(var p=path.getParent();p!=null&&p.startsWith(directory);p=p.getParent())require(!Files.isSymbolicLink(p));return Files.readAllBytes(path);}
 private static void verifyClient(JsonNode converted,JsonNode saved,String peer){require(text(saved,"id").matches("[a-f0-9-]{36}")&&peer.equals(text(saved,"clientId"))&&"saml".equals(text(saved,"protocol"))&&saved.path("enabled").asBoolean()&&saved.path("consentRequired").isBoolean()&&saved.path("consentRequired").asBoolean()&&!saved.has("secret")&&!saved.has("registrationAccessToken")&&saved.path("authenticationFlowBindingOverrides").isEmpty());
  var fields=converted.fields();while(fields.hasNext()){var f=fields.next();if(f.getKey().equals("attributes")){var attrs=f.getValue().fields();while(attrs.hasNext()){var attr=attrs.next();require(attr.getValue().equals(saved.path("attributes").get(attr.getKey())));}nativeDefaults(f.getValue(),saved.path("attributes"));}else if(f.getKey().equals("redirectUris"))require(set(f.getValue()).equals(set(saved.path(f.getKey()))));else if(f.getKey().equals("protocolMappers"))require(f.getValue().isArray()&&f.getValue().isEmpty()&&!saved.has("protocolMappers"));else require(f.getValue().equals(saved.get(f.getKey())));}
 }
 private static void nativeDefaults(JsonNode converted,JsonNode saved){var defaults=Map.of("saml.force.post.binding","true","realm_client","false","saml_force_name_id_format","false","saml_name_id_format","username","saml.allow.ecp.flow","false","saml_signature_canonicalization_method","http://www.w3.org/2001/10/xml-exc-c14n#");var extra=saved.fields();int count=0;while(extra.hasNext()){var f=extra.next();if(converted.has(f.getKey()))continue;count++;if(defaults.containsKey(f.getKey()))require(defaults.get(f.getKey()).equals(f.getValue().asText()));else if(f.getKey().equals("client.secret.creation.time"))require(f.getValue().asText().matches("[0-9]{10}"));else if(f.getKey().equals("saml.artifact.binding.identifier"))require(Base64.getDecoder().decode(f.getValue().asText()).length==20);else require(false);}require(count==8);}
 private static String verifyUiInput(Element metadata,String variant,JsonNode attributes)throws Exception{var roles=children(metadata,MD,"SPSSODescriptor");require(roles.size()==1);var extensions=children(roles.getFirst(),MD,"Extensions");var infos=extensions.isEmpty()?List.<Element>of():children(extensions.getFirst(),UI,"UIInfo");
  if(variant.equals("control")){require(infos.isEmpty()&&!attributes.has("logoUri")&&!attributes.has("policyUri"));return "";}
  require(infos.size()==1);var info=infos.getFirst();if(variant.startsWith("ui-consumer-logo-")){var logos=children(info,UI,"Logo");require(logos.size()==2&&children(info,UI,"InformationURL").isEmpty()&&children(info,UI,"PrivacyStatementURL").isEmpty());var neutral=logos.stream().filter(e->!e.hasAttributeNS(XML,"lang")).toList();var local=logos.stream().filter(e->e.hasAttributeNS(XML,"lang")).toList();require(neutral.size()==1&&local.size()==1&&(variant.endsWith("localized")?"en":"ja").equals(local.getFirst().getAttributeNS(XML,"lang"))&&"180".equals(neutral.getFirst().getAttribute("width"))&&"48".equals(neutral.getFirst().getAttribute("height"))&&"180".equals(local.getFirst().getAttribute("width"))&&"48".equals(local.getFirst().getAttribute("height"))&&!Arrays.equals(image(neutral.getFirst().getTextContent()),image(local.getFirst().getTextContent()))&&text(attributes,"logoUri").equals(logos.getFirst().getTextContent())&&!attributes.has("policyUri"));return text(attributes,"logoUri");}
  var parts=variant.substring("ui-url-".length()).split("-");require(parts.length==2);String name=switch(parts[0]){case "logo"->"Logo";case "information"->"InformationURL";case "privacy"->"PrivacyStatementURL";default->throw new IllegalArgumentException();};var nodes=children(info,UI,name);require(nodes.size()==1&&children(info,UI,"Logo").size()+children(info,UI,"InformationURL").size()+children(info,UI,"PrivacyStatementURL").size()==1);String url=nodes.getFirst().getTextContent();require(parts[1].equals(java.net.URI.create(url).getScheme()));
  if(parts[0].equals("logo"))require(url.equals(text(attributes,"logoUri"))&&!attributes.has("policyUri"));else if(parts[0].equals("privacy"))require(url.equals(text(attributes,"policyUri"))&&!attributes.has("logoUri"));else require(!attributes.has("logoUri")&&!attributes.has("policyUri")&&!attributes.has("informationUri"));return url;
 }
 private void verifyBrowser(CaseContext context,String variant,int index,Original original,TranscriptEntry request,TranscriptEntry response,Element metadata,JsonNode saved,Map<String,TranscriptEntry> entries,String candidate)throws Exception{
  var v=original.json();var observed=v.path("observation");require("samlscope-keycloak-native-ui-browser-v1".equals(text(observed,"schema"))&&context.runId().equals(text(observed,"runId"))&&variant.equals(text(observed,"variant"))&&observed.path("initialCookieCount").asInt(-1)==0&&"single-campaign-Chrome".equals(text(observed,"browserInstance"))&&observed.path("contextIndex").asInt(-1)==index&&"en-US".equals(text(observed,"preferredLanguage"))&&observed.path("credentialsPersisted").isBoolean()&&!observed.path("credentialsPersisted").asBoolean()&&observed.path("externalRequestsPermitted").isBoolean()&&!observed.path("externalRequestsPermitted").asBoolean());
  Instant start=Instant.parse(text(observed,"startedAt")),end=Instant.parse(text(observed,"completedAt"));require(start.isBefore(request.timestamp())&&end.isAfter(response.timestamp())&&!end.isAfter(original.entry().timestamp())&&observed.path("requests").isArray()&&observed.path("requests").size()==1);var sent=SecureXml.parse(content.readDecodedSaml(request)).getDocumentElement();
  var requestRaw=content.readDecodedSaml(request);var signing=certificate(text(saved.path("attributes"),"saml.signing.certificate"));require(roleCertificates(metadata,"signing").stream().anyMatch(c->Arrays.equals(c.getPublicKey().getEncoded(),signing.getPublicKey().getEncoded()))&&new XmlSignatureVerifier().hasValidEnvelopedSignature(sent,signing));
  var r=observed.path("requests").get(0);String requestId=sent.getAttribute("ID");require(requestId.equals(text(r,"requestId"))&&"POST".equals(text(r,"method"))&&request.method().equals("POST")&&request.url().equals(text(r,"targetUrl"))&&request.url().equals(sent.getAttribute("Destination"))&&sha(requestRaw).equals(text(r,"sha256"))&&requestRaw.length==r.path("bytes").asInt(-1)&&r.path("rawQuery").isNull()&&"en-US".equals(text(r,"acceptLanguage"))&&Instant.parse(text(r,"recordedAt")).isAfter(request.timestamp())&&Instant.parse(text(r,"recordedAt")).isBefore(response.timestamp()));
  require(v.path("exchange").path("success").asBoolean()&&requestId.equals(text(v.path("exchange"),"request_id"))&&set(v.path("exchange").path("transcript_ids")).equals(Set.of(request.id(),response.id())));
  var consent=observed.path("consent");require("/realms/samlscope/login-actions/required-action".equals(text(consent,"path"))&&Instant.parse(text(consent,"recordedAt")).isAfter(request.timestamp())&&Instant.parse(text(consent,"recordedAt")).isBefore(response.timestamp()));
  var publicHtml=Base64.getDecoder().decode(text(v,"publicHtmlBase64"));require(new String(publicHtml,StandardCharsets.UTF_8).contains(metadata.getAttribute("entityID")));require(publicHtml.length==consent.path("publicHtmlBytes").asInt(-1)&&sha(publicHtml).equals(text(consent,"publicHtmlSha256")));var rendered=html(publicHtml);require(rendered.consent&&rendered.accept&&rendered.nativeGrant&&rendered.language.equals("en")&&rendered.images.equals(consent.path("images").findValuesAsText("src"))&&rendered.links.equals(consent.path("policyLinks").findValuesAsText("href")));
  var nativePages=observed.path("nativePages");require(nativePages.isArray()&&nativePages.size()>=2);int found=0;for(var page:nativePages){require(page.path("status").asInt(-1)==200&&text(page,"bodySha256").matches("[a-f0-9]{64}")&&page.path("bytes").asInt(-1)>0);var at=Instant.parse(text(page,"recordedAt"));require(at.isAfter(request.timestamp())&&at.isBefore(end));if(text(page,"path").equals(text(consent,"path"))){require(at.isBefore(Instant.parse(text(consent,"recordedAt"))));found++;}}require(found==1);
  var images=consent.path("images");var links=consent.path("policyLinks");require(images.isArray()&&links.isArray());if(saved.path("attributes").has("logoUri")){require(images.size()==1&&text(images.get(0),"src").equals(text(saved.path("attributes"),"logoUri"))&&images.get(0).path("visible").isBoolean()&&images.get(0).path("visible").asBoolean()&&links.isEmpty());if(variant.startsWith("ui-consumer-logo-"))require(images.get(0).path("naturalWidth").asInt(-1)==180&&images.get(0).path("naturalHeight").asInt(-1)==48);}else if(saved.path("attributes").has("policyUri")){require(images.isEmpty()&&links.size()==1&&text(links.get(0),"href").equals(candidate)&&"privacy policy.".equals(text(links.get(0),"text"))&&links.get(0).path("visible").asBoolean());}else require(images.isEmpty()&&links.isEmpty());
 }
 static final class Rendered {boolean consent,accept,nativeGrant;String language="";final List<String>images=new ArrayList<>(),links=new ArrayList<>();}
 private static String attribute(MutableAttributeSet attrs,String name){for(var names=attrs.getAttributeNames();names.hasMoreElements();){var key=names.nextElement();if(name.equals(key.toString()))return Objects.toString(attrs.getAttribute(key),"");}return "";}
 static Rendered html(byte[] raw)throws Exception{String text=new String(raw,StandardCharsets.UTF_8);require(!text.contains("<script")&&!text.contains("session_code=")&&!text.contains("name=\"password\"")&&!text.contains("name=\"username\""));var result=new Rendered();new ParserDelegator().parse(new java.io.StringReader(text),new HTMLEditorKit.ParserCallback(){
  private boolean oauth=false;private int depth=0;private String anchor=null;
  public void handleStartTag(HTML.Tag tag,MutableAttributeSet attrs,int pos){String id=Objects.toString(attrs.getAttribute(HTML.Attribute.ID),"");if(id.equals("kc-oauth")){result.consent=true;oauth=true;depth=1;}else if(oauth)depth++;if(tag==HTML.Tag.HTML)result.language=attribute(attrs,"lang");if(tag==HTML.Tag.BODY)result.nativeGrant="login-login-oauth-grant".equals(Objects.toString(attrs.getAttribute("data-page-id"),""));if(tag==HTML.Tag.A&&oauth){anchor=Objects.toString(attrs.getAttribute(HTML.Attribute.HREF),"");result.links.add(anchor);}if(Objects.toString(attrs.getAttribute(HTML.Attribute.NAME),"").equals("accept"))result.accept=true;}
  public void handleEndTag(HTML.Tag tag,int pos){if(oauth&&--depth==0)oauth=false;if(tag==HTML.Tag.A)anchor=null;}
  public void handleSimpleTag(HTML.Tag tag,MutableAttributeSet attrs,int pos){if(tag==HTML.Tag.IMG)result.images.add(Objects.toString(attrs.getAttribute(HTML.Attribute.SRC),""));if(tag==HTML.Tag.INPUT)require(attrs.getAttribute(HTML.Attribute.VALUE)==null);if(Objects.toString(attrs.getAttribute(HTML.Attribute.NAME),"").equals("accept"))result.accept=true;}
 },true);return result;}
 static Object fixedLogo(Element metadata,String variant,String run){var normalized=(Element)metadata.cloneNode(true);var logos=normalized.getElementsByTagNameNS(UI,"Logo");require(logos.getLength()==2);for(int i=0;i<logos.getLength();i++)((Element)logos.item(i)).removeAttributeNS(XML,"lang");var certs=normalized.getElementsByTagNameNS(DS,"X509Certificate");for(int i=0;i<certs.getLength();i++)certs.item(i).setTextContent("independently-verified-condition-certificate");return UiDisplayEvidenceFile.fixedMetadata(normalized,variant,run);}
 private static byte[] image(String uri)throws Exception{require(uri.startsWith("data:image/svg+xml;base64,"));var raw=Base64.getDecoder().decode(uri.substring("data:image/svg+xml;base64,".length()));var svg=SecureXml.parse(raw).getDocumentElement();require("http://www.w3.org/2000/svg".equals(svg.getNamespaceURI())&&"180".equals(svg.getAttribute("width"))&&"48".equals(svg.getAttribute("height")));return raw;}
 private static List<X509Certificate> roleCertificates(Element metadata,String use)throws Exception{var values=new ArrayList<X509Certificate>();for(var key:children(one(metadata,MD,"SPSSODescriptor"),MD,"KeyDescriptor")){if(key.hasAttribute("use")&&!use.equals(key.getAttribute("use")))continue;var nodes=key.getElementsByTagNameNS(DS,"X509Certificate");for(int i=0;i<nodes.getLength();i++)values.add(certificate(nodes.item(i).getTextContent()));}return values;}
 private static void verifySignature(Element metadata)throws Exception{var signatures=children(metadata,DS,"Signature");require(signatures.size()==1);var certs=signatures.getFirst().getElementsByTagNameNS(DS,"X509Certificate");require(certs.getLength()==1);require(new XmlSignatureVerifier().hasValidEnvelopedSignature(metadata,certificate(certs.item(0).getTextContent())));}
 private static X509Certificate certificate(String text)throws Exception{return (X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(text)));}
 private static Element one(Element root,String ns,String name){var values=children(root,ns,name);require(values.size()==1);return values.getFirst();}
 private static Set<String> set(JsonNode array){require(array.isArray());var values=new HashSet<String>();for(var v:array)require(v.isTextual()&&values.add(v.asText()));return values;}
 private static String text(JsonNode value,String key){var node=value.path(key);require(node.isTextual()&&!node.asText().isBlank());return node.asText();}
 private static String sha(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 private static void require(boolean yes){if(!yes)throw new IllegalArgumentException("Native UI consumer proof incomplete");}
}
