package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.XmlSignatureVerifier;
import com.samlscope.saml.normal.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.zip.ZipFile;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.html.HTML;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;
import org.w3c.dom.Element;

/**
 * Original native metadata import and request-bound consent safety. Active detector originals are isolated from product pages. The known native renderer consumes Logo in an image context, drops InformationURL, and explicitly refuses the unsafe privacy scheme. Native admission refusal
 * is distinct from SAML rejection. URI storage, an image load failure, and browser blocking do
 * not prove nonuse. Developer counterexamples require a separately executed isolated renderer differential and are unavailable through the public production constructor.
 */
public final class KeycloakUiSafetyEvidence {
 public static final String CASE="IIP-MD05-fg-idp-01";
 static final List<String> VARIANTS=variants();
 private static final String MD="urn:oasis:names:tc:SAML:2.0:metadata",UI="urn:oasis:names:tc:SAML:metadata:ui",DS="http://www.w3.org/2000/09/xmldsig#",P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",XML="http://www.w3.org/XML/1998/namespace";
 private static final String TARGET="http://localhost:18180/realms/samlscope",ADMIN="http://localhost:18180/admin/realms/samlscope",SERVICES="213c45bb357e0881ead8284f12308e3c9fd8e09e7f0b6ec816f95f8b0921bea9",THEMES="a89cbd82fa30951224262aaf5326f6239e1217224678d69cfac3d3fd1b493407";
 private static final ObjectMapper JSON=new ObjectMapper();
 private static final Map<String,String> CLASSES=Map.of(
  "org/keycloak/protocol/saml/EntityDescriptorDescriptionConverter.class","f12ac7fc23ddaec03f2b0d61c47368dae8038b478a4972a66d0ff7f3415de4ec",
  "org/keycloak/forms/login/freemarker/model/ClientBean.class","ef9a20e5d87881efefa547c416cb4502774ef4a8ff3b69f6816c50bbff958093",
  "org/keycloak/forms/login/freemarker/model/OAuthGrantBean.class","ec5a9f478b99d2d46b5bbcb4581e6bccb2298d355c09f8b3df1b5b28d5ac18fe",
  "org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.class","166c279f5408e203a3e5ada8d996a1dc8326068ea188cbd20e63f5d3786b5dc3",
  "org/keycloak/validation/DefaultClientValidationProvider.class","93c2f39ecefbf85667b7969fd51f14012d251c5bcd771fe45c151630646b2d43");
 private static final Map<String,String> TEMPLATES=Map.of(
  "theme/base/login/login-oauth-grant.ftl","2b879a1228b542fcdf6949feddbee996b2f609f35d55dc933eeb063612dde746",
  "theme/keycloak.v2/login/login-oauth-grant.ftl","855c74189b438c5ae2950aef9a196de92772ffa0871e34ed5b24a64500a5396c",
  "theme/keycloak.v2/login/theme.properties","f5032f39aabb1e0dc940564937263fb0dfb99c534ec0a1f92dea6c4baf0e03e2",
  "theme/keycloak/login/theme.properties","f0e83d4d0961df9c78e585e971a560487a2d986138ddc9adcbd89d0ee96ff66b");
 private final Path directory;private final TranscriptContentReader content;private final boolean permitOfflineCalibration;
 public KeycloakUiSafetyEvidence(Path directory,TranscriptContentReader content){this(directory,content,false);}
 KeycloakUiSafetyEvidence(Path directory,TranscriptContentReader content,boolean permitOfflineCalibration){this.directory=directory.toAbsolutePath().normalize();this.content=content;this.permitOfflineCalibration=permitOfflineCalibration;}
 private Path receipt(String run){return directory.resolve(run+".keycloak-ui-safety.json");}
 public boolean exists(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&(Files.exists(receipt(run),LinkOption.NOFOLLOW_LINKS)||Files.exists(directory.resolve(run+".keycloak-ui-safety"),LinkOption.NOFOLLOW_LINKS));}
 private static List<String> variants(){return List.of("control","ui-safety-logo-data","ui-safety-information-javascript","ui-safety-privacy-javascript");}
 private record Original(TranscriptEntry entry,JsonNode json){}
 private Original original(JsonNode ref,String run,String hash,String peer,String kind,Map<String,TranscriptEntry> entries,List<EvidenceRef> evidence)throws Exception{
  String id=text(ref,"reference");require(id.matches("tx_[0-9A-HJKMNP-TV-Z]{26}"));var e=entries.get(id);require(e!=null&&e.direction()==Direction.INBOUND&&run.equals(e.runId())&&("transcripts/"+run+"/"+id+".saml.xml").equals(e.decodedSamlRef()));
  var raw=content.readDecodedSaml(e);require(raw!=null&&raw.length==e.decodedSamlBytes()&&sha(raw).equals(text(ref,"sha256")));var v=JSON.readTree(raw);
  require("samlscope-keycloak-ui-safety-original-v1".equals(text(v,"schema"))&&run.equals(text(v,"runId"))&&hash.equals(text(v,"targetMetadataSha256"))&&peer.equals(text(v,"peerEntityId"))&&kind.equals(text(v,"kind"))&&!Instant.parse(text(v,"recordedAt")).isAfter(e.timestamp()));
  evidence.add(new EvidenceRef("transcript",e.id()));return new Original(e,v);
 }
 public Optional<CaseOutcome> evaluate(CaseContext context,byte[] targetRaw){
  if(!exists(context.runId()))return Optional.empty();
  String stage="receipt";var evidence=new ArrayList<EvidenceRef>();
  try{
   require(context.transcriptComplete());var file=receipt(context.runId());var bytes=safe(file,262144);var receipt=JSON.readTree(bytes);require(receipt.path("counterfactualCalibrationOnly").isBoolean());boolean calibration=receipt.path("counterfactualCalibrationOnly").asBoolean();require(!calibration||permitOfflineCalibration);String hash=sha(targetRaw),peer=text(receipt,"peerEntityId");var target=SecureXml.parse(targetRaw).getDocumentElement();
   require("samlscope-keycloak-ui-safety-v1".equals(text(receipt,"schema"))&&context.runId().equals(text(receipt,"runId"))&&"native-ui-safety".equals(text(receipt,"campaignId"))&&hash.equals(text(receipt,"targetMetadataSha256"))&&TARGET.equals(text(receipt,"targetEntityId"))&&TARGET.equals(target.getAttribute("entityID"))&&peer.matches("http://localhost:18080/p/plan_[0-9A-HJKMNP-TV-Z]{26}"));
   var entries=new LinkedHashMap<String,TranscriptEntry>();for(var e:context.transcript().list(context.runId()))require(context.runId().equals(e.runId())&&(e.decodedSamlRef()==null||("transcripts/"+context.runId()+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef()))&&entries.put(e.id(),e)==null);
   var restore=receipt.path("restoration");require(restore.path("restored").isBoolean()&&restore.path("restored").asBoolean());
   var before=original(restore.path("before"),context.runId(),hash,peer,"client-inventory",entries,evidence);var after=original(restore.path("after"),context.runId(),hash,peer,"client-inventory",entries,evidence);
   var scopeBefore=original(restore.path("scopeBefore"),context.runId(),hash,peer,"native-scope",entries,evidence);var scopeAfter=original(restore.path("scopeAfter"),context.runId(),hash,peer,"native-scope",entries,evidence);
   require(before.json().path("clients").isArray()&&before.json().path("clients").isEmpty()&&before.json().path("clients").equals(after.json().path("clients")));
   for(String field:List.of("runtime","realm","clientPolicies","sourceJarSha256","customNativeFiles"))require(scopeBefore.json().path(field).equals(scopeAfter.json().path(field)));
   stage="native-operative-source";verifyScope(scopeBefore.json());verifySource(context.runId());
   var accepted=new ArrayList<String>();for(var v:VARIANTS)if(!Set.of("ui-safety-privacy-javascript").contains(v))accepted.add(v);
   var collected=MetadataAlgorithmEvidence.collect(accepted,context,content,targetRaw);require(collected.issues().isEmpty()&&collected.exchanges().size()==accepted.size());
   var exchanges=new HashMap<String,MetadataAlgorithmEvidence.Exchange>();for(var ex:collected.exchanges())require(exchanges.put(ex.variant(),ex)==null);var members=receipt.path("members");require(members.isArray()&&members.size()==VARIANTS.size());
   boolean unsafe=false;Original informationBrowser=null;String informationFixtureHash=null;int credentials=0;var clientIds=new HashSet<String>();var requestsUsed=new HashSet<String>();Instant last=scopeBefore.entry().timestamp();int browserIndex=0;var urlUses=new ArrayList<String>();
   for(int i=0;i<VARIANTS.size();i++){
    var member=members.get(i);String variant=text(member,"variant");require(VARIANTS.get(i).equals(variant));stage="fixture-"+variant;
    var prepared=entries.values().stream().filter(e->e.direction()==Direction.OUTBOUND&&"MetadataPrepared".equals(e.samlSummary().get("type"))&&variant.equals(e.samlSummary().get("variant"))).toList();require(prepared.size()==1);var e=prepared.getFirst();var raw=content.readDecodedSaml(e);
    require(e.timestamp().isAfter(last)&&sha(raw).equals(text(member,"fixtureSha256"))&&sha(raw).equals(e.samlSummary().get("metadataSha256"))&&"PREPARED".equals(e.samlSummary().get("delivery"))&&Integer.valueOf(200).equals(e.status()));
    var fetch=entries.get(String.valueOf(e.samlSummary().get("fetchTranscriptId")));require(fetch!=null&&fetch.direction()==Direction.INBOUND&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&variant.equals(fetch.samlSummary().get("variant"))&&Integer.valueOf(200).equals(fetch.status())&&fetch.id().equals(e.correlationId())&&Objects.equals(fetch.url(),e.url())&&!fetch.timestamp().isAfter(e.timestamp()));
    var metadata=SecureXml.parse(raw).getDocumentElement();require(MD.equals(metadata.getNamespaceURI())&&"EntityDescriptor".equals(metadata.getLocalName())&&peer.equals(metadata.getAttribute("entityID"))&&SamlSchemaValidation.isValid(metadata,SamlSchemaValidation.SchemaKind.METADATA));verifySignature(metadata);
    evidence.add(new EvidenceRef("transcript",fetch.id()));evidence.add(new EvidenceRef("transcript",e.id()));
    var converted=original(member.path("converter"),context.runId(),hash,peer,"converter",entries,evidence);var applied=original(member.path("application"),context.runId(),hash,peer,"ui-prerequisite-application",entries,evidence);var restored=original(member.path("restoration"),context.runId(),hash,peer,"client-inventory",entries,evidence);
    for(var v:List.of(converted,applied))require(variant.equals(text(v.json(),"variant"))&&sha(raw).equals(text(v.json(),"fixtureSha256")));
    require(converted.entry().timestamp().isAfter(e.timestamp())&&applied.entry().timestamp().isAfter(converted.entry().timestamp())&&restored.entry().timestamp().isAfter(applied.entry().timestamp())&&variant.equals(text(restored.json(),"variant"))&&restored.json().path("clients").equals(before.json().path("clients")));
    var conversion=nativeResponse(converted,"POST",ADMIN+"/client-description-converter",200,e.timestamp());require(sha(raw).equals(text(converted.json().path("native"),"requestSha256"))&&peer.equals(text(conversion,"clientId"))&&"saml".equals(text(conversion,"protocol"))&&!conversion.has("consentRequired"));
    var attributes=conversion.path("attributes");require(attributes.isObject()&&!attributes.has("saml.metadataDescriptorUrl")&&!attributes.has("saml.useMetadataDescriptorUrl")&&"true".equals(text(attributes,"saml.client.signature")));
    require(sha(JSON.writeValueAsBytes(conversion)).equals(text(applied.json(),"converterSha256"))&&applied.json().path("consentRequired").isBoolean()&&applied.json().path("consentRequired").asBoolean());var recipe=(ObjectNode)conversion.deepCopy();recipe.put("consentRequired",true);require(sha(JSON.writeValueAsBytes(recipe)).equals(text(applied.json().path("native"),"requestSha256")));
    String candidate=verifyUiInput(metadata,variant,attributes);stage="native-application-"+variant;
    if(!accepted.contains(variant)){
     require("rejected".equals(text(member,"nativeAdmission"))&&!member.has("persisted")&&!member.has("browser"));var error=nativeResponse(applied,"POST",ADMIN+"/clients",400,converted.entry().timestamp());require(error.equals(member.path("rejection"))&&"invalid_input".equals(text(error,"error"))&&((variant.contains("logo")?"Logo":"Policy")+" URL uses an illegal scheme").equals(text(error,"error_description")));require(member.path("orchestrationOnlyContinue").asBoolean());
     // No browser request or target protocol result is inferred for a native admission refusal.
     require(entries.values().stream().noneMatch(t->t.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(t.samlSummary().get("type"))&&variant.equals(t.samlSummary().get("variant"))));
    }else{
     require("accepted".equals(text(member,"nativeAdmission")));nativeResponse(applied,"POST",ADMIN+"/clients",201,converted.entry().timestamp());
     var persisted=original(member.path("persisted"),context.runId(),hash,peer,"operative-client",entries,evidence);var browser=original(member.path("browser"),context.runId(),hash,peer,"native-browser-ui",entries,evidence);require(persisted.entry().timestamp().isAfter(applied.entry().timestamp())&&browser.entry().timestamp().isAfter(persisted.entry().timestamp())&&restored.entry().timestamp().isAfter(browser.entry().timestamp()));
     for(var v:List.of(persisted,browser))require(variant.equals(text(v.json(),"variant"))&&sha(raw).equals(text(v.json(),"fixtureSha256")));var saved=persisted.json().path("client");verifyClient(conversion,saved,peer);require(clientIds.add(text(saved,"id")));
     var ex=exchanges.get(variant);require(ex!=null);var request=entries.get(ex.evidence().get(2).reference());var response=entries.get(ex.evidence().get(3).reference());require(requestsUsed.add(request.id())&&request.timestamp().isAfter(persisted.entry().timestamp())&&response.timestamp().isBefore(browser.entry().timestamp()));
     require(Instant.parse(text(browser.json().path("observation"),"startedAt")).isAfter(persisted.entry().timestamp()));verifyBrowser(context,variant,++browserIndex,browser,request,response,metadata,saved,entries,candidate);evidence.addAll(ex.evidence());
     var observed=browser.json().path("observation");credentials+=observed.path("credentialSubmissions").asInt(-1);
     unsafe|=safetyObservation(observed,variant,candidate,request.timestamp(),response.timestamp());
     if(variant.equals("ui-safety-information-javascript")){informationBrowser=browser;informationFixtureHash=sha(raw);}

    }
    last=restored.entry().timestamp();
   }
   require(before.entry().timestamp().isBefore(scopeBefore.entry().timestamp())&&after.entry().timestamp().isAfter(last)&&scopeAfter.entry().timestamp().isAfter(after.entry().timestamp())&&sha(bytes).equals(sha(safe(file,262144))));
   evidence.add(new EvidenceRef("native-ui-policy",context.runId()+".keycloak-ui-safety.json#"+sha(bytes)));
   require(credentials==1&&browserIndex==3);verifyCounts(receipt.path("operations"),browserIndex,credentials);
   if(calibration){require(informationBrowser!=null);unsafe|=isolatedCalibration(receipt.path("isolatedCalibration"),context.runId(),hash,informationFixtureHash,informationBrowser.json());evidence.add(new EvidenceRef("isolated-ui-calibration",context.runId()+".keycloak-ui-safety/isolated-output.json"));}
   String reason=unsafe?"browser.ui-safety.native-execution-observed":"browser.ui-safety.native-image-context-and-unused-urls";
   return Optional.of(new CaseOutcome(unsafe?Outcome.VIOLATED:Outcome.SATISFIED_WITH_NOTE,null,reason,reason,evidence.stream().distinct().toList(),Map.of("product","keycloak","native_originals_verified",true,"native_source_and_theme_verified",true,"restoration_verified",true,"full_required_conditions",List.of("SCRIPT_CAPABLE_LOGO","INFORMATION_JAVASCRIPT","PRIVACY_JAVASCRIPT"),"verified_nonuse",List.of("InformationURL","PrivacyStatementURL"),"browser_contexts",1,"user_login_count",credentials,"native_ui_saml_flows",browserIndex,"counterfactual_calibration_only",calibration)));

  }catch(Exception unproven){return Optional.of(new CaseOutcome(Outcome.NOT_VERIFIED,"native_ui_consumer_unproven","browser.ui-native-consumer.evidence-incomplete","browser.ui-native-consumer.evidence-incomplete",List.of(),Map.of("evidence_issue",stage)));}
 }
 private static JsonNode nativeResponse(Original original,String method,String url,int status,Instant after)throws Exception{
  var v=original.json().path("native");require(method.equals(text(v,"method"))&&url.equals(text(v,"url"))&&v.path("status").isInt()&&v.path("status").asInt()==status);Instant start=Instant.parse(text(v,"startedAt")),end=Instant.parse(text(v,"finishedAt"));require(!start.isBefore(after)&&!end.isBefore(start)&&!end.isAfter(original.entry().timestamp()));
  var raw=Base64.getDecoder().decode(v.path("responseBase64").asText());require(sha(raw).equals(text(v,"responseSha256")));return raw.length==0?JSON.createObjectNode():JSON.readTree(raw);
 }
 private static void verifyScope(JsonNode v){require(v.path("customNativeFiles").isArray()&&set(v.path("customNativeFiles")).equals(Set.of("/opt/keycloak/providers/README.md","/opt/keycloak/themes/README.md")));var runtime=v.path("runtime");require(runtime.path("mounts").isArray()&&runtime.path("mounts").size()==1&&"/opt/keycloak/data/import/realm-samlscope.json".equals(text(runtime.path("mounts").get(0),"Destination"))&&"bind".equals(text(runtime.path("mounts").get(0),"Type"))&&runtime.path("mounts").get(0).path("RW").isBoolean()&&!runtime.path("mounts").get(0).path("RW").asBoolean()&&runtime.path("running").asBoolean()&&"sha256:9d1f1b2b7261ff53c66cb1092dfcdc34a5fb77e81f9e6a6e75b8b6a795de8067".equals(text(runtime,"image"))&&text(runtime,"version").startsWith("Keycloak 26.7.2\n")&&text(runtime,"containerId").matches("[a-f0-9]{64}"));Instant.parse(text(runtime,"startedAt"));
  var realm=v.path("realm");require("samlscope".equals(text(realm,"realm"))&&realm.path("enabled").asBoolean()&&realm.has("loginTheme")&&realm.path("loginTheme").isNull()&&realm.has("defaultLocale")&&realm.path("defaultLocale").isNull()&&realm.path("internationalizationEnabled").isBoolean()&&!realm.path("internationalizationEnabled").asBoolean());require(v.at("/clientPolicies/policies/policies").isArray()&&v.at("/clientPolicies/policies/policies").isEmpty()&&v.at("/clientPolicies/profiles/profiles").isArray()&&v.at("/clientPolicies/profiles/profiles").isEmpty()&&SERVICES.equals(text(v.path("sourceJarSha256"),"services"))&&THEMES.equals(text(v.path("sourceJarSha256"),"themes")));
 }
 private void verifySource(String run)throws Exception{var root=directory.resolve(run+".keycloak-ui-safety");for(var jar:List.of("native-services.jar","native-themes.jar")){var path=root.resolve(jar);var raw=safe(path,33554432);require(sha(raw).equals(jar.contains("services")?SERVICES:THEMES));try(var zip=new ZipFile(path.toFile())){for(var pin:(jar.contains("services")?CLASSES:TEMPLATES).entrySet()){var entry=zip.getEntry(pin.getKey());require(entry!=null);try(var in=zip.getInputStream(entry)){require(sha(in.readNBytes(1048577)).equals(pin.getValue()));}}}}}
 private byte[] safe(Path path,long maximum)throws Exception{require(path.normalize().startsWith(directory)&&Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)&&Files.size(path)>0&&Files.size(path)<=maximum);for(var p=path.getParent();p!=null&&p.startsWith(directory);p=p.getParent())require(!Files.isSymbolicLink(p));return Files.readAllBytes(path);}
 private static void verifyClient(JsonNode converted,JsonNode saved,String peer){require(text(saved,"id").matches("[a-f0-9-]{36}")&&peer.equals(text(saved,"clientId"))&&"saml".equals(text(saved,"protocol"))&&saved.path("enabled").asBoolean()&&saved.path("consentRequired").isBoolean()&&saved.path("consentRequired").asBoolean()&&!saved.has("secret")&&!saved.has("registrationAccessToken")&&saved.path("authenticationFlowBindingOverrides").isEmpty());
  var fields=converted.fields();while(fields.hasNext()){var f=fields.next();if(f.getKey().equals("attributes")){var attrs=f.getValue().fields();while(attrs.hasNext()){var attr=attrs.next();require(attr.getValue().equals(saved.path("attributes").get(attr.getKey())));}nativeDefaults(f.getValue(),saved.path("attributes"));}else if(f.getKey().equals("redirectUris"))require(set(f.getValue()).equals(set(saved.path(f.getKey()))));else if(f.getKey().equals("protocolMappers"))require(f.getValue().isArray()&&f.getValue().isEmpty()&&!saved.has("protocolMappers"));else require(f.getValue().equals(saved.get(f.getKey())));}
 }
 private static void nativeDefaults(JsonNode converted,JsonNode saved){var defaults=Map.of("saml.force.post.binding","true","realm_client","false","saml_force_name_id_format","false","saml_name_id_format","username","saml.allow.ecp.flow","false","saml_signature_canonicalization_method","http://www.w3.org/2001/10/xml-exc-c14n#");var extra=saved.fields();int count=0;while(extra.hasNext()){var f=extra.next();if(converted.has(f.getKey()))continue;count++;if(defaults.containsKey(f.getKey()))require(defaults.get(f.getKey()).equals(f.getValue().asText()));else if(f.getKey().equals("client.secret.creation.time"))require(f.getValue().asText().matches("[0-9]{10}"));else if(f.getKey().equals("saml.artifact.binding.identifier"))require(Base64.getDecoder().decode(f.getValue().asText()).length==20);else require(false);}require(count==8);}
 private static final String TOKEN="SAMLscope-UI-safety-v1",PROBE="javascript:alert('"+TOKEN+"')",
 SVG="<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"180\" height=\"48\"><rect width=\"180\" height=\"48\" fill=\"#1d4ed8\"/><script>alert('"+TOKEN+"')</script></svg>";
 static String verifyUiInput(Element metadata,String variant,JsonNode attributes)throws Exception{
  var role=one(metadata,MD,"SPSSODescriptor");var extensions=children(role,MD,"Extensions");var infos=extensions.isEmpty()?List.<Element>of():children(extensions.getFirst(),UI,"UIInfo");
  if(variant.equals("control")){require(infos.isEmpty()&&!attributes.has("logoUri")&&!attributes.has("policyUri"));return "";}
  require(infos.size()==1);var info=infos.getFirst();String name=switch(variant){case "ui-safety-logo-data"->"Logo";case "ui-safety-information-javascript"->"InformationURL";case "ui-safety-privacy-javascript"->"PrivacyStatementURL";default->throw new IllegalArgumentException();};
  var display=children(info,UI,"DisplayName");require(display.size()==1&&"en".equals(display.getFirst().getAttributeNS(XML,"lang"))&&"SAMLscope URL policy control".equals(display.getFirst().getTextContent()));
  require(children(info,UI,"Logo").size()+children(info,UI,"InformationURL").size()+children(info,UI,"PrivacyStatementURL").size()==1);var nodes=children(info,UI,name);require(nodes.size()==1);String url=nodes.getFirst().getTextContent();
  if(name.equals("Logo")){require(url.equals("data:image/svg+xml;base64,"+Base64.getEncoder().encodeToString(SVG.getBytes(StandardCharsets.UTF_8)))&&"180".equals(nodes.getFirst().getAttribute("width"))&&"48".equals(nodes.getFirst().getAttribute("height"))&&url.equals(text(attributes,"logoUri"))&&!attributes.has("policyUri"));}
  else{require(PROBE.equals(url)&&"en".equals(nodes.getFirst().getAttributeNS(XML,"lang")));if(name.equals("PrivacyStatementURL"))require(url.equals(text(attributes,"policyUri"))&&!attributes.has("logoUri"));else require(!attributes.has("logoUri")&&!attributes.has("policyUri")&&!attributes.has("informationUri"));}
  return url;
 }
 static void verifyCounts(JsonNode counts,int flows,int credentials){require(counts.path("configurationWriteAttempts").isInt()&&counts.path("configurationWriteAttempts").asInt()==7&&counts.path("successfulConfigurationWrites").asInt(-1)==6&&counts.path("browserAttempts").asInt(-1)==flows&&counts.path("actualSamlSubmissions").asInt(-1)==flows&&counts.path("credentialSubmissions").asInt(-1)==credentials&&counts.path("browserContexts").asInt(-1)==1&&counts.path("productRestarts").asInt(-1)==0&&counts.path("humanOperations").asInt(-1)==0&&counts.path("restored").isBoolean()&&counts.path("restored").asBoolean());}
 static boolean safetyObservation(JsonNode observed,String variant,String candidate,Instant request,Instant response)throws Exception{
  require(observed.path("nativeDialogs").isArray()&&observed.path("nativeSecurityBlocks").isArray());
  var detector=observed.path("detector");require("isolated-sandbox-unsafe-sinks".equals(text(detector,"scope"))&&sha(SVG.getBytes(StandardCharsets.UTF_8)).equals(text(detector,"svgSha256"))&&PROBE.equals(text(detector,"javascriptHref"))&&detector.path("stockProductObservation").isBoolean()&&!detector.path("stockProductObservation").asBoolean());
  for(String key:List.of("activeSvg","javascriptAnchor")){var rows=detector.path(key).path("dialogs");require(rows.isArray()&&rows.size()==1&&"alert".equals(text(rows.get(0),"type"))&&rows.get(0).path("probeToken").isBoolean()&&rows.get(0).path("probeToken").asBoolean());}
  for(String key:List.of("safeImg","safeAnchor"))require(detector.path(key).path("dialogs").isArray()&&detector.path(key).path("dialogs").isEmpty());
  var begin=Instant.parse(text(detector,"startedAt"));var end=Instant.parse(text(detector,"completedAt"));require(!end.isBefore(begin)&&end.isBefore(request));
  for(var dialog:observed.path("nativeDialogs")){var at=Instant.parse(text(dialog,"recordedAt"));require("alert".equals(text(dialog,"type"))&&dialog.path("probeToken").isBoolean()&&dialog.path("probeToken").asBoolean()&&!at.isBefore(request)&&at.isBefore(response)&&"native-consent-page".equals(text(dialog,"source")));}
  if(variant.equals("ui-safety-logo-data")){var images=observed.path("consent").path("images");require(images.size()==1&&candidate.equals(text(images.get(0),"src"))&&"img".equals(text(images.get(0),"tag"))&&images.get(0).path("naturalWidth").asInt(-1)==180&&images.get(0).path("naturalHeight").asInt(-1)==48&&images.get(0).path("complete").asBoolean());}
  else require(observed.path("nativeDialogs").isEmpty());
  return !observed.path("nativeDialogs").isEmpty();
 }
 private static final String ISOLATED_RENDERER_SHA="efa0e7610eda1712b14bb2aacd8527229a3ab946f44834b3bc8c0bbdfeed4a3f";
 private boolean isolatedCalibration(JsonNode ref,String run,String targetHash,String fixtureHash,JsonNode nativeBrowser)throws Exception{
  String inputName=text(ref,"inputFile"),outputName=text(ref,"outputFile"),sourceName=text(ref,"rendererFile");require(inputName.equals("isolated-input.json")&&outputName.equals("isolated-output.json")&&sourceName.equals("isolated-renderer.mjs"));var folder=directory.resolve(run+".keycloak-ui-safety");
  var inputRaw=safe(folder.resolve(inputName),2097152);var outputRaw=safe(folder.resolve(outputName),4194304);var sourceRaw=safe(folder.resolve(sourceName),131072);require(sha(inputRaw).equals(text(ref,"inputSha256"))&&sha(outputRaw).equals(text(ref,"outputSha256"))&&sha(sourceRaw).equals(text(ref,"rendererSha256"))&&ISOLATED_RENDERER_SHA.equals(sha(sourceRaw)));
  var policyRaw=safe(folder.resolve("native-policy-supplement.json"),131072);require(sha(policyRaw).equals(text(ref,"nativePolicySha256")));var policy=JSON.readTree(policyRaw);require("after-restoration-readback-not-historic-native-response-header".equals(text(policy,"captureType"))&&run.equals(text(policy,"runId"))&&targetHash.equals(text(policy,"targetMetadataSha256"))&&"samlscope".equals(text(policy,"realm")));String csp=text(policy.path("browserSecurityHeaders"),"contentSecurityPolicy");require(csp.equals(text(policy.path("nativePublicPolicyReadback"),"contentSecurityPolicy"))&&"GET".equals(text(policy.path("nativePublicPolicyReadback"),"method"))&&"http://localhost:18180/realms/samlscope/login-actions/required-action".equals(text(policy.path("nativePublicPolicyReadback"),"url"))&&policy.path("productConfigurationWrites").asInt(-1)==0&&policy.path("samlRequests").asInt(-1)==0&&policy.path("credentialPosts").asInt(-1)==0);
  var input=JSON.readTree(inputRaw);var out=JSON.readTree(outputRaw);for(var value:List.of(input,out))require(sha(policyRaw).equals(text(value,"nativePolicyOriginalSha256"))&&text(policy,"captureType").equals(text(value,"nativePolicyCaptureType"))&&csp.equals(text(value,"nativeContentSecurityPolicy")));require(input.path("counterfactualCalibrationOnly").isBoolean()&&input.path("counterfactualCalibrationOnly").asBoolean()&&out.path("counterfactualCalibrationOnly").isBoolean()&&out.path("counterfactualCalibrationOnly").asBoolean()&&out.path("actualProductFinding").isBoolean()&&!out.path("actualProductFinding").asBoolean()&&out.path("controlsAdopted").isBoolean()&&!out.path("controlsAdopted").asBoolean());
  for(var value:List.of(input,out))require(run.equals(text(value,"runId"))&&targetHash.equals(text(value,"targetMetadataSha256"))&&fixtureHash.equals(text(value,"fixtureSha256"))&&"ui-safety-information-javascript".equals(text(value,"variant")));
  var nativeHtml=Base64.getDecoder().decode(text(nativeBrowser,"publicHtmlBase64"));require(PROBE.equals(text(input,"href"))&&Arrays.equals(nativeHtml,Base64.getDecoder().decode(text(input,"publicHtmlBase64")))&&sha(nativeHtml).equals(text(input,"publicHtmlSha256"))&&sha(inputRaw).equals(text(out,"inputSha256"))&&ISOLATED_RENDERER_SHA.equals(text(out,"rendererSourceSha256"))&&out.path("productConfigurationWrites").asInt(-1)==0&&out.path("samlRequests").asInt(-1)==0&&out.path("credentialPosts").asInt(-1)==0&&out.path("isolatedBrowserContexts").asInt(-1)==2);
  var rows=out.path("records");require(rows.isArray()&&rows.size()==2);String anchor="<a id=\"samlscope-isolated-unsafe\" href=\""+PROBE+"\">Isolated information URL</a>";byte[] stockBefore=null;Instant prior=Instant.parse(text(out,"startedAt"));require(prior.isAfter(Instant.parse(text(policy.path("nativePublicPolicyReadback"),"finishedAt"))));
  for(int i=0;i<2;i++){var row=rows.get(i);require((i==0?"isolated-stock-native-renderer":"isolated-unsanitized-information-anchor").equals(text(row,"selectedPath"))&&row.path("counterfactualCalibrationOnly").isBoolean()&&row.path("counterfactualCalibrationOnly").asBoolean()&&PROBE.equals(text(row,"href"))&&sha(nativeHtml).equals(text(row,"sourceHtmlSha256")));require(csp.equals(text(row,"nativeContentSecurityPolicy"))&&csp.equals(text(row,"renderedContentSecurityPolicy"))&&row.path("policyMutated").isBoolean()&&!row.path("policyMutated").asBoolean());var before=Base64.getDecoder().decode(text(row,"beforeHtmlBase64"));var after=Base64.getDecoder().decode(text(row,"afterHtmlBase64"));require(sha(before).equals(text(row,"beforeHtmlSha256"))&&sha(after).equals(text(row,"afterHtmlSha256"))&&Arrays.equals(before,nativeHtml));
   Instant begin=Instant.parse(text(row,"startedAt")),end=Instant.parse(text(row,"completedAt"));require(!begin.isBefore(prior)&&!end.isBefore(begin)&&!end.isAfter(Instant.parse(text(out,"completedAt"))));prior=end;var dialogs=row.path("dialogs");require(dialogs.isArray());
   if(i==0){require(Arrays.equals(before,after)&&dialogs.isEmpty());stockBefore=before;}
   else{String changed=new String(after,StandardCharsets.UTF_8);require(Arrays.equals(before,stockBefore)&&changed.indexOf(anchor)>=0&&changed.indexOf(anchor)==changed.lastIndexOf(anchor)&&changed.replace(anchor,"").equals(new String(before,StandardCharsets.UTF_8))&&dialogs.size()==1);var dialog=dialogs.get(0);Instant at=Instant.parse(text(dialog,"recordedAt"));require("alert".equals(text(dialog,"type"))&&dialog.path("probeToken").isBoolean()&&dialog.path("probeToken").asBoolean()&&"isolated-renderer".equals(text(dialog,"source"))&&!at.isBefore(begin)&&!at.isAfter(end));}
  }
  return true;
 }
 private void verifyBrowser(CaseContext context,String variant,int index,Original original,TranscriptEntry request,TranscriptEntry response,Element metadata,JsonNode saved,Map<String,TranscriptEntry> entries,String candidate)throws Exception{
  var v=original.json();var observed=v.path("observation");require("samlscope-keycloak-ui-safety-browser-v1".equals(text(observed,"schema"))&&context.runId().equals(text(observed,"runId"))&&variant.equals(text(observed,"variant"))&&observed.path("contextIndex").asInt(-1)==1&&"single-campaign-Chrome".equals(text(observed,"browserInstance"))&&observed.path("operationIndex").asInt(-1)==index&&"en-US".equals(text(observed,"preferredLanguage"))&&observed.path("credentialsPersisted").isBoolean()&&!observed.path("credentialsPersisted").asBoolean()&&observed.path("externalRequestsPermitted").isBoolean()&&!observed.path("externalRequestsPermitted").asBoolean());
  Instant start=Instant.parse(text(observed,"startedAt")),end=Instant.parse(text(observed,"completedAt"));require(start.isBefore(request.timestamp())&&end.isAfter(response.timestamp())&&!end.isAfter(original.entry().timestamp())&&observed.path("requests").isArray()&&observed.path("requests").size()==1);var sent=SecureXml.parse(content.readDecodedSaml(request)).getDocumentElement();
  var requestRaw=content.readDecodedSaml(request);var signing=certificate(text(saved.path("attributes"),"saml.signing.certificate"));require(roleCertificates(metadata,"signing").stream().anyMatch(c->Arrays.equals(c.getPublicKey().getEncoded(),signing.getPublicKey().getEncoded()))&&new XmlSignatureVerifier().hasValidEnvelopedSignature(sent,signing));
  var r=observed.path("requests").get(0);String requestId=sent.getAttribute("ID");require(requestId.equals(text(r,"requestId"))&&"POST".equals(text(r,"method"))&&request.method().equals("POST")&&request.url().equals(text(r,"targetUrl"))&&request.url().equals(sent.getAttribute("Destination"))&&sha(requestRaw).equals(text(r,"sha256"))&&requestRaw.length==r.path("bytes").asInt(-1)&&r.path("rawQuery").isNull()&&"en-US".equals(text(r,"acceptLanguage"))&&Instant.parse(text(r,"recordedAt")).isAfter(request.timestamp())&&Instant.parse(text(r,"recordedAt")).isBefore(response.timestamp()));
  require(v.path("exchange").path("success").asBoolean()&&requestId.equals(text(v.path("exchange"),"request_id"))&&set(v.path("exchange").path("transcript_ids")).equals(Set.of(request.id(),response.id())));
  var consent=observed.path("consent");require("/realms/samlscope/login-actions/required-action".equals(text(consent,"path"))&&Instant.parse(text(consent,"recordedAt")).isAfter(request.timestamp())&&Instant.parse(text(consent,"recordedAt")).isBefore(response.timestamp()));
  var publicHtml=Base64.getDecoder().decode(text(v,"publicHtmlBase64"));require(new String(publicHtml,StandardCharsets.UTF_8).contains(metadata.getAttribute("entityID")));require(publicHtml.length==consent.path("publicHtmlBytes").asInt(-1)&&sha(publicHtml).equals(text(consent,"publicHtmlSha256")));var rendered=html(publicHtml);require(rendered.consent&&rendered.accept&&rendered.nativeGrant&&rendered.language.equals("en")&&rendered.images.equals(consent.path("images").findValuesAsText("src"))&&rendered.links.equals(consent.path("policyLinks").findValuesAsText("href")));
  var nativePages=observed.path("nativePages");require(nativePages.isArray()&&nativePages.size()>=1);int found=0;for(var page:nativePages){require(page.path("status").asInt(-1)==200&&text(page,"bodySha256").matches("[a-f0-9]{64}")&&page.path("bytes").asInt(-1)>0);var at=Instant.parse(text(page,"recordedAt"));require(at.isAfter(request.timestamp())&&at.isBefore(end));if(text(page,"path").equals(text(consent,"path"))){require(at.isBefore(Instant.parse(text(consent,"recordedAt"))));found++;}}require(found==1);
  var images=consent.path("images");var links=consent.path("policyLinks");require(images.isArray()&&links.isArray());if(saved.path("attributes").has("logoUri")){require(images.size()==1&&text(images.get(0),"src").equals(text(saved.path("attributes"),"logoUri"))&&images.get(0).path("visible").isBoolean()&&images.get(0).path("visible").asBoolean()&&links.isEmpty());}else if(saved.path("attributes").has("policyUri")){require(images.isEmpty()&&links.size()==1&&text(links.get(0),"href").equals(candidate)&&"privacy policy.".equals(text(links.get(0),"text"))&&links.get(0).path("visible").asBoolean());}else require(images.isEmpty()&&links.isEmpty());
 }
 static final class Rendered {boolean consent,accept,nativeGrant;String language="";final List<String>images=new ArrayList<>(),links=new ArrayList<>();}
 private static String attribute(MutableAttributeSet attrs,String name){for(var names=attrs.getAttributeNames();names.hasMoreElements();){var key=names.nextElement();if(name.equals(key.toString()))return Objects.toString(attrs.getAttribute(key),"");}return "";}
 static Rendered html(byte[] raw)throws Exception{String text=new String(raw,StandardCharsets.UTF_8);require(!text.contains("<script")&&!text.contains("session_code=")&&!text.contains("name=\"password\"")&&!text.contains("name=\"username\""));var result=new Rendered();new ParserDelegator().parse(new java.io.StringReader(text),new HTMLEditorKit.ParserCallback(){
  private boolean oauth=false;private int depth=0;private String anchor=null;
  public void handleStartTag(HTML.Tag tag,MutableAttributeSet attrs,int pos){String id=Objects.toString(attrs.getAttribute(HTML.Attribute.ID),"");if(id.equals("kc-oauth")){result.consent=true;oauth=true;depth=1;}else if(oauth)depth++;if(tag==HTML.Tag.HTML)result.language=attribute(attrs,"lang");if(tag==HTML.Tag.BODY)result.nativeGrant="login-login-oauth-grant".equals(Objects.toString(attrs.getAttribute("data-page-id"),""));if(tag==HTML.Tag.A&&oauth){anchor=Objects.toString(attrs.getAttribute(HTML.Attribute.HREF),"");result.links.add(anchor);}if(Objects.toString(attrs.getAttribute(HTML.Attribute.NAME),"").equals("accept"))result.accept=true;}
  public void handleEndTag(HTML.Tag tag,int pos){if(oauth&&--depth==0)oauth=false;if(tag==HTML.Tag.A)anchor=null;}
  public void handleSimpleTag(HTML.Tag tag,MutableAttributeSet attrs,int pos){if(tag==HTML.Tag.IMG)result.images.add(Objects.toString(attrs.getAttribute(HTML.Attribute.SRC),""));if(tag==HTML.Tag.INPUT)require(attrs.getAttribute(HTML.Attribute.VALUE)==null);if(Objects.toString(attrs.getAttribute(HTML.Attribute.NAME),"").equals("accept"))result.accept=true;}
 },true);return result;}
 private static List<X509Certificate> roleCertificates(Element metadata,String use)throws Exception{var values=new ArrayList<X509Certificate>();for(var key:children(one(metadata,MD,"SPSSODescriptor"),MD,"KeyDescriptor")){if(key.hasAttribute("use")&&!use.equals(key.getAttribute("use")))continue;var nodes=key.getElementsByTagNameNS(DS,"X509Certificate");for(int i=0;i<nodes.getLength();i++)values.add(certificate(nodes.item(i).getTextContent()));}return values;}
 private static void verifySignature(Element metadata)throws Exception{var signatures=children(metadata,DS,"Signature");require(signatures.size()==1);var certs=signatures.getFirst().getElementsByTagNameNS(DS,"X509Certificate");require(certs.getLength()==1);require(new XmlSignatureVerifier().hasValidEnvelopedSignature(metadata,certificate(certs.item(0).getTextContent())));}
 private static X509Certificate certificate(String text)throws Exception{return (X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(text)));}
 private static Element one(Element root,String ns,String name){var values=children(root,ns,name);require(values.size()==1);return values.getFirst();}
 private static Set<String> set(JsonNode array){require(array.isArray());var values=new HashSet<String>();for(var v:array)require(v.isTextual()&&values.add(v.asText()));return values;}
 private static String text(JsonNode value,String key){var node=value.path(key);require(node.isTextual()&&!node.asText().isBlank());return node.asText();}
 private static String sha(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 private static void require(boolean yes){if(!yes)throw new IllegalArgumentException("Native UI safety proof incomplete");}
}
