package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import org.w3c.dom.Element;

/** Original-backed retained-metadata expiry. HTTP errors and declarations cannot establish expiry rejection. */
public final class MetadataValidityEvidence {
    public static final String SCHEMA="samlscope-metadata-validity-epoch-v1";
    public static final String ADAPTER="shibboleth-native-filesystem-validity-v1";
    private static final String RUN="run_[0-9A-HJKMNP-TV-Z]{26}", MD="urn:oasis:names:tc:SAML:2.0:metadata", P="urn:oasis:names:tc:SAML:2.0:protocol", S="urn:oasis:names:tc:SAML:2.0:assertion", DS="http://www.w3.org/2000/09/xmldsig#", N="urn:mace:shibboleth:2.0:metadata", XSI="http://www.w3.org/2001/XMLSchema-instance";
    private static final String SUCCESS="urn:oasis:names:tc:SAML:2.0:status:Success";
    private static final List<String> VARIANTS=List.of("live-validity-root","live-validity-parent","live-validity-child");
    private final Path directory; private final TranscriptContentReader content;
    private final Function<String,byte[]> metadata; private final BiFunction<String,String,Optional<PlanCredentials>> keys;
    public MetadataValidityEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,BiFunction<String,String,Optional<PlanCredentials>> keys) {
        this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize(); this.content=Objects.requireNonNull(content); this.metadata=Objects.requireNonNull(metadata); this.keys=Objects.requireNonNull(keys);
    }
    public boolean exists(String run) { return run!=null&&run.matches(RUN)&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS); }
    public Optional<CaseOutcome> evaluate(CaseContext context) {
        try {
            require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete()&&context.runId().matches(RUN));
            var folder=directory.resolve(context.runId()); safeParents(folder); require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
            var manifestRaw=original(folder,"manifest.json");var manifest=json(manifestRaw);
            require(SCHEMA.equals(text(manifest,"schema"))&&ADAPTER.equals(text(manifest,"adapter"))&&context.runId().equals(text(manifest,"runId")));
            var originals=manifest.path("originals");require(originals.isObject()&&originals.size()>0);
            var supplied=new HashSet<String>();originals.fieldNames().forEachRemaining(supplied::add);try(var files=Files.list(folder)){var actual=files.filter(p->!p.getFileName().toString().equals("manifest.json")).map(p->p.getFileName().toString()).collect(java.util.stream.Collectors.toSet());require(actual.equals(supplied));}
            for(var it=originals.fields();it.hasNext();) {var row=it.next();require(hash(original(folder,row.getKey())).equals(row.getValue().asText()));}
            var targetRaw=metadata.apply(context.runId());require(hash(targetRaw).equals(text(manifest,"targetMetadataSha256")));
            var target=SecureXml.parse(targetRaw).getDocumentElement();require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName()));
            var targetKeys=MetadataAlgorithmEvidence.signingKeys(target);require(!targetKeys.isEmpty());var entity=text(manifest,"entityId");var providerId="Validity"+context.runId();
            validateConfiguration(folder,entity,providerId,text(manifest,"sourcePath"));
            require(runtime(folder,"target-container-inspect-start.json").equals(runtime(folder,"target-container-inspect-end.json")));validateNativeClockBoundary(folder);
            var entries=new HashMap<String,TranscriptEntry>();var requestIds=new HashSet<String>();
            for(var e:context.transcript().list(context.runId())) {require(context.runId().equals(e.runId())&&entries.put(e.id(),e)==null&&(e.decodedSamlRef()==null||("transcripts/"+context.runId()+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())));if(e.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(e.samlSummary().get("type")))require(requestIds.add(String.valueOf(e.samlSummary().get("id"))));}
            var audit=audits(original(folder,"native-request-bound-audit.log"));var rows=manifest.path("observations");require(rows.isArray()&&rows.size()==VARIANTS.size());
            var seen=new HashSet<String>();var selected=new HashSet<String>();var evidence=new LinkedHashSet<EvidenceRef>();var successes=0;var rejected=0;var counterexamples=0;
            for(var row:rows) {
                var variant=text(row,"variant");require(VARIANTS.contains(variant)&&seen.add(variant));
                var fixture=original(folder,variant+"-fixture.xml");var root=SecureXml.parse(fixture).getDocumentElement();var sp=entity(root,entity);var expiry=effectiveExpiry(root,variant,entity);
                require(Arrays.equals(fixture,original(folder,variant+"-before-source.xml"))&&Arrays.equals(fixture,original(folder,variant+"-after-source.xml")));
                for(var phase:List.of("before","after")) require(Arrays.equals(original(folder,"configured-providers.xml"),original(folder,variant+"-"+phase+"-providers.xml")));
                var before=row.path("before");var after=row.path("after");var request=request(entries,before,selected,context,variant);var afterRequest=request(entries,after,selected,context,variant);
                var prepared=entries.get(text(row,"preparedReference"));var fetch=entries.get(text(row,"fetchReference"));require(prepared!=null&&fetch!=null&&prepared.direction()==Direction.OUTBOUND&&fetch.direction()==Direction.INBOUND&&"MetadataPrepared".equals(prepared.samlSummary().get("type"))&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&variant.equals(fetch.samlSummary().get("variant"))&&variant.equals(prepared.samlSummary().get("variant"))&&Objects.equals(fetch.status(),200)&&Objects.equals(prepared.status(),200)&&!prepared.timestamp().isBefore(fetch.timestamp())&&!prepared.timestamp().isAfter(request.timestamp())&&hash(fixture).equals(prepared.samlSummary().get("metadataSha256"))&&Arrays.equals(fixture,content.readDecodedSaml(prepared)));
                var signing=spKeys(sp,"signing");require(!signing.isEmpty()&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(root)&&signing.stream().anyMatch(c->new XmlSignatureVerifier().hasValidEnvelopedSignature(root,c)));
                var beforeXml=validRequest(request,sp,target,signing);var afterXml=validRequest(afterRequest,sp,target,signing);require(beforeXml.getAttribute("ID").equals(request.samlSummary().get("id"))&&afterXml.getAttribute("ID").equals(afterRequest.samlSummary().get("id"))&&request.timestamp().isBefore(afterRequest.timestamp()));
                var reply=response(entries,before,selected,request);verifySuccess(context,variant,reply,beforeXml,sp,target,targetKeys);
                var beforeStart=clock(folder,variant+"-before");var beforeEnd=clock(folder,variant+"-before-after-send");require(beforeStart.isBefore(expiry)&&beforeEnd.isBefore(expiry)&&!beforeEnd.isBefore(beforeStart));
                var beforeAudit=audit.get(beforeXml.getAttribute("ID"));require(beforeAudit!=null&&entity.equals(beforeAudit[2])&&beforeAudit[3].isEmpty()&&"Success".equals(beforeAudit[4])&&"true".equals(beforeAudit[5])&&within(Instant.parse(beforeAudit[8]),beforeStart,beforeEnd));
                var queryBefore=metadataQuery(folder,variant+"-before",entity);require(queryBefore.path("exitCode").asInt(-1)==0);var nativeBefore=SecureXml.parse(original(folder,variant+"-before-metadata-stdout.txt")).getDocumentElement();require(entity.equals(nativeBefore.getAttribute("entityID"))&&structure(single(sp,MD,"SPSSODescriptor")).equals(structure(single(nativeBefore,MD,"SPSSODescriptor"))));successes++;
                var afterStart=clock(folder,variant+"-after-before-send");var afterEnd=clock(folder,variant+"-after");require(afterStart.isAfter(expiry)&&afterEnd.isAfter(afterStart));
                var afterResponse=after.path("responseReference");
                if(afterResponse.isTextual()&&!afterResponse.asText().isBlank()) {
                    var returned=response(entries,after,selected,afterRequest);var xml=SecureXml.parse(content.readDecodedSaml(returned)).getDocumentElement();
                    if(SUCCESS.equals(status(xml))) {verifySuccess(context,variant,returned,afterXml,sp,target,targetKeys);var afterAudit=audit.get(afterXml.getAttribute("ID"));require(afterAudit!=null&&entity.equals(afterAudit[2])&&afterAudit[3].isEmpty()&&"Success".equals(afterAudit[4])&&within(Instant.parse(afterAudit[8]),afterStart,afterEnd));nativeHttp(folder,after,afterRequest,variant+"-after-before-send",variant+"-after",false,returned);counterexamples++;evidence.add(new EvidenceRef("transcript",returned.id()));}
                    else require(false); // An error does not by itself identify expiry as the rejection reason.
                } else {
                    require(entries.values().stream().noneMatch(e->e.direction()==Direction.INBOUND&&afterXml.getAttribute("ID").equals(e.samlSummary().get("inResponseTo"))));
                    var nativeAfter=metadataQuery(folder,variant+"-after",entity);require(nativeAfter.path("exitCode").asInt(0)==1&&original(folder,variant+"-after-metadata-stdout.txt").length==0);
                    var beforeQuery=clock(folder,variant+"-after-before-query");require(beforeQuery.isAfter(expiry));
                    var queryCompleted=Instant.parse(text(nativeAfter,"recordedAt"));var queryClock=json(original(folder,variant+"-after-before-query-clock.json"));var sendClock=json(original(folder,variant+"-after-before-send-clock.json"));require(!queryCompleted.isBefore(Instant.parse(text(queryClock,"hostCompletedAt")))&&queryCompleted.isBefore(Instant.parse(text(sendClock,"hostStartedAt"))));
                    var h=httpTransport(folder,after,afterRequest,variant+"-after-before-send",variant+"-after");require(h.path("responseStatus").asInt(0)>=400&&!h.path("samlResponseFormPresent").asBoolean(true));
                    // Native lookup returns no expired descriptor; after-use request-bound audit is unobserved.
                    // A fresh native mdquery refusal plus the unique HTTP-ingress expiry warning closes
                    // that earlier boundary. Neither the HTTP status nor absence of a response suffices.
                    validateExpiryLog(folder,variant,providerId,entity,h,queryCompleted,afterStart,afterEnd);rejected++;
                }
                for(var e:List.of(fetch,prepared,request,reply,afterRequest))evidence.add(new EvidenceRef("transcript",e.id()));
            }
            require(seen.equals(Set.copyOf(VARIANTS))&&successes==3);validateSignatureControl(context,folder,manifest.path("signatureControl"),entries,selected,audit,target,evidence);
            require(counterexamples>0||rejected==3);var reason=counterexamples>0?"metadata.validity.expired-use-observed":"metadata.validity.expiration-observed";
            evidence.add(new EvidenceRef("native-metadata-validity-evidence",context.runId()+"/manifest.json#"+hash(manifestRaw)));
            return Optional.of(new CaseOutcome(counterexamples>0?Outcome.VIOLATED:Outcome.SATISFIED,null,reason,reason,List.copyOf(evidence),Map.of("evidence_adapter",ADAPTER,"run_id",context.runId(),"native_expiry_clock","product-Instant.now","request_clock_skew_not_used",true,"required_variants",VARIANTS,"before_expiry_use",successes,"after_expiry_rejections",rejected,"after_expiry_counterexamples",counterexamples,"restored",true)));
        } catch(Exception unavailable) {return Optional.empty();}
    }
    private void validateConfiguration(Path folder,String entity,String providerId,String source)throws Exception {
        for(var kind:List.of("providers","audit"))require(Arrays.equals(original(folder,"original-"+kind+".xml"),original(folder,"final-"+kind+".xml")));
        var original=SecureXml.parse(original(folder,"original-providers.xml")).getDocumentElement();var configured=SecureXml.parse(original(folder,"configured-providers.xml")).getDocumentElement();var children=MetadataAlgorithmEvidence.children(configured,N,"MetadataProvider");require(children.size()>0);var added=children.getFirst();require(providerId.equals(added.getAttribute("id"))&&"FilesystemMetadataProvider".equals(added.getAttributeNS(XSI,"type"))&&source.equals(added.getAttribute("metadataFile"))&&MetadataAlgorithmEvidence.children(added,N,"MetadataFilter").isEmpty()&&(!added.hasAttribute("requireValidMetadata")||"true".equals(added.getAttribute("requireValidMetadata"))));configured.removeChild(added);require(structure(original).equals(structure(configured)));
        var inventories=json(original(folder,"other-provider-inventory.json"));require(inventories.isArray()&&!inventories.isEmpty()&&inventories.equals(json(original(folder,"other-provider-final-readback.json"))));var originalSources=new HashSet<String>();for(var node:MetadataAlgorithmEvidence.children(original,N,"MetadataProvider")) {require("FilesystemMetadataProvider".equals(node.getAttributeNS(XSI,"type")));originalSources.add(node.getAttribute("metadataFile").replace("%{idp.home}","/opt/reference-idp"));}var captured=new HashSet<String>();for(var row:inventories){require(captured.add(text(row,"path")));var raw=original(folder,text(row,"file"));require(hash(raw).equals(text(row,"sha256")));var metadata=SecureXml.parse(raw).getDocumentElement();require(!hasEntity(metadata,entity));}require(captured.equals(originalSources));
        var audit=SecureXml.parse(original(folder,"configured-audit.xml")).getDocumentElement();var formats=audit.getElementsByTagNameNS("http://www.springframework.org/schema/beans","entry");int matches=0;for(int i=0;i<formats.getLength();i++){var e=(Element)formats.item(i);if("Shibboleth-Audit".equals(e.getAttribute("key"))){require("SAMLscope-signature-v1|%I|%SP|%e|%S|%XX|%b|%P|%T".equals(e.getAttribute("value")));matches++;}}require(matches==1);
        var restoration=json(original(folder,"restoration.json"));require(restoration.path("restored").asBoolean(false)&&restoration.path("errors").isArray()&&restoration.path("errors").isEmpty());for(var it=restoration.path("original").fields();it.hasNext();){var pair=it.next();require(pair.getValue().equals(restoration.path("final").path(pair.getKey())));}
    }
    private TranscriptEntry request(Map<String,TranscriptEntry> entries,JsonNode row,Set<String> selected,CaseContext context,String variant)throws Exception {var e=entries.get(text(row,"requestReference"));require(e!=null&&selected.add(e.id())&&e.direction()==Direction.OUTBOUND&&"POST".equals(e.method())&&"AuthnRequest".equals(e.samlSummary().get("type"))&&"metadata-polling".equals(e.samlSummary().get("campaign"))&&variant.equals(e.samlSummary().get("variant"))&&"valid".equals(e.samlSummary().get("metadataSignatureControl")));return e;}
    private TranscriptEntry response(Map<String,TranscriptEntry> entries,JsonNode row,Set<String> selected,TranscriptEntry request){var e=entries.get(text(row,"responseReference"));require(e!=null&&selected.add(e.id())&&e.direction()==Direction.INBOUND&&"POST".equals(e.method())&&"Response".equals(e.samlSummary().get("type"))&&request.timestamp().isBefore(e.timestamp())&&request.samlSummary().get("id").equals(e.samlSummary().get("inResponseTo"))&&Boolean.TRUE.equals(e.samlSummary().get("metadataProbeAccepted")));return e;}
    private Element validRequest(TranscriptEntry entry,Element sp,Element target,List<X509Certificate> signing)throws Exception {var e=SecureXml.parse(content.readDecodedSaml(entry)).getDocumentElement();require(P.equals(e.getNamespaceURI())&&"AuthnRequest".equals(e.getLocalName())&&"2.0".equals(e.getAttribute("Version"))&&e.getAttribute("ID").equals(entry.samlSummary().get("id"))&&e.getAttribute("ID").equals(entry.correlationId())&&sp.getAttribute("entityID").equals(single(e,S,"Issuer").getTextContent()));require(!"true".equals(e.getAttribute("ForceAuthn"))&&!"true".equals(e.getAttribute("IsPassive")));var role=single(target,MD,"IDPSSODescriptor");require(MetadataAlgorithmEvidence.children(role,MD,"SingleSignOnService").stream().anyMatch(n->"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST".equals(n.getAttribute("Binding"))&&e.getAttribute("Destination").equals(n.getAttribute("Location"))));require(MetadataAlgorithmEvidence.children(single(sp,MD,"SPSSODescriptor"),MD,"AssertionConsumerService").stream().anyMatch(n->e.getAttribute("AssertionConsumerServiceURL").equals(n.getAttribute("Location"))));var v=new XmlSignatureVerifier();require(v.hasValidEnvelopedReferenceDigests(e)&&signing.stream().anyMatch(c->v.hasValidEnvelopedSignature(e,c)));return e;}
    private void verifySuccess(CaseContext context,String variant,TranscriptEntry entry,Element request,Element sp,Element target,List<X509Certificate> targetKeys)throws Exception {var recipient=request.getAttribute("AssertionConsumerServiceURL");require(recipient.equals(entry.url()));VerifiedResponseAssertion.read(SecureXml.parse(content.readDecodedSaml(entry)).getDocumentElement(),target.getAttribute("entityID"),targetKeys,sp,keys.apply(context.runId(),variant),request.getAttribute("ID"),recipient);}
    private void validateSignatureControl(CaseContext context,Path folder,JsonNode row,Map<String,TranscriptEntry> entries,Set<String> selected,Map<String,String[]> audit,Element target,Set<EvidenceRef> evidence)throws Exception {
        var entry=entries.get(text(row,"requestReference"));require(entry!=null&&selected.add(entry.id())&&entry.direction()==Direction.OUTBOUND&&"POST".equals(entry.method())&&"AuthnRequest".equals(entry.samlSummary().get("type"))&&"invalid".equals(entry.samlSummary().get("metadataSignatureControl")));var xml=SecureXml.parse(content.readDecodedSaml(entry)).getDocumentElement();var fixture=SecureXml.parse(original(folder,"live-validity-root-fixture.xml")).getDocumentElement();var sp=entity(fixture,text(json(original(folder,"manifest.json")),"entityId"));var normalRow=json(original(folder,"manifest.json")).path("observations").get(0).path("before");var normal=entries.get(text(normalRow,"requestReference"));require(normal!=null&&entry.timestamp().isBefore(normal.timestamp()));var normalXml=validRequest(normal,sp,target,spKeys(sp,"signing"));require(requestShape(xml).equals(requestShape(normalXml))&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(xml));require(P.equals(xml.getNamespaceURI())&&"AuthnRequest".equals(xml.getLocalName())&&xml.getAttribute("ID").equals(entry.samlSummary().get("id"))&&xml.getAttribute("ID").equals(entry.correlationId())&&"metadata-polling".equals(entry.samlSummary().get("campaign"))&&"live-validity-root".equals(entry.samlSummary().get("variant"))&&sp.getAttribute("entityID").equals(single(xml,S,"Issuer").getTextContent())&&MetadataAlgorithmEvidence.children(xml,DS,"Signature").size()==1&&spKeys(sp,"signing").stream().noneMatch(c->new XmlSignatureVerifier().hasValidEnvelopedSignature(xml,c)));require(entries.values().stream().noneMatch(e->e.direction()==Direction.INBOUND&&xml.getAttribute("ID").equals(e.samlSummary().get("inResponseTo"))&&SUCCESS.equals(e.samlSummary().get("statusCode"))));var fields=audit.get(xml.getAttribute("ID"));require(fields!=null&&sp.getAttribute("entityID").equals(fields[2])&&"MessageAuthenticationError".equals(fields[3])&&!"Success".equals(fields[4])&&"true".equals(fields[5])&&within(Instant.parse(fields[8]),clock(folder,"live-validity-root-before"),clock(folder,"live-validity-root-before-after-send")));nativeHttp(folder,row,entry,"live-validity-root-before","live-validity-root-before-after-send",true,null);evidence.add(new EvidenceRef("transcript",entry.id()));
    }
    private void nativeHttp(Path folder,JsonNode row,TranscriptEntry request,String begin,String end,boolean rejection,TranscriptEntry response)throws Exception {
        var h=httpTransport(folder,row,request,begin,end);
        if(rejection){require(h.path("responseStatus").asInt(0)>=400&&h.path("nativeMessageSecurityError").asBoolean(false)&&!h.path("samlResponseFormPresent").asBoolean(true));var body=original(folder,text(h,"responseBodyFile"));require(hash(body).equals(text(h,"responseBodySha256")));var html=new String(body,StandardCharsets.UTF_8);require(html.contains("Message Security Error")&&!html.matches("(?is).*<input\\b.*")&&!html.contains("SAMLResponse"));}
        else require(response!=null&&h.path("responseStatus").asInt(0)==200&&!h.path("nativeMessageSecurityError").asBoolean(true)&&h.path("samlResponseFormPresent").asBoolean(false)&&hash(content.readDecodedSaml(response)).equals(text(h,"responseSamlSha256")));
    }
    private JsonNode httpTransport(Path folder,JsonNode row,TranscriptEntry request,String begin,String end)throws Exception {
        var xml=SecureXml.parse(content.readDecodedSaml(request)).getDocumentElement();var http=row.path("nativeHttp");require(http.isArray()&&http.size()==1);var h=http.get(0);
        require(xml.getAttribute("ID").equals(text(h,"requestId"))&&hash(content.readDecodedSaml(request)).equals(text(h,"requestSha256"))&&"POST".equals(text(h,"requestMethod"))&&xml.getAttribute("Destination").equals(text(h,"requestUrl"))&&text(h,"requestUrl").equals(text(h,"responseUrl")));
        var started=Instant.parse(text(h,"startedAt"));var completed=Instant.parse(text(h,"completedAt"));var first=json(original(folder,begin+"-clock.json"));var last=json(original(folder,end+"-clock.json"));
        require(first.path("command").equals(last.path("command"))&&"native-product-os-UTC".equals(text(first,"clockDomain"))&&"native-product-os-UTC".equals(text(last,"clockDomain"))&&clock(folder,begin).equals(Instant.parse(text(first,"nativeInstant")))&&clock(folder,end).equals(Instant.parse(text(last,"nativeInstant")))&&hash(original(folder,begin+"-clock.txt")).equals(text(first,"nativeClockSha256"))&&hash(original(folder,end+"-clock.txt")).equals(text(last,"nativeClockSha256")));
        require(!started.isBefore(Instant.parse(text(first,"hostCompletedAt")))&&!completed.isBefore(started)&&!completed.isAfter(Instant.parse(text(last,"hostStartedAt"))));
        return h;
    }
    private static JsonNode metadataQuery(Path folder,String phase,String entity)throws Exception {
        var row=json(original(folder,phase+"-metadata-query.json"));var command=row.path("command");require(command.isArray()&&command.size()==5&&"/opt/reference-idp/bin/mdquery.sh".equals(command.get(0).asText())&&"-u".equals(command.get(1).asText())&&"http://localhost:8080/idp".equals(command.get(2).asText())&&"-e".equals(command.get(3).asText())&&entity.equals(command.get(4).asText())&&entity.equals(text(row,"entityId")));
        require(hash(original(folder,phase+"-metadata-stdout.txt")).equals(text(row,"stdoutSha256"))&&hash(original(folder,phase+"-metadata-stderr.txt")).equals(text(row,"stderrSha256")));return row;
    }
    private static void validateExpiryLog(Path folder,String variant,String provider,String entity,JsonNode http,Instant queryCompleted,Instant nativeBegin,Instant nativeEnd)throws Exception {
        var ranges=json(original(folder,"retrospective-log-range.json"));require("samlscope-retrospective-native-log-range-v1".equals(text(ranges,"schema"))&&"retrospective-physical-range-readback".equals(text(ranges,"evidenceKind"))&&!ranges.path("historicalBeforeOffsetCaptured").asBoolean(true)&&ranges.path("readBackUnchanged").asBoolean(false)&&ranges.path("inode").asLong(0)>0&&ranges.path("size").asLong(0)>0&&text(ranges,"nativeLogSha256").matches("[0-9a-f]{64}")&&"/opt/reference-idp/logs/idp-process.log".equals(text(ranges,"logPath"))&&!ranges.path("privateLogContentsPersisted").asBoolean(true));
        var captured=Instant.parse(text(ranges,"hostStartedAt"));var captureEnd=Instant.parse(text(ranges,"hostCompletedAt"));var started=Instant.parse(text(http,"startedAt"));var completed=Instant.parse(text(http,"completedAt"));require(captured.isAfter(completed)&&!captureEnd.isBefore(captured)&&queryCompleted.isBefore(started));
        var nativeRuntime=json(original(folder,"target-container-inspect-end.json")).get(0);var capturedRuntime=ranges.path("targetRuntime");require(text(nativeRuntime,"Id").equals(text(capturedRuntime,"id"))&&text(nativeRuntime,"Image").equals(text(capturedRuntime,"image")));var ip=text(capturedRuntime,"gateway");require(ip.matches("[0-9]{1,3}(\\.[0-9]{1,3}){3}")&&!ip.startsWith("127."));
        var rows=ranges.path("ranges");require(rows.isArray()&&rows.size()==3);var seen=new HashSet<String>();JsonNode selected=null;long previous=-1;
        for(var r:rows){require(VARIANTS.contains(text(r,"variant"))&&seen.add(text(r,"variant"))&&r.path("offsetStart").asLong(-1)>previous&&r.path("offsetEnd").asLong(-1)>r.path("offsetStart").asLong(-1)&&r.path("offsetEnd").asLong(-1)<=ranges.path("size").asLong(0)&&r.path("lineNumber").asLong(0)>0);previous=r.path("offsetEnd").asLong();if(variant.equals(text(r,"variant")))selected=r;}
        require(selected!=null&&seen.equals(Set.copyOf(VARIANTS)));var raw=original(folder,text(selected,"file"));require(raw.length==selected.path("offsetEnd").asLong()-selected.path("offsetStart").asLong()&&hash(raw).equals(text(selected,"sha256")));var line=new String(raw,StandardCharsets.UTF_8);require(line.lines().count()==1&&line.strip().equals(new String(original(folder,variant+"-after-probe-process.log"),StandardCharsets.UTF_8).strip()));
        require(line.contains(" - "+ip+" - WARN [org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver:")&&line.contains("FilesystemMetadataResolver "+provider+": Metadata backing store contained an EntityDescriptor with the ID: "+entity+",  but it was no longer valid"));
        var nativeAt=java.time.LocalDateTime.parse(line.substring(0,23),java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss,SSS")).toInstant(java.time.ZoneOffset.UTC);require(nativeAt.equals(Instant.parse(text(selected,"nativeInstant")))&&within(nativeAt,nativeBegin,nativeEnd));
    }

    private static void validateNativeClockBoundary(Path folder)throws Exception {
        var start=json(original(folder,"native-validity-boundary-start.json"));var end=json(original(folder,"native-validity-boundary-end.json"));require(start.isArray()&&start.size()==4&&start.equals(end));
        var expected=Map.of("abstract-resolver","99584e841536ae78ab7a54b89f0e1e679aa12c22c13b8922eb6b1faa531fcf4b","saml2-support","9b52664da43e9596466441b83134774096177151b569746cac8af9f2f18dc444","entity-validity","ab91cd415316ad44b9b4ad1db10649fd9a1b249af9a4cbf8263bccc66fe24f14","group-validity","8fb0aeb3edc4df1521cc1733f75fa80ad61eb79a5e3e3d69db6f917eac752494");var seen=new HashSet<String>();
        for(var row:start){var kind=text(row,"kind");require(seen.add(kind)&&expected.containsKey(kind));var jar=text(row,"jar");var expectedJar="saml2-support".equals(kind)?"cce72578ec8df5dd18cb71c88bba89bd196c640281c199ce875e2aa44154f93f":"9f04221e172dc426f90fb3873d0148a0744edbf9e7a37de7ee0e6a34f7b74581";var raw=original(folder,"native-"+jar);require(hash(raw).equals(expectedJar)&&expectedJar.equals(text(row,"jarSha256")));byte[] cls=null;try(var zip=new java.util.zip.ZipInputStream(new java.io.ByteArrayInputStream(raw))){for(var e=zip.getNextEntry();e!=null;e=zip.getNextEntry())if(e.getName().equals(text(row,"className").replace('.','/')+".class")){cls=zip.readAllBytes();break;}}require(cls!=null&&expected.get(kind).equals(hash(cls))&&expected.get(kind).equals(text(row,"classSha256"))&&Arrays.equals(cls,original(folder,"native-"+kind+".class")));
            var code=new String(original(folder,"native-"+kind+"-javap.txt"),StandardCharsets.UTF_8);require(code.contains("boolean isValid("));if(kind.endsWith("validity"))require(code.contains("java/time/Instant.now:")&&code.contains("java/time/Instant.isBefore:")&&!code.contains("clockSkew"));if("abstract-resolver".equals(kind))require(code.contains("org/opensaml/saml/saml2/common/SAML2Support.isValid:")&&code.contains("Field requireValidMetadata:Z"));if("saml2-support".equals(kind))require(code.contains("org/opensaml/core/xml/XMLObject.getParent:")&&code.contains("org/opensaml/saml/saml2/common/TimeBoundSAMLObject.isValid:"));
        }require(seen.equals(expected.keySet()));
    }
    static Instant effectiveExpiry(Element root,String variant,String entity) {var leaf=entity(root,entity);if("live-validity-root".equals(variant)){require(root==leaf);return Instant.parse(root.getAttribute("validUntil"));}require(MD.equals(root.getNamespaceURI())&&"EntitiesDescriptor".equals(root.getLocalName())&&MetadataAlgorithmEvidence.children(root,MD,"EntitiesDescriptor").size()==1);var inner=single(root,MD,"EntitiesDescriptor");require(single(inner,MD,"EntityDescriptor")==leaf);var parent=Instant.parse(root.getAttribute("validUntil"));var child=Instant.parse(inner.getAttribute("validUntil"));var value=Instant.parse(leaf.getAttribute("validUntil"));if("live-validity-parent".equals(variant)){require(parent.isBefore(child)&&parent.isBefore(value));return parent;}require(child.isBefore(parent)&&child.isBefore(value));return child;}
    private static Element entity(Element root,String entity){var values=new ArrayList<Element>();if(MD.equals(root.getNamespaceURI())&&"EntityDescriptor".equals(root.getLocalName())&&entity.equals(root.getAttribute("entityID")))values.add(root);var descendants=root.getElementsByTagNameNS(MD,"EntityDescriptor");for(int i=0;i<descendants.getLength();i++){var e=(Element)descendants.item(i);if(entity.equals(e.getAttribute("entityID")))values.add(e);}require(values.size()==1);return values.getFirst();}
    private static boolean hasEntity(Element root,String entity){if(entity.equals(root.getAttribute("entityID")))return true;var values=root.getElementsByTagNameNS(MD,"EntityDescriptor");for(int i=0;i<values.getLength();i++)if(entity.equals(((Element)values.item(i)).getAttribute("entityID")))return true;return false;}
    private static List<X509Certificate> spKeys(Element entity,String purpose)throws Exception {var result=new ArrayList<X509Certificate>();for(var key:MetadataAlgorithmEvidence.children(single(entity,MD,"SPSSODescriptor"),MD,"KeyDescriptor")){if(!Set.of("",purpose).contains(key.getAttribute("use")))continue;var values=key.getElementsByTagNameNS(DS,"X509Certificate");for(int i=0;i<values.getLength();i++)result.add((X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(values.item(i).getTextContent()))));}return result;}
    private static String requestShape(Element request){var document=SecureXml.newDocument();var clone=(Element)document.importNode(request,true);document.appendChild(clone);clone.removeAttribute("ID");clone.removeAttribute("IssueInstant");for(var signature:MetadataAlgorithmEvidence.children(clone,DS,"Signature"))clone.removeChild(signature);return structure(clone);}
    private static String status(Element response){return single(single(response,P,"Status"),P,"StatusCode").getAttribute("Value");}
    private static Element single(Element e,String ns,String name){var values=MetadataAlgorithmEvidence.children(e,ns,name);require(values.size()==1);return values.getFirst();}
    private static Map<String,String[]> audits(byte[] raw){var result=new HashMap<String,String[]>();for(var line:new String(raw,StandardCharsets.UTF_8).lines().filter(s->!s.isBlank()).toList()){var fields=line.split("\\|",-1);require(fields.length==9&&"SAMLscope-signature-v1".equals(fields[0])&&result.put(fields[1],fields)==null);}return result;}
    private static String structure(Element e){var attrs=new TreeMap<String,String>();for(int i=0;i<e.getAttributes().getLength();i++){var a=e.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put(String.valueOf(a.getNamespaceURI())+"|"+a.getLocalName(),a.getNodeValue());}var out=new StringBuilder(String.valueOf(e.getNamespaceURI())+"|"+e.getLocalName()+attrs);for(var n=e.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element element)out.append(structure(element));else if(n.getNodeType()==org.w3c.dom.Node.TEXT_NODE&&!n.getTextContent().isBlank())out.append(DS.equals(e.getNamespaceURI())&&"X509Certificate".equals(e.getLocalName())?n.getTextContent().replaceAll("\\s",""):n.getTextContent().trim());return out.toString();}
    private static Instant clock(Path folder,String phase)throws Exception{return Instant.parse(new String(original(folder,phase+"-clock.txt"),StandardCharsets.UTF_8).strip());}
    private static boolean within(Instant value,Instant start,Instant end){return !value.isBefore(start)&&!value.isAfter(end);}
    private static String runtime(Path folder,String file)throws Exception{var rows=json(original(folder,file));require(rows.isArray()&&rows.size()==1);var row=rows.get(0);require(row.path("State").path("Running").asBoolean(false)&&row.path("Config").path("Env").isMissingNode());return text(row,"Id")+"|"+text(row,"Image")+"|"+text(row.path("State"),"StartedAt");}
    private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
    private static byte[] original(Path folder,String file)throws Exception{require(file.matches("[A-Za-z0-9_.-]+"));var path=folder.resolve(file);safeParents(folder);require(Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)&&Files.size(path)<=8*1024*1024);return Files.readAllBytes(path);}
    private static void safeParents(Path p){for(var parent=p;parent!=null;parent=parent.getParent())require(!Files.isSymbolicLink(parent));}
    private static String text(JsonNode n,String name){var value=n.path(name);require(value.isTextual()&&!value.asText().isBlank());return value.asText();}
    private static String hash(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
    private static void require(boolean condition){if(!condition)throw new IllegalArgumentException("Native retained metadata validity unproven");}
}
