package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.caseexec.ActionIds;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.normal.SamlSignedRequestFactory;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import java.util.zip.ZipInputStream;
import org.w3c.dom.Element;

/** Metadata/protocol certificate comparison with original-backed native consumer epochs.
 * The selected metadata-key trust path is closed; PKIX fallback for other messages is not denied. */
public final class MetadataCertificateRuntimeEvidence {
    public static final String SCHEMA="samlscope-metadata-certificate-runtime-v1";
    public static final String ADAPTER="shibboleth-native-filesystem-certificate-runtime-v1";
    private static final String RUN="run_[0-9A-HJKMNP-TV-Z]{26}",MD="urn:oasis:names:tc:SAML:2.0:metadata",P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",DS="http://www.w3.org/2000/09/xmldsig#",N="urn:mace:shibboleth:2.0:metadata",XSI="http://www.w3.org/2001/XMLSchema-instance";
    private static final String SUCCESS="urn:oasis:names:tc:SAML:2.0:status:Success",POST="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
    private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final BiFunction<String,String,Optional<PlanCredentials>> keys;
    public MetadataCertificateRuntimeEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,BiFunction<String,String,Optional<PlanCredentials>> keys){this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.keys=Objects.requireNonNull(keys);}
    public boolean exists(String run){return run!=null&&run.matches(RUN)&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
    public Optional<CaseOutcome> evaluate(CaseContext context){
        try {
            require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete()&&context.runId().matches(RUN));var folder=directory.resolve(context.runId());safeParents(folder);require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
            var manifestRaw=original(folder,"manifest.json");var manifest=json(manifestRaw);require(SCHEMA.equals(text(manifest,"schema"))&&ADAPTER.equals(text(manifest,"adapter"))&&context.runId().equals(text(manifest,"runId")));verifyOriginals(folder,manifest);
            var targetRaw=metadata.apply(context.runId());require(hash(targetRaw).equals(text(manifest,"targetMetadataSha256")));var target=SecureXml.parse(targetRaw).getDocumentElement();require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName()));var targetSigning=MetadataAlgorithmEvidence.signingKeys(target);require(!targetSigning.isEmpty());String entity=text(manifest,"entityId");validateConfiguration(folder,entity,context.runId(),text(manifest,"sourcePath"));require(runtime(folder,"target-container-inspect-start.json").equals(runtime(folder,"target-container-inspect-end.json")));
            var entries=new HashMap<String,TranscriptEntry>();var requestIds=new HashSet<String>();for(var e:context.transcript().list(context.runId())){require(context.runId().equals(e.runId())&&entries.put(e.id(),e)==null&&(e.decodedSamlRef()==null||("transcripts/"+context.runId()+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())));if(e.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(e.samlSummary().get("type")))require(requestIds.add(e.samlSummary().get("id") instanceof String id&&!id.isBlank()?id:e.samlSummary().get("action_id") instanceof String action&&!action.isBlank()?"_"+action:e.id()));}
            validateRestoration(folder,context.runId());var created=json(original(folder,"created.json")).path("run");require(context.runId().equals(text(created,"id"))&&entity.equals("http://localhost:18080/p/"+text(created,"planId")));var audit=audits(original(folder,"native-request-bound-audit.log"));var selectedTrust=validateTrustScope(folder,entity);var observations=manifest.path("observations");require(observations.isArray()&&observations.size()==5);var seenVariants=new HashSet<String>();var selected=new HashSet<String>();var proof=new LinkedHashSet<EvidenceRef>();var verifiedFixtures=new HashSet<String>();var shapes=new HashMap<String,String>();int success=0,rejection=0,violation=0,uncertain=0;Instant previousEpoch=null;
            for(var row:observations){var variant=text(row,"variant");require(MetadataCertificateRuntimeProbeTestCase.VARIANTS.contains(variant)&&seenVariants.add(variant));var epochStart=Instant.parse(text(row,"startedAt"));var epochEnd=Instant.parse(text(row,"completedAt"));require(epochEnd.isAfter(epochStart)&&(previousEpoch==null||!epochStart.isBefore(previousEpoch)));previousEpoch=epochEnd;
                var fixture=original(folder,variant+"-fixture.xml");var peer=SecureXml.parse(fixture).getDocumentElement();require(MD.equals(peer.getNamespaceURI())&&"EntityDescriptor".equals(peer.getLocalName())&&entity.equals(peer.getAttribute("entityID")));var sp=single(peer,MD,"SPSSODescriptor");var idp=single(peer,MD,"IDPSSODescriptor");var advertised=roleCertificate(sp);var receiver=keys.apply(context.runId(),variant).orElseThrow();require(Arrays.equals(advertised.getPublicKey().getEncoded(),receiver.certificate().getPublicKey().getEncoded()));validateCondition(folder,variant,peer,advertised);var signing=advertised;require(new XmlSignatureVerifier().hasValidEnvelopedSignature(peer,advertised));
                for(var phase:List.of("before","after")){require(Arrays.equals(fixture,original(folder,variant+"-"+phase+"-source.xml"))&&Arrays.equals(original(folder,"configured-providers.xml"),original(folder,variant+"-"+phase+"-providers.xml"))&&Arrays.equals(original(folder,"configured-audit.xml"),original(folder,variant+"-"+phase+"-audit.xml")));}
                var query=json(original(folder,variant+"-metadata-query.json"));require(query.path("exitCode").asInt(-1)==0&&entity.equals(text(query,"entityId"))&&hash(original(folder,variant+"-metadata-stdout.txt")).equals(text(query,"stdoutSha256"))&&hash(original(folder,variant+"-metadata-stderr.txt")).equals(text(query,"stderrSha256")));require(query.path("command").isArray()&&query.path("command").size()==5&&"/opt/reference-idp/bin/mdquery.sh".equals(query.path("command").get(0).asText())&&"-u".equals(query.path("command").get(1).asText())&&"http://localhost:8080/idp".equals(query.path("command").get(2).asText())&&"-e".equals(query.path("command").get(3).asText())&&entity.equals(query.path("command").get(4).asText()));var nativePeer=SecureXml.parse(original(folder,variant+"-metadata-stdout.txt")).getDocumentElement();require(entity.equals(nativePeer.getAttribute("entityID"))&&structure(sp).equals(structure(single(nativePeer,MD,"SPSSODescriptor")))&&structure(idp).equals(structure(single(nativePeer,MD,"IDPSSODescriptor"))));var queryAt=Instant.parse(text(query,"recordedAt"));require(!queryAt.isBefore(epochStart));
                var prepared=entry(entries,text(row,"preparedReference"));var fetch=entry(entries,text(row,"fetchReference"));require("MetadataPrepared".equals(prepared.samlSummary().get("type"))&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&variant.equals(prepared.samlSummary().get("variant"))&&variant.equals(fetch.samlSummary().get("variant"))&&fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&prepared.direction()==Direction.OUTBOUND&&fetch.direction()==Direction.INBOUND&&Objects.equals(fetch.status(),200)&&Objects.equals(prepared.status(),200)&&!prepared.timestamp().isBefore(fetch.timestamp())&&Arrays.equals(fixture,content.readDecodedSaml(prepared))&&hash(fixture).equals(prepared.samlSummary().get("metadataSha256")));proof.add(new EvidenceRef("transcript",prepared.id()));proof.add(new EvidenceRef("transcript",fetch.id()));
                var exchanges=row.path("exchanges");require(exchanges.isArray()&&exchanges.size()==(variant.equals("control")?2:1));for(var exchange:exchanges){String fixtureId=text(exchange,"fixtureId");require(MetadataCertificateRuntimeProbeTestCase.FIXTURES.contains(fixtureId)&&variant.equals(MetadataCertificateRuntimeProbeTestCase.variant(fixtureId))&&verifiedFixtures.add(fixtureId));var request=entry(entries,text(exchange,"requestReference"));require(selected.add(request.id())&&request.direction()==Direction.OUTBOUND&&"POST".equals(request.method())&&MetadataCertificateRuntimeProbeTestCase.CASE.equals(request.samlSummary().get("scenario_case_id"))&&fixtureId.equals(request.samlSummary().get("fixture_id"))&&!request.timestamp().isBefore(prepared.timestamp()));
                    var raw=content.readDecodedSaml(request);var req=SecureXml.parse(raw).getDocumentElement();String reqId=req.getAttribute("ID");require(P.equals(req.getNamespaceURI())&&"AuthnRequest".equals(req.getLocalName())&&"2.0".equals(req.getAttribute("Version"))&&entity.equals(single(req,S,"Issuer").getTextContent())&&reqId.equals("_"+request.samlSummary().get("action_id"))&&request.correlationId().equals(request.samlSummary().get("action_id"))&&req.getAttribute("Destination").equals(request.url())&&targetPost(target).equals(request.url())&&MetadataSupersessionProbeTestCase.acs(peer,0).toString().equals(req.getAttribute("AssertionConsumerServiceURL"))&&POST.equals(req.getAttribute("ProtocolBinding"))&&!"true".equals(req.getAttribute("ForceAuthn"))&&!"true".equals(req.getAttribute("IsPassive")));
                    var verifier=new XmlSignatureVerifier();require(verifier.hasValidEnvelopedReferenceDigests(req));boolean invalid=fixtureId.endsWith("invalid-signature");var action=ActionIds.derive(context.runId(),MetadataCertificateRuntimeProbeTestCase.CASE,"await-fixture-"+fixtureId,0);require(action.equals(request.samlSummary().get("action_id")));validateRequestBytes(context.runId(),fixtureId,raw,java.net.URI.create(targetPost(target)),entity,MetadataSupersessionProbeTestCase.acs(peer,0),receiver);if(variant.equals("certificate-revocation-unreachable"))validateNetworkEpoch(folder,epochStart,Instant.parse(text(exchange.path("nativeHttp").get(0),"startedAt")));require(invalid?!verifier.hasValidEnvelopedSignature(req,advertised):verifier.hasValidEnvelopedSignature(req,advertised));String shape=shape(req);if(fixtureId.endsWith("normal"))shapes.put(variant,shape);else require(shape.equals(shapes.get(variant)));
                    var transport=http(exchange,req,raw,epochStart,epochEnd,queryAt);var beforeClock=clock(folder,text(exchange,"clockBeforeFile"));var afterClock=clock(folder,text(exchange,"clockAfterFile"));var begin=beforeClock.nativeAt();var end=afterClock.nativeAt();advertised.checkValidity(java.util.Date.from(begin));validateRevocationAt(variant,peer,begin);require(begin.equals(Instant.parse(text(exchange,"nativeBegin")))&&end.equals(Instant.parse(text(exchange,"nativeEnd")))&&!end.isBefore(begin)&&!beforeClock.hostStart().isBefore(queryAt)&&!Instant.parse(text(transport,"startedAt")).isBefore(beforeClock.hostEnd())&&!afterClock.hostStart().isBefore(Instant.parse(text(transport,"completedAt")))&&!beforeClock.hostStart().isBefore(epochStart)&&!afterClock.hostEnd().isAfter(epochEnd));var nativeAudit=audit.get(reqId);require(nativeAudit!=null&&entity.equals(nativeAudit[2])&&"POST".equals(nativeAudit[6])&&"http://shibboleth.net/ns/profiles/saml2/sso/browser".equals(nativeAudit[7])&&within(Instant.parse(nativeAudit[8]),begin,end));var matches=entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&reqId.equals(e.samlSummary().get("inResponseTo"))).toList();proof.add(new EvidenceRef("transcript",request.id()));
                    if(matches.size()==1){require(!invalid);var reply=entry(entries,text(exchange,"responseReference"));require(reply==matches.getFirst()&&selected.add(reply.id())&&reply.timestamp().isAfter(request.timestamp()));var response=SecureXml.parse(content.readDecodedSaml(reply)).getDocumentElement();require(!MetadataAlgorithmEvidence.children(response,S,"EncryptedAssertion").isEmpty());VerifiedResponseAssertion.read(response,target.getAttribute("entityID"),targetSigning,peer,Optional.of(receiver),reqId,req.getAttribute("AssertionConsumerServiceURL"));require(nativeAudit[3].isEmpty()&&"Success".equals(nativeAudit[4])&&"true".equals(nativeAudit[5])&&transport.path("samlResponseFormPresent").asBoolean(false)&&hash(content.readDecodedSaml(reply)).equals(text(transport,"responseSamlSha256")));success++;proof.add(new EvidenceRef("transcript",reply.id()));}
                    else{require(matches.isEmpty()&&exchange.path("responseReference").isNull()&&"MessageAuthenticationError".equals(nativeAudit[3])&&nativeAudit[4].isEmpty()&&transport.path("responseStatus").asInt(-1)==400&&transport.path("nativeMessageSecurityError").asBoolean(false)&&!transport.path("samlResponseFormPresent").asBoolean(true));var html=new String(original(folder,text(transport,"responseBodyFile")),StandardCharsets.UTF_8);require(hash(html.getBytes(StandardCharsets.UTF_8)).equals(text(transport,"responseBodySha256"))&&html.contains("Message Security Error")&&!html.matches("(?is).*<form\\b.*")&&!html.matches("(?is).*\\b(?:Authorization|Cookie|password|SAMLRequest|SAMLResponse)\\b.*"));if(invalid)rejection++;else{require(!variant.equals("control"));if(nativeCertificateCause(folder,exchange,variant,selectedTrust,context.runId(),text(manifest,"targetMetadataSha256"),reqId,raw,advertised,begin,end))violation++;else uncertain++;}}
                }
            }
            validateBaseline(folder,context.runId(),entries,target);var first=Instant.parse(text(observations.get(0).path("exchanges").get(0).path("nativeHttp").get(0),"startedAt"));var last=Instant.parse(text(observations.get(observations.size()-1).path("exchanges").get(0).path("nativeHttp").get(0),"completedAt"));require(!Instant.parse(text(json(original(folder,"trust-before-observed.json")),"recordedAt")).isAfter(first)&&!Instant.parse(text(json(original(folder,"trust-after-observed.json")),"recordedAt")).isBefore(last));require(seenVariants.equals(Set.copyOf(MetadataCertificateRuntimeProbeTestCase.VARIANTS))&&verifiedFixtures.equals(Set.copyOf(MetadataCertificateRuntimeProbeTestCase.FIXTURES))&&success+violation+uncertain==5&&rejection==1);require(shapes.containsKey("control"));if(violation==0)require(uncertain==0&&!selectedTrust.equals("shibboleth.PKIXSignatureTrustEngine"));var reason=violation>0?"metadata.certificate.runtime-valid-key-rejected":"metadata.certificate.runtime-no-pkix-observed";proof.add(new EvidenceRef("native-certificate-runtime-evidence",context.runId()+"/manifest.json#"+hash(manifestRaw)));return Optional.of(new CaseOutcome(violation>0?Outcome.VIOLATED:Outcome.SATISFIED,null,reason,reason,List.copyOf(proof),Map.of("evidence_adapter",ADAPTER,"run_id",context.runId(),"operative_role","SPSSODescriptor","certificate_conditions",List.copyOf(MetadataCertificateRuntimeProbeTestCase.VARIANTS),"normal_signed_encrypted_successes",success,"invalid_signature_rejected",true,"valid_advertised_key_rejections",violation,"unresolved_valid_key_rejections",uncertain,"pkix_fallback_for_untrusted_messages_asserted_absent",false,"restored",true)));
        }catch(Exception unavailable){if(Boolean.getBoolean("samlscope.certificateRuntime.debug"))unavailable.printStackTrace();return Optional.empty();}
    }
    static void validatePrepared(Element peer,String variant,String run,BiFunction<String,String,Optional<PlanCredentials>> keys)throws Exception {require(MetadataCertificateRuntimeProbeTestCase.VARIANTS.contains(variant)&&MD.equals(peer.getNamespaceURI())&&"EntityDescriptor".equals(peer.getLocalName()));var advertised=roleCertificate(single(peer,MD,"SPSSODescriptor"));var key=keys.apply(run,variant).orElseThrow();require(Arrays.equals(advertised.getPublicKey().getEncoded(),key.certificate().getPublicKey().getEncoded())&&new XmlSignatureVerifier().hasValidEnvelopedSignature(peer,advertised));}
    private static X509Certificate roleCertificate(Element sp)throws Exception{var rows=certificates(sp);require(rows.size()==2&&"signing".equals(rows.get(0).use())&&"encryption".equals(rows.get(1).use())&&Arrays.equals(rows.get(0).certificate().getEncoded(),rows.get(1).certificate().getEncoded()));return rows.get(0).certificate();}
    private static JsonNode http(JsonNode exchange,Element request,byte[] raw,Instant start,Instant end,Instant queryAt){var rows=exchange.path("nativeHttp");require(rows.isArray()&&rows.size()==1);var h=rows.get(0);var began=Instant.parse(text(h,"startedAt"));var finished=Instant.parse(text(h,"completedAt"));require("POST".equals(text(h,"requestMethod"))&&request.getAttribute("Destination").equals(text(h,"requestUrl"))&&request.getAttribute("ID").equals(text(h,"requestId"))&&hashUnchecked(raw).equals(text(h,"requestSha256"))&&began.isAfter(queryAt)&&!began.isBefore(start)&&!finished.isBefore(began)&&!finished.isAfter(end));return h;}
    private record RoleKey(String use,X509Certificate certificate,String fingerprint){}
    private static List<RoleKey> certificates(Element role)throws Exception{var result=new ArrayList<RoleKey>();for(var descriptor:MetadataAlgorithmEvidence.children(role,MD,"KeyDescriptor")){var certs=descriptor.getElementsByTagNameNS(DS,"X509Certificate");require(certs.getLength()==1);var c=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(certs.item(0).getTextContent())));result.add(new RoleKey(descriptor.getAttribute("use"),c,fingerprint(c)));}return result;}
    private static String fingerprint(X509Certificate certificate)throws Exception{return hash(certificate.getPublicKey().getEncoded());}
    private static void validateConfiguration(Path folder,String entity,String run,String source)throws Exception{for(var kind:List.of("providers","audit"))require(Arrays.equals(original(folder,"original-"+kind+".xml"),original(folder,"final-"+kind+".xml")));require(source.equals("/opt/reference-idp/metadata/certificate-runtime-"+run+".xml"));var initial=SecureXml.parse(original(folder,"original-providers.xml")).getDocumentElement();var configured=SecureXml.parse(original(folder,"configured-providers.xml")).getDocumentElement();var providers=MetadataAlgorithmEvidence.children(configured,N,"MetadataProvider");require(!providers.isEmpty());var added=providers.getFirst();require(("CertificateRuntime"+run).equals(added.getAttribute("id"))&&"FilesystemMetadataProvider".equals(added.getAttributeNS(XSI,"type"))&&source.equals(added.getAttribute("metadataFile"))&&MetadataAlgorithmEvidence.children(added,N,"MetadataFilter").isEmpty());configured.removeChild(added);require(structure(initial).equals(structure(configured)));var inventory=json(original(folder,"other-provider-inventory.json"));require(inventory.isArray()&&!inventory.isEmpty()&&inventory.equals(json(original(folder,"other-provider-final-readback.json"))));var expected=new HashSet<String>();var all=initial.getElementsByTagNameNS(N,"MetadataProvider");for(int i=0;i<all.getLength();i++){var p=(Element)all.item(i);require(p.hasAttribute("metadataFile"));expected.add(p.getAttribute("metadataFile").replace("%{idp.home}","/opt/reference-idp"));}var seen=new HashSet<String>();for(var row:inventory){require(seen.add(text(row,"path"))&&hash(original(folder,text(row,"file"))).equals(text(row,"sha256")));var xml=SecureXml.parse(original(folder,text(row,"file"))).getDocumentElement();require(!entity.equals(xml.getAttribute("entityID")));var entities=xml.getElementsByTagNameNS(MD,"EntityDescriptor");for(int i=0;i<entities.getLength();i++)require(!entity.equals(((Element)entities.item(i)).getAttribute("entityID")));}require(seen.equals(expected));var audit=SecureXml.parse(original(folder,"configured-audit.xml")).getDocumentElement();var entries=audit.getElementsByTagNameNS("http://www.springframework.org/schema/beans","entry");int formats=0;for(int i=0;i<entries.getLength();i++){var e=(Element)entries.item(i);if("Shibboleth-Audit".equals(e.getAttribute("key"))){require("SAMLscope-signature-v1|%I|%SP|%e|%S|%XX|%b|%P|%T".equals(e.getAttribute("value")));formats++;}}require(formats==1);}
    private static void verifyOriginals(Path folder,JsonNode manifest)throws Exception{var originals=manifest.path("originals");require(originals.isObject()&&originals.size()>0);var names=new HashSet<String>();originals.fieldNames().forEachRemaining(names::add);try(var paths=Files.list(folder)){require(paths.filter(p->!p.getFileName().toString().equals("manifest.json")).map(p->p.getFileName().toString()).collect(java.util.stream.Collectors.toSet()).equals(names));}for(var it=originals.fields();it.hasNext();){var row=it.next();require(hash(original(folder,row.getKey())).equals(row.getValue().asText()));}}
    private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,String id){var e=entries.get(id);require(e!=null);return e;}
    private static String targetPost(Element target){var values=target.getElementsByTagNameNS(MD,"SingleSignOnService");for(int i=0;i<values.getLength();i++){var e=(Element)values.item(i);if(POST.equals(e.getAttribute("Binding")))return e.getAttribute("Location");}throw new IllegalArgumentException("POST missing");}
    private static String shape(Element request){var d=SecureXml.newDocument();var clone=(Element)d.importNode(request,true);d.appendChild(clone);clone.removeAttribute("ID");clone.removeAttribute("IssueInstant");for(var s:MetadataAlgorithmEvidence.children(clone,DS,"Signature"))clone.removeChild(s);return structure(clone);}
    private static Element single(Element root,String ns,String local){var values=MetadataAlgorithmEvidence.children(root,ns,local);require(values.size()==1);return values.getFirst();}
    private static Map<String,String[]> audits(byte[] raw){var result=new HashMap<String,String[]>();for(var line:new String(raw,StandardCharsets.UTF_8).lines().filter(s->!s.isBlank()).toList()){var f=line.split("\\|",-1);require(f.length==9&&"SAMLscope-signature-v1".equals(f[0])&&result.put(f[1],f)==null);}return result;}
    private static String structure(Element root){var attrs=new TreeMap<String,String>();for(int i=0;i<root.getAttributes().getLength();i++){var a=root.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put(String.valueOf(a.getNamespaceURI())+"|"+a.getLocalName(),a.getNodeValue());}var value=new StringBuilder(String.valueOf(root.getNamespaceURI())+"|"+root.getLocalName()+attrs);for(var n=root.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e)value.append(structure(e));else if(n.getNodeType()==org.w3c.dom.Node.TEXT_NODE&&!n.getTextContent().isBlank())value.append(DS.equals(root.getNamespaceURI())&&"X509Certificate".equals(root.getLocalName())?n.getTextContent().replaceAll("\\s",""):n.getTextContent().trim());return value.toString();}
    private record ClockSample(Instant nativeAt,Instant hostStart,Instant hostEnd){}
    private static ClockSample clock(Path folder,String file)throws Exception{var sample=json(original(folder,file));require("native-product-os-UTC".equals(text(sample,"clockDomain"))&&sample.path("command").isArray()&&sample.path("command").size()==3&&"date".equals(sample.path("command").get(0).asText())&&"-u".equals(sample.path("command").get(1).asText())&&"+%Y-%m-%dT%H:%M:%S.%NZ".equals(sample.path("command").get(2).asText()));var raw=original(folder,text(sample,"nativeClockFile"));require(hash(raw).equals(text(sample,"nativeClockSha256")));var nativeAt=Instant.parse(new String(raw,StandardCharsets.UTF_8).strip());require(nativeAt.equals(Instant.parse(text(sample,"nativeInstant"))));var start=Instant.parse(text(sample,"hostStartedAt"));var end=Instant.parse(text(sample,"hostCompletedAt"));require(!end.isBefore(start));return new ClockSample(nativeAt,start,end);}
    private static boolean within(Instant at,Instant start,Instant end){return !at.isBefore(start)&&!at.isAfter(end);}
    static String runtime(Path folder,String name)throws Exception{var rows=json(original(folder,name));require(rows.isArray()&&rows.size()==1);var row=rows.get(0);require(row.path("State").path("Running").asBoolean(false)&&row.path("Config").path("Env").isMissingNode()&&"sha256:3c1b1fa64c58258aefc9e38d4ae60e9f0340731318a472110ea56ce88c18a11a".equals(text(row,"Image")));if(row.path("Mounts").isMissingNode()){var capture=json(original(folder,"target-container-mounts-capture.json"));require("samlscope-immutable-container-mounts-capture-v1".equals(text(capture,"schema"))&&"native-docker-inspect-readback".equals(text(capture,"source"))&&capture.path("productConfigurationWrites").asInt(-1)==0&&capture.path("protocolSubmissions").asInt(-1)==0&&capture.path("credentialPosts").asInt(-1)==0);var command=capture.path("command");require(command.isArray()&&command.size()==5&&"docker".equals(command.get(0).asText())&&"inspect".equals(command.get(1).asText())&&"--format".equals(command.get(2).asText())&&"{\"Id\":{{json .Id}},\"Image\":{{json .Image}},\"Mounts\":{{json .Mounts}}}".equals(command.get(3).asText())&&"samlscope-reference-shibboleth".equals(command.get(4).asText()));var start=Instant.parse(text(capture,"hostStartedAt"));var end=Instant.parse(text(capture,"hostCompletedAt"));require(!end.isBefore(start));var raw=original(folder,text(capture,"originalFile"));require(hash(raw).equals(text(capture,"originalSha256")));var supplement=json(raw);require(supplement.isObject()&&supplement.size()==3&&text(row,"Id").equals(text(supplement,"Id"))&&text(row,"Image").equals(text(supplement,"Image"))&&supplement.path("Mounts").isArray()&&supplement.path("Mounts").isEmpty());}else require(row.path("Mounts").isArray()&&row.path("Mounts").isEmpty());return text(row,"Id")+"|"+text(row,"Image")+"|"+text(row.path("State"),"StartedAt");}
    private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
    private static byte[] original(Path folder,String name)throws Exception{require(name.matches("[A-Za-z0-9_.-]+"));var p=folder.resolve(name);safeParents(folder);require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)<=8*1024*1024);return Files.readAllBytes(p);}
    private static void safeParents(Path p){for(;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));}
    private static String text(JsonNode root,String name){var value=root.path(name);require(value.isTextual()&&!value.asText().isBlank());return value.asText();}
    private static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
    private static String hashUnchecked(byte[] raw){try{return hash(raw);}catch(Exception impossible){throw new IllegalStateException(impossible);}}
    static void validateRequestBytes(String run,String fixture,byte[] raw,java.net.URI destination,String entity,java.net.URI acs,PlanCredentials credentials){var request=SecureXml.parse(raw).getDocumentElement();var action=ActionIds.derive(run,MetadataCertificateRuntimeProbeTestCase.CASE,"await-fixture-"+fixture,0);var rebuilt=new SamlSignedRequestFactory().build(fixture.endsWith("invalid-signature")?SamlSignedRequestFactory.Fixture.BAD_SIGNATURE_VALUE:SamlSignedRequestFactory.Fixture.VALID,"_"+action,destination,entity,acs,Instant.parse(request.getAttribute("IssueInstant")),credentials);require(Arrays.equals(raw,rebuilt));}
    private static void validateRestoration(Path folder,String run)throws Exception {
        var restored=json(original(folder,"restoration.json"));require(restored.path("restored").asBoolean(false)&&restored.path("errors").isArray()&&restored.path("errors").isEmpty()&&restored.path("original").equals(restored.path("final")));for(var kind:List.of("providers","audit")){String path="/opt/reference-idp/conf/"+(kind.equals("providers")?"metadata-providers":"audit")+".xml";require(hash(original(folder,"original-"+kind+".xml")).equals(text(restored.path("original"),path)));}
        var operations=json(original(folder,"operations.json"));require(operations.isArray());int writes=0,reloads=0,restarts=0,restores=0;for(var row:operations){String operation=text(row,"operation");if(operation.equals("write")){require(row.path("readBack").asBoolean(false));writes++;if(text(row,"label").startsWith("restore-"))restores++;}else if(operation.equals("reload")){require(row.path("completed").asBoolean(false));reloads++;}else if(operation.equals("restart")){require(row.path("completed").asBoolean(false));restarts++;}else throw new IllegalArgumentException("Unknown native operation");}
        var counts=json(original(folder,"operation-counts.json"));require(counts.path("restored").asBoolean(false)&&counts.path("personOperations").asInt(-1)==0&&counts.path("credentialPosts").asInt(-1)==1&&counts.path("productWrites").asInt(-1)==writes&&counts.path("metadataReloads").asInt(-1)==reloads&&counts.path("productRestarts").asInt(-1)==restarts&&counts.path("restorationWrites").asInt(-1)==restores&&counts.path("certificateTargetSubmissions").asInt(-1)==6&&counts.path("ordinaryBaselineSubmissions").asInt(-1)==1&&counts.path("protocolSubmissions").asInt(-1)==7&&counts.path("sameAuthenticatedClient").asBoolean(false)&&counts.path("additionalLoginBlocked").asBoolean(false));
        var ready=json(original(folder,"restored-native-readiness.json"));require(ready.path("status").asInt(-1)==200&&"http://localhost:18280/idp/shibboleth".equals(text(ready,"url"))&&!ready.path("credentialsPersisted").asBoolean(true));
    }
    private void validateBaseline(Path folder,String run,Map<String,TranscriptEntry> entries,Element target)throws Exception {
        var proof=json(original(folder,"baseline-proof.json"));require(run.equals(text(proof,"runId"))&&proof.path("protocolSubmissions").asInt(-1)==1&&!proof.path("credentialsPersisted").asBoolean(true));var request=entry(entries,text(proof,"requestReference"));var response=entry(entries,text(proof,"responseReference"));require(request.direction()==Direction.OUTBOUND&&response.direction()==Direction.INBOUND&&"GET".equals(request.method())&&"POST".equals(response.method())&&request.timestamp().isBefore(response.timestamp())&&Boolean.TRUE.equals(response.samlSummary().get("normalFlowAccepted")));var req=SecureXml.parse(content.readDecodedSaml(request)).getDocumentElement();var sp=SecureXml.parse(original(folder,"baseline-fixture.xml")).getDocumentElement();var signing=MetadataAlgorithmEvidence.signingKeys(sp);require(signing.size()==1&&new RedirectSignatureVerifier().isValidForMessage(request.rawQuery(),signing.getFirst(),content.readDecodedSaml(request))&&req.getAttribute("ID").equals(request.correlationId())&&req.getAttribute("ID").equals(response.correlationId()));var reply=SecureXml.parse(content.readDecodedSaml(response)).getDocumentElement();require(req.getAttribute("ID").equals(reply.getAttribute("InResponseTo"))&&target.getAttribute("entityID").equals(single(reply,S,"Issuer").getTextContent())&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(reply)&&MetadataAlgorithmEvidence.signingKeys(target).stream().anyMatch(c->new XmlSignatureVerifier().hasValidEnvelopedSignature(reply,c)));
        var restore=json(original(folder,"baseline-restoration.json"));require(restore.path("restored").asBoolean(false)&&restore.path("temporaryRemoved").asBoolean(false)&&Arrays.equals(original(folder,"baseline-original-providers.xml"),original(folder,"baseline-final-providers.xml")));var counts=json(original(folder,"baseline-operation-counts.json"));require(counts.path("credentialPosts").asInt(-1)==1&&counts.path("actualProtocolSubmissions").asInt(-1)==1&&counts.path("actualNativeProtocolGets").asInt(-1)==1&&counts.path("actualNativeProtocolPosts").asInt(-1)==0&&counts.path("personOperations").asInt(-1)==0);
    }
    private static void validateNetworkEpoch(Path folder,Instant start,Instant beforeRequest)throws Exception {for(var row:json(original(folder,"certificate-revocation-unreachable-network.json")))require(!Instant.parse(text(row,"startedAt")).isBefore(start)&&!Instant.parse(text(row,"completedAt")).isAfter(beforeRequest));}
    private static final String B="http://www.springframework.org/schema/beans",PROP="http://www.springframework.org/schema/p",CONS="http://www.springframework.org/schema/c";
    private static final Map<String,String> TRUST_JARS=Map.of(
        "idp-conf-impl","428e389d88bb2abcad19d69bcf759af29f7ce6beb776ccfaa5a6ea76751682ba",
        "idp-saml-impl","1a2a9f867d11c50eeaf2a6140bb5de88b0611d694ea6de2bbfe32f72a4a2998b",
        "opensaml-saml-impl","9f04221e172dc426f90fb3873d0148a0744edbf9e7a37de7ee0e6a34f7b74581",
        "opensaml-xmlsec-impl","cc67fc1bd9cb435cdbe7483ef04513c83cc9619a3015c04ad41bb6cc0eb6e68e");
    private static final Map<String,String> TRUST_CONFIGS=Map.of(
        "global","ca08485a1b5ef8cf0ac1afb80ff066237759e4fb3d884d087f905d8ca0918bcc",
        "services","0c5de788ebc611af60ebb3bf4071dcd23744f599d64d65bdb0744515d11a77c0",
        "relying-party","64e2a04dfbf2ffa2a582b995bcbf121b634ab7c8766cb8f22d3397d541f31bd5");
    private static String validateTrustScope(Path folder,String entity)throws Exception {
        for(var pin:TRUST_JARS.entrySet())require(pin.getValue().equals(hash(original(folder,"native-"+pin.getKey()+".jar"))));
        for(var phase:List.of("before","after")){
            var observed=json(original(folder,"trust-"+phase+"-observed.json"));require(entity.equals(text(observed,"entityId"))&&"http://shibboleth.net/ns/profiles/saml2/sso/browser".equals(text(observed,"profileId"))&&!observed.path("privateFieldsExported").asBoolean(true));
            for(var pin:TRUST_CONFIGS.entrySet())require(pin.getValue().equals(hash(original(folder,"trust-"+phase+"-"+pin.getKey()+".xml"))));
            require("1fcd492d07b1ca59600b763c0cddc3be85dc223841a2298bf3719274b66c4cb3".equals(hash(original(folder,"trust-"+phase+"-classpath-sha256.json"))));
            var overrides=json(original(folder,"trust-"+phase+"-override-source-inventory.json"));require(overrides.isArray()&&overrides.isEmpty());
            var properties=json(original(folder,"trust-"+phase+"-selected-properties.json"));require(properties.isObject());
            for(var it=properties.fields();it.hasNext();){var row=it.next();require((row.getKey().equals("idp.trust.signatures")&&Set.of("shibboleth.ChainingSignatureTrustEngine","shibboleth.ExplicitKeySignatureTrustEngine","shibboleth.PKIXSignatureTrustEngine").contains(row.getValue().asText()))||(row.getKey().equals("idp.security.config")&&row.getValue().asText().equals("shibboleth.DefaultSecurityConfiguration"))||(row.getKey().equals("idp.additionalProperties")&&row.getValue().asText().equals("/credentials/secrets.properties")));}
            var flags=json(original(folder,"trust-"+phase+"-process-overrides.json"));require(flags.path("nativeJavaProcessObserved").asBoolean(false)&&!flags.path("trustOverridePresent").asBoolean(true)&&!flags.path("customAgentPresent").asBoolean(true)&&!flags.path("privateFieldsExported").asBoolean(true));
            var profile=json(original(folder,"trust-"+phase+"-native-effective-profile.json"));ShibbolethSubjectConfirmationEvidence.validateProfile(profile);
            var jarPins=observed.path("nativeJars");require(jarPins.isObject()&&jarPins.size()==TRUST_JARS.size());for(var pin:TRUST_JARS.entrySet())require(pin.getValue().equals(text(jarPins,pin.getKey())));
        }
        for(var suffix:List.of("classpath-sha256.json","override-source-inventory.json","selected-properties.json","properties-sha256.json","xml-sha256.json","native-effective-profile.json","process-overrides.json"))require(Arrays.equals(original(folder,"trust-before-"+suffix),original(folder,"trust-after-"+suffix)));
        var source=original(folder,"native-idp-conf-impl.jar");var rp=SecureXml.parse(zip(source,"net/shibboleth/idp/conf/relying-party-system.xml")).getDocumentElement();var chain=bean(rp,"shibboleth.ChainingSignatureTrustEngine");require("org.opensaml.xmlsec.signature.support.impl.ChainingSignatureTrustEngine".equals(chain.getAttribute("class")));var refs=chain.getElementsByTagNameNS(B,"ref");require(refs.getLength()==2&&"shibboleth.ExplicitKeySignatureTrustEngine".equals(((Element)refs.item(0)).getAttribute("bean"))&&"shibboleth.PKIXSignatureTrustEngine".equals(((Element)refs.item(1)).getAttribute("bean")));
        var explicit=bean(rp,"shibboleth.ExplicitKeySignatureTrustEngine");require("org.opensaml.xmlsec.signature.support.impl.ExplicitKeySignatureTrustEngine".equals(explicit.getAttribute("class"))&&"shibboleth.MetadataCredentialResolver".equals(explicit.getAttributeNS(CONS,"resolver-ref")));
        var security=SecureXml.parse(zip(source,"net/shibboleth/idp/conf/security-system.xml")).getDocumentElement();var resolver=bean(security,"shibboleth.MetadataCredentialResolver");require("org.opensaml.saml.security.impl.MetadataCredentialResolver".equals(resolver.getAttribute("class"))&&"shibboleth.RoleDescriptorResolver".equals(resolver.getAttributeNS(PROP,"roleDescriptorResolver-ref")));
        var pkix=bean(rp,"shibboleth.PKIXSignatureTrustEngine");require("org.opensaml.xmlsec.signature.support.impl.PKIXSignatureTrustEngine".equals(pkix.getAttribute("class"))&&"shibboleth.MetadataPKIXValidationInformationResolver".equals(pkix.getAttributeNS(CONS,"resolver-ref")));
        // Fixed installed implementation bytes bind these stock beans to actual resolver/engine behavior.
        // Signed normal use and an invalid-signature rejection additionally exercise the selected path.
        return json(original(folder,"trust-before-selected-properties.json")).path("idp.trust.signatures").asText("shibboleth.ChainingSignatureTrustEngine");
    }
    static boolean nativeCertificateCause(Path folder,JsonNode exchange,String variant,String trust,String run,String targetDigest,String requestId,byte[] request,X509Certificate certificate,Instant start,Instant end)throws Exception {
        if(!trust.equals("shibboleth.PKIXSignatureTrustEngine")||!exchange.path("certificateCheckFailureFile").isTextual())return false;
        var cause=json(original(folder,text(exchange,"certificateCheckFailureFile")));require("samlscope-native-certpath-operation-failure-v1".equals(text(cause,"schema"))&&"native-selected-pkix-trust-engine".equals(text(cause,"source"))&&"PKIX".equals(text(cause,"algorithm"))&&trust.equals(text(cause,"trustEngineBean"))&&run.equals(text(cause,"runId"))&&targetDigest.equals(text(cause,"targetMetadataSha256"))&&requestId.equals(text(cause,"requestId"))&&hash(request).equals(text(cause,"requestSha256"))&&hash(certificate.getEncoded()).equals(text(cause,"certificateSha256"))&&within(Instant.parse(text(cause,"nativeTimestamp")),start,end));
        String required=switch(variant){case "certificate-critical-extension"->"UNRECOGNIZED_CRIT_EXT";case "certificate-unknown-ca"->"NO_TRUST_ANCHOR";case "certificate-revoked"->"REVOKED";case "certificate-revocation-unreachable"->"UNDETERMINED_REVOCATION_STATUS";default->throw new IllegalArgumentException("Unsupported certificate reason");};require("java.security.cert.CertPathValidatorException".equals(text(cause,"exceptionClass"))&&required.equals(text(cause,"reason")));var bytes=original(folder,text(cause,"exceptionTraceFile"));require(hash(bytes).equals(text(cause,"exceptionTraceSha256")));var trace=new String(bytes,StandardCharsets.UTF_8);var lines=trace.lines().toList();var certificateDigest=hash(certificate.getEncoded());require(lines.stream().filter(line->line.equals("request_id="+requestId)).count()==1&&lines.stream().filter(line->line.equals("request_sha256="+hashUnchecked(request))).count()==1&&lines.stream().filter(line->line.equals("certificate_sha256="+certificateDigest)).count()==1&&lines.stream().filter(line->line.equals("reason="+required)).count()==1&&trace.contains("java.security.cert.CertPathValidatorException:")&&trace.contains("java.security.cert.CertPathValidator.validate(")&&trace.contains("sun.security.provider.certpath.PKIXCertPathValidator.validate("));return true;
    }
    static void validateCondition(Path folder,String variant,Element peer,X509Certificate certificate)throws Exception {
        require(MetadataCertificateRuntimeProbeTestCase.VARIANTS.contains(variant));
        if(variant.equals("control"))return;
        if(variant.equals("certificate-critical-extension")){require(certificate.getCriticalExtensionOIDs()!=null&&certificate.getCriticalExtensionOIDs().contains("1.3.6.1.4.1.57264.1.1")&&certificate.hasUnsupportedCriticalExtension());return;}
        if(variant.equals("certificate-unknown-ca")){require("O=SAMLscope,CN=Unknown SAMLscope fixture CA".equals(certificate.getIssuerX500Principal().getName())&&!certificate.getIssuerX500Principal().equals(certificate.getSubjectX500Principal()));certificate.verify(certificate.getPublicKey());return;}
        var extensions=single(peer,MD,"Extensions");var proof=single(extensions,"urn:samlscope:test:certificate-revocation","RevocationOriginals");require(variant.equals(proof.getAttribute("variant")));var issuer=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(single(proof,"urn:samlscope:test:certificate-revocation","IssuerCertificate").getTextContent())));require(issuer.getBasicConstraints()>=0&&issuer.getKeyUsage()!=null&&issuer.getKeyUsage()[6]&&issuer.getSubjectX500Principal().equals(certificate.getIssuerX500Principal()));issuer.verify(issuer.getPublicKey());certificate.verify(issuer.getPublicKey());
        if(variant.equals("certificate-revoked")){
            var crl=(X509CRL)CertificateFactory.getInstance("X.509").generateCRL(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(single(proof,"urn:samlscope:test:certificate-revocation","CRL").getTextContent())));crl.verify(issuer.getPublicKey());require(crl.getIssuerX500Principal().equals(issuer.getSubjectX500Principal())&&crl.getNextUpdate()!=null&&crl.getNextUpdate().after(crl.getThisUpdate()));var revoked=crl.getRevokedCertificate(certificate.getSerialNumber());require(revoked!=null&&!revoked.getRevocationDate().after(crl.getThisUpdate()));return;
        }
        var urls=new LinkedHashSet<String>();urls.addAll(extensionUris(certificate.getExtensionValue("2.5.29.31")));urls.addAll(extensionUris(certificate.getExtensionValue("1.3.6.1.5.5.7.1.1")));var prefix="http://samlscope-reference-suite:18481/samlscope-revocation/"+certificate.getSerialNumber().toString(16);require(urls.equals(Set.of(prefix+"/unavailable.crl",prefix+"/unavailable.ocsp")));
        var network=json(original(folder,"certificate-revocation-unreachable-network.json"));require(network.isArray()&&network.size()==2);var seen=new HashSet<String>();for(var row:network){String url=text(row,"url");require(urls.contains(url)&&seen.add(url)&&row.path("exitCode").asInt(-1)==7&&"native-target-network".equals(text(row,"source"))&&row.path("command").isArray());var command=row.path("command");require(command.size()==9&&"curl".equals(command.get(0).asText())&&"--noproxy".equals(command.get(1).asText())&&"*".equals(command.get(2).asText())&&"--connect-timeout".equals(command.get(3).asText())&&"1".equals(command.get(4).asText())&&"--max-time".equals(command.get(5).asText())&&"2".equals(command.get(6).asText())&&"--silent".equals(command.get(7).asText())&&url.equals(command.get(8).asText()));require(hash(original(folder,text(row,"stdoutFile"))).equals(text(row,"stdoutSha256"))&&hash(original(folder,text(row,"stderrFile"))).equals(text(row,"stderrSha256"))&&!Instant.parse(text(row,"completedAt")).isBefore(Instant.parse(text(row,"startedAt"))));}
    }
    private static void validateRevocationAt(String variant,Element peer,Instant at)throws Exception {
        if(!variant.equals("certificate-revoked"))return;var original=single(single(peer,MD,"Extensions"),"urn:samlscope:test:certificate-revocation","RevocationOriginals");var crl=(X509CRL)CertificateFactory.getInstance("X.509").generateCRL(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(single(original,"urn:samlscope:test:certificate-revocation","CRL").getTextContent())));require(!at.isBefore(crl.getThisUpdate().toInstant())&&at.isBefore(crl.getNextUpdate().toInstant()));
    }
    static Set<String> extensionUris(byte[] encoded){require(encoded!=null);var result=new LinkedHashSet<String>();derUris(encoded,0,encoded.length,result);return result;}
    private static void derUris(byte[] bytes,int start,int end,Set<String> result){for(int pos=start;pos<end;){require(pos+2<=end);int tag=bytes[pos++]&255,length=bytes[pos++]&255;if((length&128)!=0){int count=length&127;require(count>0&&count<=4&&pos+count<=end);length=0;while(count-->0)length=(length<<8)|(bytes[pos++]&255);}require(length>=0&&pos+length<=end);if(tag==0x86){String uri=new String(bytes,pos,length,StandardCharsets.US_ASCII);require(uri.startsWith("http://")&&result.add(uri));}else if((tag&0x20)!=0||tag==4)derUris(bytes,pos,pos+length,result);pos+=length;}}
    private static Element bean(Element root,String id){var list=root.getElementsByTagNameNS(B,"bean");Element found=null;for(int i=0;i<list.getLength();i++)if(id.equals(((Element)list.item(i)).getAttribute("id"))){require(found==null);found=(Element)list.item(i);}require(found!=null);return found;}
    private static byte[] zip(byte[] bytes,String name)throws Exception{try(var zip=new ZipInputStream(new java.io.ByteArrayInputStream(bytes))){for(var entry=zip.getNextEntry();entry!=null;entry=zip.getNextEntry())if(name.equals(entry.getName()))return zip.readAllBytes();}throw new IllegalArgumentException("Native implementation resource unavailable");}
    private static void require(boolean value){if(!value)throw new IllegalArgumentException("Native metadata certificate runtime use unproven");}
}
