package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import org.w3c.dom.Element;

/** Metadata/protocol role-key comparison with original-backed native consumer epochs. */
public final class MetadataRoleKeyEvidence {
    public static final String SCHEMA="samlscope-metadata-role-key-consumption-v1";
    public static final String ADAPTER="shibboleth-native-filesystem-role-keys-v1";
    private static final String RUN="run_[0-9A-HJKMNP-TV-Z]{26}",MD="urn:oasis:names:tc:SAML:2.0:metadata",P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",DS="http://www.w3.org/2000/09/xmldsig#",N="urn:mace:shibboleth:2.0:metadata",XSI="http://www.w3.org/2001/XMLSchema-instance";
    private static final String SUCCESS="urn:oasis:names:tc:SAML:2.0:status:Success",POST="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
    private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final BiFunction<String,String,Optional<PlanCredentials>> keys;
    private final Map<String,MetadataRoleKeyNativeAdapter> nativeAdapters;
    public MetadataRoleKeyEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,BiFunction<String,String,Optional<PlanCredentials>> keys){this(directory,content,metadata,keys,new MetadataRoleKeyNativeAdapter[0]);}
    public MetadataRoleKeyEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,BiFunction<String,String,Optional<PlanCredentials>> keys,MetadataRoleKeyNativeAdapter... adapters){
        this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.keys=Objects.requireNonNull(keys);
        var registered=new HashMap<String,MetadataRoleKeyNativeAdapter>();
        for(var adapter:Objects.requireNonNull(adapters)){Objects.requireNonNull(adapter);require(!ADAPTER.equals(adapter.adapter())&&!adapter.adapter().isBlank()&&registered.put(adapter.adapter(),adapter)==null);}
        nativeAdapters=Map.copyOf(registered);
    }
    public boolean exists(String run){return run!=null&&run.matches(RUN)&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
    public Optional<CaseOutcome> evaluate(CaseContext context){
        try {
            require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete()&&context.runId().matches(RUN));var folder=directory.resolve(context.runId());safeParents(folder);require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
            var manifestRaw=original(folder,"manifest.json");var manifest=json(manifestRaw);require(SCHEMA.equals(text(manifest,"schema"))&&context.runId().equals(text(manifest,"runId")));var selectedAdapter=text(manifest,"adapter");require(ADAPTER.equals(selectedAdapter)||nativeAdapters.containsKey(selectedAdapter));verifyOriginals(folder,manifest);
            var targetRaw=metadata.apply(context.runId());require(hash(targetRaw).equals(text(manifest,"targetMetadataSha256")));var target=SecureXml.parse(targetRaw).getDocumentElement();require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName()));var targetSigning=MetadataAlgorithmEvidence.signingKeys(target);require(!targetSigning.isEmpty());String entity=text(manifest,"entityId");var nativeSession=ADAPTER.equals(selectedAdapter)?shibbolethSession(context,folder,manifest,entity):nativeAdapters.get(selectedAdapter).open(context,folder,manifest,entity);require(nativeSession!=null&&runtime(folder,"target-container-inspect-start.json").equals(runtime(folder,"target-container-inspect-end.json")));
            var entries=new HashMap<String,TranscriptEntry>();var requestIds=new HashSet<String>();for(var e:context.transcript().list(context.runId())){require(context.runId().equals(e.runId())&&entries.put(e.id(),e)==null&&(e.decodedSamlRef()==null||("transcripts/"+context.runId()+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())));if(e.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(e.samlSummary().get("type")))require(requestIds.add(e.samlSummary().get("id") instanceof String id&&!id.isBlank()?id:e.samlSummary().get("action_id") instanceof String action&&!action.isBlank()?"_"+action:e.id()));}
            var observations=manifest.path("observations");require(observations.isArray()&&observations.size()==4);var seenVariants=new HashSet<String>();var selected=new HashSet<String>();var proof=new LinkedHashSet<EvidenceRef>();var verifiedFixtures=new HashSet<String>();var shapes=new HashMap<String,String>();var roleSets=new HashMap<String,List<String>>();int success=0,rejection=0,violation=0;Instant previousEpoch=null;
            for(var row:observations){var variant=text(row,"variant");require(MetadataRoleKeyProbeTestCase.VARIANTS.contains(variant)&&seenVariants.add(variant));var epochStart=Instant.parse(text(row,"startedAt"));var epochEnd=Instant.parse(text(row,"completedAt"));require(epochEnd.isAfter(epochStart)&&(previousEpoch==null||!epochStart.isBefore(previousEpoch)));previousEpoch=epochEnd;
                var fixture=original(folder,variant+"-fixture.xml");var peer=SecureXml.parse(fixture).getDocumentElement();require(MD.equals(peer.getNamespaceURI())&&"EntityDescriptor".equals(peer.getLocalName())&&entity.equals(peer.getAttribute("entityID")));var sp=single(peer,MD,"SPSSODescriptor");var idp=single(peer,MD,"IDPSSODescriptor");boolean explicit=variant.contains("explicit"),flipped=variant.contains("idp-first");var spKeys=certificates(sp);var peerKeys=certificates(idp);validateKeyPurposes(spKeys,peerKeys,explicit);var roleOrder=MetadataAlgorithmEvidence.children(peer,MD,"SPSSODescriptor").getFirst().compareDocumentPosition(idp);require(flipped?(roleOrder&org.w3c.dom.Node.DOCUMENT_POSITION_PRECEDING)!=0:(roleOrder&org.w3c.dom.Node.DOCUMENT_POSITION_FOLLOWING)!=0);
                roleSets.put(variant,List.of(spKeys.getFirst().fingerprint(),peerKeys.getFirst().fingerprint(),explicit?spKeys.get(1).fingerprint():spKeys.getFirst().fingerprint()));
                var signing=spKeys.getFirst().certificate();var receiver=keys.apply(context.runId(),explicit?"three-signing-keys":flipped?"three-signing-keys-second":"three-signing-keys-first").orElseThrow();require(fingerprint(receiver.certificate()).equals(roleSets.get(variant).get(2)));var opposite=keys.apply(context.runId(),flipped?"three-signing-keys-first":"three-signing-keys-second").orElseThrow();require(fingerprint(opposite.certificate()).equals(peerKeys.getFirst().fingerprint()));
                var first=keys.apply(context.runId(),"three-signing-keys-first").orElseThrow();require(new XmlSignatureVerifier().hasValidEnvelopedSignature(peer,first.certificate()));
                var queryAt=nativeSession.validateEpoch(row,fixture,peer,epochStart,epochEnd);require(queryAt!=null&&!queryAt.isBefore(epochStart)&&!queryAt.isAfter(epochEnd));
                var prepared=entry(entries,text(row,"preparedReference"));var fetch=entry(entries,text(row,"fetchReference"));require("MetadataPrepared".equals(prepared.samlSummary().get("type"))&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&variant.equals(prepared.samlSummary().get("variant"))&&variant.equals(fetch.samlSummary().get("variant"))&&fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&prepared.direction()==Direction.OUTBOUND&&fetch.direction()==Direction.INBOUND&&Objects.equals(fetch.status(),200)&&Objects.equals(prepared.status(),200)&&!prepared.timestamp().isBefore(fetch.timestamp())&&Arrays.equals(fixture,content.readDecodedSaml(prepared))&&hash(fixture).equals(prepared.samlSummary().get("metadataSha256")));proof.add(new EvidenceRef("transcript",prepared.id()));proof.add(new EvidenceRef("transcript",fetch.id()));
                var exchanges=row.path("exchanges");require(exchanges.isArray()&&exchanges.size()==(explicit?(flipped?3:4):2));for(var exchange:exchanges){String fixtureId=text(exchange,"fixtureId");require(MetadataRoleKeyProbeTestCase.FIXTURES.contains(fixtureId)&&variant.equals(MetadataRoleKeyProbeTestCase.variant(fixtureId))&&verifiedFixtures.add(fixtureId));var request=entry(entries,text(exchange,"requestReference"));require(selected.add(request.id())&&request.direction()==Direction.OUTBOUND&&"POST".equals(request.method())&&MetadataRoleKeyProbeTestCase.CASE.equals(request.samlSummary().get("scenario_case_id"))&&fixtureId.equals(request.samlSummary().get("fixture_id"))&&!request.timestamp().isBefore(prepared.timestamp()));
                    var raw=content.readDecodedSaml(request);var req=SecureXml.parse(raw).getDocumentElement();String reqId=req.getAttribute("ID");require(P.equals(req.getNamespaceURI())&&"AuthnRequest".equals(req.getLocalName())&&"2.0".equals(req.getAttribute("Version"))&&entity.equals(single(req,S,"Issuer").getTextContent())&&reqId.equals("_"+request.samlSummary().get("action_id"))&&request.correlationId().equals(request.samlSummary().get("action_id"))&&req.getAttribute("Destination").equals(request.url())&&targetPost(target).equals(request.url())&&MetadataSupersessionProbeTestCase.acs(peer,0).toString().equals(req.getAttribute("AssertionConsumerServiceURL"))&&POST.equals(req.getAttribute("ProtocolBinding"))&&!"true".equals(req.getAttribute("ForceAuthn"))&&!"true".equals(req.getAttribute("IsPassive")));
                    var expected=fixtureId.endsWith("peer-key")?opposite.certificate():fixtureId.endsWith("encryption-key")?receiver.certificate():signing;var verifier=new XmlSignatureVerifier();require(verifier.hasValidEnvelopedReferenceDigests(req));boolean invalid=fixtureId.endsWith("invalid-signature");require(invalid?!verifier.hasValidEnvelopedSignature(req,expected):verifier.hasValidEnvelopedSignature(req,expected));if(!ADAPTER.equals(selectedAdapter))validateExactRequest(context,fixtureId,variant,request,req,raw,peer);String shape=shape(req);if(fixtureId.endsWith("normal"))shapes.put(variant,shape);else require(shape.equals(shapes.get(variant)));
                    var transport=http(exchange,req,raw,epochStart,epochEnd,queryAt);var matches=entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&reqId.equals(e.samlSummary().get("inResponseTo"))&&(ADAPTER.equals(selectedAdapter)||"Response".equals(e.samlSummary().get("type")))).toList();proof.add(new EvidenceRef("transcript",request.id()));
                    if(fixtureId.endsWith("normal")){require(matches.size()==1);var reply=entry(entries,text(exchange,"responseReference"));require(reply==matches.getFirst()&&selected.add(reply.id())&&reply.timestamp().isAfter(request.timestamp()));var response=SecureXml.parse(content.readDecodedSaml(reply)).getDocumentElement();require(!MetadataAlgorithmEvidence.children(response,S,"EncryptedAssertion").isEmpty());VerifiedResponseAssertion.read(response,target.getAttribute("entityID"),targetSigning,peer,Optional.of(receiver),reqId,req.getAttribute("AssertionConsumerServiceURL"));require(failsDecrypt(response,opposite.privateKey())&&(explicit?failsDecrypt(response,keys.apply(context.runId(),flipped?"three-signing-keys-second":"three-signing-keys-first").orElseThrow().privateKey()):true));require(transport.path("samlResponseFormPresent").asBoolean(false)&&hash(content.readDecodedSaml(reply)).equals(text(transport,"responseSamlSha256")));nativeSession.validateExchange(row,exchange,req,raw,transport,queryAt,epochStart,epochEnd,MetadataRoleKeyNativeAdapter.Disposition.NORMAL_SUCCESS);success++;proof.add(new EvidenceRef("transcript",reply.id()));}
                    else if(matches.isEmpty()){require(!transport.path("samlResponseFormPresent").asBoolean(true));nativeSession.validateExchange(row,exchange,req,raw,transport,queryAt,epochStart,epochEnd,MetadataRoleKeyNativeAdapter.Disposition.SIGNATURE_REJECTED);if(!exchange.path("responseReference").isNull()){var rejectionEntry=entry(entries,text(exchange,"responseReference"));require(rejectionEntry.direction()==Direction.INBOUND&&rejectionEntry.timestamp().isAfter(request.timestamp()));proof.add(new EvidenceRef("transcript",rejectionEntry.id()));}rejection++;}
                    else{require(!invalid&&fixtureId.endsWith("peer-key")&&matches.size()==1);var reply=entry(entries,text(exchange,"responseReference"));require(reply==matches.getFirst()&&selected.add(reply.id())&&reply.timestamp().isAfter(request.timestamp()));var response=SecureXml.parse(content.readDecodedSaml(reply)).getDocumentElement();VerifiedResponseAssertion.read(response,target.getAttribute("entityID"),targetSigning,peer,Optional.of(receiver),reqId,req.getAttribute("AssertionConsumerServiceURL"));require(transport.path("samlResponseFormPresent").asBoolean(false)&&hash(content.readDecodedSaml(reply)).equals(text(transport,"responseSamlSha256")));nativeSession.validateExchange(row,exchange,req,raw,transport,queryAt,epochStart,epochEnd,MetadataRoleKeyNativeAdapter.Disposition.CROSS_ROLE_SUCCESS);violation++;proof.add(new EvidenceRef("transcript",reply.id()));}
                }
            }
            require(seenVariants.equals(Set.copyOf(MetadataRoleKeyProbeTestCase.VARIANTS))&&verifiedFixtures.equals(Set.copyOf(MetadataRoleKeyProbeTestCase.FIXTURES))&&success==4&&rejection+violation==7);var a=roleSets.get(MetadataRoleKeyProbeTestCase.VARIANTS.get(0));var b=roleSets.get(MetadataRoleKeyProbeTestCase.VARIANTS.get(1));var c=roleSets.get(MetadataRoleKeyProbeTestCase.VARIANTS.get(2));var d=roleSets.get(MetadataRoleKeyProbeTestCase.VARIANTS.get(3));require(a.get(0).equals(b.get(1))&&a.get(1).equals(b.get(0))&&a.get(2).equals(b.get(2))&&c.get(0).equals(a.get(0))&&c.get(1).equals(a.get(1))&&d.get(0).equals(b.get(0))&&d.get(1).equals(b.get(1)));
            var reason=violation>0?"metadata.role-keys.cross-role-accepted":"metadata.role-keys.scoped-use-observed";proof.add(new EvidenceRef("native-role-key-evidence",context.runId()+"/manifest.json#"+hash(manifestRaw)));return Optional.of(new CaseOutcome(violation>0?Outcome.VIOLATED:Outcome.SATISFIED,null,reason,reason,List.copyOf(proof),Map.of("evidence_adapter",selectedAdapter,"run_id",context.runId(),"operative_role","SPSSODescriptor","peer_role_retained",true,"role_order_and_key_swaps",4,"normal_signed_encrypted_successes",success,"explicit_rejections",rejection,"cross_role_acceptance",violation,"restored",true)));
        }catch(Exception unavailable){return Optional.empty();}
    }
    private void validateExactRequest(CaseContext context,String fixtureId,String variant,TranscriptEntry request,Element req,byte[] raw,Element peer){
        var action=com.samlscope.core.caseexec.ActionIds.derive(context.runId(),MetadataRoleKeyProbeTestCase.CASE,"await-fixture-"+fixtureId,0);
        require(action.equals(request.samlSummary().get("action_id")));
        String alias=fixtureId.endsWith("encryption-key")?"three-signing-keys":fixtureId.endsWith("peer-key")?(variant.contains("idp-first")?"three-signing-keys-first":"three-signing-keys-second"):(variant.contains("idp-first")?"three-signing-keys-second":"three-signing-keys-first");
        var credential=keys.apply(context.runId(),alias).orElseThrow();
        var kind=fixtureId.endsWith("invalid-signature")?com.samlscope.saml.normal.SamlSignedRequestFactory.Fixture.BAD_SIGNATURE_VALUE:com.samlscope.saml.normal.SamlSignedRequestFactory.Fixture.VALID;
        var expected=new com.samlscope.saml.normal.SamlSignedRequestFactory().build(kind,"_"+action,java.net.URI.create(req.getAttribute("Destination")),peer.getAttribute("entityID"),MetadataSupersessionProbeTestCase.acs(peer,0),Instant.parse(req.getAttribute("IssueInstant")),credential);
        require(Arrays.equals(expected,raw));
    }
    private static MetadataRoleKeyNativeAdapter.Session shibbolethSession(CaseContext context,Path folder,JsonNode manifest,String entity)throws Exception{
        validateConfiguration(folder,entity,context.runId(),text(manifest,"sourcePath"));
        var audit=audits(original(folder,"native-request-bound-audit.log"));
        return new MetadataRoleKeyNativeAdapter.Session(){
            @Override public Instant validateEpoch(JsonNode row,byte[] fixture,Element peer,Instant startedAt,Instant completedAt)throws Exception{
                var variant=text(row,"variant");
                for(var phase:List.of("before","after")){require(Arrays.equals(fixture,original(folder,variant+"-"+phase+"-source.xml"))&&Arrays.equals(original(folder,"configured-providers.xml"),original(folder,variant+"-"+phase+"-providers.xml"))&&Arrays.equals(original(folder,"configured-audit.xml"),original(folder,variant+"-"+phase+"-audit.xml")));}
                var query=json(original(folder,variant+"-metadata-query.json"));require(query.path("exitCode").asInt(-1)==0&&entity.equals(text(query,"entityId"))&&hash(original(folder,variant+"-metadata-stdout.txt")).equals(text(query,"stdoutSha256"))&&hash(original(folder,variant+"-metadata-stderr.txt")).equals(text(query,"stderrSha256")));require(query.path("command").isArray()&&query.path("command").size()==5&&"/opt/reference-idp/bin/mdquery.sh".equals(query.path("command").get(0).asText())&&"-u".equals(query.path("command").get(1).asText())&&"http://localhost:8080/idp".equals(query.path("command").get(2).asText())&&"-e".equals(query.path("command").get(3).asText())&&entity.equals(query.path("command").get(4).asText()));var nativePeer=SecureXml.parse(original(folder,variant+"-metadata-stdout.txt")).getDocumentElement();require(entity.equals(nativePeer.getAttribute("entityID"))&&structure(single(peer,MD,"SPSSODescriptor")).equals(structure(single(nativePeer,MD,"SPSSODescriptor")))&&structure(single(peer,MD,"IDPSSODescriptor")).equals(structure(single(nativePeer,MD,"IDPSSODescriptor"))));return Instant.parse(text(query,"recordedAt"));
            }
            @Override public void validateExchange(JsonNode row,JsonNode exchange,Element request,byte[] raw,JsonNode transport,Instant queryAt,Instant epochStart,Instant epochEnd,MetadataRoleKeyNativeAdapter.Disposition disposition)throws Exception{
                var beforeClock=clock(folder,text(exchange,"clockBeforeFile"));var afterClock=clock(folder,text(exchange,"clockAfterFile"));var begin=beforeClock.nativeAt();var end=afterClock.nativeAt();require(begin.equals(Instant.parse(text(exchange,"nativeBegin")))&&end.equals(Instant.parse(text(exchange,"nativeEnd")))&&!end.isBefore(begin)&&!beforeClock.hostStart().isBefore(queryAt)&&!Instant.parse(text(transport,"startedAt")).isBefore(beforeClock.hostEnd())&&!afterClock.hostStart().isBefore(Instant.parse(text(transport,"completedAt")))&&!beforeClock.hostStart().isBefore(epochStart)&&!afterClock.hostEnd().isAfter(epochEnd));var nativeAudit=audit.get(request.getAttribute("ID"));require(nativeAudit!=null&&entity.equals(nativeAudit[2])&&"POST".equals(nativeAudit[6])&&"http://shibboleth.net/ns/profiles/saml2/sso/browser".equals(nativeAudit[7])&&within(Instant.parse(nativeAudit[8]),begin,end));
                if(disposition==MetadataRoleKeyNativeAdapter.Disposition.SIGNATURE_REJECTED){require(exchange.path("responseReference").isNull()&&"MessageAuthenticationError".equals(nativeAudit[3])&&nativeAudit[4].isEmpty()&&transport.path("nativeMessageSecurityError").asBoolean(false));var html=new String(original(folder,text(transport,"responseBodyFile")),StandardCharsets.UTF_8);require(hash(html.getBytes(StandardCharsets.UTF_8)).equals(text(transport,"responseBodySha256"))&&html.contains("Message Security Error")&&!html.matches("(?is).*<form\\b.*")&&!html.matches("(?is).*\\b(?:Authorization|Cookie|password|SAMLRequest|SAMLResponse)\\b.*"));}
                else require(nativeAudit[3].isEmpty()&&"Success".equals(nativeAudit[4])&&(disposition!=MetadataRoleKeyNativeAdapter.Disposition.NORMAL_SUCCESS||"true".equals(nativeAudit[5])));
            }
        };
    }
    static void validatePrepared(Element peer,String variant,String run,BiFunction<String,String,Optional<PlanCredentials>> keys)throws Exception {
        require(MetadataRoleKeyProbeTestCase.VARIANTS.contains(variant)&&MD.equals(peer.getNamespaceURI())&&"EntityDescriptor".equals(peer.getLocalName()));
        var sp=single(peer,MD,"SPSSODescriptor");var idp=single(peer,MD,"IDPSSODescriptor");boolean explicit=variant.contains("explicit"),flipped=variant.contains("idp-first");var operative=certificates(sp);var other=certificates(idp);validateKeyPurposes(operative,other,explicit);
        var first=keys.apply(run,"three-signing-keys-first").orElseThrow();var second=keys.apply(run,"three-signing-keys-second").orElseThrow();var third=keys.apply(run,"three-signing-keys").orElseThrow();
        require(new XmlSignatureVerifier().hasValidEnvelopedSignature(peer,first.certificate())&&operative.getFirst().fingerprint().equals(fingerprint(flipped?second.certificate():first.certificate()))&&other.getFirst().fingerprint().equals(fingerprint(flipped?first.certificate():second.certificate()))&&(explicit?operative.get(1).fingerprint().equals(fingerprint(third.certificate())):true));
    }
    private static boolean failsDecrypt(Element response,java.security.PrivateKey key){try{new SamlXmlDecrypter().decrypt(single(response,S,"EncryptedAssertion"),key);return false;}catch(RuntimeException unavailable){return true;}}
    private static JsonNode http(JsonNode exchange,Element request,byte[] raw,Instant start,Instant end,Instant queryAt){var rows=exchange.path("nativeHttp");require(rows.isArray()&&rows.size()==1);var h=rows.get(0);var began=Instant.parse(text(h,"startedAt"));var finished=Instant.parse(text(h,"completedAt"));require("POST".equals(text(h,"requestMethod"))&&request.getAttribute("Destination").equals(text(h,"requestUrl"))&&request.getAttribute("ID").equals(text(h,"requestId"))&&hashUnchecked(raw).equals(text(h,"requestSha256"))&&began.isAfter(queryAt)&&!began.isBefore(start)&&!finished.isBefore(began)&&!finished.isAfter(end));return h;}
    private static void validateKeyPurposes(List<RoleKey> sp,List<RoleKey> peer,boolean explicit){require(sp.size()==(explicit?2:1)&&peer.size()==(explicit?2:1));if(explicit){require("signing".equals(sp.get(0).use())&&"encryption".equals(sp.get(1).use())&&"signing".equals(peer.get(0).use())&&"encryption".equals(peer.get(1).use())&&peer.get(0).fingerprint().equals(peer.get(1).fingerprint())&&!sp.get(0).fingerprint().equals(sp.get(1).fingerprint())&&!peer.get(0).fingerprint().equals(sp.get(1).fingerprint()));}else require(sp.getFirst().use().isEmpty()&&peer.getFirst().use().isEmpty());require(!sp.getFirst().fingerprint().equals(peer.getFirst().fingerprint()));}
    private record RoleKey(String use,X509Certificate certificate,String fingerprint){}
    private static List<RoleKey> certificates(Element role)throws Exception{var result=new ArrayList<RoleKey>();for(var descriptor:MetadataAlgorithmEvidence.children(role,MD,"KeyDescriptor")){var certs=descriptor.getElementsByTagNameNS(DS,"X509Certificate");require(certs.getLength()==1);var c=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(certs.item(0).getTextContent())));result.add(new RoleKey(descriptor.getAttribute("use"),c,fingerprint(c)));}return result;}
    private static String fingerprint(X509Certificate certificate)throws Exception{return hash(certificate.getPublicKey().getEncoded());}
    private static void validateConfiguration(Path folder,String entity,String run,String source)throws Exception{for(var kind:List.of("providers","audit"))require(Arrays.equals(original(folder,"original-"+kind+".xml"),original(folder,"final-"+kind+".xml")));require(source.equals("/opt/reference-idp/metadata/role-keys-"+run+".xml"));var initial=SecureXml.parse(original(folder,"original-providers.xml")).getDocumentElement();var configured=SecureXml.parse(original(folder,"configured-providers.xml")).getDocumentElement();var providers=MetadataAlgorithmEvidence.children(configured,N,"MetadataProvider");require(!providers.isEmpty());var added=providers.getFirst();require(("RoleKeys"+run).equals(added.getAttribute("id"))&&"FilesystemMetadataProvider".equals(added.getAttributeNS(XSI,"type"))&&source.equals(added.getAttribute("metadataFile"))&&MetadataAlgorithmEvidence.children(added,N,"MetadataFilter").isEmpty());configured.removeChild(added);require(structure(initial).equals(structure(configured)));var inventory=json(original(folder,"other-provider-inventory.json"));require(inventory.isArray()&&!inventory.isEmpty()&&inventory.equals(json(original(folder,"other-provider-final-readback.json"))));var expected=new HashSet<String>();var all=initial.getElementsByTagNameNS(N,"MetadataProvider");for(int i=0;i<all.getLength();i++){var p=(Element)all.item(i);require(p.hasAttribute("metadataFile"));expected.add(p.getAttribute("metadataFile").replace("%{idp.home}","/opt/reference-idp"));}var seen=new HashSet<String>();for(var row:inventory){require(seen.add(text(row,"path"))&&hash(original(folder,text(row,"file"))).equals(text(row,"sha256")));var xml=SecureXml.parse(original(folder,text(row,"file"))).getDocumentElement();require(!entity.equals(xml.getAttribute("entityID")));var entities=xml.getElementsByTagNameNS(MD,"EntityDescriptor");for(int i=0;i<entities.getLength();i++)require(!entity.equals(((Element)entities.item(i)).getAttribute("entityID")));}require(seen.equals(expected));var audit=SecureXml.parse(original(folder,"configured-audit.xml")).getDocumentElement();var entries=audit.getElementsByTagNameNS("http://www.springframework.org/schema/beans","entry");int formats=0;for(int i=0;i<entries.getLength();i++){var e=(Element)entries.item(i);if("Shibboleth-Audit".equals(e.getAttribute("key"))){require("SAMLscope-signature-v1|%I|%SP|%e|%S|%XX|%b|%P|%T".equals(e.getAttribute("value")));formats++;}}require(formats==1);}
    private static void verifyOriginals(Path folder,JsonNode manifest)throws Exception{var originals=manifest.path("originals");require(originals.isObject()&&originals.size()>0);var names=new HashSet<String>();originals.fieldNames().forEachRemaining(names::add);try(var paths=Files.list(folder)){require(paths.filter(p->!p.getFileName().toString().equals("manifest.json")).map(p->p.getFileName().toString()).collect(java.util.stream.Collectors.toSet()).equals(names));}for(var it=originals.fields();it.hasNext();){var row=it.next();require(hash(original(folder,row.getKey())).equals(row.getValue().asText()));}}
    private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,String id){var e=entries.get(id);require(e!=null);return e;}
    private static String targetPost(Element target){var values=target.getElementsByTagNameNS(MD,"SingleSignOnService");for(int i=0;i<values.getLength();i++){var e=(Element)values.item(i);if(POST.equals(e.getAttribute("Binding")))return e.getAttribute("Location");}throw new IllegalArgumentException("POST missing");}
    private static String shape(Element request){var d=SecureXml.newDocument();var clone=(Element)d.importNode(request,true);d.appendChild(clone);clone.removeAttribute("ID");clone.removeAttribute("IssueInstant");for(var s:MetadataAlgorithmEvidence.children(clone,DS,"Signature"))clone.removeChild(s);return structure(clone);}
    static Element single(Element root,String ns,String local){var values=MetadataAlgorithmEvidence.children(root,ns,local);require(values.size()==1);return values.getFirst();}
    private static Map<String,String[]> audits(byte[] raw){var result=new HashMap<String,String[]>();for(var line:new String(raw,StandardCharsets.UTF_8).lines().filter(s->!s.isBlank()).toList()){var f=line.split("\\|",-1);require(f.length==9&&"SAMLscope-signature-v1".equals(f[0])&&result.put(f[1],f)==null);}return result;}
    static String structure(Element root){var attrs=new TreeMap<String,String>();for(int i=0;i<root.getAttributes().getLength();i++){var a=root.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put(String.valueOf(a.getNamespaceURI())+"|"+a.getLocalName(),a.getNodeValue());}var value=new StringBuilder(String.valueOf(root.getNamespaceURI())+"|"+root.getLocalName()+attrs);for(var n=root.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e)value.append(structure(e));else if(n.getNodeType()==org.w3c.dom.Node.TEXT_NODE&&!n.getTextContent().isBlank())value.append(DS.equals(root.getNamespaceURI())&&"X509Certificate".equals(root.getLocalName())?n.getTextContent().replaceAll("\\s",""):n.getTextContent().trim());return value.toString();}
    private record ClockSample(Instant nativeAt,Instant hostStart,Instant hostEnd){}
    private static ClockSample clock(Path folder,String file)throws Exception{var sample=json(original(folder,file));require("native-product-os-UTC".equals(text(sample,"clockDomain"))&&sample.path("command").isArray()&&sample.path("command").size()==3&&"date".equals(sample.path("command").get(0).asText())&&"-u".equals(sample.path("command").get(1).asText())&&"+%Y-%m-%dT%H:%M:%S.%NZ".equals(sample.path("command").get(2).asText()));var raw=original(folder,text(sample,"nativeClockFile"));require(hash(raw).equals(text(sample,"nativeClockSha256")));var nativeAt=Instant.parse(new String(raw,StandardCharsets.UTF_8).strip());require(nativeAt.equals(Instant.parse(text(sample,"nativeInstant"))));var start=Instant.parse(text(sample,"hostStartedAt"));var end=Instant.parse(text(sample,"hostCompletedAt"));require(!end.isBefore(start));return new ClockSample(nativeAt,start,end);}
    private static boolean within(Instant at,Instant start,Instant end){return !at.isBefore(start)&&!at.isAfter(end);}
    private static String runtime(Path folder,String name)throws Exception{var rows=json(original(folder,name));require(rows.isArray()&&rows.size()==1);var row=rows.get(0);require(row.path("State").path("Running").asBoolean(false)&&row.path("Config").path("Env").isMissingNode());return text(row,"Id")+"|"+text(row,"Image")+"|"+text(row.path("State"),"StartedAt");}
    static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
    static byte[] original(Path folder,String name)throws Exception{require(name.matches("[A-Za-z0-9_.-]+"));var p=folder.resolve(name);safeParents(folder);require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)<=8*1024*1024);return Files.readAllBytes(p);}
    private static void safeParents(Path p){for(;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));}
    static String text(JsonNode root,String name){var value=root.path(name);require(value.isTextual()&&!value.asText().isBlank());return value.asText();}
    static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
    static String hashUnchecked(byte[] raw){try{return hash(raw);}catch(Exception impossible){throw new IllegalStateException(impossible);}}
    static void require(boolean value){if(!value)throw new IllegalArgumentException("Native role/purpose key consumption unproven");}
}
