package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import java.util.zip.ZipInputStream;
import org.w3c.dom.*;

/** Narrow installed stock-browser factory proof, including actual native effective profile and signed semantic controls.
 * No arbitrary custom Java capability is inferred. Controls calibrate the observer and are never product observations. */
public final class ShibbolethSubjectConfirmationEvidence {
 public static final String SCHEMA="samlscope-shibboleth-subject-confirmation-v1";
 public static final String FR="IIP-SSO01-fr-idp-01",GD="IIP-SSO01-gd-idp-01";
 private static final String RUN="run_[0-9A-HJKMNP-TV-Z]{26}",TARGET="http://localhost:18280/idp/shibboleth",SUFFIX=".shibboleth-subject-confirmation";
 private static final String P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#",BEARER="urn:oasis:names:tc:SAML:2.0:cm:bearer",POST="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
 private static final String B="http://www.springframework.org/schema/beans",U="http://www.springframework.org/schema/util",PROP="http://www.springframework.org/schema/p",F="http://www.springframework.org/schema/webflow";
 private static final String IMAGE="sha256:3c1b1fa64c58258aefc9e38d4ae60e9f0340731318a472110ea56ce88c18a11a",PROFILE="http://shibboleth.net/ns/profiles/saml2/sso/browser";
 private static final Map<String,String> SOURCES=Map.ofEntries(Map.entry("idp-admin-impl.jar","0670f8210fa414610904c121ebf932952d634eaadf201fe302b8a7cbbd1e27a4"),
  Map.entry("idp-conf-impl.jar","428e389d88bb2abcad19d69bcf759af29f7ce6beb776ccfaa5a6ea76751682ba"),
  Map.entry("idp-profile-impl.jar","aaa769a9ccdfb1428173e3932d598ced0302908fab3b8bfe2100331678c9f405"),
  Map.entry("idp-saml-api.jar","2215e33871c40fd38ca7b83004eeabb89ba34a8c7211237d0ff5b6150d5096cc"),
  Map.entry("idp-saml-impl.jar","1a2a9f867d11c50eeaf2a6140bb5de88b0611d694ea6de2bbfe32f72a4a2998b"),
  Map.entry("opensaml-profile-impl.jar","ed65b8524022fd870b588fedb994a7c4b2f0e4fe63a5d62085ca7c419f6a751f"),
  Map.entry("opensaml-saml-api.jar","cce72578ec8df5dd18cb71c88bba89bd196c640281c199ce875e2aa44154f93f"),
  Map.entry("opensaml-saml-impl.jar","9f04221e172dc426f90fb3873d0148a0744edbf9e7a37de7ee0e6a34f7b74581"));
 private static final Map<String,String> CONFIGS=Map.ofEntries(Map.entry("attribute-filter.xml","9fbf53657357481a4415f34ce7d97f4339fdd27ab362281e1d0875cda512a849"),
  Map.entry("attribute-resolver.xml","a5a884b93b0486255151f56aca84c2c33a63bf3df5f707e993a1b8215f6854e9"),
  Map.entry("audit.xml","894db8675bec8034ef070245e18d968c510bdb01e876f49713c8ba370881c941"),
  Map.entry("authn-events.xml","e46df61db460448ee7ccf43398df6354f53ea8566b5caabaa19fa78381b0bc37"),
  Map.entry("c14n.xml","bbeb00dfe0372ce2d4db997f81f98cf7d51bc1fd46082f71c0492b7521fbfde3"),
  Map.entry("conditions-flow.xml","ec9156cc1da98e1b80b78c22cec1a130a609e4118761ad3832677e80d22353d8"),
  Map.entry("credentials.xml","3124af484cabff8882b412ee33902d2f51a8555000ce240c16d8e8fb5c80f951"),
  Map.entry("global.xml","ca08485a1b5ef8cf0ac1afb80ff066237759e4fb3d884d087f905d8ca0918bcc"),
  Map.entry("intercept-events.xml","6a8f113390eb26f63a493c29f132a1099f0b6ef19bfd713595b3ba641fca08a4"),
  Map.entry("relying-party.xml","64e2a04dfbf2ffa2a582b995bcbf121b634ab7c8766cb8f22d3397d541f31bd5"),
  Map.entry("saml-nameid.xml","ba5b2f3b05dc7cf6aa7b9c9de2d73d18aad75fe53a85adad946c20cb6621b358"),
  Map.entry("services.xml","0c5de788ebc611af60ebb3bf4071dcd23744f599d64d65bdb0744515d11a77c0"));
 private static final String CLASSPATH="1fcd492d07b1ca59600b763c0cddc3be85dc223841a2298bf3719274b66c4cb3",PRODUCER="66bb78f994dbc0f21bf2ad71c068400e34c0056850daee8d1bebd25283c71221";
 private final Path directory;private final TranscriptContentReader content;private final Function<String,String> profiles;
 private final BiFunction<String,String,Optional<PlanCredentials>> metadataKeys;
 public ShibbolethSubjectConfirmationEvidence(Path directory,TranscriptContentReader content,Function<String,String> profiles,BiFunction<String,String,Optional<PlanCredentials>> metadataKeys) {
  this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.profiles=Objects.requireNonNull(profiles);this.metadataKeys=Objects.requireNonNull(metadataKeys);
 }
 public boolean exists(String run){return run!=null&&run.matches(RUN)&&(Files.exists(directory.resolve(run+SUFFIX+".json"),LinkOption.NOFOLLOW_LINKS)||Files.exists(directory.resolve(run+SUFFIX),LinkOption.NOFOLLOW_LINKS));}
 public Optional<CaseOutcome> evaluate(CaseContext context,String id,byte[] targetRaw) {
  if(!Set.of(FR,GD).contains(id)||!exists(context.runId()))return Optional.empty();String stage="native-subject-confirmation-originals-unproven";
  try {
   require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete()&&"browser_sso_idp".equals(profiles.apply(context.runId())));safeParents(directory);
   var manifestRaw=original(directory,context.runId()+SUFFIX+".json");var m=json(manifestRaw);var folder=directory.resolve(context.runId()+SUFFIX);safeParents(folder);require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
   require(SCHEMA.equals(text(m,"schema"))&&context.runId().equals(text(m,"runId"))&&"native-subject-confirmation".equals(text(m,"campaignId"))&&TARGET.equals(text(m,"targetEntityId"))&&hash(targetRaw).equals(text(m,"targetMetadataSha256")));
   var files=m.path("files");require(files.isObject()&&files.size()>0);for(var i=files.fields();i.hasNext();){var f=i.next();require(hash(original(folder,f.getKey())).equals(f.getValue().asText()));}
   var created=json(checked(folder,files,"created.json")).path("run");require(context.runId().equals(text(created,"id")));String entity="http://localhost:18080/p/"+text(created,"planId");
   var target=SecureXml.parse(targetRaw).getDocumentElement();require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName())&&TARGET.equals(target.getAttribute("entityID")));var targetKeys=MetadataAlgorithmEvidence.signingKeys(target);require(!targetKeys.isEmpty());
   var entries=new HashMap<String,TranscriptEntry>();for(var e:context.transcript().list(context.runId())) {require(context.runId().equals(e.runId())&&e.id().matches("tx_[0-9A-HJKMNP-TV-Z]{26}")&&entries.put(e.id(),e)==null);if(e.decodedSamlRef()!=null)require(("transcripts/"+context.runId()+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())&&content.readDecodedSaml(e)!=null&&content.readDecodedSaml(e).length==e.decodedSamlBytes());}
   require(entries.size()==5);var fetch=entry(entries,m,"fetchReference","MetadataFetch",Direction.INBOUND);var prepared=entry(entries,m,"metadataReference","MetadataPrepared",Direction.OUTBOUND);
   require(fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&!prepared.timestamp().isBefore(fetch.timestamp()));var fixture=checked(folder,files,"control.fixture.xml");require(Arrays.equals(fixture,content.readDecodedSaml(prepared))&&hash(fixture).equals(prepared.samlSummary().get("metadataSha256")));
   var sp=SecureXml.parse(fixture).getDocumentElement();require(MD.equals(sp.getNamespaceURI())&&"EntityDescriptor".equals(sp.getLocalName())&&entity.equals(sp.getAttribute("entityID")));var peerKeys=MetadataAlgorithmEvidence.signingKeys(sp);require(!peerKeys.isEmpty()&&signed(sp,peerKeys));
   var nativeSp=SecureXml.parse(checked(folder,files,"native-effective-sp-metadata.xml")).getDocumentElement();require(entity.equals(nativeSp.getAttribute("entityID"))&&structure(one(sp,MD,"SPSSODescriptor")).equals(structure(one(nativeSp,MD,"SPSSODescriptor"))));
   var nativeRead=json(checked(folder,files,"native-effective-sp-metadata-read.json"));require(context.runId().equals(text(nativeRead,"runId"))&&entity.equals(text(nativeRead,"entityId"))&&hash(checked(folder,files,"native-effective-sp-metadata.xml")).equals(text(nativeRead,"sha256"))&&nativeRead.path("exitCode").asInt(-1)==0);
   stage="native-effective-bearer-factory-unproven";
   validateSelectedStockSsoConfiguration(folder,files);
   stage="native-correlated-ordinary-bearer-unproven";
   var request=entry(entries,m,"positiveRequestReference","AuthnRequest",Direction.OUTBOUND);var negative=entry(entries,m,"negativeRequestReference","AuthnRequest",Direction.OUTBOUND);var response=entry(entries,m,"positiveResponseReference","Response",Direction.INBOUND);
   var req=SecureXml.parse(content.readDecodedSaml(request)).getDocumentElement();var neg=SecureXml.parse(content.readDecodedSaml(negative)).getDocumentElement();require(P.equals(req.getNamespaceURI())&&"AuthnRequest".equals(req.getLocalName())&&entity.equals(issuer(req))&&POST.equals(req.getAttribute("ProtocolBinding"))&&signed(req,peerKeys)&&!MetadataProbeCorrelation.signatureControl(request)&&MetadataProbeCorrelation.signatureControl(negative)&&!signed(neg,peerKeys)&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(neg));
   require("POST".equals(request.method())&&"POST".equals(negative.method())&&"http://localhost:18280/idp/profile/SAML2/POST/SSO".equals(request.url())&&request.url().equals(negative.url())&&!request.timestamp().isBefore(prepared.timestamp())&&!response.timestamp().isBefore(request.timestamp()));
   String rid=req.getAttribute("ID"),recipient=req.getAttribute("AssertionConsumerServiceURL");require(!rid.isBlank()&&!recipient.isBlank()&&rid.equals(request.correlationId())&&rid.equals(response.correlationId()));
   var assertion=VerifiedResponseAssertion.read(SecureXml.parse(content.readDecodedSaml(response)).getDocumentElement(),TARGET,targetKeys,sp,metadataKeys.apply(context.runId(),"control"),rid,recipient);require(ordinaryBearer(assertion));
   var start=Instant.parse(text(json(checked(folder,files,"before-protocol-observed.json")),"recordedAt"));var end=Instant.parse(text(json(checked(folder,files,"after-protocol-observed.json")),"recordedAt"));require(!start.isAfter(negative.timestamp())&&!end.isBefore(response.timestamp()));
   for(var phase:List.of("before-protocol","after-protocol")){var obs=json(checked(folder,files,phase+"-native-effective-profile-observed.json"));require(entity.equals(text(obs,"requester"))&&PROFILE.equals(text(obs,"profile"))&&"native-dumpconfig-admin-profile".equals(text(obs,"source"))&&!obs.path("privateFieldsExported").asBoolean(true));var at=Instant.parse(text(obs,"recordedAt"));require(phase.equals("before-protocol")?!at.isAfter(negative.timestamp()):!at.isBefore(response.timestamp()));}
   validateHttp(folder,files,context.runId(),negative,content.readDecodedSaml(negative));for(var e:entries.values())require(!(e.direction()==Direction.INBOUND&&"Response".equals(e.samlSummary().get("type"))&&negative.correlationId().equals(e.correlationId())));
   stage="native-signed-attester-controls-unproven";require(PRODUCER.equals(hash(checked(folder,files,"ShibbolethSubjectConfirmationProducer.java"))));var producer=json(checked(folder,files,"producer.json"));require("samlscope-shibboleth-attester-calibration-v1".equals(text(producer,"schema"))&&request.id().equals(text(producer,"positiveRequestReference"))&&rid.equals(text(producer,"requestId"))&&recipient.equals(text(producer,"recipient"))&&entity.equals(text(producer,"spEntityId"))&&TARGET.equals(text(producer,"targetEntityId"))&&!producer.path("controlsAdopted").asBoolean(true)&&!producer.path("nativePrivateKeyExported").asBoolean(true)&&PRODUCER.equals(text(producer,"sourceSha256")));
   String structure=null;for(var kind:List.of("foreign-positive","foreign-missing-identifier","multiple-positive","multiple-packed-identifiers")){var raw=checked(folder,files,kind+".xml");require(hash(raw).equals(text(producer.path("files"),kind)));var controlled=controlAssertion(raw,targetKeys,entity,rid,recipient);var shape=withoutConfirmations(controlled);if(structure==null)structure=shape;else require(structure.equals(shape));var permitted=kind.startsWith("foreign")?List.of("urn:samlscope:attester-control:one"):List.of("urn:samlscope:attester-control:one","urn:samlscope:attester-control:two");require(identifiesSeparateAttesters(controlled,permitted)==kind.endsWith("positive"));}
   var refs=new ArrayList<EvidenceRef>();for(var e:List.of(fetch,prepared,negative,request,response))refs.add(new EvidenceRef("transcript",e.id()));refs.add(new EvidenceRef("native-shibboleth-subject-confirmation",context.runId()+SUFFIX+".json#"+hash(manifestRaw)));
   return Optional.of(new CaseOutcome(Outcome.SATISFIED_WITH_NOTE,null,"browser.subject-confirmation.native-no-opportunity","The selected stock Shibboleth browser bearer factory admits one subject attester; the approved alternate-attester observation is unavailable in this effective configuration.",refs,Map.of("product","shibboleth","evidence_adapter",SCHEMA,"run_id",context.runId(),"subject_confirmation_count",1,"attester_identifier_count",0,"no_observation_opportunity",true,"scope","this-run-selected-stock-native-browser-profile","custom_java_capability_asserted",false,"native_signed_semantic_controls",4,"case_id",id)));
  }catch(Exception unproven){if(Boolean.getBoolean("samlscope.shibSubjectConfirmation.debug"))unproven.printStackTrace();return Optional.of(CaseOutcome.notVerified(stage,"browser.subject-confirmation.native-unproven"));}
 }
 /** Shared original-backed selected stock profile closure; it makes no CaseOutcome. */
 static void validateSelectedStockSsoConfiguration(Path folder,JsonNode files)throws Exception {
   for(var pin:SOURCES.entrySet())require(pin.getValue().equals(hash(checked(folder,files,"native-"+pin.getKey()))));
   for(var pin:CONFIGS.entrySet())for(var phase:List.of("original","before-protocol","after-protocol","final"))require(pin.getValue().equals(hash(checked(folder,files,phase+"-"+pin.getKey()))));
   for(var phase:List.of("original","before-protocol","after-protocol","final"))require(CLASSPATH.equals(hash(checked(folder,files,phase+"-classpath-sha256.json")))&&json(checked(folder,files,phase+"-override-source-inventory.json")).isArray()&&json(checked(folder,files,phase+"-override-source-inventory.json")).isEmpty());
   require(runtime(json(checked(folder,files,"target-container-inspect-start.json"))).equals(runtime(json(checked(folder,files,"target-container-inspect-end.json")))));
   var provider=checked(folder,files,"original-providers.xml");require(Arrays.equals(provider,checked(folder,files,"final-providers.xml")));var restoration=json(checked(folder,files,"restoration.json"));require(restoration.path("restored").asBoolean(false)&&restoration.path("temporary_file_removed").asBoolean(false)&&hash(provider).equals(text(restoration,"original_sha256"))&&hash(provider).equals(text(restoration,"final_sha256")));
   // Known stock service/resource/bean bytes are pinned above. Inspect the selected native flow/action too.
   var stock=zip(checked(folder,files,"native-idp-conf-impl.jar"),"net/shibboleth/idp/flows/saml/saml2/sso-abstract-flow.xml");var flow=SecureXml.parse(stock).getDocumentElement();var actions=flow.getElementsByTagNameNS(F,"evaluate");int addCount=0;for(int i=0;i<actions.getLength();i++)if("AddSubjectConfirmationToSubjects".equals(((Element)actions.item(i)).getAttribute("expression")))addCount++;require(addCount==1);
   var beans=SecureXml.parse(zip(checked(folder,files,"native-idp-conf-impl.jar"),"net/shibboleth/idp/flows/saml/saml2/sso-abstract-beans.xml")).getDocumentElement();var action=byId(beans,B,"bean","AddSubjectConfirmationToSubjects");require("org.opensaml.saml.saml2.profile.impl.AddSubjectConfirmationToSubjects".equals(action.getAttribute("class"))&&BEARER.equals(action.getAttributeNS(PROP,"method")));
   var before=json(checked(folder,files,"before-protocol-native-effective-profile.json"));require(before.equals(json(checked(folder,files,"after-protocol-native-effective-profile.json"))));validateProfile(before);
   var XMLS=json(checked(folder,files,"before-protocol-xml-inventory.json"));require(XMLS.equals(json(checked(folder,files,"after-protocol-xml-inventory.json")))&&XMLS.isArray());for(var path:XMLS)if(path.asText().startsWith("/opt/reference-idp/flows/"))require(Set.of("/opt/reference-idp/flows/authn/conditions/conditions-flow.xml","/opt/reference-idp/flows/authn/conditions/account-locked/account-locked-flow.xml","/opt/reference-idp/flows/authn/conditions/expired-password/expired-password-flow.xml","/opt/reference-idp/flows/authn/conditions/expiring-password/expiring-password-flow.xml").contains(path.asText()));
 }
 static void validateProfile(JsonNode n){require(n.isObject()&&n.size()==2);var rp=n.path("RelyingPartyConfiguration");require(rp.size()==4&&!rp.path("detailedErrors").asBoolean(true)&&"shibboleth.DefaultRelyingParty".equals(text(rp,"id"))&&"shibboleth.DefaultSecurityConfiguration".equals(text(rp,"securityConfiguration"))&&TARGET.equals(text(rp,"issuer")));var p=n.path("ProfileConfiguration");require(p.size()==25&&PROFILE.equals(text(p,"id"))&&"net.shibboleth.idp.saml.authn.principal.impl.MapDrivenAuthnContextTranslationStrategy".equals(text(p,"authnContextTranslationStrategy"))&&"shibboleth.DefaultArtifactConfiguration".equals(text(p,"artfactConfiguration"))&&"PT5M".equals(text(p,"assertionLifetime"))&&p.path("disallowedFeatures").isInt()&&p.path("disallowedFeatures").asInt(-1)==0);for(String key:List.of("checkInResponseTo","proxiedAuthnInstant","encryptAssertions","resolveAttributes","includeConditionsNotBefore","checkAddress","signResponses"))require(p.path(key).isBoolean()&&p.path(key).asBoolean());for(String key:List.of("encryptionOptional","skipEndpointValidationWhenSigned","requireSignedRequests","encryptAttributes","encryptNameIDs","signAssertions","ignoreScoping","signRequests","requireSignedAssertions","suppressAuthenticatingAuthority","ignoreRequestSignatures","forceAuthn","randomizeFriendlyName"))require(p.path(key).isBoolean()&&!p.path(key).asBoolean());}
 private void validateHttp(Path folder,JsonNode files,String run,TranscriptEntry negative,byte[] request)throws Exception {var http=json(checked(folder,files,"native-http-observations.json"));require(run.equals(text(http,"runId"))&&"control".equals(text(http,"variant")));var matches=new ArrayList<JsonNode>();for(var row:http.path("records"))if(negative.correlationId().equals(row.path("requestId").asText()))matches.add(row);require(matches.size()==1);var row=matches.getFirst();require(hash(request).equals(text(row,"requestSha256"))&&negative.url().equals(text(row,"requestUrl"))&&negative.url().equals(text(row,"responseUrl"))&&row.path("responseStatus").asInt(-1)==400&&row.path("nativeMessageSecurityError").asBoolean(false)&&!row.path("samlResponseFormPresent").asBoolean(true));var raw=checked(folder,files,"native-rejection.html");require(hash(raw).equals(text(row,"responseBodySha256"))&&new String(raw,StandardCharsets.UTF_8).contains("Message Security Error"));require(!Instant.parse(text(row,"startedAt")).isBefore(negative.timestamp())&&!Instant.parse(text(row,"completedAt")).isBefore(Instant.parse(text(row,"startedAt"))));}
 static boolean ordinaryBearer(Element a){var subject=one(a,S,"Subject");var sc=children(subject,S,"SubjectConfirmation");return sc.size()==1&&BEARER.equals(sc.getFirst().getAttribute("Method"))&&identifiers(sc.getFirst()).isEmpty();}
 static boolean identifiesSeparateAttesters(Element assertion,List<String> permitted){var confirmations=children(one(assertion,S,"Subject"),S,"SubjectConfirmation");if(confirmations.size()!=permitted.size())return false;var actual=new HashSet<String>();for(var sc:confirmations){var ids=identifiers(sc);if(!BEARER.equals(sc.getAttribute("Method"))||ids.size()!=1||ids.getFirst().getTextContent().isBlank()||!actual.add(ids.getFirst().getTextContent()))return false;}return actual.equals(new HashSet<>(permitted));}
 private static List<Element> identifiers(Element sc){var values=new ArrayList<Element>();for(var name:List.of("BaseID","NameID","EncryptedID"))values.addAll(children(sc,S,name));return values;}
 private static Element controlAssertion(byte[] raw,List<X509Certificate> keys,String entity,String request,String recipient){var root=SecureXml.parse(raw).getDocumentElement();require(P.equals(root.getNamespaceURI())&&"Response".equals(root.getLocalName())&&signed(root,keys)&&TARGET.equals(issuer(root))&&request.equals(root.getAttribute("InResponseTo"))&&recipient.equals(root.getAttribute("Destination"))&&"urn:oasis:names:tc:SAML:2.0:status:Success".equals(one(one(root,P,"Status"),P,"StatusCode").getAttribute("Value")));var a=one(root,S,"Assertion");require(children(root,S,"EncryptedAssertion").isEmpty()&&signed(a,keys)&&TARGET.equals(issuer(a)));var audiences=a.getElementsByTagNameNS(S,"Audience");require(audiences.getLength()==1&&entity.equals(audiences.item(0).getTextContent()));for(var sc:children(one(a,S,"Subject"),S,"SubjectConfirmation")){var data=one(sc,S,"SubjectConfirmationData");require(request.equals(data.getAttribute("InResponseTo"))&&recipient.equals(data.getAttribute("Recipient")));}return a;}
 private static String withoutConfirmations(Element e){var clone=(Element)e.cloneNode(true);var nodes=new ArrayList<Node>();for(var kind:List.of("Signature","SubjectConfirmation")){var found=clone.getElementsByTagNameNS(kind.equals("Signature")?DS:S,kind);for(int i=0;i<found.getLength();i++)nodes.add(found.item(i));}for(var node:nodes)node.getParentNode().removeChild(node);return structure(clone);}
 private static String structure(Element e){var attrs=new TreeMap<String,String>();for(int i=0;i<e.getAttributes().getLength();i++){var a=e.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put("{"+a.getNamespaceURI()+"}"+a.getLocalName(),a.getNodeValue());}var parts=new ArrayList<String>();for(Node n=e.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element child)parts.add(structure(child));else if(n.getNodeType()==Node.TEXT_NODE&&!n.getNodeValue().isBlank())parts.add(n.getNodeValue());return "{"+e.getNamespaceURI()+"}"+e.getLocalName()+attrs+parts;}
 private static boolean signed(Element e,List<X509Certificate> keys){var v=new XmlSignatureVerifier();return v.hasValidEnvelopedReferenceDigests(e)&&keys.stream().anyMatch(k->v.hasValidEnvelopedSignature(e,k));}
 private static String issuer(Element e){return one(e,S,"Issuer").getTextContent();}
 private static Element one(Element e,String ns,String local){var values=children(e,ns,local);require(values.size()==1);return values.getFirst();}
 private static Element byId(Element e,String ns,String local,String id){var values=children(e,ns,local).stream().filter(n->id.equals(n.getAttribute("id"))).toList();require(values.size()==1);return values.getFirst();}
 private static byte[] zip(byte[] jar,String path)throws Exception {try(var z=new ZipInputStream(new java.io.ByteArrayInputStream(jar))){for(var e=z.getNextEntry();e!=null;e=z.getNextEntry())if(path.equals(e.getName()))return z.readAllBytes();}throw new IllegalArgumentException("Native source absent");}
 private static String runtime(JsonNode rows){require(rows.isArray()&&rows.size()==1);var r=rows.get(0);require(IMAGE.equals(text(r,"Image"))&&r.path("State").path("Running").asBoolean(false)&&r.path("Mounts").isArray()&&r.path("Mounts").isEmpty());return text(r,"Id")+"|"+text(r.path("State"),"StartedAt")+"|"+text(r,"Image");}
 private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,JsonNode m,String field,String kind,Direction d){var e=entries.get(text(m,field));require(e!=null&&d==e.direction()&&kind.equals(e.samlSummary().get("type"))&&("Response".equals(kind)||"control".equals(e.samlSummary().get("variant"))));return e;}
 private static byte[] checked(Path folder,JsonNode files,String name)throws Exception{var b=original(folder,name);require(hash(b).equals(files.path(name).asText()));return b;}
 private static byte[] original(Path folder,String name)throws Exception {require(name.matches("[A-Za-z0-9._-]+")&&!Set.of(".","..").contains(name));safeParents(folder);var p=folder.resolve(name);require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)>0&&Files.size(p)<32*1024*1024);return Files.readAllBytes(p);}
 private static void safeParents(Path p){for(;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));}
 private static JsonNode json(byte[] b)throws Exception{return new JsonCodec().mapper().readTree(b);}
 private static String text(JsonNode n,String key){var v=n.path(key);require(v.isTextual()&&!v.asText().isBlank());return v.asText();}
 private static String hash(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
 private static void require(boolean ok){if(!ok)throw new IllegalArgumentException("Native subject confirmation proof incomplete");}
}
