package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.normal.SamlSchemaValidation;
import com.samlscope.saml.normal.SamlSchemaValidation.SchemaKind;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.store.JsonCodec;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import java.util.zip.*;
import org.w3c.dom.*;

/** Reads accepted native metadata and actual processing; errors and retained values alone never
 * prove conformance. Historical rollover remains a distinct, original same-Run native epoch. */
public final class ShibbolethMetadataApplicationEvidence {
 public static final String SCHEMA="samlscope-shibboleth-metadata-application-v1",ADAPTER="shibboleth-native-accepted-metadata-application-v1",CAMPAIGN="native-metadata-supersession";
 static final String MD="urn:oasis:names:tc:SAML:2.0:metadata",P="urn:oasis:names:tc:SAML:2.0:protocol",A="urn:oasis:names:tc:SAML:2.0:assertion",DS="http://www.w3.org/2000/09/xmldsig#",SOAP="http://schemas.xmlsoap.org/soap/envelope/",ECP="urn:oasis:names:tc:SAML:2.0:profiles:SSO:ecp",POST="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",REDIRECT="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",PAOS="urn:oasis:names:tc:SAML:2.0:bindings:PAOS",SOAP_BINDING="urn:oasis:names:tc:SAML:2.0:bindings:SOAP",BROWSER="http://shibboleth.net/ns/profiles/saml2/sso/browser",ECP_PROFILE="http://shibboleth.net/ns/profiles/saml2/sso/ecp",LOGOUT="http://shibboleth.net/ns/profiles/saml2/logout";
 static final List<String> ECP_FIXTURES=List.of("fixture-ecp-metadata-rollover-first-paos","fixture-ecp-metadata-rollover-second-paos","fixture-ecp-metadata-rollover-unadvertised-paos","fixture-ecp-metadata-b-paos","fixture-ecp-metadata-b-invalid-signature-paos","fixture-ecp-metadata-b-old-key-paos");
 static final Map<String,String> JARS=Map.of("idp-conf-impl","428e389d88bb2abcad19d69bcf759af29f7ce6beb776ccfaa5a6ea76751682ba","idp-saml-impl","1a2a9f867d11c50eeaf2a6140bb5de88b0611d694ea6de2bbfe32f72a4a2998b","opensaml-saml-impl","9f04221e172dc426f90fb3873d0148a0744edbf9e7a37de7ee0e6a34f7b74581","opensaml-xmlsec-impl","cc67fc1bd9cb435cdbe7483ef04513c83cc9619a3015c04ad41bb6cc0eb6e68e");
 final Path directory;final TranscriptContentReader content;final Function<String,byte[]> targetMetadata;final BiFunction<String,String,Optional<PlanCredentials>> pollingKeys;final SamlDecryptionKeyProvider primaryKeys;final boolean offlineCalibrationAllowed;
 public ShibbolethMetadataApplicationEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> targetMetadata,BiFunction<String,String,Optional<PlanCredentials>> pollingKeys,SamlDecryptionKeyProvider primaryKeys){this(directory,content,targetMetadata,pollingKeys,primaryKeys,false);}
 ShibbolethMetadataApplicationEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> targetMetadata,BiFunction<String,String,Optional<PlanCredentials>> pollingKeys,SamlDecryptionKeyProvider primaryKeys,boolean offlineCalibrationAllowed){this.offlineCalibrationAllowed=offlineCalibrationAllowed;this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.targetMetadata=Objects.requireNonNull(targetMetadata);this.pollingKeys=Objects.requireNonNull(pollingKeys);this.primaryKeys=Objects.requireNonNull(primaryKeys);}
 public boolean exists(String run){return validRun(run)&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
 public CaseOutcome evaluate(String id,CaseContext context){String stage="receipt-unavailable";try{
  require(MetadataSupersessionProbeTestCase.supports(id)&&context.transcriptComplete());Frame f=new Frame(id,context);
  stage="original-history-unproven";f.load();stage="accepted-native-epochs-unproven";f.epochs();
  stage="restoration-unproven";f.restore("");f.restore("prior-rollover/");stage="operative-source-unproven";f.source();
  stage="normal-controls-unproven";f.baseline();f.phases();stage="simultaneous-rollover-unproven";f.ecp();
  stage="browser-and-slo-controls-unproven";f.browser();stage="full-application-scope-unproven";f.scope();
  require(Arrays.equals(f.manifestRaw,read(f.folder,"manifest.json",524288)));
  String reason=MetadataSupersessionProbeTestCase.APPLICATION.equals(id)?"metadata.application.accepted-native-application-observed":"metadata.supersession.accepted-native-replacement-observed";
  return f.outcome(f.violation==null?Outcome.SATISFIED:Outcome.VIOLATED,f.violation==null?reason:f.violation);
 }catch(Unproven e){return pending(stage,e.issue);}catch(Exception e){return pending(stage,"original-unreadable");}}
 static CaseOutcome pending(String stage,String issue){return new CaseOutcome(Outcome.NOT_VERIFIED,"native_metadata_application_originals_unproven","metadata.application.full-native-proof-unproven","metadata.application.full-native-proof-unproven",List.of(),Map.of("evidence_issue",stage,"original_issue",issue));}
 final class Frame {
  final CaseContext context;final String id,run;final Path folder;final Map<String,TranscriptEntry> entries=new LinkedHashMap<>();final Map<String,Epoch> epochs=new LinkedHashMap<>();final LinkedHashSet<EvidenceRef> refs=new LinkedHashSet<>();final Map<String,JsonNode> probes=new LinkedHashMap<>();final Map<String,Boolean> accepted=new LinkedHashMap<>();
  JsonNode m,projection;byte[] manifestRaw,targetRaw;Element target,oldMetadata,newMetadata,rolloverMetadata,normalPrincipal;List<X509Certificate> targetKeys;String plan,entity,targetEntity;String[] audits;boolean equalRoles=true;String violation=null;
  Frame(String id,CaseContext context){this.id=id;this.context=context;run=context.runId();require(validRun(run));folder=directory.resolve(run);}
  byte[] file(String name)throws Exception{byte[] raw=read(folder,name,33554432);require(hash(raw).equals(text(m.path("files"),name)));return raw;}
  JsonNode node(String name)throws Exception{return json(file(name));}
  TranscriptEntry entry(String id){var e=entries.get(id);require(e!=null);return e;}
  byte[] decoded(TranscriptEntry e){require(e.decodedSamlRef()!=null);byte[] raw=content.readDecodedSaml(e);require(raw!=null&&raw.length>0&&raw.length==e.decodedSamlBytes());refs.add(new EvidenceRef("transcript",e.id()));return raw;}
  void load()throws Exception{
   manifestRaw=read(folder,"manifest.json",524288);m=json(manifestRaw);require(SCHEMA.equals(text(m,"schema"))&&ADAPTER.equals(text(m,"adapter"))&&CAMPAIGN.equals(text(m,"campaignId"))&&run.equals(text(m,"runId")));
   require(!m.has("calibration")||offlineCalibrationAllowed);
   plan=text(m,"planId");require(plan.matches("plan_[0-9A-HJKMNP-TV-Z]{26}"));entity=text(m,"entityId");require(entity.equals("http://localhost:18080/p/"+plan));
   targetRaw=targetMetadata.apply(run);require(hash(targetRaw).equals(text(m,"targetMetadataSha256")));target=xml(targetRaw);targetEntity=target.getAttribute("entityID");require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName())&&!targetEntity.isBlank());targetKeys=MetadataAlgorithmEvidence.signingKeys(target);require(!targetKeys.isEmpty());
   require(text(m,"sourceUrl").equals("http://samlscope-reference-suite:8080/p/"+plan+"/metadata/live?run="+run)&&text(m,"backingFile").equals("/opt/reference-idp/metadata/application-"+run+".xml"));
   for(var e:context.transcript().list(run))require(run.equals(e.runId())&&entries.put(e.id(),e)==null);require(!entries.isEmpty());for(var e:entries.values())if(e.decodedSamlRef()!=null)require(e.decodedSamlRef().equals("transcripts/"+run+"/"+e.id()+".saml.xml"));
   require(m.path("files").isObject()&&!m.path("files").isEmpty());var fs=m.path("files").fields();while(fs.hasNext()){var x=fs.next();require(x.getValue().isTextual()&&hash(read(folder,x.getKey(),33554432)).equals(x.getValue().asText()));}
   audits=new String(file("native-application-audit.log"),StandardCharsets.UTF_8).split("\\R");require(m.path("probes").isArray()&&m.path("probes").size()==18);for(var p:m.path("probes"))require(probes.put(text(p,"fixture"),p)==null);
   var expected=new HashSet<>(ECP_FIXTURES);expected.addAll(MetadataSupersessionProbeTestCase.FIXTURES);expected.addAll(MetadataSupersessionProbeTestCase.SLO_FIXTURES);require(probes.keySet().equals(expected));
   projection=node("native-paos-cause-projection.json");require(run.equals(text(projection,"runId"))&&entity.equals(text(projection,"entityId"))&&!projection.path("privateLogPersisted").asBoolean(true));
  }
  void epochs()throws Exception{
   require(m.path("epochReferences").isArray()&&m.path("epochReferences").size()==36);
   for(var ref:m.path("epochReferences")){
    String label=text(ref,"label"),variant=text(ref,"variant"),root=ref.path("nativeRoot").asText("native");require(Set.of("native","prior-rollover/native").contains(root));var tx=entry(text(ref,"reference"));require(tx.direction()==Direction.INBOUND&&tx.status()!=null&&tx.status()==204);byte[] raw=decoded(tx);require(hash(raw).equals(text(ref,"sha256")));JsonNode n=json(raw);
    require("samlscope-shibboleth-metadata-application-original-v1".equals(text(n,"schema"))&&"native-accepted-metadata-epoch".equals(text(n,"kind"))&&label.equals(text(n,"label"))&&variant.equals(text(n,"variant"))&&run.equals(text(n,"runId"))&&CAMPAIGN.equals(text(n,"campaignId"))&&text(m,"targetMetadataSha256").equals(text(n,"targetMetadataSha256"))&&text(m,"sourceUrl").equals(text(n,"sourceUrl")));
    require(Arrays.equals(raw,file(root.replace("native","native-originals")+"/"+label+".json")));Instant start=at(n,"startedAt"),end=at(n,"finishedAt");require(!at(n,"recordedAt").isBefore(start)&&!end.isBefore(at(n,"recordedAt"))&&!tx.timestamp().isBefore(end));ClockRead bc=clock(node(root+"/"+text(n,"clockBeforeFile"))),ac=clock(node(root+"/"+text(n,"clockAfterFile")));require(!bc.start.isBefore(start)&&!end.isBefore(ac.end)&&!ac.start.isBefore(bc.end));
    byte[] cache=file(root+"/"+text(n,"cacheFile"));require(hash(cache).equals(text(n,"cacheSha256")));var prepared=entry(text(n,"preparedReference"));var fetch=entry(text(n,"fetchReference"));
    require("MetadataPrepared".equals(prepared.samlSummary().get("type"))&&variant.equals(prepared.samlSummary().get("variant"))&&"live".equals(prepared.samlSummary().get("feed"))&&fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&Arrays.equals(cache,decoded(prepared))&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&fetch.url().equals(text(m,"sourceUrl"))&&nativeFetch(fetch)&&!prepared.timestamp().isBefore(fetch.timestamp())&&!end.isBefore(prepared.timestamp()));
    if(n.has("preparedSelection"))latest(n.path("preparedSelection"),prepared,variant,cache,start,end);
    Element metadata=xml(cache);metadata(metadata,variant);byte[] query=file(root+"/"+text(n,"queryFile"));require(hash(query).equals(text(n,"querySha256")));Element effective=xml(query);require(entity.equals(effective.getAttribute("entityID"))&&children(effective,MD,"SPSSODescriptor").size()==1);equalRoles&=semantic(role(metadata)).equals(semantic(role(effective)));
    require(strings(n.path("queryCommand")).equals(List.of("/opt/reference-idp/bin/mdquery.sh","-u","http://localhost:8080/idp","-e",entity))&&n.path("runtime").path("running").asBoolean(false));
    for(String kind:List.of("providers","audit","public-metadata"))require(text(n.path("configurationSha256"),kind).equals(hash(file("configured-"+kind+".xml"))));JsonNode browser=node(root+"/"+text(n.path("profiles"),"browser")),ecp=node(root+"/"+text(n.path("profiles"),"ecp"));profile(browser,BROWSER);profile(ecp,ECP_PROFILE);
    require(epochs.put(label,new Epoch(n,tx,root,metadata,effective,start,end,bc,ac))==null);
   }
   oldMetadata=epoch("control-before").metadata;newMetadata=epoch("no-valid-until-before").metadata;rolloverMetadata=epoch("multiple-signing-keys-first-before").metadata;
   require(disjoint(certs(oldMetadata,"signing"),certs(newMetadata,"signing"))&&disjoint(certs(rolloverMetadata,"signing"),certs(newMetadata,"signing"))&&certs(rolloverMetadata,"signing").size()==2&&!endpoint(oldMetadata,"AssertionConsumerService",POST,0).equals(endpoint(newMetadata,"AssertionConsumerService",POST,0)));
   require(epoch("control-after").end.isBefore(epoch("no-valid-until-before").start));for(var e:epochs.values())if(!e.root.startsWith("prior-rollover"))require(sameRuntime(e,epoch("no-valid-until-before")));
  }
  void latest(JsonNode s,TranscriptEntry chosen,String variant,byte[] cache,Instant start,Instant end){Instant lower=numberInstant(s.path("lowerHostEpoch")),upper=numberInstant(s.path("upperHostEpoch"));require(!upper.isBefore(start)&&!end.isBefore(upper)&&lower.isBefore(upper));var matching=new ArrayList<TranscriptEntry>();
   for(var e:entries.values())if("MetadataPrepared".equals(e.samlSummary().get("type"))&&variant.equals(e.samlSummary().get("variant"))&&"live".equals(e.samlSummary().get("feed"))&&!e.timestamp().isBefore(lower)&&!e.timestamp().isAfter(upper)){var fetch=entries.get(e.samlSummary().get("fetchTranscriptId"));if(fetch!=null&&nativeFetch(fetch)&&text(m,"sourceUrl").equals(fetch.url())&&Arrays.equals(cache,content.readDecodedSaml(e)))matching.add(e);}
   require(!matching.isEmpty());Instant latest=matching.stream().map(TranscriptEntry::timestamp).max(Instant::compareTo).orElseThrow();require(matching.stream().filter(e->e.timestamp().equals(latest)).count()==1&&chosen.timestamp().equals(latest));require(strings(s.path("candidatePreparedReferences")).equals(matching.stream().map(TranscriptEntry::id).toList())&&strings(s.path("candidateFetchReferences")).equals(matching.stream().map(e->(String)e.samlSummary().get("fetchTranscriptId")).toList()));
  }
  void metadata(Element md,String variant)throws Exception{require(MD.equals(md.getNamespaceURI())&&"EntityDescriptor".equals(md.getLocalName())&&entity.equals(md.getAttribute("entityID"))&&SamlSchemaValidation.isValid(md,SchemaKind.METADATA));var sig=one(children(md,DS,"Signature"));var cert=one(children(one(children(one(children(sig,DS,"KeyInfo")),DS,"X509Data")),DS,"X509Certificate"));require(new XmlSignatureVerifier().hasValidEnvelopedSignature(md,certificate(cert)));var role=role(md);
   require("true".equals(role.getAttribute("AuthnRequestsSigned"))&&P.equals(role.getAttribute("protocolSupportEnumeration"))&&children(role,MD,"AssertionConsumerService").size()==4&&children(role,MD,"SingleLogoutService").size()==3);endpoint(md,"AssertionConsumerService",POST,0);endpoint(md,"AssertionConsumerService",POST,1);endpoint(md,"AssertionConsumerService",PAOS,2);endpoint(md,"AssertionConsumerService",REDIRECT,3);for(String binding:List.of(POST,REDIRECT,SOAP_BINDING))endpoint(md,"SingleLogoutService",binding,-1);require(!certs(md,"encryption").isEmpty());var key=pollingKeys.apply(run,variant).orElseThrow();require(certs(md,"signing").stream().anyMatch(c->sameKey(c,key.certificate())));
  }
  void restore(String prefix)throws Exception{JsonNode r=node(prefix+"restoration.json");require(r.path("restored").asBoolean(false)&&r.path("backingFileRemoved").asBoolean(false)&&r.path("failures").isArray()&&r.path("failures").isEmpty());for(String kind:List.of("providers","audit","public-metadata")){byte[] before=file(prefix+"original-"+kind+".xml"),after=file(prefix+"final-"+kind+".xml");require(Arrays.equals(before,after)&&hash(before).equals(text(r.path("original"),kind))&&hash(after).equals(text(r.path("final"),kind)));}
   JsonNode inventory=node(prefix+"existing-provider-inventory.json");require(inventory.isArray()&&inventory.size()==r.path("existingSources").size());int index=0;for(var src:inventory){var end=r.path("existingSources").get(index);require(text(src,"path").equals(text(end,"path"))&&text(src,"sha256").equals(text(end,"sha256"))&&hash(file(prefix+text(src,"file"))).equals(text(src,"sha256")));index++;}
   JsonNode operations=node(prefix+"operations.json"),counts=node(prefix+"operation-counts.json");require(operations.isArray()&&counts.path("personOperations").asInt(-1)==0&&!counts.path("allCredentialValuesPersisted").asBoolean(true));int writes=0,restores=0,restarts=0,reloads=0;
   for(var op:operations){String kind=text(op,"operation");Instant at=at(op,"recordedAt");if(kind.equals("product-config-write")){writes++;if(text(op,"label").startsWith("restore-"))restores++;require(op.path("readBack").asBoolean(false));}else if(kind.equals("product-restart")){restarts++;require(op.path("completed").asBoolean(false));}else if(kind.equals("native-provider-reload"))reloads++;else throw new Unproven("unknown-native-operation");if(prefix.isEmpty())require(at.isBefore(epoch("control-before").start)||at.isAfter(epoch("browser-matrix-after").end));require(!at(r,"recordedAt").isBefore(at));}
   require(writes==counts.path("productConfigurationWrites").asInt(-1)&&restores==counts.path("restorationWrites").asInt(-1)&&restarts==counts.path("productRestarts").asInt(-1)&&reloads==counts.path("nativeProviderReloads").asInt(-1));
  }
  void source()throws Exception{for(var jar:JARS.entrySet())require(hash(file("native/native-"+jar.getKey()+".jar")).equals(jar.getValue())&&hash(file("prior-rollover/native/native-"+jar.getKey()+".jar")).equals(jar.getValue()));trust(epoch("control-before"));trust(epoch("browser-matrix-after"));
   for(String suffix:List.of("classpath-sha256.json","selected-properties.json","properties-sha256.json","xml-sha256.json","override-source-inventory.json","process-overrides.json","global.xml","services.xml","relying-party.xml"))require(Arrays.equals(file("native/trust-control-before-"+suffix),file("native/trust-browser-matrix-after-"+suffix)));
   Element providers=xml(file("configured-providers.xml"));var list=providers.getElementsByTagNameNS("urn:mace:shibboleth:2.0:metadata","MetadataProvider");int matches=0;for(int i=0;i<list.getLength();i++){Element p=(Element)list.item(i);if(("Application"+run).equals(p.getAttribute("id"))){matches++;require(text(m,"sourceUrl").equals(p.getAttribute("metadataURL"))&&text(m,"backingFile").equals(p.getAttribute("backingFile"))&&p.getAttributeNS("http://www.w3.org/2001/XMLSchema-instance","type").endsWith("FileBackedHTTPMetadataProvider"));}}require(matches==1);
   ShibbolethMetadataApplicationSource.validate(file("native/native-idp-conf-impl.jar"),file("native/native-idp-saml-impl.jar"),file("native/native-opensaml-saml-impl.jar"),file("native/native-opensaml-xmlsec-impl.jar"));
  }
  void trust(Epoch e)throws Exception{require(e.n.path("fullTrustScope").asBoolean(false));String pre=e.root+"/trust-"+text(e.n,"label")+"-";JsonNode observed=node(pre+"observed.json");require(entity.equals(text(observed,"entityId"))&&!observed.path("privateFieldsExported").asBoolean(true)&&!at(observed,"recordedAt").isBefore(e.start)&&!e.end.isBefore(at(observed,"recordedAt")));for(var jar:JARS.entrySet())require(jar.getValue().equals(text(observed.path("nativeJars"),jar.getKey())));
   ShibbolethSelfContainedTrustEvidenceFile.validateSelectedProperties(node(pre+"selected-properties.json"));require(node(pre+"override-source-inventory.json").isArray()&&node(pre+"override-source-inventory.json").isEmpty());JsonNode flags=node(pre+"process-overrides.json");require(flags.path("nativeJavaProcessObserved").asBoolean(false)&&!flags.path("customAgentPresent").asBoolean(true)&&!flags.path("trustOverridePresent").asBoolean(true)&&!flags.path("privateFieldsExported").asBoolean(true));
   JsonNode cp=node(pre+"classpath-sha256.json");for(var jar:JARS.entrySet())require(jar.getValue().equals(text(cp,"/usr/local/tomcat/webapps/idp/WEB-INF/lib/"+jar.getKey()+"-"+"5.2.3"+".jar")));
   for(var pair:Map.of("global","ca08485a1b5ef8cf0ac1afb80ff066237759e4fb3d884d087f905d8ca0918bcc","services","0c5de788ebc611af60ebb3bf4071dcd23744f599d64d65bdb0744515d11a77c0","relying-party","64e2a04dfbf2ffa2a582b995bcbf121b634ab7c8766cb8f22d3397d541f31bd5").entrySet())require(hash(file(pre+pair.getKey()+".xml")).equals(pair.getValue()));
  }
  void baseline()throws Exception{JsonNode b=node("baseline.json");var ids=strings(b.path("references"));require(ids.size()==2);var req=entry(ids.getFirst());var rsp=entry(ids.getLast());Element request=xml(decoded(req));require(req.direction()==Direction.OUTBOUND&&rsp.direction()==Direction.INBOUND&&req.timestamp().isBefore(rsp.timestamp()));byte[] bytes=file("native/baseline-cached-metadata.xml");require(hash(bytes).equals(text(b,"metadataSha256")));Element metadata=xml(bytes);var key=new PlanCredentials(primaryKeys.keyFor(run).orElseThrow(),certs(metadata,"encryption").getFirst());require(entity.equals(metadata.getAttribute("entityID"))&&certs(metadata,"signing").stream().anyMatch(c->sameKey(c,key.certificate()))&&"GET".equals(req.method())&&new RedirectSignatureVerifier().isValidForMessage(req.rawQuery(),key.certificate(),decoded(req)));normalPrincipal=normal(request,xml(decoded(rsp)),rsp,metadata,Optional.of(key),endpoint(metadata,"AssertionConsumerService",POST,0));require(audit(request.getAttribute("ID")).status.equals("Success"));}
  void phases()throws Exception{require(m.path("phases").isArray()&&m.path("phases").size()==3);var seen=new HashSet<String>();for(var phase:m.path("phases")){String variant=text(phase,"variant");require(Set.of("control","multiple-signing-keys-first","no-valid-until").contains(variant)&&seen.add(variant));Epoch before=refEpoch(phase.path("beforeEpoch")),after=refEpoch(phase.path("afterEpoch"));require(sameRuntime(before,after)&&before.end.isBefore(after.start));String pre=phase.path("nativeRoot").asText("native").startsWith("prior-rollover")?"prior-rollover/":"";JsonNode flow=node(pre+text(phase,"flowFile"));require(run.equals(text(flow,"run"))&&variant.equals(text(flow,"variant")));var ids=strings(flow.path("positive_exchange").path("transcript_ids"));require(ids.size()==2);var req=entry(ids.getFirst());var rsp=entry(ids.getLast());Element request=xml(decoded(req));window(before,after,req,rsp);require(valid(request,certs(before.metadata,"signing"))&&entity.equals(issuer(request))&&endpoint(before.metadata,"AssertionConsumerService",POST,0).equals(request.getAttribute("AssertionConsumerServiceURL")));normal(request,xml(decoded(rsp)),rsp,before.metadata,pollingKeys.apply(run,variant),endpoint(before.metadata,"AssertionConsumerService",POST,0));Audit audit=audit(request.getAttribute("ID"));require(audit.status.equals("Success")&&audit.error.isEmpty()&&audit.inBinding.equals("POST")&&audit.outBinding.equals("POST")&&audit.profile.equals(BROWSER));nativeTime(audit,before,after);
    if(variant.equals("no-valid-until")){var badIds=strings(flow.path("negative_control").path("exchange").path("transcript_ids"));require(badIds.size()==1);var bad=entry(badIds.getFirst());require(!valid(xml(decoded(bad)),certs(before.metadata,"signing")));rejection(bad,before,after,"MessageAuthenticationError",pre);}
   }}
  void ecp()throws Exception{for(String fixture:ECP_FIXTURES){JsonNode p=probes.get(fixture);Epoch before=refEpoch(p.path("beforeEpoch")),after=refEpoch(p.path("afterEpoch"));var req=entry(text(p,"requestReference"));var ids=strings(p.path("responseReferences"));require(ids.size()==1);var rsp=entry(ids.getFirst());window(before,after,req,rsp);require(req.direction()==Direction.OUTBOUND&&rsp.direction()==Direction.INBOUND&&"POST".equals(req.method())&&"POST".equals(rsp.method())&&"SENT".equals(text(p.path("collectionResult"),"dispatchState"))&&"SENT".equals(text(p.path("collectionResult"),"outboxStatus"))&&p.path("collectionResult").path("incidents").isEmpty());Element request=soap(xml(decoded(req)),"AuthnRequest"),envelope=xml(decoded(rsp));request(p,req,request);require(PAOS.equals(request.getAttribute("ProtocolBinding"))&&endpoint(before.metadata,"AssertionConsumerService",PAOS,2).equals(request.getAttribute("AssertionConsumerServiceURL")));boolean negative=fixture.contains("unadvertised")||fixture.contains("invalid-signature")||fixture.contains("old-key");
    if(fixture.contains("first-paos"))require(valid(request,List.of(certs(rolloverMetadata,"signing").getFirst())));else if(fixture.contains("second-paos"))require(valid(request,List.of(certs(rolloverMetadata,"signing").getLast())));else if(fixture.contains("invalid-signature"))require(!valid(request,certs(newMetadata,"signing")));else if(fixture.contains("old-key"))require(valid(request,certs(oldMetadata,"signing"))&&!valid(request,certs(newMetadata,"signing")));else if(fixture.contains("unadvertised"))require(valid(request,List.of(pollingKeys.apply(run,"multiple-signing-keys-unadvertised").orElseThrow().certificate()))&&!valid(request,certs(rolloverMetadata,"signing")));else require(valid(request,certs(newMetadata,"signing")));
    if(negative){require(children(one(children(envelope,SOAP,"Body")),SOAP,"Fault").size()==1&&rsp.status()!=null&&rsp.status()==500);ShibbolethMetadataApplicationSource.validatePaosCause(projection,fixture,text(p,"actionId"),req.id(),rsp.id(),hash(decoded(req)),hash(decoded(rsp)),entity,before.after.nativeAt,after.before.nativeAt,new String(file("native-application-audit.log"),StandardCharsets.UTF_8));Audit audit=audit(request.getAttribute("ID"));require(audit.error.isEmpty()&&audit.status.isEmpty()&&audit.inBinding.equals("SOAP")&&audit.profile.equals(ECP_PROFILE));nativeTime(audit,before,after);}
    else{Element response=soap(envelope,"Response");String destination=endpoint(before.metadata,"AssertionConsumerService",PAOS,2);require(destination.equals(one(children(one(children(envelope,SOAP,"Header")),ECP,"Response")).getAttribute("AssertionConsumerServiceURL")));normal(request,response,rsp,before.metadata,pollingKeys.apply(run,fixture.contains("rollover")?"multiple-signing-keys-first":"no-valid-until"),destination);Audit audit=audit(request.getAttribute("ID"));require(audit.status.equals("Success")&&audit.error.isEmpty()&&audit.inBinding.equals("SOAP")&&audit.outBinding.equals("SOAP")&&audit.profile.equals(ECP_PROFILE));nativeTime(audit,before,after);}
    accepted.put(fixture,!negative);
   }}
  void browser()throws Exception{var fixtures=new ArrayList<>(MetadataSupersessionProbeTestCase.FIXTURES);fixtures.addAll(MetadataSupersessionProbeTestCase.SLO_FIXTURES);for(String fixture:fixtures){JsonNode p=probes.get(fixture);Epoch before=refEpoch(p.path("beforeEpoch")),after=refEpoch(p.path("afterEpoch"));var req=entry(text(p,"requestReference"));Element request=xml(decoded(req));request(p,req,request);require(req.direction()==Direction.OUTBOUND&&MetadataSupersessionProbeTestCase.APPLICATION.equals(text(p,"sourceCaseId")));boolean slo=fixture.endsWith("slo-route");require(P.equals(request.getNamespaceURI())&&(slo?"LogoutRequest":"AuthnRequest").equals(request.getLocalName()));List<X509Certificate> keys=fixture.startsWith("old-key")?certs(oldMetadata,"signing"):fixture.startsWith("rollover-first")?List.of(certs(rolloverMetadata,"signing").getFirst()):fixture.startsWith("rollover-second")?List.of(certs(rolloverMetadata,"signing").getLast()):certs(newMetadata,"signing");
    if(fixture.equals("new-key-redirect"))require("GET".equals(req.method())&&keys.stream().anyMatch(c->new RedirectSignatureVerifier().isValidForMessage(req.rawQuery(),c,decoded(req))));else require("POST".equals(req.method())&&(fixture.contains("invalid-signature")?!valid(request,keys):valid(request,keys)));
    String destination=slo?endpoint(newMetadata,"SingleLogoutService",REDIRECT,-1):fixture.equals("new-key-old-acs")?endpoint(oldMetadata,"AssertionConsumerService",POST,0):fixture.equals("new-key-second-acs")?endpoint(newMetadata,"AssertionConsumerService",POST,1):endpoint(newMetadata,"AssertionConsumerService",POST,0);
    if(!slo){if(fixture.equals("new-key-default-acs"))require(!request.hasAttribute("AssertionConsumerServiceURL")&&!request.hasAttribute("ProtocolBinding"));else require(destination.equals(request.getAttribute("AssertionConsumerServiceURL"))&&POST.equals(request.getAttribute("ProtocolBinding")));}
    boolean negative=fixture.startsWith("old-key")||fixture.startsWith("rollover-")||fixture.contains("invalid-signature")||fixture.equals("new-key-old-acs");var responses=responses(request.getAttribute("ID"));
    if((negative||fixture.equals("new-key-second-acs"))&&responses.isEmpty()){rejection(req,before,after,(fixture.equals("new-key-old-acs")||fixture.equals("new-key-second-acs"))?"EndpointResolutionFailed":"MessageAuthenticationError","");accepted.put(fixture,false);}
    else {require(responses.size()==1);var rsp=responses.getFirst();window(before,after,req,rsp);Element response=xml(decoded(rsp));
     if(slo){require(!negative&&P.equals(response.getNamespaceURI())&&"LogoutResponse".equals(response.getLocalName())&&"GET".equals(rsp.method())&&destination.equals(response.getAttribute("Destination"))&&targetEntity.equals(issuer(response))&&request.getAttribute("ID").equals(response.getAttribute("InResponseTo"))&&targetKeys.stream().anyMatch(c->new RedirectSignatureVerifier().isValidForMessage(rsp.rawQuery(),c,decoded(rsp))));var status=one(children(one(children(response,P,"Status")),P,"StatusCode"));require(status.getAttribute("Value").equals("urn:oasis:names:tc:SAML:2.0:status:Requester")&&one(children(status,P,"StatusCode")).getAttribute("Value").equals("urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal"));Audit a=audit(request.getAttribute("ID"));require(a.error.isEmpty()&&a.status.equals("Requester")&&a.inBinding.equals("POST")&&a.outBinding.equals("Redirect")&&a.profile.equals(LOGOUT));nativeTime(a,before,after);}
     else{normal(request,response,rsp,newMetadata,pollingKeys.apply(run,"no-valid-until"),destination);Audit a=audit(request.getAttribute("ID"));require(a.error.isEmpty()&&a.status.equals("Success")&&a.inBinding.equals("GET".equals(req.method())?"Redirect":"POST")&&a.outBinding.equals("POST")&&a.profile.equals(BROWSER));nativeTime(a,before,after);if(fixture.contains("invalid-signature"))throw new Unproven("invalid-signature-control-accepted");}
     http(req,rsp,request,slo,before,after);accepted.put(fixture,true);
    }
   }}
  void scope()throws Exception{require(accepted.size()==18);var expected=Set.of("new-key-explicit-acs","new-key-default-acs","new-key-second-acs","new-key-redirect","new-key-slo-route","fixture-ecp-metadata-b-paos","fixture-ecp-metadata-rollover-first-paos","fixture-ecp-metadata-rollover-second-paos");
   for(var p:accepted.entrySet())if(p.getValue()!=expected.contains(p.getKey())) {
    if(p.getKey().equals("new-key-second-acs")&&!p.getValue())violation="metadata.application.accepted-endpoint-rejected";
    else if(Set.of("old-key-new-acs","rollover-first-key-new-acs","rollover-second-key-new-acs","new-key-old-acs").contains(p.getKey())&&p.getValue())violation="metadata.supersession.conflicting-old-information-retained";
    else throw new Unproven("native-control-or-required-axis-unproven");
   }
   require(equalRoles||violation!=null);
   // Complete application requires the operative selection proof, not only native mdquery values.
   // The proof selects from the unmodified accepted B role using the actual native resolver and
   // loaded outgoing descriptors. Unsupported Browser Redirect ACS is a negative-only selection.
   var labels=Map.of("post-default","new-key-default-acs","post-second","new-key-second-acs","paos","fixture-ecp-metadata-b-paos","slo-front","new-key-slo-route","old-acs","new-key-old-acs");
   var requestRefs=new LinkedHashMap<String,String>();var requests=new LinkedHashMap<String,byte[]>();for(var label:labels.entrySet()){String ref=text(probes.get(label.getValue()),"requestReference");requestRefs.put(label.getKey(),ref);requests.put(label.getKey(),decoded(entry(ref)));}
   Epoch original=epoch("no-valid-until-before");
   ShibbolethMetadataApplicationSource.validateSelection(file("native-selection-input.json"),file("native-selection-output.json"),file("native-selection-invocation.json"),file("native-selection-source.java"),file("selection-operations.json"),file("selection-native-jars-before.sha256"),file("selection-native-jars-after.sha256"),file(original.root+"/"+text(original.n,"cacheFile")),newMetadata,oldMetadata,run,entity,requestRefs,requests,file("native/native-idp-conf-impl.jar"),file("native/native-idp-saml-impl.jar"),file("native/native-opensaml-saml-impl.jar"),file("native/native-opensaml-saml-api.jar"));
   JsonNode sdk=node("selection-operations.json").path("nativeContainerBefore"),nativeRuntime=original.n.path("runtime");
   for(String field:List.of("id","image","mounts"))require(sdk.path(field).equals(nativeRuntime.path(field)));require(sdk.path("running").asBoolean(false));
   if(m.has("calibration")) {
    JsonNode c=m.path("calibration");
    ShibbolethMetadataApplicationSource.validateCalibration(file(text(c,"inputFile")),file(text(c,"outputFile")),file(text(c,"invocationFile")),file(text(c,"sourceFile")),file(text(c,"operationsFile")),file(text(c,"jarsBeforeFile")),file(text(c,"jarsAfterFile")),file("selection-native-jars-before.sha256"),file("native-selection-input.json"),file("native-selection-output.json"),file(epoch("control-before").root+"/"+text(epoch("control-before").n,"cacheFile")),newMetadata,oldMetadata,text(c,"selectedConsumer"),sdk);
    violation=text(c,"selectedConsumer").equals("drop-accepted-b-secondary-acs")?"metadata.application.accepted-endpoint-omitted":"metadata.supersession.conflicting-old-information-retained";
   }
  }
  void request(JsonNode p,TranscriptEntry e,Element req){require(("_"+text(p,"actionId")).equals(req.getAttribute("ID"))&&text(p,"actionId").equals(e.correlationId())&&entity.equals(issuer(req))&&("GET".equals(e.method())?e.rawQuery()!=null&&e.url().equals(req.getAttribute("Destination")+(req.getAttribute("Destination").contains("?")?"&":"?")+e.rawQuery()):e.url().equals(req.getAttribute("Destination")))&&(ECP_FIXTURES.contains(text(p,"fixture"))?"EcpSoapRequest".equals(e.samlSummary().get("type"))&&text(p,"actionId").equals(com.samlscope.core.caseexec.ActionIds.derive(run,text(p,"fixture"),"send-baseline",0)):text(p,"fixture").equals(e.samlSummary().get("fixture_id")))&&!e.timestamp().isBefore(Instant.parse(req.getAttribute("IssueInstant"))));String local=req.getLocalName().equals("LogoutRequest")?"SingleLogoutService":"SingleSignOnService";boolean advertised=false;for(var idp:children(target,MD,"IDPSSODescriptor"))for(var service:children(idp,MD,local))advertised|=req.getAttribute("Destination").equals(service.getAttribute("Location"));require(advertised);}
  Element normal(Element req,Element rsp,TranscriptEntry e,Element md,Optional<PlanCredentials> key,String destination){require(e.direction()==Direction.INBOUND&&targetEntity.equals(issuer(rsp)));Element assertion=VerifiedResponseAssertion.read(rsp,targetEntity,targetKeys,md,key,req.getAttribute("ID"),destination);var statement=children(assertion,A,"AuthnStatement");require(statement.size()==1&&!statement.getFirst().getAttribute("SessionIndex").isBlank()&&children(rsp,A,"EncryptedAssertion").size()==1);return assertion;}
  List<TranscriptEntry> responses(String req){return entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&req.equals(e.samlSummary().get("inResponseTo"))&&Set.of("Response","LogoutResponse").contains(e.samlSummary().get("type"))).toList();}
  void rejection(TranscriptEntry req,Epoch before,Epoch after,String cause,String pre)throws Exception{Element request=xml(decoded(req));require(responses(request.getAttribute("ID")).isEmpty());var observations=entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&"BrowserResponseObservation".equals(e.samlSummary().get("type"))&&req.correlationId().equals(e.correlationId())).toList();JsonNode h=uniqueHttp(pre,request.getAttribute("ID"));require(hash(decoded(req)).equals(text(h,"requestSha256"))&&req.url().equals(text(h,"requestUrl"))&&req.method().equals(text(h,"requestMethod"))&&h.path("responseStatus").asInt(-1)==400);hostWindow(before,after,at(h,"startedAt"),at(h,"completedAt"));byte[] body=file(pre+text(h,"responseBodyFile"));require(hash(body).equals(text(h,"responseBodySha256"))&&visibleError(body,cause));if(!observations.isEmpty()){require(observations.size()==1);var observation=observations.getFirst();window(before,after,req,observation);require(observation.status()!=null&&observation.status()==400&&observation.bodyBytes()==body.length&&Arrays.equals(body,body(observation)));refs.add(new EvidenceRef("transcript",observation.id()));}else require(req.samlSummary().containsKey("metadataSignatureGroup"));Audit a=audit(request.getAttribute("ID"));require(a.error.equals(cause)&&a.status.isEmpty()&&a.signature.equals("true")&&a.inBinding.equals("POST")&&a.outBinding.isEmpty()&&a.profile.equals(request.getLocalName().equals("LogoutRequest")?LOGOUT:BROWSER));nativeTime(a,before,after);}
  byte[] body(TranscriptEntry e)throws Exception{require(e.bodyRef()!=null&&e.bodyRef().equals("transcripts/"+run+"/"+e.id()+".body"));return read(directory.getParent(),e.bodyRef(),1048576);}
  JsonNode uniqueHttp(String pre,String request)throws Exception{var matches=new ArrayList<JsonNode>();for(var h:node(pre+"native-http.json"))if(request.equals(h.path("requestId").asText()))matches.add(h);require(matches.size()==1);return matches.getFirst();}
  void http(TranscriptEntry req,TranscriptEntry rsp,Element request,boolean slo,Epoch before,Epoch after)throws Exception{
   JsonNode h=uniqueHttp("",request.getAttribute("ID"));require(hash(decoded(req)).equals(text(h,"requestSha256"))&&req.url().equals(text(h,"requestUrl"))&&req.method().equals(text(h,"requestMethod")));
   if("GET".equals(req.method())) {
    // This original records the native Redirect submission only. Completion is established by
    // the separately signature-verified correlated Response and request-bound native audit.
    require(!slo&&"native-target-redirect-submission".equals(text(h,"observation"))&&hash(req.rawQuery().getBytes(StandardCharsets.UTF_8)).equals(text(h,"rawQuerySha256")));
    hostWindow(before,after,at(h,"startedAt"),rsp.timestamp());
   }else {
    require(hash(decoded(rsp)).equals(text(h,"responseSamlSha256")));hostWindow(before,after,at(h,"startedAt"),at(h,"completedAt"));
    if(slo)require(hash(rsp.rawQuery().getBytes(StandardCharsets.UTF_8)).equals(text(h,"responseRawQuerySha256"))&&h.path("responseStatus").asInt(-1)==302);else require(h.path("responseStatus").asInt(-1)==200);
   }
  }
  Audit audit(String req){var list=new ArrayList<Audit>();for(String line:audits)if(line.startsWith("SAMLscope-application-v1|")){String[] a=line.substring("SAMLscope-application-v1|".length()).split("\\|",-1);require(a.length==11);if(req.equals(a[0]))list.add(new Audit(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],Instant.parse(a[10])));}require(list.size()==1);var a=list.getFirst();require(entity.equals(a.entity)&&a.signature.equals("true"));return a;}
  Epoch epoch(String label){var e=epochs.get(label);require(e!=null);return e;}
  Epoch refEpoch(JsonNode ref){var found=epochs.values().stream().filter(e->text(ref,"reference").equals(e.tx.id())).toList();require(found.size()==1&&text(ref,"sha256").equals(hashUnchecked(content.readDecodedSaml(found.getFirst().tx))));return found.getFirst();}
  void window(Epoch b,Epoch a,TranscriptEntry req,TranscriptEntry rsp){require(sameRuntime(b,a)&&b.end.isBefore(req.timestamp())&&req.timestamp().isBefore(rsp.timestamp())&&rsp.timestamp().isBefore(a.start));}
  void hostWindow(Epoch b,Epoch a,Instant start,Instant end){require(!start.isBefore(b.end)&&!end.isBefore(start)&&!a.start.isBefore(end));}
  void nativeTime(Audit audit,Epoch b,Epoch a){require(!audit.at.isBefore(b.after.nativeAt)&&!a.before.nativeAt.isBefore(audit.at));}
  CaseOutcome outcome(Outcome value,String reason)throws Exception{for(var ref:refs)if(ref.kind().equals("transcript"))require(entries.containsKey(ref.reference())&&run.equals(entries.get(ref.reference()).runId()));refs.add(new EvidenceRef("native-metadata-application-evidence",run+"/manifest.json#"+hash(manifestRaw)));return new CaseOutcome(value,null,reason,reason,List.copyOf(refs),Map.ofEntries(Map.entry("adapter",ADAPTER),Map.entry("run_id",run),Map.entry("accepted_metadata_application_verified",true),Map.entry("simultaneous_rollover_controls_verified",true),Map.entry("original_request_response_signatures_verified",true),Map.entry("restored",true),Map.entry("slo_observation_scope","endpoint-selection-only"),Map.entry("historical_rollover_epoch_preserved",true),Map.entry("receipt_sha256",hash(manifestRaw)),Map.entry("counterfactual_calibration_only",m.has("calibration")),Map.entry("proof_scope",m.has("calibration")?"isolated-native-consumer-calibration":"recorded-native-application")));}
 }
 record Epoch(JsonNode n,TranscriptEntry tx,String root,Element metadata,Element effective,Instant start,Instant end,ClockRead before,ClockRead after){}
 record ClockRead(Instant start,Instant end,Instant nativeAt){}
 record Audit(String request,String inResponseTo,String response,String entity,String error,String status,String signature,String inBinding,String outBinding,String profile,Instant at){}
 static boolean sameRuntime(Epoch a,Epoch b){return a.n.path("runtime").equals(b.n.path("runtime"));}
 static ClockRead clock(JsonNode n)throws Exception{require("samlscope-native-clock-v1".equals(text(n,"schema"))&&strings(n.path("command")).equals(List.of("date","-u","+%Y-%m-%dT%H:%M:%S.%NZ"))&&hash((text(n,"stdout")+"\n").getBytes(StandardCharsets.UTF_8)).equals(text(n,"stdoutSha256")));Instant start=at(n,"startedAt"),end=at(n,"finishedAt");require(!end.isBefore(start));return new ClockRead(start,end,at(n,"stdout"));}
 static boolean nativeFetch(TranscriptEntry e){return e.headers()!=null&&e.headers().entrySet().stream().filter(x->x.getKey().equalsIgnoreCase("User-Agent")).flatMap(x->x.getValue().stream()).anyMatch(v->v.startsWith("Shibboleth/"));}
 static void profile(JsonNode n,String id){JsonNode p=n.path("ProfileConfiguration"),r=n.path("RelyingPartyConfiguration");require(id.equals(text(p,"id"))&&"shibboleth.DefaultRelyingParty".equals(text(r,"id"))&&"shibboleth.DefaultSecurityConfiguration".equals(text(r,"securityConfiguration"))&&!p.path("ignoreRequestSignatures").asBoolean(true)&&!p.path("skipEndpointValidationWhenSigned").asBoolean(true)&&p.path("signResponses").asBoolean(false)&&p.path("encryptAssertions").asBoolean(false)&&!p.path("encryptionOptional").asBoolean(true));}
 static Element role(Element md){return one(children(md,MD,"SPSSODescriptor"));}
 static String endpoint(Element md,String local,String binding,int index){var matches=children(role(md),MD,local).stream().filter(e->binding.equals(e.getAttribute("Binding"))&&(index<0||Integer.toString(index).equals(e.getAttribute("index")))).toList();require(matches.size()==1&&!matches.getFirst().getAttribute("Location").isBlank());return matches.getFirst().getAttribute("Location");}
 static List<X509Certificate> certs(Element md,String use)throws Exception{var result=new ArrayList<X509Certificate>();for(var d:children(role(md),MD,"KeyDescriptor"))if(d.getAttribute("use").isBlank()||use.equals(d.getAttribute("use")))for(var i:children(d,DS,"KeyInfo"))for(var x:children(i,DS,"X509Data"))for(var c:children(x,DS,"X509Certificate"))result.add(certificate(c));return result;}
 static X509Certificate certificate(Element e)throws Exception{return (X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(e.getTextContent().replaceAll("\\s+",""))));}
 static boolean sameKey(X509Certificate a,X509Certificate b){return Arrays.equals(a.getPublicKey().getEncoded(),b.getPublicKey().getEncoded());}
 static boolean disjoint(List<X509Certificate>a,List<X509Certificate>b){return !a.isEmpty()&&!b.isEmpty()&&a.stream().noneMatch(x->b.stream().anyMatch(y->sameKey(x,y)));}
 static boolean valid(Element xml,List<X509Certificate> certs){return certs.stream().anyMatch(c->new XmlSignatureVerifier().hasValidEnvelopedSignature(xml,c));}
 static String issuer(Element root){return one(children(root,A,"Issuer")).getTextContent().strip();}
 static String subject(Element assertion){return semantic(one(children(one(children(assertion,A,"Subject")),A,"NameID")));}
 static Element soap(Element envelope,String local){require(SOAP.equals(envelope.getNamespaceURI())&&"Envelope".equals(envelope.getLocalName()));return one(children(one(children(envelope,SOAP,"Body")),P,local));}
 static Element one(List<Element> nodes){require(nodes.size()==1);return nodes.getFirst();}
 static Element xml(byte[] raw){return SecureXml.parse(raw).getDocumentElement();}
 static boolean visibleError(byte[] raw,String cause){String body=new String(raw,StandardCharsets.UTF_8).replaceAll("(?is)<(script|style)\\b[^>]*>.*?</\\1>","");return body.contains(cause.equals("EndpointResolutionFailed")?"Unable to Respond":"Message Security Error")&&!body.contains("name=\"SAMLResponse\"");}
 static String semantic(Element root){var b=new StringBuilder("{").append(root.getNamespaceURI()).append('}').append(root.getLocalName());var attrs=new TreeMap<String,String>();for(int i=0;i<root.getAttributes().getLength();i++){var a=root.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put("{"+a.getNamespaceURI()+"}"+a.getLocalName(),a.getNodeValue());}b.append(attrs);for(Node n=root.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e)b.append(semantic(e));else if(n.getNodeType()==Node.TEXT_NODE&&!n.getTextContent().isBlank())b.append(n.getTextContent().replaceAll("\\s+",""));return b.toString();}
 static JsonNode json(byte[] raw)throws IOException{return new JsonCodec().mapper().readTree(raw);}
 static String text(JsonNode n,String key){var v=n.path(key);require(v.isTextual()&&!v.asText().isBlank());return v.asText();}
 static List<String> strings(JsonNode n){require(n.isArray());var result=new ArrayList<String>();for(var v:n){require(v.isTextual());result.add(v.asText());}return List.copyOf(result);}
 static Instant at(JsonNode n,String key){return Instant.parse(text(n,key));}
 static Instant numberInstant(JsonNode n){require(n.isNumber());var d=new java.math.BigDecimal(n.asText());long s=d.longValue();return Instant.ofEpochSecond(s,d.subtract(java.math.BigDecimal.valueOf(s)).movePointRight(9).intValue());}
 static boolean validRun(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}");}
 static byte[] read(Path root,String name,int max)throws IOException{require(name.matches("[A-Za-z0-9][A-Za-z0-9._/-]*")&&!name.contains(".."));Path f=root.resolve(name).toAbsolutePath().normalize();require(f.startsWith(root.toAbsolutePath().normalize()));for(Path p=f;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));require(Files.isRegularFile(f,LinkOption.NOFOLLOW_LINKS)&&Files.size(f)<=max);return Files.readAllBytes(f);}
 static String hash(byte[] raw)throws Exception{require(raw!=null);return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 static String hashUnchecked(byte[] raw){try{return hash(raw);}catch(Exception e){throw new Unproven("unreadable-hash");}}
 static void require(boolean b){if(!b)throw new Unproven("original-binding-unproven");}
 static final class Unproven extends IllegalArgumentException{final String issue;Unproven(String issue){super("Native application evidence unproven");this.issue=issue;}}
}
