package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.util.*;
import java.util.function.Function;
import java.util.zip.ZipInputStream;
import org.w3c.dom.*;

/** Six authenticated native exchanges under the selected stock crypto-transient factory.
 * Source and effective configuration establish absence of AllowCreate-driven persistent
 * associations; ordinary login/logout state is neither excluded nor treated as failure.
 * Polling control checks only its signed outer Response; all six normative observations
 * independently verify and decrypt the actual Assertion with the Run's primary key. */
final class ShibbolethTransientAllowCreateEvidence {
 static final String SCHEMA="samlscope-shibboleth-transient-allow-create-v1",CASE=TransientAllowCreateScenarioTestCase.CASE;
 private static final String SUFFIX=".shibboleth-transient-allow-create",RUN="run_[0-9A-HJKMNP-TV-Z]{26}",TARGET="http://localhost:18280/idp/shibboleth";
 private static final String P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#",POST="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
 private static final String PROPERTY_INVENTORY="e00c49d9604cb94889816c924ede29e898e9f1cb4ae9155d79b09203b9fd25cb";
 private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final SamlDecryptionKeyProvider keys;
 ShibbolethTransientAllowCreateEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,SamlDecryptionKeyProvider keys){this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.keys=Objects.requireNonNull(keys);}
 boolean exists(String run){return run!=null&&run.matches(RUN)&&(Files.exists(directory.resolve(run+SUFFIX+".json"),LinkOption.NOFOLLOW_LINKS)||Files.exists(directory.resolve(run+SUFFIX),LinkOption.NOFOLLOW_LINKS));}
 Optional<CaseOutcome> evaluate(CaseContext context){
  if(!exists(context.runId()))return Optional.empty();String stage="native-transient-originals-unproven";
  try{
   require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete());var run=context.runId();var rawManifest=original(directory,run+SUFFIX+".json");var m=json(rawManifest);var files=m.path("files");var folder=directory.resolve(run+SUFFIX);byte[] targetRaw=metadata.apply(run);
   require(SCHEMA.equals(text(m,"schema"))&&run.equals(text(m,"runId"))&&"native-transient-allow-create".equals(text(m,"campaignId"))&&TARGET.equals(text(m,"targetEntityId"))&&hash(targetRaw).equals(text(m,"targetMetadataSha256"))&&files.isObject());
   for(var it=files.fields();it.hasNext();){var row=it.next();require(hash(original(folder,row.getKey())).equals(row.getValue().asText()));}
   var created=json(checked(folder,files,"created.json")).path("run");var plan=json(checked(folder,files,"plan.json")).at("/plan/plan");require(run.equals(text(created,"id"))&&text(created,"planId").equals(text(plan,"id"))&&"browser_sso_idp".equals(text(plan,"profile")));String entity="http://localhost:18080/p/"+text(created,"planId");
   var entries=new HashMap<String,TranscriptEntry>();for(var e:context.transcript().list(run)){require(run.equals(e.runId())&&e.id().matches("tx_[0-9A-HJKMNP-TV-Z]{26}")&&entries.put(e.id(),e)==null);if(e.decodedSamlRef()!=null)require(("transcripts/"+run+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())&&content.readDecodedSaml(e)!=null&&e.decodedSamlBytes()==content.readDecodedSaml(e).length);}
   require(entries.size()>=17&&entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&"Response".equals(e.samlSummary().get("type"))).count()==7);var target=SecureXml.parse(targetRaw).getDocumentElement();require(MD.equals(target.getNamespaceURI())&&"EntityDescriptor".equals(target.getLocalName())&&TARGET.equals(target.getAttribute("entityID")));var targetKeys=MetadataAlgorithmEvidence.signingKeys(target);require(!targetKeys.isEmpty());
   var refs=new LinkedHashSet<EvidenceRef>();var fetch=entry(entries,m,"fetchReference","MetadataFetch",Direction.INBOUND);var prepared=entry(entries,m,"metadataReference","MetadataPrepared",Direction.OUTBOUND);var fixture=checked(folder,files,"control.fixture.xml");require(fetch.id().equals(prepared.samlSummary().get("fetchTranscriptId"))&&!prepared.timestamp().isBefore(fetch.timestamp())&&Arrays.equals(fixture,content.readDecodedSaml(prepared))&&hash(fixture).equals(prepared.samlSummary().get("metadataSha256")));
   var controlPeer=SecureXml.parse(fixture).getDocumentElement();require(entity.equals(controlPeer.getAttribute("entityID")));var controlKeys=MetadataAlgorithmEvidence.signingKeys(controlPeer);require(!controlKeys.isEmpty()&&signed(controlPeer,controlKeys));var controlNative=SecureXml.parse(checked(folder,files,"native-effective-sp-metadata.xml")).getDocumentElement();require(structure(one(controlPeer,MD,"SPSSODescriptor")).equals(structure(one(controlNative,MD,"SPSSODescriptor"))));
   stage="native-effective-transient-factory-unproven";ShibbolethSubjectConfirmationEvidence.validateSelectedStockSsoConfiguration(folder,files);
   for(var phase:List.of("original","before-protocol","after-protocol","before-matrix","after-matrix","final"))require(PROPERTY_INVENTORY.equals(hash(checked(folder,files,phase+"-properties-sha256.json"))));
   for(var phase:List.of("before-matrix","after-matrix")){
    var inventory=json(checked(folder,files,phase+"-xml-inventory-sha256.json"));require(inventory.equals(json(checked(folder,files,"before-protocol-xml-inventory-sha256.json"))));require(Arrays.equals(checked(folder,files,phase+"-classpath-sha256.json"),checked(folder,files,"original-classpath-sha256.json"))&&json(checked(folder,files,phase+"-override-source-inventory.json")).isEmpty());
    var effective=json(checked(folder,files,phase+"-native-effective-profile.json"));ShibbolethSubjectConfirmationEvidence.validateProfile(effective);require(effective.equals(json(checked(folder,files,"before-protocol-native-effective-profile.json"))));var observed=json(checked(folder,files,phase+"-native-effective-profile-observed.json"));require(entity.equals(text(observed,"requester"))&&"native-dumpconfig-admin-profile".equals(text(observed,"source"))&&!observed.path("privateFieldsExported").asBoolean(true));
   }
   validateTransientFactory(checked(folder,files,"native-idp-conf-impl.jar"),checked(folder,files,"native-idp-saml-impl.jar"),checked(folder,files,"before-matrix-saml-nameid.xml"));
   var launch=json(checked(folder,files,"target-container-inspect-start.json")).get(0).path("Config");require(launch.equals(json(checked(folder,files,"target-container-inspect-end.json")).get(0).path("Config")));for(var env:launch.path("Env")){String value=env.asText();if(value.startsWith("JAVA_OPTS="))require("JAVA_OPTS=-Xmx3000m".equals(value));require(!value.contains("idp.transientId")&&!value.startsWith("JAVA_TOOL_OPTIONS=")&&!value.startsWith("_JAVA_OPTIONS="));}
   var peerBytes=checked(folder,files,"matrix-sp-metadata.xml");require(Arrays.equals(peerBytes,checked(folder,files,"matrix-sp-metadata-readback.xml")));var peer=SecureXml.parse(peerBytes).getDocumentElement();require(entity.equals(peer.getAttribute("entityID")));var peerKeys=MetadataAlgorithmEvidence.signingKeys(peer);require(!peerKeys.isEmpty()&&signed(peer,peerKeys));var nativePeerBytes=checked(folder,files,"matrix-native-effective-sp-metadata.xml");var nativePeer=SecureXml.parse(nativePeerBytes).getDocumentElement();var nativeRead=json(checked(folder,files,"matrix-native-effective-sp-read.json"));require(entity.equals(nativePeer.getAttribute("entityID"))&&structure(one(peer,MD,"SPSSODescriptor")).equals(structure(one(nativePeer,MD,"SPSSODescriptor")))&&run.equals(text(nativeRead,"runId"))&&entity.equals(text(nativeRead,"entityId"))&&hash(nativePeerBytes).equals(text(nativeRead,"sha256"))&&nativeRead.path("exitCode").asInt(-1)==0);
   var negative=entry(entries,m,"negativeRequestReference","AuthnRequest",Direction.OUTBOUND);var positive=entry(entries,m,"positiveRequestReference","AuthnRequest",Direction.OUTBOUND);var controlResponse=entry(entries,m,"positiveResponseReference","Response",Direction.INBOUND);var negativeRaw=content.readDecodedSaml(negative);var positiveXml=SecureXml.parse(content.readDecodedSaml(positive)).getDocumentElement();var negativeXml=SecureXml.parse(negativeRaw).getDocumentElement();
   require(MetadataProbeCorrelation.signatureControl(negative)&&!MetadataProbeCorrelation.signatureControl(positive)&&!signed(negativeXml,controlKeys)&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(negativeXml)&&signed(positiveXml,controlKeys));require(positive.timestamp().isAfter(negative.timestamp())&&!controlResponse.timestamp().isBefore(positive.timestamp())&&!negative.timestamp().isBefore(prepared.timestamp()));
   var outer=SecureXml.parse(content.readDecodedSaml(controlResponse)).getDocumentElement();require(responseMatches(outer,positiveXml,entity)&&signed(outer,targetKeys)&&children(outer,S,"Assertion").isEmpty()&&children(outer,S,"EncryptedAssertion").size()==1);
   var nativeHttp=json(checked(folder,files,"normal-native-http-observations.json"));require(run.equals(text(nativeHttp,"runId")));var rejected=matching(nativeHttp,negative.correlationId());require(hash(negativeRaw).equals(text(rejected,"requestSha256"))&&negative.url().equals(text(rejected,"requestUrl"))&&negative.url().equals(text(rejected,"responseUrl"))&&rejected.path("responseStatus").asInt(-1)==400&&rejected.path("nativeMessageSecurityError").asBoolean(false)&&!rejected.path("samlResponseFormPresent").asBoolean(true));var error=checked(folder,files,"native-rejection.html");require(hash(error).equals(text(rejected,"responseBodySha256"))&&new String(error,StandardCharsets.UTF_8).contains("Message Security Error")&&!new String(error,StandardCharsets.UTF_8).matches("(?is).*<input\\b.*"));
   for(var e:entries.values())if(e.direction()==Direction.INBOUND&&"Response".equals(e.samlSummary().get("type")))require(!negative.correlationId().equals(SecureXml.parse(content.readDecodedSaml(e)).getDocumentElement().getAttribute("InResponseTo")));
   stage="native-six-transient-policy-exchanges-unproven";require(m.path("matrix").size()==6);var seen=new HashSet<String>();var ids=new HashSet<String>();String fixed=null,principal=null,authentication=null,nativeSession=null;var audits=auditRecords(folder,files,run,entity);var privateKey=keys.keyFor(run).orElseThrow();var encryptionCertificate=encryptionCertificate(peer);var planKey=new PlanCredentials(privateKey,encryptionCertificate);var http=json(checked(folder,files,"matrix-native-http-observations.json"));require(run.equals(text(http,"runId"))&&!http.path("privateCredentialsExported").asBoolean(true)&&http.path("records").size()==6);
   Instant before=at(folder,files,"before-matrix-observed.json"),after=at(folder,files,"after-matrix-observed.json");require(before.isAfter(controlResponse.timestamp())&&!after.isBefore(before));
   for(var row:m.path("matrix")){
    String key=text(row,"key");require(SimpleSamlPhpTransientAllowCreateEvidence.KEYS.contains(key)&&seen.add(key));var request=entries.get(text(row,"requestReference"));var response=entries.get(text(row,"responseReference"));require(request!=null&&response!=null&&request.direction()==Direction.OUTBOUND&&response.direction()==Direction.INBOUND&&"AuthnRequest".equals(request.samlSummary().get("type"))&&"Response".equals(response.samlSummary().get("type"))&&CASE.equals(request.samlSummary().get("scenario_case_id"))&&key.equals(request.samlSummary().get("fixture_id")));
    byte[] requestRaw=content.readDecodedSaml(request);var rq=SecureXml.parse(requestRaw).getDocumentElement();String id=rq.getAttribute("ID"),recipient=rq.getAttribute("AssertionConsumerServiceURL"),action=String.valueOf(request.samlSummary().get("action_id"));require(action.matches("action_[0-9a-f]{32}")&&action.equals(request.correlationId())&&("_"+action).equals(id)&&id.equals(response.correlationId())&&ids.add(id)&&P.equals(rq.getNamespaceURI())&&"AuthnRequest".equals(rq.getLocalName())&&entity.equals(issuer(rq))&&POST.equals(rq.getAttribute("ProtocolBinding"))&&!truth(rq.getAttribute("ForceAuthn"))&&!truth(rq.getAttribute("IsPassive"))&&SimpleSamlPhpTransientAllowCreateEvidence.policyMatchesRequest(rq,key));
    require("POST".equals(request.method())&&"http://localhost:18280/idp/profile/SAML2/POST/SSO".equals(request.url())&&request.url().equals(rq.getAttribute("Destination"))&&signed(rq,peerKeys)&&!request.timestamp().isBefore(before)&&!response.timestamp().isBefore(request.timestamp())&&!response.timestamp().isAfter(after));require(children(one(peer,MD,"SPSSODescriptor"),MD,"AssertionConsumerService").stream().anyMatch(e->POST.equals(e.getAttribute("Binding"))&&recipient.equals(e.getAttribute("Location"))));
    String normalized=fixedRequest(rq);if(fixed==null)fixed=normalized;else require(fixed.equals(normalized));var assertion=VerifiedResponseAssertion.read(SecureXml.parse(content.readDecodedSaml(response)).getDocumentElement(),TARGET,targetKeys,peer,Optional.of(planKey),id,recipient);require(SimpleSamlPhpTransientAllowCreateEvidence.transientAssertion(assertion));String authn=authentication(assertion);var audit=authenticatedAudit(audits,assertion,entity);String user=audit[3];if(principal==null){principal=user;authentication=authn;nativeSession=audit[19];}else require(principal.equals(user)&&authentication.equals(authn)&&nativeSession.equals(audit[19]));
    var nativeRow=matching(http,id);require(hash(requestRaw).equals(text(nativeRow,"requestSha256"))&&request.url().equals(text(nativeRow,"requestUrl"))&&request.url().equals(text(nativeRow,"responseUrl"))&&nativeRow.path("responseStatus").asInt(-1)==200&&nativeRow.path("samlResponseFormPresent").asBoolean(false));Instant start=Instant.parse(text(nativeRow,"startedAt")),end=Instant.parse(text(nativeRow,"completedAt"));require(!start.isBefore(before)&&!end.isBefore(start)&&!end.isAfter(after));
    require(entries.values().stream().filter(e->e.direction()==Direction.INBOUND&&"Response".equals(e.samlSummary().get("type"))&&id.equals(SecureXml.parse(content.readDecodedSaml(e)).getDocumentElement().getAttribute("InResponseTo"))).count()==1);refs.add(new EvidenceRef("transcript",request.id()));refs.add(new EvidenceRef("transcript",response.id()));
   }
   require(seen.equals(new HashSet<>(SimpleSamlPhpTransientAllowCreateEvidence.KEYS))&&principal!=null&&authentication!=null);var counts=json(checked(folder,files,"additional-operation-counts.json"));require(counts.path("matrixProtocolAttempts").asInt(-1)==6&&counts.path("credentialPosts").asInt(-1)==0&&counts.path("metadataWrites").asInt(-1)==1&&counts.path("reloads").asInt(-1)==1&&counts.path("productRestarts").asInt(-1)==0&&counts.path("humanOperations").asInt(-1)==0);
   stage="native-signed-transient-controls-unproven";var producer=json(checked(folder,files,"producer.json"));var source=checked(folder,files,"ShibbolethTransientAllowCreateProducer.java");require("83a67880ecb6609a3298ec898866993dee8b9af72edca86bf259b5c475d2df91".equals(hash(source))&&hash(source).equals(text(producer,"sourceSha256"))&&"samlscope-shibboleth-transient-calibration-v1".equals(text(producer,"schema"))&&TARGET.equals(text(producer,"targetEntityId"))&&entity.equals(text(producer,"spEntityId"))&&!producer.path("controlsAdopted").asBoolean(true)&&!producer.path("nativePrivateKeyExported").asBoolean(true));
   var controlRequest=entries.get(text(producer,"positiveRequestReference"));require(controlRequest!=null&&text(m.path("matrix").get(0),"requestReference").equals(controlRequest.id()));var cq=SecureXml.parse(content.readDecodedSaml(controlRequest)).getDocumentElement();require(cq.getAttribute("ID").equals(text(producer,"requestId"))&&cq.getAttribute("AssertionConsumerServiceURL").equals(text(producer,"recipient")));String syntheticUser=null,syntheticAuthn=null;
   for(String kind:List.of("transient-positive","persistent-format","foreign-principal","changed-authentication")){var raw=checked(folder,files,kind+".xml");require(hash(raw).equals(text(producer.path("files"),kind)));var a=VerifiedResponseAssertion.read(SecureXml.parse(raw).getDocumentElement(),TARGET,targetKeys,peer,Optional.empty(),cq.getAttribute("ID"),cq.getAttribute("AssertionConsumerServiceURL"));if(kind.equals("transient-positive")){require(SimpleSamlPhpTransientAllowCreateEvidence.transientAssertion(a));syntheticUser=uid(a);syntheticAuthn=authentication(a);}require(consistentTransientAssertion(a,syntheticUser,syntheticAuthn)==kind.equals("transient-positive"));}
   for(var e:List.of(fetch,prepared,negative,positive,controlResponse))refs.add(new EvidenceRef("transcript",e.id()));refs.add(new EvidenceRef("native-shibboleth-transient-allow-create",run+SUFFIX+".json#"+hash(rawManifest)));
   return Optional.of(new CaseOutcome(Outcome.SATISFIED,null,"browser.nameid.transient-allow-create-ignored","All six authenticated native transient flows succeeded under the same stock crypto-transient factory, which neither reads AllowCreate nor creates persistent identifier associations from it.",List.copyOf(refs),Map.ofEntries(Map.entry("adapter",SCHEMA),Map.entry("case_id",CASE),Map.entry("run_id",run),Map.entry("required_conditions",SimpleSamlPhpTransientAllowCreateEvidence.KEYS),Map.entry("configuration_restored",true),Map.entry("allow_create_persistence_dependency_absent",true),Map.entry("ordinary_session_storage_asserted_absent",false),Map.entry("scope","this-run-selected-stock-native-crypto-transient-factory"),Map.entry("poll_control_assertion_decrypted",false),Map.entry("native_signed_semantic_controls",4),Map.entry("attested",false))));
  }catch(Exception unproven){if(Boolean.getBoolean("samlscope.shibTransientAllowCreate.debug"))unproven.printStackTrace();return Optional.of(CaseOutcome.notVerified(stage,"browser.nameid.transient-allow-create-native-unproven"));}
 }
 private static void validateTransientFactory(byte[] configJar,byte[] samlJar,byte[] configuredNameid)throws Exception{
  var beans=SecureXml.parse(zip(configJar,"net/shibboleth/idp/conf/saml-nameid-system.xml")).getDocumentElement();var nodes=beans.getElementsByTagNameNS("http://www.springframework.org/schema/beans","bean");Element transientBean=null,crypto=null;for(int i=0;i<nodes.getLength();i++){var e=(Element)nodes.item(i);if("shibboleth.SAML2TransientGenerator".equals(e.getAttribute("id")))transientBean=e;if("shibboleth.CryptoTransientIdGenerator".equals(e.getAttribute("id")))crypto=e;}
  require(transientBean!=null&&crypto!=null&&"net.shibboleth.idp.saml.nameid.impl.TransientSAML2NameIDGenerator".equals(transientBean.getAttribute("class"))&&"#{'%{idp.transientId.generator:shibboleth.CryptoTransientIdGenerator}'.trim()}".equals(transientBean.getAttributeNS("http://www.springframework.org/schema/p","transientIdGenerator-ref"))&&"net.shibboleth.idp.saml.nameid.impl.CryptoTransientIdGenerationStrategy".equals(crypto.getAttribute("class")));
  var selected=SecureXml.parse(configuredNameid).getDocumentElement().getElementsByTagNameNS("http://www.springframework.org/schema/util","list");Element generators=null;for(int i=0;i<selected.getLength();i++){var e=(Element)selected.item(i);if("shibboleth.SAML2NameIDGenerators".equals(e.getAttribute("id"))){require(generators==null);generators=e;}}require(generators!=null&&children(generators,"http://www.springframework.org/schema/beans","ref").size()==1&&"shibboleth.SAML2TransientGenerator".equals(children(generators,"http://www.springframework.org/schema/beans","ref").getFirst().getAttribute("bean")));for(Node n=generators.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element)require("ref".equals(n.getLocalName())&&"http://www.springframework.org/schema/beans".equals(n.getNamespaceURI()));
  var id=methodCode(zip(samlJar,"net/shibboleth/idp/saml/nameid/impl/TransientSAML2NameIDGenerator.class"),"getIdentifier","(Lorg/opensaml/profile/context/ProfileRequestContext;)Ljava/lang/String;");require("a139ec1036534bbb4fee8ef4cb6626a886de8a0244fc7fc85b3f10a4043f1bdc".equals(hash(id.code))&&id.calls.size()==9&&id.calls.contains("net/shibboleth/idp/authn/context/SubjectContext.getPrincipalName()Ljava/lang/String;")&&id.calls.contains("net/shibboleth/idp/saml/nameid/impl/TransientIdGenerationStrategy.generate(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"));
  var cryptoMethod=methodCode(zip(samlJar,"net/shibboleth/idp/saml/nameid/impl/CryptoTransientIdGenerationStrategy.class"),"generate","(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");require("e500d3614778dac3b613688ec978da79f0cff61313cd1bb63d1846169151b3ec".equals(hash(cryptoMethod.code))&&cryptoMethod.calls.size()==11&&cryptoMethod.calls.contains("net/shibboleth/shared/security/DataSealer.wrap(Ljava/lang/String;Ljava/time/Instant;)Ljava/lang/String;"));
 }
 /** Read native Code attributes and actual invoke instructions, rather than infer
  * behavior from absent constant-pool strings. Exact method bytes above bind the
  * reviewed principal→peer scoped sealer path, whose only output is the sealed ID. */
 private record NativeMethod(byte[] code,List<String> calls){}
 private static NativeMethod methodCode(byte[] bytes,String name,String descriptor)throws Exception{
  try(var in=new java.io.DataInputStream(new java.io.ByteArrayInputStream(bytes))){require(in.readInt()==0xcafebabe);in.readUnsignedShort();in.readUnsignedShort();Object[] cp=new Object[in.readUnsignedShort()];for(int i=1;i<cp.length;i++){int tag=in.readUnsignedByte();switch(tag){case 1->cp[i]=in.readUTF();case 3,4->in.skipNBytes(4);case 5,6->{in.skipNBytes(8);i++;}case 7,8,16,19,20->cp[i]=new int[]{tag,in.readUnsignedShort()};case 9,10,11,12,17,18->cp[i]=new int[]{tag,in.readUnsignedShort(),in.readUnsignedShort()};case 15->in.skipNBytes(3);default->throw new IllegalArgumentException();}}
   in.skipNBytes(6);in.skipNBytes(in.readUnsignedShort()*2L);int fields=in.readUnsignedShort();for(int i=0;i<fields;i++){in.skipNBytes(6);skipAttributes(in);}int methods=in.readUnsignedShort();NativeMethod found=null;
   for(int i=0;i<methods;i++){in.readUnsignedShort();String method=(String)cp[in.readUnsignedShort()],desc=(String)cp[in.readUnsignedShort()];int attrs=in.readUnsignedShort();for(int j=0;j<attrs;j++){String attribute=(String)cp[in.readUnsignedShort()];int length=in.readInt();require(length>=0&&length<=bytes.length);byte[] body=in.readNBytes(length);require(body.length==length);if(name.equals(method)&&descriptor.equals(desc)&&"Code".equals(attribute)){require(found==null);try(var codeIn=new java.io.DataInputStream(new java.io.ByteArrayInputStream(body))){codeIn.skipNBytes(4);int n=codeIn.readInt();require(n>0&&n<=body.length);byte[] code=codeIn.readNBytes(n);var calls=new ArrayList<String>();for(int offset=0;offset<code.length;){int op=Byte.toUnsignedInt(code[offset]),step=opcodeLength(op);require(offset+step<=code.length);if(op>=182&&op<=185){int index=(Byte.toUnsignedInt(code[offset+1])<<8)|Byte.toUnsignedInt(code[offset+2]);var ref=(int[])cp[index];require(ref[0]==10||ref[0]==11);String owner=(String)cp[((int[])cp[ref[1]])[1]];var nt=(int[])cp[ref[2]];calls.add(owner+"."+cp[nt[1]]+cp[nt[2]]);}offset+=step;}found=new NativeMethod(code,List.copyOf(calls));}}}}
   require(found!=null);return found;
  }
 }
 private static void skipAttributes(java.io.DataInputStream in)throws Exception{int n=in.readUnsignedShort();for(int i=0;i<n;i++){in.readUnsignedShort();long size=Integer.toUnsignedLong(in.readInt());require(size<=33554432);in.skipNBytes(size);}}
 private static int opcodeLength(int op){if(op==185||op==186)return 5;if(op==17||op==19||op==20||(op>=153&&op<=168)||(op>=178&&op<=184)||op==187||op==189||op==192||op==193||op==198||op==199)return 3;if(op==16||op==18||(op>=21&&op<=25)||(op>=54&&op<=58)||op==188)return 2;require(op!=170&&op!=171&&op!=196&&op!=200&&op!=201);return 1;}
 private static X509Certificate encryptionCertificate(Element sp)throws Exception{var roles=children(sp,MD,"SPSSODescriptor");require(roles.size()==1);var keys=children(roles.getFirst(),MD,"KeyDescriptor").stream().filter(e->"encryption".equals(e.getAttribute("use"))).toList();require(keys.size()==1);var encoded=keys.getFirst().getElementsByTagNameNS(DS,"X509Certificate");require(encoded.getLength()==1);return (X509Certificate)java.security.cert.CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(encoded.item(0).getTextContent())));}
 private static boolean responseMatches(Element response,Element request,String entity){return P.equals(response.getNamespaceURI())&&"Response".equals(response.getLocalName())&&TARGET.equals(issuer(response))&&request.getAttribute("ID").equals(response.getAttribute("InResponseTo"))&&request.getAttribute("AssertionConsumerServiceURL").equals(response.getAttribute("Destination"))&&"urn:oasis:names:tc:SAML:2.0:status:Success".equals(one(one(response,P,"Status"),P,"StatusCode").getAttribute("Value"))&&entity.equals(issuer(request));}
 private static String uid(Element a){var values=new ArrayList<String>();for(var statement:children(a,S,"AttributeStatement"))for(var attribute:children(statement,S,"Attribute"))if(Set.of("uid","urn:oid:0.9.2342.19200300.100.1.1").contains(attribute.getAttribute("Name")))for(var v:children(attribute,S,"AttributeValue"))values.add(v.getTextContent());require(values.size()==1&&!values.getFirst().isBlank());return values.getFirst();}
 static boolean consistentTransientAssertion(Element a,String user,String authn){try{return SimpleSamlPhpTransientAllowCreateEvidence.transientAssertion(a)&&uid(a).equals(user)&&authentication(a).equals(authn);}catch(RuntimeException invalid){return false;}}
 private static String authentication(Element a){var statement=one(a,S,"AuthnStatement");require(!statement.getAttribute("AuthnInstant").isBlank());var cls=one(one(statement,S,"AuthnContext"),S,"AuthnContextClassRef").getTextContent();require(Set.of("urn:oasis:names:tc:SAML:2.0:ac:classes:Password","urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport").contains(cls));return statement.getAttribute("AuthnInstant")+"/"+cls;}
 private static List<String[]> auditRecords(Path folder,JsonNode files,String run,String entity)throws Exception{
  var raw=checked(folder,files,"audit-public.log");var observed=json(checked(folder,files,"audit-public-observed.json"));var source=checked(folder,files,"audit-public-collector.py");
  require(run.equals(text(observed,"runId"))&&entity.equals(text(observed,"entityId"))&&observed.path("rowCount").asInt(-1)==7&&observed.path("nameIdFieldHashed").asBoolean(false)&&observed.path("nativeLoginSessionFieldHashed").asBoolean(false)&&!observed.path("privateCredentialsExported").asBoolean(true)&&observed.path("productConfigurationWrites").asInt(-1)==0&&observed.path("protocolOperations").asInt(-1)==0&&hash(raw).equals(text(observed,"publicOriginalSha256"))&&hash(source).equals(text(observed,"sourceSha256"))&&"b690f2ef1a5b2091a6d8f784d1721d21bc8018511aaaa3e097cfa6a414011df1".equals(hash(source)));
  var audit=checked(folder,files,"before-matrix-audit.xml");require(hash(audit).equals(text(observed,"auditConfigurationSha256"))&&Arrays.equals(audit,checked(folder,files,"after-matrix-audit.xml"))&&Arrays.equals(audit,checked(folder,files,"final-audit.xml"))&&new String(audit,StandardCharsets.UTF_8).contains("%a|%ST|%T|%u|%SP|%i|%ac|%t|%attr|%n|%f|%SSO|%XX|%XA|%b|%bb|%e|%S|%SS|%s|%UA"));
  var system=new String(zip(checked(folder,files,"native-idp-conf-impl.jar"),"net/shibboleth/idp/conf/audit-system.xml"),StandardCharsets.UTF_8);require(system.contains("net.shibboleth.idp.saml.profile.SAMLAuditFields.ASSERTION_ID")&&system.contains("net.shibboleth.idp.saml.audit.impl.AssertionIDAuditExtractor")&&system.contains("net.shibboleth.idp.saml.audit.impl.NameIDAuditExtractor"));
  var rows=new ArrayList<String[]>();var ids=new HashSet<String>();for(var line:new String(raw,StandardCharsets.UTF_8).split("\\R")){var f=line.split("\\|",-1);require(f.length==21&&entity.equals(f[4])&&!f[3].isBlank()&&!f[5].isBlank()&&ids.add(f[5])&&f[9].matches("sha256:[0-9a-f]{64}")&&f[19].matches("sha256:[0-9a-f]{64}")&&"Success".equals(f[17])&&f[18].isEmpty());Instant.parse(f[1]);Instant.parse(f[2]);Instant.parse(f[7]);rows.add(f);}require(rows.size()==7);return rows;
 }
 private static String[] authenticatedAudit(List<String[]> rows,Element assertion,String entity)throws Exception{
  var hits=rows.stream().filter(f->assertion.getAttribute("ID").equals(f[5])).toList();require(hits.size()==1);var f=hits.getFirst();var name=one(one(assertion,S,"Subject"),S,"NameID");var auth=one(assertion,S,"AuthnStatement");require(entity.equals(f[4])&&("sha256:"+hash(name.getTextContent().getBytes(StandardCharsets.UTF_8))).equals(f[9])&&"transient".equals(f[10])&&"password".equals(f[6])&&"true".equals(f[11])&&Instant.parse(f[7]).equals(Instant.parse(auth.getAttribute("AuthnInstant")))&&!Instant.parse(f[2]).isBefore(Instant.parse(f[1]))&&Instant.parse(f[1]).isAfter(Instant.parse(f[7])));return f;
 }
 private static String fixedRequest(Element request){var clone=(Element)request.cloneNode(true);clone.removeAttribute("ID");clone.removeAttribute("IssueInstant");for(var e:children(clone,DS,"Signature"))clone.removeChild(e);for(var e:children(clone,P,"NameIDPolicy"))clone.removeChild(e);return structure(clone);}
 private static String structure(Element e){var attrs=new TreeMap<String,String>();for(int i=0;i<e.getAttributes().getLength();i++){var a=e.getAttributes().item(i);if(!"http://www.w3.org/2000/xmlns/".equals(a.getNamespaceURI()))attrs.put("{"+a.getNamespaceURI()+"}"+a.getLocalName(),a.getNodeValue());}var parts=new ArrayList<String>();for(Node n=e.getFirstChild();n!=null;n=n.getNextSibling()){if(n instanceof Element child)parts.add(structure(child));else if(n.getNodeType()==Node.TEXT_NODE&&!n.getNodeValue().isBlank())parts.add(n.getNodeValue());}return "{"+e.getNamespaceURI()+"}"+e.getLocalName()+attrs+parts;}
 private static JsonNode matching(JsonNode records,String id){var rows=new ArrayList<JsonNode>();for(var row:records.path("records"))if(id.equals(row.path("requestId").asText()))rows.add(row);require(rows.size()==1);return rows.getFirst();}
 private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,JsonNode m,String name,String type,Direction direction){var e=entries.get(text(m,name));require(e!=null&&e.direction()==direction&&type.equals(e.samlSummary().get("type")));return e;}
 private static Element one(Element e,String ns,String kind){var values=children(e,ns,kind);require(values.size()==1);return values.getFirst();}
 private static String issuer(Element e){return one(e,S,"Issuer").getTextContent();}
 private static boolean signed(Element e,List<X509Certificate> keys){var v=new XmlSignatureVerifier();return v.hasValidEnvelopedReferenceDigests(e)&&keys.stream().anyMatch(k->v.hasValidEnvelopedSignature(e,k));}
 private static boolean truth(String s){return "true".equals(s)||"1".equals(s);}
 private static Instant at(Path folder,JsonNode files,String name)throws Exception{return Instant.parse(text(json(checked(folder,files,name)),"recordedAt"));}
 private static byte[] checked(Path folder,JsonNode files,String name)throws Exception{var raw=original(folder,name);require(hash(raw).equals(files.path(name).asText()));return raw;}
 private static byte[] original(Path folder,String name)throws Exception{require(name.matches("[A-Za-z0-9._-]+")&&!Set.of(".","..").contains(name));var path=folder.resolve(name);for(Path p=path;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));require(Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)&&Files.size(path)<33554432);return Files.readAllBytes(path);}
 private static byte[] zip(byte[] raw,String entry)throws Exception{try(var z=new ZipInputStream(new java.io.ByteArrayInputStream(raw))){for(var e=z.getNextEntry();e!=null;e=z.getNextEntry())if(entry.equals(e.getName()))return z.readAllBytes();}throw new IllegalArgumentException();}
 private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
 private static String text(JsonNode n,String key){var v=n.path(key);require(v.isTextual()&&!v.asText().isBlank());return v.asText();}
 private static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 private static void require(boolean v){if(!v)throw new IllegalArgumentException("Native crypto-transient proof incomplete");}
}
