package com.samlscope.runner.cases;

import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.PlanCredentials;
import com.samlscope.saml.crypto.XmlSignatureVerifier;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.saml.normal.*;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.net.URI;
import java.security.MessageDigest;
import java.security.cert.*;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import java.util.regex.Pattern;
import org.w3c.dom.Element;

/** Original-backed accepted certificate runtime use on the installed native SSP IdP path.
 * Parser acceptance is insufficient; each accepted certificate must verify a real signed request.
 * Ordinary signature errors have no PKIX cause and remain NOT_VERIFIED.
 * The M0 baseline must carry a plaintext signed Assertion: the polling provider does not
 * expose the Plan-primary receiver. Encrypted baselines remain NOT_VERIFIED; prepared
 * certificate responses use their actual advertised polling-variant receiver. */
public final class SimpleSamlPhpMetadataCertificateRuntimeEvidence {
    public static final String SCHEMA="samlscope-simplesamlphp-certificate-runtime-v1",ADAPTER="simplesamlphp-native-certificate-runtime-v1",CAMPAIGN="native-metadata-certificate-runtime",KIND="native-certificate-runtime-evidence";
    private static final String ORIGINAL="samlscope-simplesamlphp-certificate-runtime-original-v1",TARGET="http://localhost:18380/idp",BASE="http://localhost:18080",MD="urn:oasis:names:tc:SAML:2.0:metadata",P="urn:oasis:names:tc:SAML:2.0:protocol",DS="http://www.w3.org/2000/09/xmldsig#";
    private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final BiFunction<String,String,Optional<PlanCredentials>> keys;
    public SimpleSamlPhpMetadataCertificateRuntimeEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,BiFunction<String,String,Optional<PlanCredentials>> keys){this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.keys=Objects.requireNonNull(keys);}
    public boolean exists(String run){return validRun(run)&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
    private CaseOutcome pending(){return CaseOutcome.notVerified("native_certificate_runtime_originals_unavailable","metadata.certificate.runtime-native-unproven");}
    private static boolean validRun(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}");}
    private static void require(boolean condition){if(!condition)throw new IllegalArgumentException("Native signer proof unavailable");}
    static String hash(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
    private static JsonNode json(byte[] bytes)throws Exception{return new JsonCodec().mapper().readTree(bytes);}
    private static String text(JsonNode node,String field){require(node.path(field).isTextual()&&!node.path(field).asText().isBlank());return node.path(field).asText();}
    private static Instant at(JsonNode node,String field){return Instant.parse(text(node,field));}
    private byte[] raw(Path folder,String name)throws Exception {
        require(!name.isBlank()&&!Path.of(name).isAbsolute());var file=folder.resolve(name).normalize();require(file.startsWith(folder)&&!file.equals(folder));
        for(var p=file;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));require(Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS));return Files.readAllBytes(file);
    }
    private byte[] file(Path folder,JsonNode m,String name)throws Exception{var bytes=raw(folder,name);require(hash(bytes).equals(text(m.path("files"),name)));return bytes;}
    private JsonNode node(Path folder,JsonNode m,String name)throws Exception{return json(file(folder,m,name));}
    private Map<String,TranscriptEntry> history(CaseContext c,String run){
        require(validRun(run));var result=new LinkedHashMap<String,TranscriptEntry>();
        for(var e:c.transcript().list(run)){require(run.equals(e.runId())&&result.put(e.id(),e)==null);if(e.decodedSamlRef()!=null)require(("transcripts/"+run+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef()));}return result;
    }
    private byte[] decoded(TranscriptEntry e)throws Exception{require(e!=null&&e.decodedSamlRef()!=null);var bytes=content.readDecodedSaml(e);require(bytes!=null&&bytes.length==e.decodedSamlBytes());return bytes;}
    private JsonNode original(CaseContext c,Path folder,JsonNode m,String name,String kind)throws Exception {
        var ref=m.path("originals").path(name);var e=history(c,c.runId()).get(text(ref,"reference"));var bytes=decoded(e);
        require(hash(bytes).equals(text(ref,"sha256"))&&Arrays.equals(bytes,file(folder,m,"native-originals/"+name+".json")));
        require(e.direction()==Direction.INBOUND&&"POST".equals(e.method())&&Objects.equals(e.status(),204)&&"application/json".equals(e.contentType())&&(BASE+"/p/"+text(m,"planId")+"/sp/paos?run="+c.runId()).equals(e.url()));
        var n=json(bytes);require(ORIGINAL.equals(text(n,"schema"))&&c.runId().equals(text(n,"runId"))&&CAMPAIGN.equals(text(n,"campaignId"))&&kind.equals(text(n,"kind"))&&m.path("targetMetadataSha256").equals(n.path("targetMetadataSha256"))&&at(n,"recordedAt").isBefore(e.timestamp())&&!sensitive(n));return n;
    }
    static boolean sensitive(JsonNode n){
        if(n.isObject()){var fields=n.fields();while(fields.hasNext()){var e=fields.next();String k=e.getKey().toLowerCase(Locale.ROOT).replaceAll("[-_.]","");if(Set.of("cookie","setcookie","authorization","proxyauthorization","password","passwd","secret","credentials","token","accesstoken","refreshtoken","registrationaccesstoken","privatekey","metadatasignprivatekey").contains(k)||sensitive(e.getValue()))return true;}}
        else if(n.isArray())for(var item:n)if(sensitive(item))return true;return false;
    }
    private static List<X509Certificate> spKeys(Element root)throws Exception {
        var roles=children(root,MD,"SPSSODescriptor");require(roles.size()==1);var result=new ArrayList<X509Certificate>();
        for(var kd:children(roles.getFirst(),MD,"KeyDescriptor")){if(!kd.getAttribute("use").isBlank()&&!"signing".equals(kd.getAttribute("use")))continue;var certs=kd.getElementsByTagNameNS(DS,"X509Certificate");for(int i=0;i<certs.getLength();i++)result.add(certificate(certs.item(i).getTextContent()));}require(!result.isEmpty());return result;
    }
    private static X509Certificate certificate(String value)throws Exception{return (X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(value)));}
    private static Set<String> certHashes(List<X509Certificate> certificates)throws Exception{var result=new HashSet<String>();for(var c:certificates)result.add(hash(c.getEncoded()));return result;}
    private static Element fixture(byte[] raw,String entity)throws Exception {var root=SecureXml.parse(raw).getDocumentElement();require(MD.equals(root.getNamespaceURI())&&"EntityDescriptor".equals(root.getLocalName())&&entity.equals(root.getAttribute("entityID"))&&KeycloakSubjectConfirmationEvidence.signed(root,spKeys(root)));return root;}
    private static URI destination(Element target){var roles=children(target,MD,"IDPSSODescriptor");require(roles.size()==1);var urls=new HashSet<String>();for(var e:children(roles.getFirst(),MD,"SingleSignOnService"))if("urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST".equals(e.getAttribute("Binding")))urls.add(e.getAttribute("Location"));require(urls.size()==1);var uri=URI.create(urls.iterator().next());require("http".equals(uri.getScheme())&&"localhost".equals(uri.getHost())&&uri.getPort()==18380&&uri.getRawQuery()==null&&uri.getRawFragment()==null);return uri;}
    private static final Map<String,String> SOURCE=Map.of(
        "native-idp.php","ae55fc922431d29ca6e87654ae2071500a4c3d7185ed80a6fcc5b26eed12495d",
        "native-message.php","ab017ee6cf9fb66db1037e40ed50feff0b277b1a5d43fd8ca774a3d27ce355d2",
        "native-configuration.php","53837359cd60433082d3968843605a864bab97f23be482447bcfef37e7f6946e",
        "native-parser.php","8620bb26fd41d2be29d2611883839a4cfde0b6c8458c274e2d40a002678fd93d",
        "native-handler.php","43a0e730d624c5a937f800c4e7e045ff3625eeb0738d81a4ab1dac96f82fe040",
        "native-source.php","48fe4682d980e62416c751b7a39406ebf9664bf539e6a1557e7f54df770398c6",
        "native-signed-helper.php","4928545a8147e4222288def64a992ed8fbf0ba54243079fc3c919470b2cc766c",
        "native-utils.php","5845e28158c7641d5ce1e6b9205e8005b6d9c090e1888ea46416abb8fdf0018d",
        "native-xml-security-key.php","6c89ac116aca2c05791712749450be474218fd97cd9a66b7aad9d2ba4e6cba17",
        "native-xml-security-dsig.php","79597160c501fbdbe19bdca12b6797c06c38c4eae7cad6d0d1dca89301a5734f");
    private JsonNode state(CaseContext c,Path folder,JsonNode m,String label,String phase,List<X509Certificate> expected)throws Exception{
        var n=original(c,folder,m,label,"native-certificate-state");require(phase.equals(text(n,"phase"))&&n.path("peers").isArray()&&n.path("peers").size()==1);
        var raw=file(folder,m,"native-readbacks/"+label+".json");require(hash(raw).equals(text(n,"nativeReadbackSha256")));var readback=json(raw);require(!sensitive(readback));for(String f:List.of("peers","configurationSha256","metadataSources","hostedIdp","sourceHashes","operativeClasses"))require(n.path(f).equals(readback.path(f)));
        require(n.path("metadataSources").equals(json("[{\"type\":\"flatfile\"}]".getBytes(StandardCharsets.UTF_8)))&&TARGET.equals(n.at("/hostedIdp/entityId").asText())&&n.at("/hostedIdp/authproc").isArray()&&n.at("/hostedIdp/authproc").isEmpty());
        require(at(n,"nativeStartedAt").isBefore(at(n,"nativeFinishedAt"))&&at(n,"nativeFinishedAt").isBefore(at(n,"recordedAt"))&&n.at("/runtime/running").asBoolean(false));
        for(var s:SOURCE.entrySet())require(s.getValue().equals(text(n.path("sourceHashes"),s.getKey()))&&s.getValue().equals(hash(file(folder,m,"native-source/"+s.getKey()))));
        var operative=Map.of("SAML2\\Utils",List.of("/var/simplesamlphp/vendor/simplesamlphp/saml2-legacy/src/SAML2/Utils.php","native-utils.php"),"SAML2\\SignedElementHelper",List.of("/var/simplesamlphp/vendor/simplesamlphp/saml2-legacy/src/SAML2/SignedElementHelper.php","native-signed-helper.php"),"RobRichards\\XMLSecLibs\\XMLSecurityDSig",List.of("/var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php","native-xml-security-dsig.php"),"RobRichards\\XMLSecLibs\\XMLSecurityKey",List.of("/var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php","native-xml-security-key.php"));require(n.path("operativeClasses").size()==4);for(var row:operative.entrySet()){var actual=n.path("operativeClasses").path(row.getKey());require(row.getValue().get(0).equals(text(actual,"path"))&&SOURCE.get(row.getValue().get(1)).equals(text(actual,"sha256")));}
        String cfg=phase.equals("initial")||phase.equals("restored")?"original-configuration.php":text(n,"variant")+"-configuration.php";require(hash(file(folder,m,cfg)).equals(text(n,"configurationSha256")));
        var peer=n.path("peers").get(0);require(text(m,"entityId").equals(text(peer,"entityId")));
        if(expected==null)require(peer.path("present").isBoolean()&&!peer.path("present").asBoolean());else{require(peer.path("present").asBoolean(false)&&peer.at("/resolvedMetadata/validate.authnrequest").isBoolean()&&peer.at("/resolvedMetadata/validate.authnrequest").asBoolean());var found=new HashSet<String>();for(var k:peer.path("signingKeys")){require("X509Certificate".equals(text(k,"type"))&&k.path("signing").asBoolean(false));require(found.add(hash(certificate(text(k,"X509Certificate")).getEncoded())));}require(found.equals(certHashes(expected)));}
        return n;
    }
    /** An explicit additional-check operation is required; a generic signature rejection has no certificate-path cause. */
    static void validateAdditionalCheckCause(Path folder,JsonNode m,JsonNode original,JsonNode probe,JsonNode http,byte[] request,X509Certificate certificate,Element fixture)throws Exception{
        require(probe.path("actionId").equals(original.path("actionId"))&&probe.path("requestReference").equals(original.path("requestReference"))&&probe.path("responseReference").equals(original.path("responseReference")));
        var check=original.path("check");String variant=text(check,"variant");boolean revoked=variant.equals("certificate-revoked");require(revoked||variant.equals("certificate-revocation-unreachable"));String reason=revoked?"CERTIFICATE_REVOKED":"UNDETERMINED_REVOCATION_STATUS";int errorCode=revoked?23:3;require("samlscope-simplesamlphp-openssl-additional-certificate-check-v1".equals(text(check,"schema"))&&"native-selected-additional-revocation-check".equals(text(check,"source"))&&reason.equals(text(check,"reason"))&&check.path("errorCode").asInt(-1)==errorCode&&check.path("nativeSignatureVerified").isBoolean()&&check.path("nativeSignatureVerified").asBoolean()&&"SimpleSAML\\Module\\saml\\Message::checkSign".equals(text(check,"nativeSignatureMethod")));
        var q=SecureXml.parse(request).getDocumentElement();require(q.getAttribute("ID").equals(text(check,"requestId"))&&hash(request).equals(text(check,"requestSha256"))&&hash(certificate.getEncoded()).equals(text(check,"certificateSha256"))&&text(m.path("files"),variant+"-fixture.xml").equals(text(check,"fixtureSha256")));
        var extension=fixture.getElementsByTagNameNS("urn:samlscope:test:certificate-revocation","RevocationOriginals");require(extension.getLength()==1);var ext=(Element)extension.item(0);var issuer=certificate(ext.getElementsByTagNameNS("urn:samlscope:test:certificate-revocation","IssuerCertificate").item(0).getTextContent());require(hash(issuer.getEncoded()).equals(text(check,"issuerCertificateSha256")));if(revoked){var crlBytes=Base64.getMimeDecoder().decode(ext.getElementsByTagNameNS("urn:samlscope:test:certificate-revocation","CRL").item(0).getTextContent());require(hash(crlBytes).equals(text(check,"crlSha256")));}
        var start=at(http,"startedAt");var finish=at(http,"finishedAt");require(!at(check,"operationStartedAt").isBefore(start)&&!at(check,"operationCompletedAt").isAfter(finish)&&at(check,"operationStartedAt").isBefore(at(check,"operationCompletedAt")));
        String source=text(check,"checkerSourceFile");require(!Path.of(source).isAbsolute()&&folder.resolve(source).normalize().startsWith(folder)&&!Files.isSymbolicLink(folder.resolve(source)));var sourceBytes=Files.readAllBytes(folder.resolve(source));require("f2adb48cbb6a3767ce439e642e34008f4080f3688c5f47c90cd79546d61e86fc".equals(hash(sourceBytes))&&hash(sourceBytes).equals(text(check,"checkerSourceSha256"))&&hash(sourceBytes).equals(text(m.path("files"),source)));
        var setup=check.path("setup");var failure=check.path("failure");require(setup.path("exitCode").asInt(-1)==0&&failure.path("exitCode").asInt(-1)==2&&check.path("selectedOperation").equals(failure.path("command")));var setupCommand=setup.path("command");var failureCommand=failure.path("command");require(setupCommand.size()==5&&failureCommand.size()==(revoked?8:6)&&"/usr/bin/openssl".equals(setupCommand.get(0).asText())&&"verify".equals(setupCommand.get(1).asText())&&"-CAfile".equals(setupCommand.get(2).asText())&&"/usr/bin/openssl".equals(failureCommand.get(0).asText())&&"verify".equals(failureCommand.get(1).asText())&&"-CAfile".equals(failureCommand.get(2).asText())&&setupCommand.get(3).equals(failureCommand.get(3))&&setupCommand.get(4).equals(failureCommand.get(revoked?7:5))&&setupCommand.get(3).asText().endsWith("/issuer.pem")&&setupCommand.get(4).asText().endsWith("/leaf.pem")&&(revoked?"-CRLfile".equals(failureCommand.get(4).asText())&&"-crl_check".equals(failureCommand.get(6).asText())&&failureCommand.get(5).asText().endsWith("/revoked.crl.pem"):"-crl_check".equals(failureCommand.get(4).asText())));
        for(var phase:List.of(setup,failure))for(var stream:List.of("stdout","stderr")){String name=text(phase,stream+"File");require(!Path.of(name).isAbsolute()&&folder.resolve(name).normalize().startsWith(folder)&&!Files.isSymbolicLink(folder.resolve(name)));var raw=Files.readAllBytes(folder.resolve(name));require(hash(raw).equals(text(phase,stream+"Sha256"))&&hash(raw).equals(text(m.path("files"),name)));}
        String producerFile=text(check,"nativeProducerOriginalFile");require(!Path.of(producerFile).isAbsolute()&&folder.resolve(producerFile).normalize().startsWith(folder)&&!Files.isSymbolicLink(folder.resolve(producerFile)));var producerBytes=Files.readAllBytes(folder.resolve(producerFile));require(hash(producerBytes).equals(text(check,"nativeProducerOriginalSha256"))&&hash(producerBytes).equals(text(m.path("files"),producerFile)));var producer=json(producerBytes);require("samlscope-simplesamlphp-openssl-certificate-check-calibration-v1".equals(text(producer,"schema"))&&producer.path("controlsAdopted").isBoolean()&&!producer.path("controlsAdopted").asBoolean()&&producer.path("actualProductFinding").isBoolean()&&!producer.path("actualProductFinding").asBoolean()&&producer.path("counterfactualCalibrationOnly").asBoolean(false)&&producer.path("records").isArray()&&producer.path("checkerSourceSha256").equals(check.path("checkerSourceSha256"))&&producer.path("runId").equals(m.path("runId"))&&producer.path("targetMetadataSha256").equals(m.path("targetMetadataSha256")));JsonNode nativeRow=null;int found=0;for(var row:producer.path("records"))if(variant.equals(row.path("variant").asText())){nativeRow=row;found++;}require(found==1);for(var field:List.of("variant","requestId","requestSha256","fixtureSha256","certificateSha256","issuerCertificateSha256","nativeSignatureVerified","nativeSignatureMethod","errorCode","reason","selectedOperation"))require(nativeRow.path(field).equals(check.path(field)));if(revoked)require(nativeRow.path("crlSha256").equals(check.path("crlSha256")));require(nativeRow.path("signatureVerifiedAt").equals(check.path("diagnosticNativeSignatureVerifiedAt"))&&check.path("counterfactualCalibrationOnly").asBoolean(false));for(var phaseName:List.of("setup","failure")){var originalPhase=nativeRow.path(phaseName);var declared=check.path(phaseName);for(var field:List.of("command","startedAt","completedAt","exitCode"))require(originalPhase.path(field).equals(declared.path(field)));for(var stream:List.of("stdout","stderr"))require(originalPhase.path(stream).asText().equals(Files.readString(folder.resolve(text(declared,stream+"File")))));}
        var setupOut=Files.readString(folder.resolve(text(setup,"stdoutFile")));var failureError=Files.readString(folder.resolve(text(failure,"stderrFile")));require(setupOut.contains(setupCommand.get(4).asText()+": OK")&&failureError.contains(revoked?"error 23 at 0 depth lookup: certificate revoked":"error 3 at 0 depth lookup: unable to get certificate CRL"));if(!revoked){var policy=check.path("revocationPolicy");require(policy.equals(nativeRow.path("revocationPolicy"))&&policy.size()==4&&"native-curl-certificate-CDP/AIA".equals(text(policy,"lookupSource"))&&"UNAVAILABLE".equals(text(policy,"lookupOutcome"))&&policy.path("requireRevocationEvidence").isBoolean()&&policy.path("requireRevocationEvidence").asBoolean()&&"fail-closed".equals(text(policy,"failureMode")));require(check.path("network").size()==2&&nativeRow.path("network").size()==2);String prefix="http://samlscope-reference-suite:18481/samlscope-revocation/"+certificate.getSerialNumber().toString(16)+"/unavailable";for(int i=0;i<2;i++){var network=check.path("network").get(i);var nativeNetwork=nativeRow.path("network").get(i);String url=prefix+(i==0?".crl":".ocsp");require(url.equals(text(network,"url"))&&network.path("url").equals(nativeNetwork.path("url"))&&network.path("exitCode").asInt(-1)==7&&network.path("command").equals(json(("[\"/usr/bin/curl\",\"--noproxy\",\"*\",\"--connect-timeout\",\"1\",\"--max-time\",\"2\",\"--silent\",\"--show-error\",\""+url+"\"]").getBytes(StandardCharsets.UTF_8))));for(var field:List.of("command","startedAt","completedAt","exitCode"))require(network.path(field).equals(nativeNetwork.path(field)));require(!at(network,"startedAt").isBefore(at(setup,"completedAt"))&&!at(network,"completedAt").isAfter(at(failure,"startedAt")));for(var stream:List.of("stdout","stderr")){String name=text(network,stream+"File");require(!Path.of(name).isAbsolute()&&folder.resolve(name).normalize().startsWith(folder)&&!Files.isSymbolicLink(folder.resolve(name)));var raw=Files.readAllBytes(folder.resolve(name));require(hash(raw).equals(text(network,stream+"Sha256"))&&hash(raw).equals(text(m.path("files"),name))&&nativeNetwork.path(stream).asText().equals(new String(raw,StandardCharsets.UTF_8)));if(stream.equals("stderr"))require(new String(raw,StandardCharsets.UTF_8).contains("curl: (7)"));}}}
    }
    public Optional<CaseOutcome> evaluate(CaseContext c){if(!exists(c.runId()))return Optional.empty();try{return Optional.of(checked(c));}catch(Exception unavailable){return Optional.of(pending());}}
    private CaseOutcome checked(CaseContext c)throws Exception{
        require(c.targetRole()==com.samlscope.core.plan.TargetRole.IDP&&c.transcriptComplete());var folder=directory.resolve(c.runId());var manifest=raw(folder,"manifest.json");var m=json(manifest);
        require(SCHEMA.equals(text(m,"schema"))&&ADAPTER.equals(text(m,"adapter"))&&CAMPAIGN.equals(text(m,"campaignId"))&&c.runId().equals(text(m,"runId"))&&TARGET.equals(text(m,"targetEntityId")));
        for(var names=m.path("files").fieldNames();names.hasNext();)file(folder,m,names.next());require(hash(file(folder,m,"native-parser-command.php")).equals("abb80516e0fcc62d0768e142ddcfa7818bb8d8a533cdce0950441ee6d3a2543d")&&hash(file(folder,m,"native-readback-command.php")).equals("513ed34f387b7c034549bc3226d02f8c868a0c1ddc667dc19ce80218de815b1e"));String plan=text(m,"planId"),entity=text(m,"entityId");require(plan.matches("plan_[0-9A-HJKMNP-TV-Z]{26}")&&entity.equals(BASE+"/p/"+plan));var created=node(folder,m,"created.json");require(c.runId().equals(created.at("/run/id").asText())&&plan.equals(created.at("/run/planId").asText()));
        var targetRaw=metadata.apply(c.runId());require(Arrays.equals(targetRaw,file(folder,m,"target-metadata.xml"))&&hash(targetRaw).equals(text(m,"targetMetadataSha256")));var target=SecureXml.parse(targetRaw).getDocumentElement();require(TARGET.equals(target.getAttribute("entityID")));var dst=destination(target);var h=history(c,c.runId());
        var baseline=node(folder,m,"baseline.json");require("recorded".equals(text(baseline,"receipt"))&&baseline.path("protocolSubmissions").asInt(-1)==1&&baseline.path("credentialPosts").asInt(-1)==1&&baseline.path("outboundReferences").size()==1);var baseRequest=h.get(baseline.path("outboundReferences").get(0).asText());require(baseRequest!=null&&baseRequest.direction()==Direction.OUTBOUND&&"GET".equals(baseRequest.method()));var baseRaw=decoded(baseRequest);var baseQ=SecureXml.parse(baseRaw).getDocumentElement();var basePeer=fixture(file(folder,m,"baseline-fixture.xml"),entity);require(new RedirectSignatureVerifier().isValidForMessage(baseRequest.rawQuery(),spKeys(basePeer).getFirst(),baseRaw));var baseResponses=h.values().stream().filter(e->e.direction()==Direction.INBOUND&&baseQ.getAttribute("ID").equals(e.samlSummary().get("inResponseTo"))).toList();require(baseResponses.size()==1&&Boolean.TRUE.equals(baseResponses.getFirst().samlSummary().get("normalFlowAccepted")));var baseResponse=SecureXml.parse(decoded(baseResponses.getFirst())).getDocumentElement();require(children(baseResponse,"urn:oasis:names:tc:SAML:2.0:assertion","Assertion").size()==1&&children(baseResponse,"urn:oasis:names:tc:SAML:2.0:assertion","EncryptedAssertion").isEmpty());VerifiedResponseAssertion.read(baseResponse,TARGET,MetadataAlgorithmEvidence.signingKeys(target),basePeer,Optional.empty(),baseQ.getAttribute("ID"),MetadataSupersessionProbeTestCase.acs(basePeer,0).toString());
        var initial=state(c,folder,m,"initial","initial",null);var baselineBefore=state(c,folder,m,"baseline-before","configured",spKeys(basePeer));var baselineAfter=state(c,folder,m,"baseline-after","configured",spKeys(basePeer));require(baselineBefore.path("runtime").equals(initial.path("runtime"))&&baselineAfter.path("runtime").equals(initial.path("runtime"))&&baseRequest.timestamp().isAfter(at(baselineBefore,"recordedAt"))&&baseResponses.getFirst().timestamp().isBefore(at(baselineAfter,"recordedAt")));var baselineConversion=original(c,folder,m,"baseline-conversion","native-metadata-conversion");require(hash(file(folder,m,"baseline-fixture.xml")).equals(text(baselineConversion,"fixtureSha256")));var baselineParser=file(folder,m,"baseline-parser-output.json");require(hash(baselineParser).equals(text(baselineConversion,"parserOutputSha256"))&&json(baselineParser).equals(baselineConversion.path("parserOutput")));var baselineConfig=new java.io.ByteArrayOutputStream();baselineConfig.write(file(folder,m,"original-configuration.php"));baselineConfig.write("\n".getBytes(StandardCharsets.UTF_8));baselineConfig.write(baselineConversion.at("/parserOutput/php").asText().getBytes(StandardCharsets.UTF_8));baselineConfig.write("\n".getBytes(StandardCharsets.UTF_8));require(Arrays.equals(baselineConfig.toByteArray(),file(folder,m,"baseline-configuration.php")));var epochs=m.path("epochs");require(epochs.isArray()&&epochs.size()==5);var evidence=new ArrayList<EvidenceRef>();var seen=new LinkedHashSet<String>();int normal=0,invalid=0,violations=0;Instant last=at(baselineAfter,"recordedAt");
        for(var epoch:epochs){String v=text(epoch,"variant");require(MetadataCertificateRuntimeProbeTestCase.VARIANTS.contains(v)&&seen.add(v));var before=state(c,folder,m,v+"-before","configured",spKeys(SecureXml.parse(file(folder,m,v+"-fixture.xml")).getDocumentElement()));var after=state(c,folder,m,v+"-after","configured",spKeys(SecureXml.parse(file(folder,m,v+"-fixture.xml")).getDocumentElement()));require(before.path("runtime").equals(initial.path("runtime"))&&after.path("runtime").equals(initial.path("runtime"))&&at(before,"recordedAt").isAfter(last));last=at(after,"recordedAt");
            var peer=SecureXml.parse(file(folder,m,v+"-fixture.xml")).getDocumentElement();MetadataCertificateRuntimeEvidence.validatePrepared(peer,v,c.runId(),keys);require(entity.equals(peer.getAttribute("entityID")));var cert=spKeys(peer).getFirst();MetadataCertificateRuntimeEvidence.validateCondition(folder,v,peer,cert);
            var prepared=h.get(text(epoch,"preparedReference"));require(prepared!=null&&"MetadataPrepared".equals(prepared.samlSummary().get("type"))&&v.equals(prepared.samlSummary().get("variant"))&&"live".equals(prepared.samlSummary().get("feed"))&&Arrays.equals(decoded(prepared),file(folder,m,v+"-fixture.xml")));
            var converted=original(c,folder,m,v+"-conversion","native-metadata-conversion");var parser=file(folder,m,v+"-parser-output.json");require(hash(parser).equals(text(converted,"parserOutputSha256"))&&converted.path("parserOutput").equals(json(parser))&&hash(file(folder,m,v+"-fixture.xml")).equals(text(converted,"fixtureSha256"))&&entity.equals(converted.path("entityId").asText())&&converted.at("/parserOutput/validateAuthnRequest").asBoolean(false));
            var overlay=converted.at("/parserOutput/php").asText().getBytes(StandardCharsets.UTF_8);var expected=new java.io.ByteArrayOutputStream();expected.write(file(folder,m,"original-configuration.php"));expected.write("\n".getBytes(StandardCharsets.UTF_8));expected.write(overlay);expected.write("\n".getBytes(StandardCharsets.UTF_8));require(Arrays.equals(expected.toByteArray(),file(folder,m,v+"-configuration.php")));
            var exchanges=epoch.path("probes");require(exchanges.isArray()&&exchanges.size()==(v.equals("control")?2:1));for(var row:exchanges){String fixture=text(row,"fixture");require(fixture.equals(v+"-normal")||v.equals("control")&&fixture.equals("control-invalid-signature"));boolean bad=fixture.endsWith("invalid-signature");var req=h.get(text(row,"requestReference"));var rsp=h.get(text(row,"responseReference"));String action=ActionIds.derive(c.runId(),MetadataCertificateRuntimeProbeTestCase.CASE,"await-fixture-"+fixture,0);require(req!=null&&rsp!=null&&req.direction()==Direction.OUTBOUND&&"POST".equals(req.method())&&action.equals(req.correlationId())&&req.timestamp().isAfter(at(before,"recordedAt"))&&rsp.timestamp().isAfter(req.timestamp())&&rsp.timestamp().isBefore(at(after,"recordedAt")));require(h.values().stream().filter(e->e.direction()==Direction.OUTBOUND&&action.equals(e.correlationId())&&"AuthnRequest".equals(e.samlSummary().get("type"))).count()==1);var bytes=decoded(req);var q=SecureXml.parse(bytes).getDocumentElement();String id="_"+action;var correlated=h.values().stream().filter(e->e.direction()==Direction.INBOUND&&id.equals(e.samlSummary().get("inResponseTo"))).toList();if(bad)require(correlated.isEmpty());else if("POST".equals(rsp.method()))require(correlated.size()==1&&correlated.getFirst().id().equals(rsp.id()));else require(correlated.isEmpty());var at=Instant.parse(q.getAttribute("IssueInstant"));require(id.equals(q.getAttribute("ID"))&&!at.isAfter(req.timestamp()));var acs=MetadataSupersessionProbeTestCase.acs(peer,0).toString();var signer=keys.apply(c.runId(),v).orElseThrow();require(Arrays.equals(bytes,new SamlSignedRequestFactory().build(bad?SamlSignedRequestFactory.Fixture.BAD_SIGNATURE_VALUE:SamlSignedRequestFactory.Fixture.VALID,id,dst,entity,URI.create(acs),at,signer)));var verifier=new XmlSignatureVerifier();require(verifier.hasValidEnvelopedReferenceDigests(q)&&(bad?!verifier.hasValidEnvelopedSignature(q,cert):verifier.hasValidEnvelopedSignature(q,cert)));
                if(v.equals("certificate-revoked")){var crlElement=peer.getElementsByTagNameNS("urn:samlscope:test:certificate-revocation","CRL").item(0);var crl=(X509CRL)CertificateFactory.getInstance("X.509").generateCRL(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(crlElement.getTextContent())));require(!at.isBefore(crl.getThisUpdate().toInstant())&&at.isBefore(crl.getNextUpdate().toInstant()));}
                if(v.equals("certificate-revocation-unreachable"))for(var n:node(folder,m,"certificate-revocation-unreachable-network.json"))require(!at(n,"startedAt").isBefore(at(before,"nativeFinishedAt"))&&!at(n,"completedAt").isAfter(req.timestamp()));
                var delivery=original(c,folder,m,text(row,"nativeHttpOriginal"),"native-http-response");var actual=delivery.path("native");require(action.equals(text(delivery,"actionId"))&&req.id().equals(text(delivery,"requestReference"))&&rsp.id().equals(text(delivery,"responseReference"))&&id.equals(text(actual,"requestId"))&&hash(bytes).equals(text(actual,"requestSha256"))&&dst.toString().equals(text(actual,"requestUrl"))&&dst.toString().equals(text(actual,"responseUrl"))&&"POST".equals(text(actual,"method"))&&!at(actual,"startedAt").isBefore(req.timestamp())&&at(actual,"startedAt").isAfter(at(before,"recordedAt"))&&!at(actual,"finishedAt").isBefore(at(actual,"startedAt"))&&!at(actual,"finishedAt").isAfter(rsp.timestamp())&&at(actual,"finishedAt").isBefore(at(after,"recordedAt")));
                if(!bad&&"POST".equals(rsp.method())){require(rsp.direction()==Direction.INBOUND&&"POST".equals(rsp.method())&&acs.equals(rsp.url())&&id.equals(rsp.samlSummary().get("inResponseTo")));var response=SecureXml.parse(decoded(rsp)).getDocumentElement();VerifiedResponseAssertion.read(response,TARGET,MetadataAlgorithmEvidence.signingKeys(target),peer,keys.apply(c.runId(),v),id,acs);normal++;}
                else{require(rsp.direction()==Direction.INBOUND&&"BROWSER".equals(rsp.method())&&Integer.valueOf(500).equals(rsp.status())&&dst.toString().equals(rsp.url())&&("transcripts/"+c.runId()+"/"+rsp.id()+".body").equals(rsp.bodyRef()));var body=raw(directory.getParent(),rsp.bodyRef());require(body.length==rsp.bodyBytes()&&SimpleSamlPhpRegisteredSignerEvidence.nativeSignatureRejection(new String(body,StandardCharsets.UTF_8),entity));var record=original(c,folder,m,text(row,"nativeHttpOriginal"),"native-http-response");var n=record.path("native");require(action.equals(text(record,"actionId"))&&req.id().equals(text(record,"requestReference"))&&rsp.id().equals(text(record,"responseReference"))&&id.equals(text(n,"requestId"))&&hash(bytes).equals(text(n,"requestSha256"))&&hash(body).equals(text(n,"responseBodySha256"))&&n.path("responseBodyBytes").asLong(-1)==body.length&&n.path("responseStatus").asInt(-1)==500&&dst.toString().equals(text(n,"requestUrl"))&&dst.toString().equals(text(n,"responseUrl"))&&"POST".equals(text(n,"method"))&&!at(n,"startedAt").isBefore(req.timestamp())&&!at(n,"finishedAt").isBefore(at(n,"startedAt"))&&!at(n,"finishedAt").isAfter(rsp.timestamp()));if(bad)invalid++;else{require(Set.of("certificate-revoked","certificate-revocation-unreachable").contains(v)&&row.path("nativeCertificateCheckOriginal").isTextual());var check=original(c,folder,m,text(row,"nativeCertificateCheckOriginal"),"native-additional-certificate-check");validateAdditionalCheckCause(folder,m,check,row,n,bytes,cert,peer);violations++;}}
                evidence.add(new EvidenceRef("transcript",req.id()));evidence.add(new EvidenceRef("transcript",rsp.id()));
            }
        }
        require(normal+violations==5&&normal>=1&&invalid==1&&seen.equals(new LinkedHashSet<>(MetadataCertificateRuntimeProbeTestCase.VARIANTS)));var restored=state(c,folder,m,"restoration","restored",null);require(restored.path("restored").asBoolean(false)&&restored.path("runtime").equals(initial.path("runtime"))&&at(restored,"recordedAt").isAfter(last)&&Arrays.equals(file(folder,m,"original-configuration.php"),file(folder,m,"final-configuration.php")));var costs=node(folder,m,"operation-counts.json");int loginCount=1,writes=7,restoreWrites=1;require(costs.path("restored").asBoolean(false)&&costs.path("nativeConfigurationWrites").asInt()==writes&&costs.path("restorationWrites").asInt()==restoreWrites&&costs.path("initialBaselineSubmissions").asInt()==1&&costs.path("actualOutboxTargetAttempts").asInt()==6&&costs.path("protocolSubmissions").asInt()==7&&costs.path("credentialPosts").asInt()==loginCount&&costs.path("credentialPostAttempts").asInt()==loginCount&&costs.path("personOperations").asInt(-1)==0&&costs.path("productRestarts").asInt(-1)==0);evidence.add(new EvidenceRef(KIND,c.runId()+"/manifest.json#"+hash(manifest)));String reason=violations==0?"metadata.certificate.runtime-no-pkix-observed":"metadata.certificate.runtime-additional-revocation-check-observed";return new CaseOutcome(violations==0?Outcome.SATISFIED:Outcome.VIOLATED,null,reason,reason,evidence,Map.of("evidence_adapter",ADAPTER,"native_run_id",c.runId(),"native_certificate_conditions",seen,"native_extra_checks_source_closure","legacy-native-openssl-verify","user_login_count",loginCount));
    }
}
