package com.samlscope.runner.cases;
import com.fasterxml.jackson.databind.JsonNode;import com.samlscope.core.caseexec.CaseContext;import com.samlscope.core.evaluation.*;import com.samlscope.core.transcript.*;import com.samlscope.saml.crypto.*;import com.samlscope.saml.normal.SecureXml;import com.samlscope.store.JsonCodec;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.cert.X509Certificate;import java.time.Instant;import java.util.*;import java.util.function.Function;import org.w3c.dom.Element;
import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
/** Reference-only native UserPass/source proof; no assertion that ordinary remote users possess Docker/admin access. */
final class SimpleSamlPhpAuthenticationIdentityEvidence {
 static final String CASE="IIP-SSO01-ae-idp-01",SCHEMA="samlscope-simplesamlphp-authentication-identity-v1",REASON="browser.authentication-identity.native-unproven";
 private static final String TARGET="http://localhost:18380/idp",S="urn:oasis:names:tc:SAML:2.0:assertion",P="urn:oasis:names:tc:SAML:2.0:protocol",AUTH="ea23df120a13b50435b97c71e1aa5c5194fe619e3d2eeeb24ce9a09cb44c99ad",CONFIG="a1b218b29003289e01e4154a9d5d7cbffa33a3b9629057d0ae51d652d0393cf3",USER="samlscope-m0-user";
 private static final Map<String,String> PINS=Map.ofEntries(Map.entry("collector.py","d50b78ea63cf98a760ed8f3e4625e11964850a267153274e429aff277caf4654"),
Map.entry("helper-keyvalue_runtime_campaign.py","52ae423938a43026b38d720fe9cbde6681ba21d7511cf33faca6ab2366151f5e"),
Map.entry("helper-metadata_refresh_campaign.py","28fad4a9dc68068796c2b43c128bec1acf84a57c9662a935ee06c3bcbb50be88"),
Map.entry("helper-native_ui_privacy.py","944e9a5345e4c714740bdbf87d69cbb61015d0cd37b8ac61a7109a929851ab05"),
Map.entry("helper-signed_request_observation.py","2df41a96b2194577186351eb9a6eddf6588138c3ae16279163fd9c54c6f95485"),
Map.entry("helper-subject_confirmation_campaign.py","d4cc95685f333c774b84871829c1a93149ccd2a87dd1023fb6ddbb6df5a72c3c"),
Map.entry("native-assertion.php","b935848a17dcfdb4c113618d3460dd1aa1645118f75876dce90ea92d97d33003"),
Map.entry("native-attribute-limit.php","e3dbf076807713125373a0cf6ab2495e9181685dbd5d29b7344bc31a748f361f"),
Map.entry("native-auth-processing.php","e6d5023490fbc94dc1a743bb5105f1d093f4eec0a8c48fe030353029e7ea5c5d"),
Map.entry("native-auth-source.php","5e58ab08d8d03d6720b1bade592119e353fdf8ac1f96a97234575234e57a58d0"),
Map.entry("native-auth-state.php","59576819feb0d08c19ff34bdee6f239b8edc94e1806fc056ff83b69e6b39ec8a"),
Map.entry("native-configuration.php","53837359cd60433082d3968843605a864bab97f23be482447bcfef37e7f6946e"),
Map.entry("native-idp-saml2.php","ae55fc922431d29ca6e87654ae2071500a4c3d7185ed80a6fcc5b26eed12495d"),
Map.entry("native-idp.php","313760d280f557ffbba61fd4622fbf7e9892b21425d8d24d26d9f08eb9312888"),
Map.entry("native-language-adaptor.php","f74d170f691a90b5281e77dabfbb026db2ec4eae5ee57a6badf990544622a7ba"),
Map.entry("native-login-controller.php","56fd31e89b2272e56b08861fc748704a96d0772c3fc4635f11f54967463c8ed5"),
Map.entry("native-message.php","ab017ee6cf9fb66db1037e40ed50feff0b277b1a5d43fd8ca774a3d27ce355d2"),
Map.entry("native-parser-command.php","5008495fba0e65487a4849cf46f592c577215f96d5b4f3fd87321ebc6930edf9"),
Map.entry("native-parser.php","8620bb26fd41d2be29d2611883839a4cfde0b6c8458c274e2d40a002678fd93d"),
Map.entry("native-policy-command.php","a5801c78f58f96e114e9e76a7e87c3efdf5f59d936bb14787a4e96ff4a949a18"),
Map.entry("native-principal-command.php","757bfdfb3feff81a32985f37f2cbc5b81115596d5cc0c2bd9f6d10338744d219"),
Map.entry("native-producer-command.php","635799da14f5ab1827eaf3ace950e9777593de9464a51c55a53b0900dcf213f7"),
Map.entry("native-response.php","27d7f1d4a5ea73b22107b7615c230b156f3dcaa012e843f380d879f53826a64a"),
Map.entry("native-session-command.php","238bb8d1e9680f16072bdd0271f28a6a2bbb914c6c1f93cef35406db3d14fecb"),
Map.entry("native-session.php","66dc24f2ceacd6a1754fdba0aeda2adfc1eac4d42c3f3e16f915a2e5d382f435"),
Map.entry("native-state-command.php","f3bf3a3f462dd658794b6472cc6bafc1723c3e84beb0f285dbb20616072b3759"),
Map.entry("native-subject-confirmation-data.php","79ab1c7623b0fa5c0507c55541afdae4e533f35c5664049541c0500220fca048"),
Map.entry("native-subject-confirmation.php","40746d3785ee55fa4999d49cd19c32625e415d0a37e0f193508138485a5a6a0e"),
Map.entry("native-userpass-base.php","cb69bac6366c580fd3dd41dcdae37831119cecc8897b62d0b8d22efd129f2169"),
Map.entry("native-userpass.php","8465e71fabec88578369eaf780dfe86c6ab3f0f2cdf4b24eb52bf134918f9b48"),
Map.entry("native-verify-command.php","7a7452c1614a02501ed77e3d881d344dcb04f0d57f4423f4865e98edf1cadbc6"),
Map.entry("native-web-browser-sso.php","47ddeecace975b77645aa91a4b4551429dc60d02dc1b9baa6c633c30bf1e75f4"),
Map.entry("native-xml-signer.php","5845e28158c7641d5ce1e6b9205e8005b6d9c090e1888ea46416abb8fdf0018d"));
 private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final SamlDecryptionKeyProvider keys;
 SimpleSamlPhpAuthenticationIdentityEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,SamlDecryptionKeyProvider keys){this.directory=directory.toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.keys=Objects.requireNonNull(keys);}
 boolean exists(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
 Optional<CaseOutcome> evaluate(CaseContext context){if(!exists(context.runId()))return Optional.empty();String stage="native-authentication-identity-originals-unproven";try{
  require(context.transcriptComplete());Path folder=directory.resolve(context.runId());require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));var receipt=json(original(folder,"manifest.json"));var files=receipt.path("files");byte[] targetRaw=metadata.apply(context.runId());require(SCHEMA.equals(text(receipt,"schema"))&&CASE.equals(text(receipt,"caseId"))&&context.runId().equals(text(receipt,"runId"))&&"native-authentication-identity".equals(text(receipt,"campaignId"))&&TARGET.equals(text(receipt,"targetEntityId"))&&hash(targetRaw).equals(text(receipt,"targetMetadataSha256")));
  for(var pin:PINS.entrySet()){var source=checked(folder,files,pin.getKey());require(hash(source).equals(pin.getValue()));if(pin.getKey().startsWith("native-")&&pin.getKey().endsWith(".php")&&!pin.getKey().endsWith("-command.php"))require(Arrays.equals(source,checked(folder,files,pin.getKey().replace(".php","-after.php"))));}
  var identity=json(checked(folder,files,"identity-before.json"));require(identity.equals(json(checked(folder,files,"identity-after.json")))&&identity.path("running").asBoolean(false)&&"sha256:9ae050473c68ce13c5451839cb64257eaa17be3a4d2c9a3f87996bbe0cebb0aa".equals(text(identity,"imageId")));
  var created=json(checked(folder,files,"created.json")).path("run");require(context.runId().equals(text(created,"id")));String entity="http://localhost:18080/p/"+text(created,"planId");var plan=json(checked(folder,files,"plan.json")).at("/plan/plan");require("browser_sso_idp".equals(text(plan,"profile"))&&text(created,"planId").equals(text(plan,"id")));
  var baseline=new HashMap<String,byte[]>();var restoration=json(checked(folder,files,"restoration.json"));for(String label:List.of("remote","hosted","override")){byte[] old=checked(folder,files,label+"-original.php");baseline.put(label,old);require(Arrays.equals(old,checked(folder,files,label+"-final.php"))&&restoration.path(label).path("restored").asBoolean(false)&&hash(old).equals(text(restoration.path(label),"original_sha256"))&&hash(old).equals(text(restoration.path(label),"final_sha256")));}
  var target=SecureXml.parse(targetRaw).getDocumentElement();require(TARGET.equals(target.getAttribute("entityID")));var signing=MetadataAlgorithmEvidence.signingKeys(target);require(!signing.isEmpty());var policies=new HashMap<String,JsonNode>();var fixtureKeys=new HashMap<String,List<X509Certificate>>();
  for(String epoch:List.of("control","passive")){String fixtureName=epoch.equals("control")?"control":"baseline";byte[] fixture=checked(folder,files,fixtureName+".fixture.xml");var fx=SecureXml.parse(fixture).getDocumentElement();require(entity.equals(fx.getAttribute("entityID")));var pub=MetadataAlgorithmEvidence.signingKeys(fx);require(!pub.isEmpty()&&signed(fx,pub));fixtureKeys.put(epoch,pub);var parser=json(checked(folder,files,fixtureName+".parser.stdout"));require(json(checked(folder,files,fixtureName+".parser-return.json")).path("returncode").asInt(-1)==0);byte[] remote=(new String(baseline.get("remote"),StandardCharsets.UTF_8)+"\n"+text(parser,"php")+"\n").getBytes(StandardCharsets.UTF_8);
   JsonNode before=json(checked(folder,files,epoch+"-before.policy.json"));require(before.equals(json(checked(folder,files,epoch+"-after.policy.json"))));validatePolicy(before,entity);policies.put(epoch,before);for(String phase:List.of("before","after"))for(String label:baseline.keySet())require(Arrays.equals(checked(folder,files,epoch+"-"+phase+"."+label+".php"),label.equals("remote")?remote:baseline.get(label)));
  }
  var nativePrincipal=json(checked(folder,files,"native-principal.json"));require("exampleauth:UserPass".equals(text(nativePrincipal,"class"))&&AUTH.equals(text(nativePrincipal,"sourceSha256"))&&USER.equals(text(nativePrincipal,"authenticatedPrincipal"))&&!nativePrincipal.path("credentialsPersisted").asBoolean(true)&&nativePrincipal.path("users").size()==1&&USER.equals(text(nativePrincipal.path("users").get(0),"principal"))&&nativePrincipal.path("authenticatedAttributes").equals(nativePrincipal.path("users").get(0).path("attributes"))&&nativePrincipal.at("/authenticatedAttributes/uid").size()==1&&USER.equals(nativePrincipal.at("/authenticatedAttributes/uid/0").asText()));
  var entries=new HashMap<String,TranscriptEntry>();for(var e:context.transcript().list(context.runId()))require(context.runId().equals(e.runId())&&entries.put(e.id(),e)==null);var positive=entry(entries,receipt,"positiveRequestReference",Direction.OUTBOUND);var positiveResponse=entry(entries,receipt,"positiveResponseReference",Direction.INBOUND);var negative=entry(entries,receipt,"negativeRequestReference",Direction.OUTBOUND);var error=entry(entries,receipt,"errorRequestReference",Direction.OUTBOUND);var errorResponse=entry(entries,receipt,"errorResponseReference",Direction.INBOUND);
  stage="native-authentication-identity-wire-unproven";var normalRequest=SecureXml.parse(content.readDecodedSaml(positive)).getDocumentElement();var passiveRequest=SecureXml.parse(content.readDecodedSaml(error)).getDocumentElement();require(signed(normalRequest,fixtureKeys.get("control"))&&!Boolean.parseBoolean(normalRequest.getAttribute("ForceAuthn"))&&!Boolean.parseBoolean(normalRequest.getAttribute("IsPassive"))&&entity.equals(issuer(normalRequest))&&signed(passiveRequest,fixtureKeys.get("passive"))&&"true".equals(passiveRequest.getAttribute("ForceAuthn"))&&"true".equals(passiveRequest.getAttribute("IsPassive"))&&entity.equals(issuer(passiveRequest))&&"force-authn-passive".equals(error.samlSummary().get("fixture_id"))&&"IIP-IDP06-c-idp-01".equals(error.samlSummary().get("scenario_case_id")));
  var negativeXml=SecureXml.parse(content.readDecodedSaml(negative)).getDocumentElement();require(!signed(negativeXml,fixtureKeys.get("control"))&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(negativeXml)&&MetadataProbeCorrelation.signatureControl(negative));var badHttp=http(folder,files,negativeXml.getAttribute("ID"));require(badHttp.path("response_status").asInt()==500&&"signature-value-invalid".equals(text(badHttp,"native_signature_rejection"))&&new String(checked(folder,files,"native-http-originals."+negativeXml.getAttribute("ID")+".html"),StandardCharsets.UTF_8).contains("NOTVALIDCERTSIGNATURE"));
  byte[] normalRaw=content.readDecodedSaml(positiveResponse),errorRaw=content.readDecodedSaml(errorResponse);var normal=assertion(normalRaw,normalRequest,signing,context.runId());require(authenticated(normal)&&noIdentity(errorRaw,passiveRequest,signing));require(positive.timestamp().isBefore(positiveResponse.timestamp())&&error.timestamp().isBefore(errorResponse.timestamp()));
  var challenge=http(folder,files,normalRequest.getAttribute("ID"));transport(folder,files,challenge,positive,content.readDecodedSaml(positive));transport(folder,files,http(folder,files,passiveRequest.getAttribute("ID")),error,content.readDecodedSaml(error));String html=new String(checked(folder,files,"native-http-originals."+normalRequest.getAttribute("ID")+".html"),StandardCharsets.UTF_8);require(challenge.path("response_status").asInt()==200&&text(challenge,"response_url").endsWith("/simplesaml/module.php/core/loginuserpass")&&html.contains("name=\"username\"")&&html.contains("name=\"password\"")&&html.contains("name=\"AuthState\"")&&!html.matches("(?s).*_[0-9a-f]{40}.*"));
  var observations=json(checked(folder,files,"native-state-observations.json")).path("observations");require(observations.size()==1);var state=observations.get(0);require(!state.path("stateHandlePersisted").asBoolean(true)&&normalRequest.getAttribute("ID").equals(text(state.path("state"),"requestId"))&&normalRequest.getAttribute("AssertionConsumerServiceURL").equals(text(state.path("state"),"consumerURL"))&&state.at("/state/idpMetadata").equals(policies.get("control").path("hosted"))&&state.at("/state/spMetadata").equals(policies.get("control").path("peer"))&&!state.at("/state/forceAuthn").asBoolean(true)&&!state.at("/state/isPassive").asBoolean(true));
  var sessions=json(checked(folder,files,"native-session-observations.json")).path("observations");require(sessions.size()==1);var session=sessions.get(0);require("native-login-challenge".equals(text(session,"kind"))&&!session.at("/session/authenticated").asBoolean(true)&&session.path("credentialPostsSoFar").asInt(-1)==0&&!session.at("/session/credentialsPersisted").asBoolean(true));var actions=json(checked(folder,files,"native-credential-actions.json")).path("records");require(actions.size()==1&&"credential-post".equals(text(actions.get(0),"kind"))&&!actions.get(0).path("valuesPersisted").asBoolean(true)&&Instant.parse(text(session,"at")).isBefore(Instant.parse(text(actions.get(0),"at"))));
  var fresh=json(checked(folder,files,"fresh-passive-client.json"));require(fresh.path("cookieCount").asInt(-1)==0&&fresh.path("credentialPosts").asInt(-1)==0&&!fresh.at("/session/authenticated").asBoolean(true)&&!fresh.at("/session/credentialsPersisted").asBoolean(true));
  var checks=json(checked(folder,files,"native-signature-selfchecks.json")).path("records");require(checks.size()==3);var requestIds=Set.of(normalRequest.getAttribute("ID"),passiveRequest.getAttribute("ID"),negativeXml.getAttribute("ID"));var seen=new HashSet<String>();for(var c:checks){String id=text(c,"requestId");require(requestIds.contains(id)&&seen.add(id)&&entity.equals(text(c,"spEntityId"))&&!c.path("privateMaterialPersisted").asBoolean(true)&&hash(content.readDecodedSaml(id.equals(normalRequest.getAttribute("ID"))?positive:id.equals(passiveRequest.getAttribute("ID"))?error:negative)).equals(text(c,"requestSha256"))&&c.path("valid").asBoolean(false)==!id.equals(negativeXml.getAttribute("ID")));}
  stage="native-authentication-identity-controls-unproven";require(!authenticated(assertion(checked(folder,files,"wrong-principal.xml"),normalRequest,signing,context.runId()))&&!noIdentity(checked(folder,files,"error-with-assertion.xml"),passiveRequest,signing));var completion=json(checked(folder,files,"read-only-producer-completion.json"));require(completion.path("nativeRuntimeUnchanged").asBoolean(false)&&completion.path("nativeSignedProducerInvocations").asInt()==2&&completion.path("protocolSends").asInt(-1)==0&&completion.path("productConfigurationWrites").asInt(-1)==0&&hash(checked(folder,files,"operation-counts.json")).equals(text(completion,"originalCountsSha256")));var counts=json(checked(folder,files,"operation-counts.json"));require(counts.path("protocolOperationsAttempted").asInt()==3&&counts.path("credentialPosts").asInt()==1&&counts.path("nativeParserInvocations").asInt()==2&&counts.path("nativeSignedProducerInvocations").asInt(-1)==0&&counts.path("productRestarts").asInt(-1)==0&&counts.path("humanOperations").asInt(-1)==0&&counts.path("restored").asBoolean(false));
  return Optional.of(new CaseOutcome(Outcome.SATISFIED,null,"browser.authentication-identity.native-observed","browser.authentication-identity.native-observed",List.of(positive,positiveResponse,negative,error,errorResponse).stream().map(e->new EvidenceRef("transcript",e.id())).toList(),Map.of("native_evidence_adapter","simplesamlphp-authentication-identity","ambient_authentication_excluded",true,"normal_native_challenge",true,"native_identity_error_no_assertion",true,"configuration_restored",true,"reference_adapter_requires_local_docker_admin",true)));
 }catch(Exception absent){return Optional.of(CaseOutcome.notVerified(stage,REASON));}}
 private static void validatePolicy(JsonNode p,String entity){require(TARGET.equals(text(p,"targetEntityId"))&&entity.equals(text(p,"spEntityId"))&&"example-userpass".equals(text(p.path("hosted"),"auth"))&&"exampleauth:UserPass".equals(text(p.path("authsource"),"class"))&&p.at("/authsource/authproc").isNull()&&p.at("/hosted/authproc").isMissingNode()&&p.at("/peer/authproc").isMissingNode()&&!p.path("proxyAuthnContext").asBoolean(true)&&AUTH.equals(text(p,"authsourceSha256"))&&CONFIG.equals(text(p,"configSha256"))&&p.path("globalAuthproc").equals(new JsonCodec().mapper().valueToTree(Map.of("30","core:LanguageAdaptor","50","core:AttributeLimit","99","core:LanguageAdaptor")))&&p.at("/peer/validate.authnrequest").asBoolean(false));}
 private Element assertion(byte[] bytes,Element rq,List<X509Certificate> signing,String run){var response=response(bytes,rq,signing);require(success(response));var a=new ArrayList<>(children(response,S,"Assertion"));for(var encrypted:children(response,S,"EncryptedAssertion"))a.add(new SamlXmlDecrypter().decrypt(encrypted,keys.keyFor(run).orElseThrow()));require(a.size()==1&&(signed(response,signing)||signed(a.getFirst(),signing)));var authn=children(a.getFirst(),S,"AuthnStatement");require(authn.size()==1&&!authn.getFirst().getAttribute("AuthnInstant").isBlank());var audience=a.getFirst().getElementsByTagNameNS(S,"Audience");require(audience.getLength()==1&&issuer(rq).equals(audience.item(0).getTextContent()));var data=a.getFirst().getElementsByTagNameNS(S,"SubjectConfirmationData");require(data.getLength()==1&&rq.getAttribute("ID").equals(((Element)data.item(0)).getAttribute("InResponseTo"))&&rq.getAttribute("AssertionConsumerServiceURL").equals(((Element)data.item(0)).getAttribute("Recipient")));return a.getFirst();}
 private static boolean authenticated(Element a){var values=new ArrayList<Element>();var all=a.getElementsByTagNameNS(S,"Attribute");for(int i=0;i<all.getLength();i++)if("uid".equals(((Element)all.item(i)).getAttribute("Name")))values.add((Element)all.item(i));return values.size()==1&&children(values.getFirst(),S,"AttributeValue").size()==1&&USER.equals(children(values.getFirst(),S,"AttributeValue").getFirst().getTextContent());}
 private static boolean noIdentity(byte[] bytes,Element rq,List<X509Certificate> signing){var response=response(bytes,rq,signing);return signed(response,signing)&&!success(response)&&children(response,S,"Assertion").isEmpty()&&children(response,S,"EncryptedAssertion").isEmpty();}
 private static Element response(byte[] bytes,Element rq,List<X509Certificate> signing){var r=SecureXml.parse(bytes).getDocumentElement();require(P.equals(r.getNamespaceURI())&&"Response".equals(r.getLocalName())&&rq.getAttribute("ID").equals(r.getAttribute("InResponseTo"))&&rq.getAttribute("AssertionConsumerServiceURL").equals(r.getAttribute("Destination"))&&TARGET.equals(issuer(r)));return r;}
 private static boolean success(Element e){var s=children(e,P,"Status");require(s.size()==1);var c=children(s.getFirst(),P,"StatusCode");require(c.size()==1);return "urn:oasis:names:tc:SAML:2.0:status:Success".equals(c.getFirst().getAttribute("Value"));}
 private static void transport(Path folder,JsonNode files,JsonNode h,TranscriptEntry e,byte[] expected)throws Exception{byte[] xml=checked(folder,files,"native-http-originals."+text(h,"request_id")+".request.xml");require(Arrays.equals(xml,expected)&&hash(xml).equals(text(h,"request_sha256"))&&e.decodedSamlBytes()==xml.length&&"POST".equals(e.method())&&e.url().toString().equals(text(h,"request_url")));byte[] body=checked(folder,files,"native-http-originals."+text(h,"request_id")+".request.body");require(hash(body).equals(text(h,"request_body_sha256")));var fields=new HashMap<String,String>();for(String part:new String(body,StandardCharsets.UTF_8).split("&")){var pair=part.split("=",2);require(pair.length==2&&fields.put(java.net.URLDecoder.decode(pair[0],StandardCharsets.UTF_8),java.net.URLDecoder.decode(pair[1],StandardCharsets.UTF_8))==null);}require(fields.keySet().stream().allMatch(Set.of("SAMLRequest","RelayState")::contains)&&Arrays.equals(expected,Base64.getDecoder().decode(fields.get("SAMLRequest"))));}
 private static JsonNode http(Path folder,JsonNode files,String id)throws Exception{var rows=new ArrayList<JsonNode>();for(var v:json(checked(folder,files,"native-http-observations.json")).path("records"))if(id.equals(text(v,"request_id")))rows.add(v);require(rows.size()==1);return rows.getFirst();}
 private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,JsonNode r,String f,Direction d){var e=entries.get(text(r,f));require(e!=null&&e.direction()==d);return e;}
 private static String issuer(Element e){var x=children(e,S,"Issuer");require(x.size()==1);return x.getFirst().getTextContent();}
 private static boolean signed(Element e,List<X509Certificate> keys){var v=new XmlSignatureVerifier();return v.hasValidEnvelopedReferenceDigests(e)&&keys.stream().anyMatch(k->v.hasValidEnvelopedSignature(e,k));}
 private static byte[] original(Path folder,String name)throws Exception{require(name.matches("[A-Za-z0-9._-]+")&&!name.equals(".")&&!name.equals(".."));var p=folder.resolve(name);for(var a=p;a!=null;a=a.getParent())require(!Files.isSymbolicLink(a));require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)<4194304);return Files.readAllBytes(p);}
 private static byte[] checked(Path p,JsonNode files,String name)throws Exception{var b=original(p,name);require(hash(b).equals(files.path(name).asText()));return b;}
 private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}private static String text(JsonNode n,String f){require(n.path(f).isTextual()&&!n.path(f).asText().isBlank());return n.path(f).asText();}private static String hash(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}private static void require(boolean b){if(!b)throw new IllegalArgumentException("Native identity proof incomplete");}
}
