package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.util.*;
import java.util.function.*;
import org.w3c.dom.Element;
import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;

/** Retained native expiry, scoped to the original metadata, native seconds clock and actual POSTs. */
final class SimpleSamlPhpMetadataValidityEvidence {
    static final String SCHEMA="samlscope-simplesamlphp-metadata-validity-v1", ADAPTER="simplesamlphp-native-filesystem-validity-v1";
    static final List<String> VARIANTS=List.of("live-validity-root","live-validity-parent","live-validity-child");
    private static final String MD="urn:oasis:names:tc:SAML:2.0:metadata", P="urn:oasis:names:tc:SAML:2.0:protocol", S="urn:oasis:names:tc:SAML:2.0:assertion", SUCCESS="urn:oasis:names:tc:SAML:2.0:status:Success";
    private static final Map<String,String> PINS=Map.of(
        "native-parser.php","8620bb26fd41d2be29d2611883839a4cfde0b6c8458c274e2d40a002678fd93d",
        "native-handler.php","43a0e730d624c5a937f800c4e7e045ff3625eeb0738d81a4ab1dac96f82fe040",
        "native-source.php","48fe4682d980e62416c751b7a39406ebf9664bf539e6a1557e7f54df770398c6",
        "native-idp.php","ae55fc922431d29ca6e87654ae2071500a4c3d7185ed80a6fcc5b26eed12495d",
        "native-parser-command.php","0964fd7683ba2400f48f6ab2d726e235173a3d8471a26a052f8b6c8fbb3a1db2",
        "native-readback-command.php","eea36c2522e5470e0cc4b0c156dee7c946c4907c04060e821670eefb964a490d");
    private final Path directory; private final TranscriptContentReader content;
    private final Function<String,byte[]> targetMetadata;
    private final BiFunction<String,String,Optional<PlanCredentials>> keys;
    SimpleSamlPhpMetadataValidityEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> targetMetadata,BiFunction<String,String,Optional<PlanCredentials>> keys) {
        this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.targetMetadata=Objects.requireNonNull(targetMetadata);this.keys=Objects.requireNonNull(keys);
    }
    boolean exists(String run) {return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
    Optional<CaseOutcome> evaluate(CaseContext context) {
        if(!exists(context.runId()))return Optional.empty();String stage="native-validity-originals-unproven";
        try {
            require(context.targetRole()==TargetRole.IDP&&context.transcriptComplete());Path folder=directory.resolve(context.runId());safe(folder);require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
            byte[] receiptRaw=original(folder,"manifest.json");var receipt=json(receiptRaw);byte[] targetRaw=targetMetadata.apply(context.runId());var target=SecureXml.parse(targetRaw).getDocumentElement();
            require(SCHEMA.equals(text(receipt,"schema"))&&ADAPTER.equals(text(receipt,"adapter"))&&context.runId().equals(text(receipt,"runId"))&&"native-metadata-validity".equals(text(receipt,"campaignId"))&&"IIP-MD05-ar-idp-01".equals(text(receipt,"caseId"))&&hash(targetRaw).equals(text(receipt,"targetMetadataSha256"))&&target.getAttribute("entityID").equals(text(receipt,"targetEntityId")));
            var files=receipt.path("originals");require(files.isObject()&&!files.isEmpty());var expected=new HashSet<String>();files.fieldNames().forEachRemaining(expected::add);
            try(var listing=Files.list(folder)){require(listing.map(p->p.getFileName().toString()).filter(s->!s.equals("manifest.json")).collect(java.util.stream.Collectors.toSet()).equals(expected));}
            for(var it=files.fields();it.hasNext();){var row=it.next();require(hash(original(folder,row.getKey())).equals(row.getValue().asText()));}
            for(var pin:PINS.entrySet()){var source=original(folder,pin.getKey());require(hash(source).equals(pin.getValue()));if(!pin.getKey().endsWith("-command.php"))require(Arrays.equals(source,original(folder,"final-"+pin.getKey())));}
            require(runtime(folder,"start").equals(runtime(folder,"end")));
            var created=json(original(folder,"created.json")).path("run");require(context.runId().equals(text(created,"id")));String peer="http://localhost:18080/p/"+text(created,"planId");require(peer.equals(text(receipt,"entityId")));
            var plan=json(original(folder,"plan.json")).at("/plan/plan");require("metadata_idp".equals(text(plan,"profile"))&&text(created,"planId").equals(text(plan,"id")));
            byte[] initial=original(folder,"original-configuration.php");require(Arrays.equals(initial,original(folder,"final-configuration.php"))&&!new String(initial,StandardCharsets.UTF_8).contains("?>")&&!new String(initial,StandardCharsets.UTF_8).contains(peer));
            var restoration=json(original(folder,"restoration.json"));require(restoration.path("restored").asBoolean(false)&&hash(initial).equals(text(restoration,"original_sha256"))&&hash(initial).equals(text(restoration,"final_sha256")));
            var entries=new LinkedHashMap<String,TranscriptEntry>();var ids=new HashSet<String>();for(var e:context.transcript().list(context.runId())){require(sameRunOriginal(context.runId(),e)&&entries.put(e.id(),e)==null);if(e.direction()==Direction.OUTBOUND&&"AuthnRequest".equals(e.samlSummary().get("type")))require(ids.add(String.valueOf(e.samlSummary().get("id"))));}
            var signing=MetadataAlgorithmEvidence.signingKeys(target);require(!signing.isEmpty());var selected=new HashSet<String>();var evidence=new LinkedHashSet<EvidenceRef>();var rows=receipt.path("observations");require(rows.isArray()&&rows.size()==3);var seen=new HashSet<String>();int rejected=0,violations=0;Element firstSp=null;TranscriptEntry firstNormalRequest=null;
            stage="native-validity-retained-expiry-unproven";
            for(var row:rows){String variant=text(row,"variant");require(VARIANTS.contains(variant)&&seen.add(variant));byte[] fixture=original(folder,variant+"-fixture.xml");var root=SecureXml.parse(fixture).getDocumentElement();var sp=entity(root,peer);var expiry=effectiveExpiry(root,variant,peer);var spSigning=roleSigningKeys(sp);require(!spSigning.isEmpty()&&signed(root,spSigning));
                var parser=json(original(folder,variant+"-parser-output.json"));require(peer.equals(text(parser,"entityId"))&&parser.path("expire").isIntegralNumber()&&parser.path("expire").asLong()==expiry.getEpochSecond()&&parser.path("validateAuthnRequest").asBoolean(false));byte[] configured=(new String(initial,StandardCharsets.UTF_8)+"\n"+text(parser,"php")+"\n").getBytes(StandardCharsets.UTF_8);
                var phaseNames=List.of("before","before-after-send","after-before-send","after");var phases=new ArrayList<JsonNode>();
                for(String phase:phaseNames){require(Arrays.equals(configured,original(folder,variant+"-"+phase+"-configuration.php")));var nativeState=json(original(folder,variant+"-"+phase+"-native.json"));require(peer.equals(text(nativeState,"entityId"))&&hash(configured).equals(text(nativeState,"configurationSha256"))&&nativeState.path("metadataSources").equals(json("[{\"type\":\"flatfile\"}]".getBytes(StandardCharsets.UTF_8))));var flat=nativeState.path("flatfileMetadata");require(flat.isObject()&&flat.path("expire").asLong(-1)==expiry.getEpochSecond()&&peer.equals(text(flat,"entityid"))&&flat.path("validate.authnrequest").asBoolean(false));nativeKeys(flat,spSigning);require(nativeState.path("nativeTimeBefore").isIntegralNumber()&&nativeState.path("nativeTimeAfter").isIntegralNumber()&&nativeState.path("nativeTimeAfter").asLong()>=nativeState.path("nativeTimeBefore").asLong());clock(folder,variant+"-"+phase,nativeState);phases.add(nativeState);}
                require(phases.get(0).path("nativeTimeAfter").asLong()<expiry.getEpochSecond()&&phases.get(1).path("nativeTimeAfter").asLong()<expiry.getEpochSecond()&&phases.get(2).path("nativeTimeBefore").asLong()>expiry.getEpochSecond()&&phases.get(3).path("nativeTimeBefore").asLong()>expiry.getEpochSecond());
                require(phases.get(0).path("nativeTimeAfter").asLong()<=phases.get(1).path("nativeTimeBefore").asLong()&&phases.get(1).path("nativeTimeAfter").asLong()<phases.get(2).path("nativeTimeBefore").asLong()&&phases.get(2).path("nativeTimeAfter").asLong()<=phases.get(3).path("nativeTimeBefore").asLong());
                for(var phase:phases.subList(0,2)){require(phase.path("resolutionError").isNull()&&phase.path("resolvedMetadata").isObject());var resolved=((com.fasterxml.jackson.databind.node.ObjectNode)phase.path("resolvedMetadata")).deepCopy();require(peer.equals(text(resolved,"metadata-index")));resolved.remove("metadata-index");require(resolved.equals(phase.path("flatfileMetadata")));}
                var before=row.path("before");var after=row.path("after");var rq=request(entries,before,selected,variant,false);var afterRq=request(entries,after,selected,variant,false);var rqXml=validRequest(rq,sp,target,spSigning,true);var afterXml=validRequest(afterRq,sp,target,spSigning,true);require(rq.timestamp().isBefore(afterRq.timestamp()));
                var prepared=prepared(entries,fixture,variant,rq);var afterPrepared=prepared(entries,original(folder,variant+"-after-unconsumed-suite-prepared.xml"),variant,afterRq);var later=SecureXml.parse(content.readDecodedSaml(afterPrepared)).getDocumentElement();require(effectiveExpiry(later,variant,peer).isAfter(afterRq.timestamp())&&signed(later,roleSigningKeys(entity(later,peer)))&&Arrays.equals(fixture,original(folder,variant+"-before-suite-prepared.xml")));require(prepared.timestamp().isBefore(rq.timestamp())&&rq.timestamp().isBefore(afterPrepared.timestamp()));
                var reply=response(entries,before,selected,rq);success(context,variant,reply,rqXml,sp,target,signing);withinEpoch(folder,variant+"-before",variant+"-before-after-send",rq,reply,phases.get(0),phases.get(1));http(folder,before,rq,null,false);httpWindow(folder,before,variant+"-before",variant+"-before-after-send");evidence.add(new EvidenceRef("transcript",reply.id()));
                withinEpoch(folder,variant+"-after-before-send",variant+"-after",afterRq,null,phases.get(2),phases.get(3));
                if(after.path("responseReference").isTextual()&&!after.path("responseReference").asText().isBlank()){var late=response(entries,after,selected,afterRq);success(context,variant,late,afterXml,sp,target,signing);require(phases.get(2).path("resolvedMetadata").isObject()&&phases.get(3).path("resolvedMetadata").isObject());withinEpoch(folder,variant+"-after-before-send",variant+"-after",afterRq,late,phases.get(2),phases.get(3));http(folder,after,afterRq,null,false);require(after.path("nativeHttp").get(0).path("samlResponseFormPresent").asBoolean(false)&&after.path("nativeHttp").get(0).path("exactResponseUrl").asBoolean(false)&&afterRq.url().equals(text(after.path("nativeHttp").get(0),"responseUrl")));evidence.add(new EvidenceRef("transcript",late.id()));violations++;}
                else {require(noResponse(entries,afterXml.getAttribute("ID")));for(var phase:phases.subList(2,4)){require(phase.path("resolvedMetadata").isNull()&&"Exception".equals(text(phase.path("resolutionError"),"class"))&&expired(text(phase.path("resolutionError"),"message"),peer));}http(folder,after,afterRq,peer,true);rejected++;}
                httpWindow(folder,after,variant+"-after-before-send",variant+"-after");for(var e:List.of(prepared,afterPrepared,rq,afterRq))evidence.add(new EvidenceRef("transcript",e.id()));if(variant.equals("live-validity-root")){firstSp=sp;firstNormalRequest=rq;}
            }
            require(seen.equals(Set.copyOf(VARIANTS))&&firstSp!=null);stage="native-validity-signature-control-unproven";var negative=receipt.path("signatureControl");var invalid=request(entries,negative,selected,"live-validity-root",true);validRequest(invalid,firstSp,target,roleSigningKeys(firstSp),false);require(noResponse(entries,String.valueOf(invalid.samlSummary().get("id"))));http(folder,negative,invalid,null,true);require(firstNormalRequest!=null&&invalid.timestamp().isBefore(firstNormalRequest.timestamp())&&Instant.parse(text(negative.path("nativeHttp").get(0),"finishedAt")).isBefore(firstNormalRequest.timestamp()));withinEpoch(folder,"live-validity-root-before","live-validity-root-before-after-send",invalid,null,null,null);httpWindow(folder,negative,"live-validity-root-before","live-validity-root-before-after-send");evidence.add(new EvidenceRef("transcript",invalid.id()));
            var counts=json(original(folder,"operation-counts.json"));require(counts.path("restored").asBoolean(false)&&counts.path("productConfigurationWrites").asInt(-1)==4&&counts.path("configurationApplyWrites").asInt(-1)==3&&counts.path("restorationWrites").asInt(-1)==1&&counts.path("protocolSubmissions").asInt(-1)>=7&&counts.path("credentialPosts").asInt(-1)>=1&&counts.path("sharedAuthenticatedClients").asInt(-1)==1&&counts.path("productRestarts").asInt(-1)==0&&counts.path("personOperations").asInt(-1)==0);
            String reason=violations>0?"metadata.validity.expired-use-observed":"metadata.validity.expiration-observed";evidence.add(new EvidenceRef("native-metadata-validity-evidence",context.runId()+"/manifest.json#"+hash(receiptRaw)));
            return Optional.of(new CaseOutcome(violations>0?Outcome.VIOLATED:Outcome.SATISFIED,null,reason,reason,List.copyOf(evidence),Map.of("evidence_adapter",ADAPTER,"run_id",context.runId(),"native_expiry_clock","product-time-seconds","expiry_fraction_preserved_in_source",true,"required_variants",VARIANTS,"before_expiry_use",3,"after_expiry_rejections",rejected,"after_expiry_counterexamples",violations,"restored",true)));
        }catch(Exception unproven){return Optional.of(new CaseOutcome(Outcome.NOT_VERIFIED,"native_metadata_validity_unproven","metadata.validity.native-evidence-incomplete","metadata.validity.native-evidence-incomplete",List.of(),Map.of("evidence_stage",stage)));}
    }
    static boolean sameRunOriginal(String run,TranscriptEntry entry){return run.equals(entry.runId())&&(entry.decodedSamlRef()==null||("transcripts/"+run+"/"+entry.id()+".saml.xml").equals(entry.decodedSamlRef()));}
    private TranscriptEntry request(Map<String,TranscriptEntry> entries,JsonNode row,Set<String> used,String variant,boolean invalid){var e=entries.get(text(row,"requestReference"));require(e!=null&&used.add(e.id())&&e.direction()==Direction.OUTBOUND&&"POST".equals(e.method())&&"AuthnRequest".equals(e.samlSummary().get("type"))&&"metadata-polling".equals(e.samlSummary().get("campaign"))&&variant.equals(e.samlSummary().get("variant"))&&MetadataProbeCorrelation.signatureControl(e)==invalid&&row.path("invalidSignature").asBoolean(false)==invalid);return e;}
    private TranscriptEntry prepared(Map<String,TranscriptEntry> entries,byte[] bytes,String variant,TranscriptEntry rq)throws Exception {var found=new ArrayList<TranscriptEntry>();for(var e:entries.values())if(e.direction()==Direction.OUTBOUND&&"MetadataPrepared".equals(e.samlSummary().get("type"))&&variant.equals(e.samlSummary().get("variant"))&&Arrays.equals(bytes,content.readDecodedSaml(e)))found.add(e);require(found.size()==1);var e=found.getFirst();var fetch=entries.get(String.valueOf(e.samlSummary().get("fetchTranscriptId")));require(fetch!=null&&fetch.direction()==Direction.INBOUND&&"MetadataFetch".equals(fetch.samlSummary().get("type"))&&variant.equals(fetch.samlSummary().get("variant"))&&fetch.id().equals(e.correlationId())&&Objects.equals(fetch.status(),200)&&!fetch.timestamp().isAfter(e.timestamp())&&e.timestamp().isBefore(rq.timestamp())&&hash(bytes).equals(e.samlSummary().get("metadataSha256")));return e;}
    private Element validRequest(TranscriptEntry e,Element sp,Element target,List<X509Certificate> certs,boolean valid)throws Exception {var rq=SecureXml.parse(content.readDecodedSaml(e)).getDocumentElement();require(P.equals(rq.getNamespaceURI())&&"AuthnRequest".equals(rq.getLocalName())&&"2.0".equals(rq.getAttribute("Version"))&&rq.getAttribute("ID").equals(e.samlSummary().get("id"))&&rq.getAttribute("ID").equals(e.correlationId())&&sp.getAttribute("entityID").equals(one(rq,S,"Issuer").getTextContent())&&rq.getAttribute("Destination").equals(e.url())&&children(one(target,MD,"IDPSSODescriptor"),MD,"SingleSignOnService").stream().anyMatch(ep->e.url().equals(ep.getAttribute("Location")))&&children(one(sp,MD,"SPSSODescriptor"),MD,"AssertionConsumerService").stream().anyMatch(ep->rq.getAttribute("AssertionConsumerServiceURL").equals(ep.getAttribute("Location")))&&MetadataProbeCorrelation.matches(rq.getAttribute("AssertionConsumerServiceURL"),e.runId(),String.valueOf(e.samlSummary().get("variant")))&&Set.of("","false","0").contains(rq.getAttribute("ForceAuthn"))&&Set.of("","false","0").contains(rq.getAttribute("IsPassive"))&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(rq)&&signed(rq,certs)==valid);return rq;}
    private TranscriptEntry response(Map<String,TranscriptEntry> entries,JsonNode row,Set<String> used,TranscriptEntry rq){var e=entries.get(text(row,"responseReference"));require(e!=null&&used.add(e.id())&&e.direction()==Direction.INBOUND&&"POST".equals(e.method())&&"Response".equals(e.samlSummary().get("type"))&&rq.timestamp().isBefore(e.timestamp())&&rq.samlSummary().get("id").equals(e.samlSummary().get("inResponseTo"))&&Boolean.TRUE.equals(e.samlSummary().get("metadataProbeAccepted")));require(entries.values().stream().filter(v->v.direction()==Direction.INBOUND&&Objects.equals(v.samlSummary().get("inResponseTo"),rq.samlSummary().get("id"))).count()==1);return e;}
    private void success(CaseContext context,String variant,TranscriptEntry received,Element rq,Element sp,Element target,List<X509Certificate> signing)throws Exception {var xml=SecureXml.parse(content.readDecodedSaml(received)).getDocumentElement();require(P.equals(xml.getNamespaceURI())&&"Response".equals(xml.getLocalName())&&rq.getAttribute("ID").equals(xml.getAttribute("InResponseTo"))&&rq.getAttribute("AssertionConsumerServiceURL").equals(xml.getAttribute("Destination"))&&received.url().equals(xml.getAttribute("Destination"))&&target.getAttribute("entityID").equals(one(xml,S,"Issuer").getTextContent())&&SUCCESS.equals(one(one(xml,P,"Status"),P,"StatusCode").getAttribute("Value")));var assertions=new ArrayList<>(children(xml,S,"Assertion"));for(var encrypted:children(xml,S,"EncryptedAssertion"))assertions.add(new SamlXmlDecrypter().decrypt(encrypted,keys.apply(context.runId(),variant).orElseThrow().privateKey()));require(assertions.size()==1&&(signed(xml,signing)||signed(assertions.getFirst(),signing)));var assertion=assertions.getFirst();require(target.getAttribute("entityID").equals(one(assertion,S,"Issuer").getTextContent())&&assertion.getElementsByTagNameNS(S,"AuthnStatement").getLength()==1&&assertion.getElementsByTagNameNS(S,"Audience").getLength()==1&&sp.getAttribute("entityID").equals(assertion.getElementsByTagNameNS(S,"Audience").item(0).getTextContent()));var data=assertion.getElementsByTagNameNS(S,"SubjectConfirmationData");require(data.getLength()==1&&rq.getAttribute("ID").equals(((Element)data.item(0)).getAttribute("InResponseTo"))&&rq.getAttribute("AssertionConsumerServiceURL").equals(((Element)data.item(0)).getAttribute("Recipient")));}
    private void http(Path folder,JsonNode row,TranscriptEntry sent,String peer,boolean error)throws Exception {var values=row.path("nativeHttp");require(values.isArray()&&values.size()==1);var h=values.get(0);byte[] raw=content.readDecodedSaml(sent);String id=String.valueOf(sent.samlSummary().get("id"));require(id.equals(text(h,"requestId"))&&hash(raw).equals(text(h,"requestSha256"))&&"POST".equals(text(h,"method"))&&sent.url().equals(text(h,"requestUrl")));Instant start=Instant.parse(text(h,"startedAt")),end=Instant.parse(text(h,"finishedAt"));require(!start.isBefore(sent.timestamp())&&!end.isBefore(start));if(!error)require(h.path("responseStatus").asInt()==200&&!h.path("publicTerminalError").asBoolean(true));if(error){require(h.path("responseStatus").asInt()==500&&h.path("exactResponseUrl").asBoolean(false)&&sent.url().equals(text(h,"responseUrl"))&&h.path("publicTerminalError").asBoolean(false)&&!h.path("samlResponseFormPresent").asBoolean(true));byte[] body=original(folder,id+"-native-error.html");require(hash(body).equals(text(h,"responseSha256")));String html=new String(body,StandardCharsets.UTF_8);require(!html.matches("(?is).*<\\s*input\\b.*")&&!html.contains("SAMLResponse")&&!html.contains("SAMLRequest"));if(peer==null)require(html.contains("NOTVALIDCERTSIGNATURE")&&html.contains("SimpleSAML\\Module\\saml\\Message::checkSign"));else require(expired(visible(html),peer)&&html.contains("MetaDataStorageHandler"));}}
    private static void clock(Path folder,String label,JsonNode state)throws Exception {var range=json(original(folder,label+"-clock.json"));Instant start=Instant.parse(text(range,"startedAt")),end=Instant.parse(text(range,"finishedAt"));require(!end.isBefore(start));/* Product time() and host capture clocks are distinct domains. Native expiry is checked against native seconds; host bracketing is checked independently. */}
    private static void httpWindow(Path folder,JsonNode observation,String startLabel,String endLabel)throws Exception {var a=json(original(folder,startLabel+"-clock.json"));var b=json(original(folder,endLabel+"-clock.json"));Instant start=Instant.parse(text(a,"finishedAt")),end=Instant.parse(text(b,"startedAt"));require(start.isBefore(end));var h=observation.path("nativeHttp").get(0);Instant sent=Instant.parse(text(h,"startedAt")),received=Instant.parse(text(h,"finishedAt"));require(!sent.isBefore(start)&&!received.isAfter(end)&&!received.isBefore(sent));}
    private static void withinEpoch(Path folder,String start,String end,TranscriptEntry rq,TranscriptEntry response,JsonNode before,JsonNode after)throws Exception {var a=json(original(folder,start+"-clock.json"));var b=json(original(folder,end+"-clock.json"));require(!rq.timestamp().isBefore(Instant.parse(text(a,"finishedAt")))&&!rq.timestamp().isAfter(Instant.parse(text(b,"startedAt"))));if(response!=null)require(!response.timestamp().isAfter(Instant.parse(text(b,"startedAt"))));}
    static Instant effectiveExpiry(Element root,String variant,String peer) {var expiry=new ArrayList<Instant>();Element child=entity(root,peer);for(org.w3c.dom.Node n=child;n instanceof Element e;n=n.getParentNode())if(MD.equals(e.getNamespaceURI())&&Set.of("EntityDescriptor","EntitiesDescriptor").contains(e.getLocalName())&&e.hasAttribute("validUntil"))expiry.add(Instant.parse(e.getAttribute("validUntil")));require(!expiry.isEmpty());Instant min=Collections.min(expiry);require(variant.equals("live-validity-root")?"EntityDescriptor".equals(root.getLocalName())&&expiry.size()==1:"EntitiesDescriptor".equals(root.getLocalName())&&expiry.size()==3);if(variant.equals("live-validity-parent")){var groups=children(root,MD,"EntitiesDescriptor");require(groups.size()==1&&Instant.parse(root.getAttribute("validUntil")).equals(min)&&Instant.parse(groups.getFirst().getAttribute("validUntil")).isAfter(min)&&Instant.parse(child.getAttribute("validUntil")).isAfter(min));}else if(variant.equals("live-validity-child")){var groups=children(root,MD,"EntitiesDescriptor");require(groups.size()==1&&Instant.parse(groups.getFirst().getAttribute("validUntil")).equals(min)&&Instant.parse(root.getAttribute("validUntil")).isAfter(min)&&Instant.parse(child.getAttribute("validUntil")).isAfter(min));}else require(variant.equals("live-validity-root"));return min;}
    private static Element entity(Element root,String id){var matches=new ArrayList<Element>();if(MD.equals(root.getNamespaceURI())&&"EntityDescriptor".equals(root.getLocalName())&&id.equals(root.getAttribute("entityID")))matches.add(root);var all=root.getElementsByTagNameNS(MD,"EntityDescriptor");for(int i=0;i<all.getLength();i++)if(id.equals(((Element)all.item(i)).getAttribute("entityID")))matches.add((Element)all.item(i));require(matches.size()==1);return matches.getFirst();}
    private static List<X509Certificate> roleSigningKeys(Element entity)throws Exception {
        var result=new ArrayList<X509Certificate>();var role=one(entity,MD,"SPSSODescriptor");for(var kd:children(role,MD,"KeyDescriptor"))if(!kd.hasAttribute("use")||"signing".equals(kd.getAttribute("use"))){var all=kd.getElementsByTagNameNS("http://www.w3.org/2000/09/xmldsig#","X509Certificate");for(int i=0;i<all.getLength();i++)result.add((X509Certificate)java.security.cert.CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(all.item(i).getTextContent()))));}return result;
    }
    private static void nativeKeys(JsonNode metadata,List<X509Certificate> signing)throws Exception {require(metadata.path("keys").isArray()&&!metadata.path("keys").isEmpty());var found=new ArrayList<X509Certificate>();for(var k:metadata.path("keys"))if(k.path("signing").asBoolean(false)){require("X509Certificate".equals(text(k,"type")));found.add((X509Certificate)java.security.cert.CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(text(k,"X509Certificate")))));}require(found.size()==signing.size());for(var c:signing)require(found.stream().anyMatch(k->Arrays.equals(k.getPublicKey().getEncoded(),c.getPublicKey().getEncoded())));}
    private static String runtime(Path f,String epoch)throws Exception {var rows=json(original(f,"target-container-inspect-"+epoch+".json"));require(rows.isArray()&&rows.size()==1);var row=rows.get(0);require(row.at("/State/Running").asBoolean(false)&&row.at("/Config/Env").isMissingNode());return text(row,"Id")+"|"+text(row,"Image")+"|"+text(row.path("State"),"StartedAt");}
    private static boolean noResponse(Map<String,TranscriptEntry> entries,String id){return entries.values().stream().noneMatch(e->e.direction()==Direction.INBOUND&&id.equals(e.samlSummary().get("inResponseTo")));}
    private static boolean expired(String text,String peer){return java.util.regex.Pattern.compile("(?s).*Metadata for the entity \\["+java.util.regex.Pattern.quote(peer)+"\\] expired [0-9]+ seconds ago\\..*").matcher(text).matches();}
    private static String visible(String html){return html.replaceAll("(?is)<(script|style)\\b[^>]*>.*?</\\1>","").replaceAll("(?s)<[^>]*>"," ").replace("&amp;","&").replace("&#91;","[").replace("&#93;","]").replace("&quot;","\"");}
    private static Element one(Element root,String ns,String local){var all=children(root,ns,local);require(all.size()==1);return all.getFirst();}
    private static boolean signed(Element root,List<X509Certificate> certificates){return certificates.stream().anyMatch(c->new XmlSignatureVerifier().hasValidEnvelopedSignature(root,c));}
    private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
    private static byte[] original(Path f,String name)throws Exception {require(name.matches("[A-Za-z0-9_.-]+"));safe(f);Path p=f.resolve(name);require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)<=8*1024*1024);return Files.readAllBytes(p);}
    private static void safe(Path p){for(;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));}
    private static String text(JsonNode n,String k){require(n.path(k).isTextual()&&!n.path(k).asText().isBlank());return n.path(k).asText();}
    private static String hash(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
    private static void require(boolean value){if(!value)throw new IllegalArgumentException("Native metadata expiry proof incomplete");}
}
