package com.samlscope.runner.cases;
import static com.samlscope.runner.cases.MetadataAlgorithmEvidence.children;
import com.fasterxml.jackson.databind.JsonNode;
import com.samlscope.core.caseexec.CaseContext;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.cert.X509Certificate;import java.time.Instant;import java.util.*;import java.util.function.Function;import org.w3c.dom.Element;
/** Only a calibrated actual unknown-key acceptance counterexample, never partial positive coverage. */
final class SimpleSamlPhpEncryptedLogoutEvidence {
 static final String CASE="IIP-IDP19-c-idp-01",SCHEMA="samlscope-simplesamlphp-encrypted-logout-v1",REASON="slo.encrypted-id.multiple-keys.unknown-key-accepted";
 private static final String TARGET="http://localhost:18380/idp",IMAGE="sha256:9ae050473c68ce13c5451839cb64257eaa17be3a4d2c9a3f87996bbe0cebb0aa",P="urn:oasis:names:tc:SAML:2.0:protocol",S="urn:oasis:names:tc:SAML:2.0:assertion";
 private static final Map<String,String> PINS=Map.ofEntries(
 Map.entry("collector.py","a3f5dfad337a36280589a143486275d479b1ae8770564af645004d9135b364b2"),
 Map.entry("native-assertion.php","b935848a17dcfdb4c113618d3460dd1aa1645118f75876dce90ea92d97d33003"),
 Map.entry("native-attribute-limit.php","e3dbf076807713125373a0cf6ab2495e9181685dbd5d29b7344bc31a748f361f"),
 Map.entry("native-auth-processing.php","e6d5023490fbc94dc1a743bb5105f1d093f4eec0a8c48fe030353029e7ea5c5d"),
 Map.entry("native-auth-source.php","5e58ab08d8d03d6720b1bade592119e353fdf8ac1f96a97234575234e57a58d0"),
 Map.entry("native-auth-state.php","59576819feb0d08c19ff34bdee6f239b8edc94e1806fc056ff83b69e6b39ec8a"),
 Map.entry("native-client-collector.py","d4cc95685f333c774b84871829c1a93149ccd2a87dd1023fb6ddbb6df5a72c3c"),
 Map.entry("native-configuration.php","53837359cd60433082d3968843605a864bab97f23be482447bcfef37e7f6946e"),
 Map.entry("native-crypto.php","eedf4f4d133e117235d6829c4e386570c5168ad01afe060b3a31f38d0a1db0f3"),
 Map.entry("native-decrypt-command.php","34c3216e08f993e4a027c8de096fdc8d2b6c5b2a908a76fb73bebfa496464f96"),
 Map.entry("native-generate-command.php","95c9b897ef28de1873bf3b94a9802db561c7eb7a8824cf6c46103c9975973060"),
 Map.entry("native-http-client.py","a3d1fda57bee9aaad2daf974727510f0abf2df20419f5f27be2163d4fc900360"),
 Map.entry("native-idp-saml2.php","ae55fc922431d29ca6e87654ae2071500a4c3d7185ed80a6fcc5b26eed12495d"),
 Map.entry("native-idp.php","313760d280f557ffbba61fd4622fbf7e9892b21425d8d24d26d9f08eb9312888"),
 Map.entry("native-keys-command.php","2b2dc075808383a04a27761487ced48ec1f389228d802c0a329adba7ccfedcb1"),
 Map.entry("native-keyvalue-client.py","52ae423938a43026b38d720fe9cbde6681ba21d7511cf33faca6ab2366151f5e"),
 Map.entry("native-language-adaptor.php","f74d170f691a90b5281e77dabfbb026db2ec4eae5ee57a6badf990544622a7ba"),
 Map.entry("native-login-controller.php","56fd31e89b2272e56b08861fc748704a96d0772c3fc4635f11f54967463c8ed5"),
 Map.entry("native-logout-request.php","c034e1cb690c313b3e86422eb2265a078b4bd7be2bd435dd40a3bbe0b523eb7b"),
 Map.entry("native-message.php","ab017ee6cf9fb66db1037e40ed50feff0b277b1a5d43fd8ca774a3d27ce355d2"),
 Map.entry("native-parser-command.php","5008495fba0e65487a4849cf46f592c577215f96d5b4f3fd87321ebc6930edf9"),
 Map.entry("native-parser.php","8620bb26fd41d2be29d2611883839a4cfde0b6c8458c274e2d40a002678fd93d"),
 Map.entry("native-policy-command.php","a5801c78f58f96e114e9e76a7e87c3efdf5f59d936bb14787a4e96ff4a949a18"),
 Map.entry("native-refresh-client.py","28fad4a9dc68068796c2b43c128bec1acf84a57c9662a935ee06c3bcbb50be88"),
 Map.entry("native-response.php","27d7f1d4a5ea73b22107b7615c230b156f3dcaa012e843f380d879f53826a64a"),
 Map.entry("native-session-command.php","238bb8d1e9680f16072bdd0271f28a6a2bbb914c6c1f93cef35406db3d14fecb"),
 Map.entry("native-session.php","66dc24f2ceacd6a1754fdba0aeda2adfc1eac4d42c3f3e16f915a2e5d382f435"),
 Map.entry("native-signature-client.py","2df41a96b2194577186351eb9a6eddf6588138c3ae16279163fd9c54c6f95485"),
 Map.entry("native-state-command.php","f3bf3a3f462dd658794b6472cc6bafc1723c3e84beb0f285dbb20616072b3759"),
 Map.entry("native-subject-confirmation-data.php","79ab1c7623b0fa5c0507c55541afdae4e533f35c5664049541c0500220fca048"),
 Map.entry("native-subject-confirmation.php","40746d3785ee55fa4999d49cd19c32625e415d0a37e0f193508138485a5a6a0e"),
 Map.entry("native-ui-privacy.py","944e9a5345e4c714740bdbf87d69cbb61015d0cd37b8ac61a7109a929851ab05"),
 Map.entry("native-userpass-base.php","cb69bac6366c580fd3dd41dcdae37831119cecc8897b62d0b8d22efd129f2169"),
 Map.entry("native-userpass.php","8465e71fabec88578369eaf780dfe86c6ab3f0f2cdf4b24eb52bf134918f9b48"),
 Map.entry("native-verify-command.php","7a7452c1614a02501ed77e3d881d344dcb04f0d57f4423f4865e98edf1cadbc6"),
 Map.entry("native-web-browser-sso.php","47ddeecace975b77645aa91a4b4551429dc60d02dc1b9baa6c633c30bf1e75f4"),
 Map.entry("native-xml-signer.php","5845e28158c7641d5ce1e6b9205e8005b6d9c090e1888ea46416abb8fdf0018d"));
    private final Path directory;private final TranscriptContentReader content;private final Function<String,byte[]> metadata;private final Function<String,IdpBasicLogoutScenarioTestCase.Configuration> configurations;
    SimpleSamlPhpEncryptedLogoutEvidence(Path directory,TranscriptContentReader content,Function<String,byte[]> metadata,Function<String,IdpBasicLogoutScenarioTestCase.Configuration> configurations){this.directory=Objects.requireNonNull(directory).toAbsolutePath().normalize();this.content=Objects.requireNonNull(content);this.metadata=Objects.requireNonNull(metadata);this.configurations=Objects.requireNonNull(configurations);}
    boolean exists(String run){return run!=null&&run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&Files.exists(directory.resolve(run),LinkOption.NOFOLLOW_LINKS);}
    Optional<CaseOutcome> evaluate(CaseContext context){
        if(!exists(context.runId()))return Optional.empty();String stage="native-encrypted-logout-originals-unproven";
        try{
            require(context.transcriptComplete());Path folder=directory.resolve(context.runId());for(Path p=folder;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p));require(Files.isDirectory(folder,LinkOption.NOFOLLOW_LINKS));
            var receipt=json(original(folder,"manifest.json"));var files=receipt.path("files");byte[] targetRaw=metadata.apply(context.runId());require(files.isObject()&&SCHEMA.equals(text(receipt,"schema"))&&context.runId().equals(text(receipt,"runId"))&&"native-encrypted-logout".equals(text(receipt,"campaignId"))&&TARGET.equals(text(receipt,"targetEntityId"))&&hash(targetRaw).equals(text(receipt,"targetMetadataSha256")));
            for(var pin:PINS.entrySet()){byte[] source=checked(folder,files,pin.getKey());require(pin.getValue().equals(hash(source)));if(pin.getKey().startsWith("native-")&&pin.getKey().endsWith(".php")&&!pin.getKey().endsWith("-command.php"))require(Arrays.equals(source,checked(folder,files,pin.getKey().replace(".php","-after.php"))));}
            var identity=json(checked(folder,files,"identity-before.json"));require(identity.equals(json(checked(folder,files,"identity-after.json")))&&identity.path("running").asBoolean(false)&&IMAGE.equals(text(identity,"imageId")));
            var created=json(checked(folder,files,"created.json")).path("run");require(context.runId().equals(text(created,"id")));String entity="http://localhost:18080/p/"+text(created,"planId");var plan=json(checked(folder,files,"plan.json")).at("/plan/plan");require("single_logout_idp".equals(text(plan,"profile"))&&text(created,"planId").equals(text(plan,"id")));
            var configuration=configurations.apply(context.runId());require(configuration!=null&&configuration.suiteCredentials()!=null&&TARGET.equals(configuration.targetIssuer())&&entity.equals(configuration.login().suiteIssuer()));var suite=configuration.suiteCredentials();
            var target=SecureXml.parse(targetRaw).getDocumentElement();require(TARGET.equals(target.getAttribute("entityID")));var targetKeys=MetadataAlgorithmEvidence.signingKeys(target);require(!targetKeys.isEmpty());
            var entries=new HashMap<String,TranscriptEntry>();for(var entry:context.transcript().list(context.runId())){require(context.runId().equals(entry.runId())&&entry.id().matches("tx_[0-9A-HJKMNP-TV-Z]{26}")&&entries.put(entry.id(),entry)==null);if(entry.decodedSamlRef()!=null)require(("transcripts/"+context.runId()+"/"+entry.id()+".saml.xml").equals(entry.decodedSamlRef())&&content.readDecodedSaml(entry)!=null&&content.readDecodedSaml(entry).length==entry.decodedSamlBytes());}
            var restore=json(checked(folder,files,"restoration.json"));var baseline=new HashMap<String,byte[]>();for(String name:List.of("remote","hosted","override")){byte[] value=checked(folder,files,name+"-original.php");baseline.put(name,value);require(Arrays.equals(value,checked(folder,files,name+"-final.php"))&&restore.path(name).path("restored").asBoolean(false)&&hash(value).equals(text(restore.path(name),"original_sha256"))&&hash(value).equals(text(restore.path(name),"final_sha256")));}
            var cleanup=json(checked(folder,files,"ephemeral-key-cleanup.json"));require(cleanup.path("created").asBoolean(false)&&cleanup.path("removed").asBoolean(false)&&!cleanup.path("privateMaterialArchived").asBoolean(true));
            var policy=json(checked(folder,files,"baseline-before.policy.json"));validatePolicy(policy,entity);require(policy.equals(json(checked(folder,files,"after.policy.json"))));
            byte[] hosted=(new String(baseline.get("hosted"),StandardCharsets.UTF_8)+"\n$metadata['"+TARGET+"']['new_privatekey']='/tmp/samlscope-encrypted-logout-key.pem';\n$metadata['"+TARGET+"']['new_certificate']='/tmp/samlscope-encrypted-logout-cert.pem';\n$metadata['"+TARGET+"']['sign.logout']=true;\n").getBytes(StandardCharsets.UTF_8);
            byte[] fixture=checked(folder,files,"baseline.fixture.xml");var peer=SecureXml.parse(fixture).getDocumentElement();require(entity.equals(peer.getAttribute("entityID"))&&signed(peer,List.of(suite.certificate())));var peerKeys=MetadataAlgorithmEvidence.signingKeys(peer);require(peerKeys.stream().anyMatch(c->Arrays.equals(c.getPublicKey().getEncoded(),suite.certificate().getPublicKey().getEncoded())));
            var parser=json(checked(folder,files,"baseline.parser.stdout"));require(parser.path("php").isTextual()&&new String(checked(folder,files,"baseline.parser.stderr"),StandardCharsets.UTF_8).isBlank());byte[] remote=concat(baseline.get("remote"),("\n"+text(parser,"php")+"\n").getBytes(StandardCharsets.UTF_8));
            for(String prefix:files.properties().stream().map(Map.Entry::getKey).filter(n->n.endsWith(".policy.json")&&n.startsWith("stage-")).map(n->n.substring(0,n.length()-".policy.json".length())).toList()){require(policy.equals(json(checked(folder,files,prefix+".policy.json"))));for(String name:baseline.keySet())require(Arrays.equals(checked(folder,files,prefix+"."+name+".php"),name.equals("remote")?remote:name.equals("hosted")?hosted:baseline.get(name)));}
            for(String prefix:List.of("baseline-before","after")){for(String name:baseline.keySet())require(Arrays.equals(checked(folder,files,prefix+"."+name+".php"),name.equals("remote")?remote:name.equals("hosted")?hosted:baseline.get(name)));}
            var keyReadback=json(checked(folder,files,"baseline-before.decryption-keys.json"));require(keyReadback.equals(json(checked(folder,files,"after.decryption-keys.json")))&&TARGET.equals(text(keyReadback,"targetEntityId"))&&entity.equals(text(keyReadback,"spEntityId"))&&!keyReadback.path("privateMaterialPersisted").asBoolean(true));var keys=keyReadback.path("keys");require(keys.size()==2);var keyHashes=new HashSet<String>();for(var key:keys){byte[] publicKey=Base64.getDecoder().decode(text(key,"spkiBase64"));require(hash(publicKey).equals(text(key,"spkiSha256"))&&keyHashes.add(hash(publicKey))&&!Arrays.equals(publicKey,suite.certificate().getPublicKey().getEncoded()));}
            require(configuration.targetEncryptionKeys().size()==2&&configuration.targetEncryptionKeys().stream().map(k->hash(k.getEncoded())).collect(java.util.stream.Collectors.toSet()).equals(keyHashes));
            var certificate=(X509Certificate)java.security.cert.CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(checked(folder,files,"new-public-certificate.pem")));require(hash(certificate.getPublicKey().getEncoded()).equals(text(keys.get(0),"spkiSha256"))&&targetKeys.stream().anyMatch(k->hash(k.getPublicKey().getEncoded()).equals(text(keys.get(1),"spkiSha256"))));
            var selfChecks=json(checked(folder,files,"native-signature-selfchecks.json"));require(selfChecks.path("nativeVerificationInvocations").asInt(-1)==8&&selfChecks.path("records").size()==8);var verifiedRequestIds=new HashSet<String>();for(var check:selfChecks.path("records")){String requestId=text(check,"requestId");require(verifiedRequestIds.add(requestId)&&entity.equals(text(check,"spEntityId")));var transport=http(folder,files,requestId);require(text(check,"requestSha256").equals(text(transport,"request_sha256"))&&(!check.path("privateMaterialPersisted").asBoolean(true))&&(check.path("valid").asBoolean(false)||check.path("allowInvalidControl").asBoolean(false)));}
            stage="native-encrypted-logout-controls-unproven";var refs=new LinkedHashSet<EvidenceRef>();var positive=entry(entries,receipt,"positiveRequestReference","AuthnRequest",Direction.OUTBOUND);var negative=entry(entries,receipt,"negativeRequestReference","AuthnRequest",Direction.OUTBOUND);var positiveResponse=entry(entries,receipt,"positiveResponseReference","Response",Direction.INBOUND);byte[] positiveBytes=content.readDecodedSaml(positive),negativeBytes=content.readDecodedSaml(negative);var controlPeer=SecureXml.parse(checked(folder,files,"control.fixture.xml")).getDocumentElement();var controlKeys=MetadataAlgorithmEvidence.signingKeys(controlPeer);require(!controlKeys.isEmpty()&&signed(controlPeer,controlKeys)&&signed(SecureXml.parse(positiveBytes).getDocumentElement(),controlKeys)&&!signed(SecureXml.parse(negativeBytes).getDocumentElement(),controlKeys)&&new XmlSignatureVerifier().hasValidEnvelopedReferenceDigests(SecureXml.parse(negativeBytes).getDocumentElement())&&MetadataProbeCorrelation.signatureControl(negative));
            var controlAssertion=login(content.readDecodedSaml(positiveResponse),SecureXml.parse(positiveBytes).getDocumentElement(),targetKeys,entity,suite);var negativeHttp=http(folder,files,SecureXml.parse(negativeBytes).getDocumentElement().getAttribute("ID"));require(negativeHttp.path("response_status").asInt()==500&&"signature-value-invalid".equals(text(negativeHttp,"native_signature_rejection"))&&new String(checked(folder,files,"native-http-originals."+text(negativeHttp,"request_id")+".html"),StandardCharsets.UTF_8).contains("NOTVALIDCERTSIGNATURE"));
            for(var e:List.of(positive,negative,positiveResponse))refs.add(new EvidenceRef("transcript",e.id()));
            stage="native-encrypted-logout-matrix-unproven";require(receipt.path("matrix").size()==3);var matrixKinds=new HashSet<String>();var requestIds=new HashSet<String>();var authenticatedIndexes=new HashSet<String>();boolean unknownCounterexample=false;int encryptedCount=0;
            for(var row:receipt.path("matrix")){
                String caseId=text(row,"caseId"),fixtureId=text(row,"fixtureId"),kind=caseId+":"+fixtureId;require(Set.of("IIP-IDP17-a-idp-01:slo-basic-logout","IIP-IDP19-c-idp-01:slo-basic-logout-control","IIP-IDP19-c-idp-01:slo-basic-logout").contains(kind)&&matrixKinds.add(kind));
                var request=entry(entries,row,"requestReference","LogoutRequest",Direction.OUTBOUND);var response=entry(entries,row,"responseReference","LogoutResponse",Direction.INBOUND);var loginRequest=entry(entries,row,"loginRequestReference","AuthnRequest",Direction.OUTBOUND);var loginResponse=entry(entries,row,"loginResponseReference","Response",Direction.INBOUND);
                byte[] requestBytes=content.readDecodedSaml(request),responseBytes=content.readDecodedSaml(response);var rq=SecureXml.parse(requestBytes).getDocumentElement();String id=rq.getAttribute("ID"),action=(String)request.samlSummary().get("action_id");require(id.equals("_"+action)&&requestIds.add(id)&&caseId.equals(request.samlSummary().get("scenario_case_id"))&&fixtureId.equals(request.samlSummary().get("fixture_id"))&&action.equals(request.correlationId())&&action.equals(response.correlationId())&&entity.equals(issuer(rq))&&"2.0".equals(rq.getAttribute("Version"))&&configuration.logoutEndpoint().toString().equals(rq.getAttribute("Destination"))&&"GET".equals(request.method()));
                require(new RedirectSignatureVerifier().isValidForMessage(request.rawQuery(),suite.certificate(),requestBytes)&&request.url().toString().endsWith("?"+request.rawQuery()));
                var loginXml=SecureXml.parse(content.readDecodedSaml(loginRequest)).getDocumentElement();require(caseId.equals(loginRequest.samlSummary().get("scenario_case_id"))&&signed(loginXml,peerKeys));var assertion=login(content.readDecodedSaml(loginResponse),loginXml,targetKeys,entity,suite);var subject=children(assertion,S,"Subject");require(subject.size()==1&&children(subject.getFirst(),S,"NameID").size()==1);var name=children(subject.getFirst(),S,"NameID").getFirst();var authn=children(assertion,S,"AuthnStatement");require(authn.size()==1);String index=authn.getFirst().getAttribute("SessionIndex");require(!index.isBlank()&&children(rq,P,"SessionIndex").size()==1&&index.equals(children(rq,P,"SessionIndex").getFirst().getTextContent()));
                require(loginRequest.timestamp().isBefore(loginResponse.timestamp())&&loginResponse.timestamp().isBefore(request.timestamp())&&request.timestamp().isBefore(response.timestamp()));
                var responseXml=SecureXml.parse(responseBytes).getDocumentElement();require(P.equals(responseXml.getNamespaceURI())&&"LogoutResponse".equals(responseXml.getLocalName())&&id.equals(responseXml.getAttribute("InResponseTo"))&&TARGET.equals(issuer(responseXml))&&configuration.suiteLogoutEndpoint().toString().equals(responseXml.getAttribute("Destination"))&&"GET".equals(response.method())&&targetKeys.stream().anyMatch(c->new RedirectSignatureVerifier().isValidForMessage(response.rawQuery(),c,responseBytes))&&success(responseXml));
                var transport=http(folder,files,id);require("GET".equals(text(transport,"request_method"))&&hash(requestBytes).equals(text(transport,"request_sha256"))&&request.url().toString().equals(text(transport,"request_url"))&&hash(request.rawQuery().getBytes(StandardCharsets.UTF_8)).equals(text(transport,"raw_query_sha256"))&&hash(request.rawQuery().getBytes(StandardCharsets.UTF_8)).equals(text(transport,"request_body_sha256"))&&Arrays.equals(requestBytes,checked(folder,files,"native-http-originals."+id+".request.xml"))&&Arrays.equals(request.rawQuery().getBytes(StandardCharsets.UTF_8),checked(folder,files,"native-http-originals."+id+".request.body"))&&!transport.path("nativeDirectResponseBody").asBoolean(true));
                String responseUrl=text(transport,"native_signed_response_url");require(responseUrl.equals(configuration.suiteLogoutEndpoint()+"?"+response.rawQuery())&&Set.of(302,303).contains(transport.path("native_signed_response_status").asInt())&&text(transport,"native_signed_response_source_url").equals("http://localhost:18380/simplesaml/module.php/core/logout-resume"));Instant start=Instant.parse(text(transport,"started_at")),finish=Instant.parse(text(transport,"observed_at"));require(start.isBefore(finish));var dispatches=json(checked(folder,files,"steps.json"));int selectedStep=-1;for(int step=0;step<dispatches.size();step++){var captured=dispatches.get(step);if(action.equals(captured.path("actionId").asText())&&caseId.equals(captured.path("caseId").asText())&&captured.path("sentToTarget").asBoolean(false))selectedStep=step;}require(selectedStep>=0&&Instant.parse(text(json(checked(folder,files,"stage-"+selectedStep+"-before.observed.json")),"recordedAt")).isBefore(start)&&Instant.parse(text(json(checked(folder,files,"after.observed.json")),"recordedAt")).isAfter(finish));
                var before=session(folder,files,id,"before-native-dispatch");var after=session(folder,files,id,"after-native-response");var beforeState=before.path("session");var afterState=after.path("session");require(Instant.parse(text(before,"recordedAt")).isBefore(start)&&!Instant.parse(text(after,"recordedAt")).isBefore(finish)&&beforeState.path("authenticated").asBoolean(false)&&!afterState.path("authenticated").asBoolean(true)&&text(beforeState,"sessionSha256").equals(text(afterState,"sessionSha256"))&&authenticatedIndexes.add(index)&&beforeState.path("associations").size()==1&&afterState.path("associations").size()==0&&!beforeState.path("credentialsPersisted").asBoolean(true)&&!afterState.path("credentialsPersisted").asBoolean(true));var association=beforeState.path("associations").get(0);require(entity.equals(text(association,"entity"))&&name.getTextContent().equals(text(association,"nameId"))&&name.getAttribute("Format").equals(text(association,"nameIdFormat"))&&"\\SimpleSAML\\Module\\saml\\IdP\\SAML2".equals(text(association,"handler")));
                var encrypted=children(rq,S,"EncryptedID");if(caseId.startsWith("IIP-IDP19-")){encryptedCount++;require(encrypted.size()==1&&children(rq,S,"NameID").isEmpty());var nativeDecrypt=json(checked(folder,files,"native-decrypt-"+id+".json"));require(id.equals(text(nativeDecrypt,"requestId"))&&hash(requestBytes).equals(text(nativeDecrypt,"requestSha256"))&&TARGET.equals(text(nativeDecrypt,"targetEntityId"))&&entity.equals(text(nativeDecrypt,"spEntityId"))&&!nativeDecrypt.path("privateMaterialPersisted").asBoolean(true)&&nativeDecrypt.path("keysTried").size()==2);boolean unknown=fixtureId.endsWith("-control");String selectedHash=hash(configuration.targetEncryptionKeys().get(1).getEncoded());int selected=text(keys.get(0),"spkiSha256").equals(selectedHash)?0:1;require(text(keys.get(selected),"spkiSha256").equals(selectedHash));
                    for(int key=0;key<2;key++){var tried=nativeDecrypt.path("keysTried").get(key);require(tried.path("keyIndex").isIntegralNumber()&&tried.path("keyIndex").asInt(-1)==key&&tried.path("encryptedBefore").isBoolean()&&tried.path("decrypted").isBoolean()&&text(tried,"spkiSha256").equals(text(keys.get(key),"spkiSha256"))&&tried.path("encryptedBefore").asBoolean(false));if(!unknown&&selected==key)require(tried.path("decrypted").asBoolean(false)&&name.getTextContent().equals(text(tried,"nameId"))&&name.getAttribute("Format").equals(text(tried,"nameIdFormat")));else require(!tried.path("decrypted").asBoolean(true)&&tried.path("exceptionClass").isTextual());}
                    checked(folder,files,"native-decrypt-"+id+".json.stderr");var nativeAttempts=json(checked(folder,files,"native-decryption-attempts.json"));require(nativeAttempts.isArray()&&nativeAttempts.size()==2);int matchingAttempt=0;for(var attempt:nativeAttempts)if(id.equals(text(attempt,"requestId"))){matchingAttempt++;require(attempt.path("returncode").isIntegralNumber()&&attempt.path("returncode").asInt(-1)==0&&("native-decrypt-"+id+".json").equals(text(attempt,"file")));}require(matchingAttempt==1);if(unknown){var plain=new SamlXmlDecrypter().decrypt(encrypted.getFirst(),suite.privateKey());require(S.equals(plain.getNamespaceURI())&&"NameID".equals(plain.getLocalName())&&name.getTextContent().equals(plain.getTextContent())&&name.getAttribute("Format").equals(plain.getAttribute("Format")));if(CASE.equals(caseId))unknownCounterexample=true;}
                }else require(encrypted.isEmpty()&&children(rq,S,"NameID").size()==1&&name.getTextContent().equals(children(rq,S,"NameID").getFirst().getTextContent()));
                for(var e:List.of(loginRequest,loginResponse,request,response))refs.add(new EvidenceRef("transcript",e.id()));
            }
            require(encryptedCount==2&&unknownCounterexample);var counts=json(checked(folder,files,"operation-counts.json"));require(counts.path("protocolOperationsAttempted").asInt(-1)==8&&counts.path("credentialPosts").asInt(-1)==4&&counts.path("nativeParserInvocations").asInt(-1)==2&&counts.path("nativeDecryptInvocations").asInt(-1)==2&&counts.path("nativeVerificationInvocations").asInt(-1)==8&&counts.path("productRestarts").asInt(-1)==0&&counts.path("humanOperations").asInt(-1)==0&&counts.path("restored").asBoolean(false));
            return Optional.of(new CaseOutcome(Outcome.VIOLATED,null,REASON,REASON,List.copyOf(refs),Map.of("native_evidence_adapter","simplesamlphp-encrypted-logout","registered_native_keys",2,"registered_key_wire_controls",1,"unknown_key_decryption_failed",true,"unknown_key_signed_success",true,"configuration_restored",true)));
        }catch(Exception missing){return Optional.of(CaseOutcome.notVerified(stage,"slo.encrypted-id.native-unproven"));}
    }
    private static void validatePolicy(JsonNode policy,String entity){require(TARGET.equals(text(policy,"targetEntityId"))&&entity.equals(text(policy,"spEntityId"))&&policy.path("hosted").path("sign.logout").asBoolean(false)&&"example-userpass".equals(text(policy.path("hosted"),"auth"))&&"exampleauth:UserPass".equals(text(policy.path("authsource"),"class"))&&!policy.path("proxyAuthnContext").asBoolean(true)&&policy.path("peer").path("validate.authnrequest").asBoolean(false)&&policy.path("peer").path("saml20.sign.assertion").asBoolean(false));}
    private Element login(byte[] raw,Element request,List<X509Certificate> targetKeys,String entity,PlanCredentials suite){var root=SecureXml.parse(raw).getDocumentElement();require(P.equals(root.getNamespaceURI())&&"Response".equals(root.getLocalName())&&request.getAttribute("ID").equals(root.getAttribute("InResponseTo"))&&request.getAttribute("AssertionConsumerServiceURL").equals(root.getAttribute("Destination"))&&TARGET.equals(issuer(root))&&success(root));var assertions=new ArrayList<>(children(root,S,"Assertion"));for(var encrypted:children(root,S,"EncryptedAssertion"))assertions.add(new SamlXmlDecrypter().decrypt(encrypted,suite.privateKey()));require(assertions.size()==1);var assertion=assertions.getFirst();require((signed(root,targetKeys)||signed(assertion,targetKeys))&&TARGET.equals(issuer(assertion)));var audiences=assertion.getElementsByTagNameNS(S,"Audience");require(audiences.getLength()==1&&entity.equals(audiences.item(0).getTextContent()));return assertion;}
    private static boolean success(Element root){var statuses=children(root,P,"Status");require(statuses.size()==1);var codes=children(statuses.getFirst(),P,"StatusCode");return codes.size()==1&&"urn:oasis:names:tc:SAML:2.0:status:Success".equals(codes.getFirst().getAttribute("Value"));}
    private static JsonNode session(Path folder,JsonNode files,String id,String phase)throws Exception{var values=new ArrayList<JsonNode>();for(var row:json(checked(folder,files,"native-session-observations.json")).path("observations"))if(id.equals(text(row,"requestId"))&&phase.equals(text(row,"phase")))values.add(row);require(values.size()==1);return values.getFirst();}
    private static JsonNode http(Path folder,JsonNode files,String id)throws Exception{var values=new ArrayList<JsonNode>();for(var row:json(checked(folder,files,"native-http-observations.json")).path("records"))if(id.equals(text(row,"request_id")))values.add(row);require(values.size()==1);return values.getFirst();}
    private static boolean signed(Element e,List<X509Certificate> keys){var verifier=new XmlSignatureVerifier();return verifier.hasValidEnvelopedReferenceDigests(e)&&keys.stream().anyMatch(k->verifier.hasValidEnvelopedSignature(e,k));}
    private static String issuer(Element root){var values=children(root,S,"Issuer");require(values.size()==1);return values.getFirst().getTextContent();}
    private static TranscriptEntry entry(Map<String,TranscriptEntry> entries,JsonNode receipt,String field,String type,Direction direction){var e=entries.get(text(receipt,field));require(e!=null&&e.direction()==direction&&type.equals(e.samlSummary().get("type")));return e;}
    private static byte[] concat(byte[] a,byte[] b){var answer=Arrays.copyOf(a,a.length+b.length);System.arraycopy(b,0,answer,a.length,b.length);return answer;}
    private static byte[] checked(Path folder,JsonNode files,String name)throws Exception{var value=original(folder,name);require(hash(value).equals(files.path(name).asText()));return value;}
    private static byte[] original(Path folder,String name)throws Exception{require(name.matches("[A-Za-z0-9._-]+")&&!Set.of(".","..").contains(name));Path p=folder.resolve(name);for(Path a=p;a!=null;a=a.getParent())require(!Files.isSymbolicLink(a));require(Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&Files.size(p)<4194304);return Files.readAllBytes(p);}
    private static JsonNode json(byte[] raw)throws Exception{return new JsonCodec().mapper().readTree(raw);}
    private static String text(JsonNode node,String field){require(node.path(field).isTextual()&&!node.path(field).asText().isBlank());return node.path(field).asText();}
    private static String hash(byte[] value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(Exception impossible){throw new IllegalStateException(impossible);}}
    private static void require(boolean condition){if(!condition)throw new IllegalArgumentException("Native encrypted logout proof incomplete");}
}
