#!/usr/bin/env python3
"""Render the reviewed publication register; classifications are not inferred by this tool."""
import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def source_row(s):
    allocation = s['material_allocation_status']
    if allocation not in {'QUOTATION_OR_IMPLEMENTATION_COMMENTARY', 'REFERENCE_OR_INDEPENDENT_IMPLEMENTATION'}:
        raise ValueError('Unclassified source use: ' + s['id'])
    quoted = allocation == 'QUOTATION_OR_IMPLEMENTATION_COMMENTARY'
    return dict(material=s['id'], location='tests/specs.yaml; ' + ('tests/coverage.yaml / tests/cases.yaml; profiles, docs, UI and licensed exports via material-index' if quoted else 'catalog references / independent implementation; see publication-audit.md'),
        use='C' if quoted else 'A/B', owner=s.get('rights_holder', 'Source authors identified by the original document'),
        basis=s['source_url'], conditions='Title, edition, copyright, permission text and modification credit from source-notices.json' if quoted else 'Retain the accurate source locator; no document reproduction license is claimed',
        status=s['publication_status'], action=s['usage_review'], implemented=s.get('resolved_by_implementation', False),
        requires_inquiry=s.get('requires_inquiry', False), requires_legal_review=s.get('requires_legal_review', s['publication_status'] == 'RED'))

def render():
    registry = json.loads((ROOT / 'LICENSES/source-notices.json').read_text())
    java = json.loads((ROOT / 'web/public/licenses/java-dependencies.json').read_text())
    extra = json.loads((ROOT / 'LICENSES/publication-other-materials.json').read_text())
    rows = []
    for s in registry['sources']:
        rows.append(source_row(s))
    for p in java['packages']:
        evidence = p.get('permission')
        if not evidence:
            raise ValueError('Unreviewed runtime package: ' + p['file'])
        if any(s.get('review_status') != 'REVIEWED_UPSTREAM_DISTRIBUTION_CONTEXT' for s in p['embedded_schemas']):
            raise ValueError('Unreviewed embedded resource: ' + p['file'])
        rows.append(dict(material=p['file'], location='ZIP/TAR lib/' + p['file'] + '; Java runtime' + ('; embedded XSD resources listed below' if p['embedded_schemas'] else ''), use='D',
            owner=(', '.join(evidence.get('publisher_author_names', [])) or 'Upstream package authors') + '; resource-specific copyright holders in retained headers/notices',
            basis='; '.join(e['source_url'] for e in evidence['pom_evidence']),
            conditions=evidence['required_conditions'], status=evidence['publication_status'],
            action='Original JAR SHA-256 verified; package/parent POM and resource notices retained' + ('; full historical W3C notices added' if p['file'].startswith(('opensaml-soap-api-', 'opensaml-xmlsec-api-', 'xmlsec-')) else '') + ('; exact upstream source availability supplied' if evidence.get('source_availability') else ''),
            implemented=evidence.get('resolved_by_implementation', False),
            requires_inquiry=evidence.get('requires_inquiry', False),
            requires_legal_review=evidence.get('requires_legal_review', evidence['publication_status'] == 'RED')))
    for item in extra['materials']:
        for file, digest in item.get('file_sha256', {}).items():
            if hashlib.sha256((ROOT / file).read_bytes()).hexdigest() != digest:
                raise ValueError('Changed reviewed material: ' + file)
    rows += extra['materials']
    if any(r['status'] not in {'GREEN', 'YELLOW', 'RED'} for r in rows):
        raise ValueError('Unknown publication status')
    totals = Counter(r['status'] for r in rows)
    stats = {s: totals[s] for s in ['GREEN','YELLOW','RED']}
    stats.update(inquiry=sum(r.get('requires_inquiry', False) for r in rows), resolved_by_implementation=sum(r.get('implemented',False) for r in rows), remaining_legal_decisions=sum(r.get('requires_legal_review', r['status'] == 'RED') for r in rows))
    result = {'review_date':'2026-09-11', 'counting_unit':'Each source ID, exact Java/browser package version, or explicitly named other material group; embedded schemas are subordinate resources, not double-counted.', 'counts':stats, 'materials':rows}
    lines = ['# Publication material register', '', 'Generated by `dev/licensing/publication_audit.py`; see [publication-audit.md](publication-audit.md) for rationale, scope and validation. Do not edit this register by hand.', '', 'Counting unit: ' + result['counting_unit'], '', '```json',json.dumps(stats,indent=2),'```','', '| 素材 | 実際の利用箇所 | 利用形態 | 原権利者 | 根拠となる許諾 | 必要表示 | 公開判定 | 対応 |', '| --- | --- | --- | --- | --- | --- | --- | --- |']
    def cell(v): return str(v).replace('|','\\|').replace('\n',' ')
    for r in rows:
        lines.append('| ' + ' | '.join(cell(r[k]) for k in ['material','location','use','owner','basis','conditions','status','action']) + ' |')
    lines += ['', '## Embedded XSD byte inventory', '', 'These resources remain inside their original upstream JAR. This is not a grant to extract, modify or independently relicense them. Package-specific grants and original resource exceptions both apply.', '', '| Package | Resource | SHA-256 |', '| --- | --- | --- |']
    for p in java['packages']:
        for s in p['embedded_schemas']:
            lines.append('| '+p['file']+' | '+s['file']+' | '+s['sha256']+' |')
    return result, '\n'.join(lines)+'\n'

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    data,md=render()
    for name,text in [('publication-register.json',json.dumps(data,ensure_ascii=False,indent=2)+'\n'),('publication-register.md',md)]:
        path=ROOT/'LICENSES'/name
        if args.check:
            if not path.exists() or path.read_text()!=text: raise SystemExit('Regenerate '+name)
        else: path.write_text(text)
    print(json.dumps(data['counts']))
if __name__=='__main__':main()
