package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.node.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.logout.SloPropagationFixtures;
import com.samlscope.store.JsonCodec;
import com.sun.net.httpserver.*;
import java.io.*;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.security.cert.*;
import java.math.BigInteger;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.w3c.dom.*;
import org.bouncycastle.cert.jcajce.*;
import org.bouncycastle.operator.jcajce.*;

/** Isolated real HTTP/SAML control target. Private keys and session objects remain in memory. */
public final class SoapContinuationActor {
    static final String P="urn:oasis:names:tc:SAML:2.0:protocol",A="urn:oasis:names:tc:SAML:2.0:assertion",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#",SOAP="http://schemas.xmlsoap.org/soap/envelope/",B="urn:oasis:names:tc:SAML:2.0:bindings:SOAP",SUCCESS=P.replace("protocol","status:Success"),RESPONDER=P.replace("protocol","status:Responder");
    static final String CASE="IIP-IDP17-r-idp-01";
    static final JsonCodec JSON=new JsonCodec();
    interface Continuation { boolean continueAfter(String status); }
    static final class ContinuingActor implements Continuation { public boolean continueAfter(String status){return true;} }
    static final class StopAfterErrorActor implements Continuation { public boolean continueAfter(String status){return SUCCESS.equals(status);} }
    record Session(String label,String entity,String index,String name,String endpoint) {}
    private Path output,receipt; private final Path source,baseOutput;
    private final String run,plan,entity;
    private final PlanCredentials suite,target;
    private Continuation continuation;
    private final Map<String,byte[]> preparedCache=new HashMap<>(),originCache=new HashMap<>(),authnCache=new HashMap<>();
    private final Map<String,Instant> preparedTimes=new HashMap<>();
    private final List<TranscriptEntry> entries=new ArrayList<>();
    private final Map<String,byte[]> decoded=new LinkedHashMap<>();
    private final Map<String,Session> registered=new LinkedHashMap<>();
    private final List<Map<String,Object>> trials=new ArrayList<>();
    private final HttpClient client=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).connectTimeout(Duration.ofSeconds(5)).build();
    private final HttpServer server;
    private final ExecutorService executor=Executors.newCachedThreadPool();
    private String targetEntity,targetSoap,callback,trial,preparedRef,preparedSha;
    private Map<String,Element> peers; private Map<String,String> baselines;
    private int next=0;private boolean firstParticipant;
    private final List<Map<String,Object>> operationEvents=new ArrayList<>();
    private final List<String> attempted=new ArrayList<>();
    private Map<String,Object> operationInput;
    private Map<String,Object> operationOutput;
    private final Map<String,String> requestRefs=new LinkedHashMap<>(),responseRefs=new LinkedHashMap<>();
    private SoapContinuationActor(Path output,String mode,Path source)throws Exception {
        this.baseOutput=output.toAbsolutePath();this.source=source.toRealPath();require(!Files.exists(this.baseOutput));Files.createDirectories(this.baseOutput);setOutput("baseline");
        require("paired".equals(mode));continuation=new ContinuingActor();
        run="run_00000000000000000000000000";plan="plan_00000000000000000000000000";entity="http://localhost:18080/p/"+plan;
        suite=credentials("suite");target=credentials("target");server=HttpServer.create(new InetSocketAddress(InetAddress.getLoopbackAddress(),0),0);server.setExecutor(executor);
        callback="http://localhost:"+server.getAddress().getPort();targetEntity=callback+"/idp/shibboleth";targetSoap=callback+"/idp/profile/SAML2/SOAP/SLO";
        server.createContext("/idp/profile/SAML2/POST/SSO",this::authenticate);server.createContext("/idp/profile/SAML2/SOAP/SLO",this::logout);server.createContext("/p/",this::participant);server.start();
    }
    static PlanCredentials credentials(String subject)throws Exception {
        var generator=KeyPairGenerator.getInstance("RSA");generator.initialize(2048);var pair=generator.generateKeyPair();var now=Instant.now();
        var name=new org.bouncycastle.asn1.x500.X500Name("CN=SOAP control "+subject);
        var builder=new JcaX509v3CertificateBuilder(name,new BigInteger(160,new SecureRandom()).abs(),Date.from(now.minusSeconds(60)),Date.from(now.plusSeconds(3600)),name,pair.getPublic());
        var certificate=new JcaX509CertificateConverter().getCertificate(builder.build(new JcaContentSignerBuilder("SHA256withRSA").build(pair.getPrivate())));return new PlanCredentials(pair.getPrivate(),certificate);
    }
    static String hash(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
    static void require(boolean condition){if(!condition)throw new IllegalArgumentException("Invalid actual SOAP actor operation");}
    static Element element(Document d,Element parent,String ns,String name,String text){var e=d.createElementNS(ns,name);if(text!=null)e.setTextContent(text);parent.appendChild(e);return e;}
    Element message(String type,String id,String issuer,String destination,String responseTo,String status,String session,String name)throws Exception {
        var d=SecureXml.newDocument();var root=d.createElementNS(P,"samlp:"+type);d.appendChild(root);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:samlp",P);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:saml",A);root.setAttribute("ID",id);root.setAttribute("Version","2.0");root.setAttribute("IssueInstant",Instant.now().toString());if(destination!=null)root.setAttribute("Destination",destination);if(responseTo!=null)root.setAttribute("InResponseTo",responseTo);
        element(d,root,A,"saml:Issuer",issuer);
        if(type.endsWith("Response")){var s=element(d,root,P,"samlp:Status",null);var code=element(d,s,P,"samlp:StatusCode",null);code.setAttribute("Value",status);}
        if("LogoutRequest".equals(type)){element(d,root,A,"saml:NameID",name);element(d,root,P,"samlp:SessionIndex",session);}
        if("Response".equals(type)){var assertion=element(d,root,A,"saml:Assertion",null);assertion.setAttribute("ID",id+"-assertion");assertion.setAttribute("Version","2.0");assertion.setAttribute("IssueInstant",Instant.now().toString());element(d,assertion,A,"saml:Issuer",issuer);var subject=element(d,assertion,A,"saml:Subject",null);element(d,subject,A,"saml:NameID",name);var confirmation=element(d,subject,A,"saml:SubjectConfirmation",null);confirmation.setAttribute("Method","urn:oasis:names:tc:SAML:2.0:cm:bearer");var data=element(d,confirmation,A,"saml:SubjectConfirmationData",null);data.setAttribute("Recipient",destination);data.setAttribute("InResponseTo",responseTo);data.setAttribute("NotOnOrAfter",Instant.now().plusSeconds(300).toString());var conditions=element(d,assertion,A,"saml:Conditions",null);var restriction=element(d,conditions,A,"saml:AudienceRestriction",null);element(d,restriction,A,"saml:Audience",name.substring(name.indexOf('|')+1));var statement=element(d,assertion,A,"saml:AuthnStatement",null);statement.setAttribute("SessionIndex",session);statement.setAttribute("AuthnInstant",Instant.now().toString());subject.getFirstChild().setTextContent(name.substring(0,name.indexOf('|')));new XmlSigner().sign(assertion,target,(Element)assertion.getFirstChild().getNextSibling());}
        new XmlSigner().sign(root,issuer.equals(targetEntity)?target:suite,(Element)root.getFirstChild().getNextSibling());return root;
    }
    static byte[] bytes(Element element){var doc=SecureXml.newDocument();doc.appendChild(doc.importNode(element,true));return SecureXml.serialize(doc);}
    static byte[] soap(Element inner){var d=SecureXml.newDocument();var root=d.createElementNS(SOAP,"soap:Envelope");d.appendChild(root);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:soap",SOAP);var body=element(d,root,SOAP,"soap:Body",null);body.appendChild(d.importNode(inner,true));return SecureXml.serialize(d);}
    static Element inner(byte[] raw){var root=SecureXml.parse(raw).getDocumentElement();if(!SOAP.equals(root.getNamespaceURI()))return root;var nodes=root.getElementsByTagNameNS(SOAP,"Body");require(nodes.getLength()==1);Element child=null;for(var n=nodes.item(0).getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e){require(child==null);child=e;}require(child!=null);return child;}
    static String text(Element root,String ns,String name){var nodes=root.getElementsByTagNameNS(ns,name);require(nodes.getLength()==1);return nodes.item(0).getTextContent();}
    static String mode(String trial){return "failure".equals(trial)?"first-arrival":"all-success";}
    static String status(Element root){var nodes=root.getElementsByTagNameNS(P,"StatusCode");require(nodes.getLength()>=1);return ((Element)nodes.item(0)).getAttribute("Value");}
    synchronized String record(Direction direction,String url,Integer status,String correlation,byte[] raw,byte[] saml,Map<String,Object> summary)throws Exception {
        String id="tx_"+String.format("%026d",++next);var at=Instant.now();entries.add(new TranscriptEntry(id,run,direction,at,correlation,"POST",url,status,Map.of(),"transcripts/"+run+"/"+id+".body",raw.length,"transcripts/"+run+"/"+id+".saml.xml",saml.length,"text/xml",URI.create(url).getRawQuery(),summary));decoded.put(id,saml);write("soap/"+id+".xml",raw);return id;
    }
    void setOutput(String name)throws Exception{output=baseOutput.resolve(name);Files.createDirectories(output);receipt=output.resolve("receipt");Files.createDirectories(receipt);}
    void write(String name,byte[] bytes)throws Exception{Path file=receipt.resolve(name);Files.createDirectories(file.getParent());Files.write(file,bytes);}
    static void respond(HttpExchange exchange,byte[] response)throws Exception{exchange.getResponseHeaders().set("Content-Type","text/xml");exchange.sendResponseHeaders(200,response.length);exchange.getResponseBody().write(response);exchange.close();}
    void authenticate(HttpExchange exchange)throws IOException{try {
        byte[] raw=exchange.getRequestBody().readAllBytes();var q=inner(raw);require("AuthnRequest".equals(q.getLocalName())&&new XmlSignatureVerifier().hasValidEnvelopedSignature(q,suite.certificate()));String issuer=text(q,A,"Issuer");String label=issuer.equals(entity)?"primary":issuer.substring((entity+"/sp-").length());require(peers.containsKey(label)&&!registered.containsKey(label));String index="public-"+trial+"-"+label;String principal="public-control-principal-"+trial;var peer=peers.get(label);String endpoint=((Element)peer.getElementsByTagNameNS(MD,"SingleLogoutService").item(0)).getAttribute("Location");registered.put(label,new Session(label,issuer,index,principal,endpoint));var response=message("Response","_registration_"+trial+"_"+label,targetEntity,q.getAttribute("AssertionConsumerServiceURL"),q.getAttribute("ID"),SUCCESS,index,principal+"|"+issuer);respond(exchange,bytes(response));
    }catch(Exception ex){exchange.sendResponseHeaders(500,-1);exchange.close();}}
    Map<String,Object> peerSummary(String type,String label){var m=new LinkedHashMap<String,Object>();m.put("type",type);m.put("transport","SOAP");m.put("propagationFixture","error-v2");m.put("propagationMode",mode(trial));m.put("propagationOrdinal",requestRefs.size()+1);m.put("propagationTrial",trial);m.put("propagationParticipant",label);m.put("preparedMetadataRef",preparedRef);m.put("preparedMetadataSha256",preparedSha);return m;}
    void participant(HttpExchange exchange)throws IOException{try{
        byte[] raw=exchange.getRequestBody().readAllBytes();var q=inner(raw);require(new XmlSignatureVerifier().hasValidEnvelopedSignature(q,target.certificate()));String url=callback+exchange.getRequestURI();String label=null;for(var session:registered.values())if(session.endpoint().equals(url))label=session.label();require(label!=null&&!requestRefs.containsKey(label));String ref=record(Direction.INBOUND,url,null,q.getAttribute("ID"),raw,raw,peerSummary("LogoutRequest",label));requestRefs.put(label,ref);String status="failure".equals(trial)&&firstParticipant?RESPONDER:SUCCESS;firstParticipant=false;var response=message("LogoutResponse","_participant_"+trial+"_"+label,registered.get(label).entity(),targetSoap,q.getAttribute("ID"),status,null,null);byte[] envelope=soap(response);var summary=peerSummary("LogoutResponse",label);summary.put("propagationOrdinal",requestRefs.size());summary.put("producerBoundary","soapResponse-return");summary.put("responseStatus",status);responseRefs.put(label,record(Direction.OUTBOUND,targetSoap,200,response.getAttribute("ID"),envelope,envelope,summary));respond(exchange,envelope);
    }catch(Exception ex){exchange.sendResponseHeaders(500,-1);exchange.close();}}
    void logout(HttpExchange exchange)throws IOException{try{
        byte[] raw=exchange.getRequestBody().readAllBytes();var origin=inner(raw);require(new XmlSignatureVerifier().hasValidEnvelopedSignature(origin,suite.certificate())&&entity.equals(text(origin,A,"Issuer")));var primary=registered.get("primary");require(primary!=null&&primary.index().equals(text(origin,P,"SessionIndex"))&&primary.name().equals(text(origin,A,"NameID")));var remaining=new LinkedHashMap<>(registered);remaining.remove("primary");require(remaining.size()==3);var selected=new ArrayList<Map<String,Object>>();for(var s:remaining.values())selected.add(Map.of("label",s.label(),"entity",s.entity(),"endpoint",s.endpoint(),"sessionIndexSha256",hash(s.index().getBytes(StandardCharsets.UTF_8)),"nameIdSha256",hash(("{"+A+"}NameID{}"+s.name()).getBytes(StandardCharsets.UTF_8))));
        operationInput=Map.of("schema","samlscope-slo-continuation-actor-input-v1","runId",run,"trial",trial,"targetMetadataSha256",hash(Files.readAllBytes(output.resolve("target-metadata.xml"))),"preparedSha256",preparedSha,"originRequestId",origin.getAttribute("ID"),"originRequestSha256",hash(bytes(origin)),"selectedSessions",selected);
        write("actor/"+trial+"-input.json",JSON.mapper().writeValueAsBytes(operationInput));attempted.clear();operationEvents.clear();boolean failed=false;
        while(!remaining.isEmpty()) {
            var session=remaining.values().iterator().next();remaining.remove(session.label());var request=message("LogoutRequest","_propagation_"+trial+"_"+session.label(),targetEntity,session.endpoint(),null,null,session.index(),session.name());byte[] envelope=soap(request);attempted.add(session.label());var begin=Instant.now();
            operationEvents.add(Map.of("event","send","label",session.label(),"requestId",request.getAttribute("ID"),"requestSha256",hash(bytes(request)),"rawEnvelopeSha256",hash(envelope),"at",begin.toString()));
            var result=client.send(HttpRequest.newBuilder(URI.create(session.endpoint())).timeout(Duration.ofSeconds(8)).header("Content-Type","text/xml").POST(HttpRequest.BodyPublishers.ofByteArray(envelope)).build(),HttpResponse.BodyHandlers.ofByteArray());require(result.statusCode()==200);var response=inner(result.body());require(new XmlSignatureVerifier().hasValidEnvelopedSignature(response,suite.certificate())&&session.entity().equals(text(response,A,"Issuer"))&&request.getAttribute("ID").equals(response.getAttribute("InResponseTo")));String resultStatus=status(response);operationEvents.add(Map.of("event","verified-response","label",session.label(),"requestId",request.getAttribute("ID"),"responseId",response.getAttribute("ID"),"responseSha256",hash(bytes(response)),"rawEnvelopeSha256",hash(result.body()),"status",resultStatus,"at",Instant.now().toString()));failed|=!SUCCESS.equals(resultStatus);
            if(!continuation.continueAfter(resultStatus))break;
        }
        var response=message("LogoutResponse","_origin_final_"+trial,targetEntity,null,origin.getAttribute("ID"),SUCCESS,null,null);if(failed){var top=(Element)response.getElementsByTagNameNS(P,"StatusCode").item(0);var sub=element(response.getOwnerDocument(),top,P,"samlp:StatusCode",null);sub.setAttribute("Value","urn:oasis:names:tc:SAML:2.0:status:PartialLogout");var sig=(Element)response.getElementsByTagNameNS(DS,"Signature").item(0);sig.getParentNode().removeChild(sig);new XmlSigner().sign(response,target,(Element)response.getFirstChild().getNextSibling());}
        operationOutput=Map.of("schema","samlscope-slo-continuation-actor-output-v1","runId",run,"trial",trial,"originRequestId",origin.getAttribute("ID"),"actorClass",continuation.getClass().getName(),"events",List.copyOf(operationEvents),"terminal",Map.of("at",Instant.now().toString(),"selected",selected.stream().map(x->x.get("label")).toList(),"attempted",List.copyOf(attempted),"remaining",List.copyOf(remaining.keySet()),"originFinalId",response.getAttribute("ID"),"originFinalSha256",hash(bytes(response))));write("actor/"+trial+"-output.json",JSON.mapper().writeValueAsBytes(operationOutput));trace();respond(exchange,soap(response));
    }catch(Exception ex){exchange.sendResponseHeaders(500,-1);exchange.close();}}
    Map<String,String> producerClasses()throws Exception {Path base=Path.of(SoapContinuationActor.class.getProtectionDomain().getCodeSource().getLocation().toURI());var classes=new TreeMap<String,String>();try(var paths=Files.walk(base)){for(var file:paths.filter(Files::isRegularFile).toList())if(file.getFileName().toString().startsWith("SoapContinuationActor")&&file.toString().endsWith(".class"))classes.put(file.getFileName().toString(),hash(Files.readAllBytes(file)));}require(!classes.isEmpty());return classes;}
    void trace()throws Exception {var doc=SecureXml.newDocument();String ns="urn:samlscope:diagnostic:continuation";var root=doc.createElementNS(ns,"proof:Operation");doc.appendChild(root);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:proof",ns);root.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:saml",A);root.setAttribute("ID","_actor_trace_"+trial);root.setAttribute("runId",run);root.setAttribute("trial",trial);root.setAttribute("sourceSha256",hash(Files.readAllBytes(source)));root.setAttribute("classesSha256",hash(JSON.mapper().writeValueAsBytes(producerClasses())));root.setAttribute("inputSha256",hash(Files.readAllBytes(receipt.resolve("actor/"+trial+"-input.json"))));root.setAttribute("outputSha256",hash(Files.readAllBytes(receipt.resolve("actor/"+trial+"-output.json"))));element(doc,root,A,"saml:Issuer",targetEntity);element(doc,root,ns,"proof:Input",Base64.getEncoder().encodeToString(Files.readAllBytes(receipt.resolve("actor/"+trial+"-input.json"))));element(doc,root,ns,"proof:Output",Base64.getEncoder().encodeToString(Files.readAllBytes(receipt.resolve("actor/"+trial+"-output.json"))));new XmlSigner().sign(root,target,(Element)root.getFirstChild().getNextSibling());write("actor/"+trial+"-trace.xml",SecureXml.serialize(doc));}
    byte[] targetMetadata()throws Exception{return ("<md:EntityDescriptor xmlns:md='"+MD+"' xmlns:ds='"+DS+"' entityID='"+targetEntity+"'><md:IDPSSODescriptor protocolSupportEnumeration='"+P+"'><md:KeyDescriptor use='signing'><ds:KeyInfo><ds:X509Data><ds:X509Certificate>"+Base64.getEncoder().encodeToString(target.certificate().getEncoded())+"</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleSignOnService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' Location='"+callback+"/idp/profile/SAML2/POST/SSO'/><md:SingleLogoutService Binding='"+B+"' Location='"+targetSoap+"'/></md:IDPSSODescriptor></md:EntityDescriptor>").getBytes(StandardCharsets.UTF_8);}
    void trial(String trial)throws Exception {
        this.trial=trial;registered.clear();requestRefs.clear();responseRefs.clear();firstParticipant=true;baselines=new LinkedHashMap<>();var at=preparedTimes.computeIfAbsent(trial,k->Instant.now());byte[] md=preparedCache.get(trial);if(md==null){md=SloPropagationFixtures.prepare(URI.create(entity),URI.create(entity+"/sp/acs/0"),suite,run,trial,at,URI.create(callback));preparedCache.put(trial,md);}preparedSha=hash(md);var summary=Map.<String,Object>of("type","MetadataPrepared","variant","slo-propagation-soap-"+trial,"case_id",CASE,"run_id",run,"plan_id",plan,"prepared_at",at.toString());preparedRef=record(Direction.OUTBOUND,entity+"/metadata",200,null,md,md,summary);peers=ShibbolethNativeSloContinuationEvidence.preparedPeers(SecureXml.parse(md).getDocumentElement(),entity,run,trial);
        for(String label:List.of("primary","fail","remain","remain2")){String peerEntity=label.equals("primary")?entity:entity+"/sp-"+label;var request=message("AuthnRequest","_registration_request_"+trial+"_"+label,peerEntity,callback+"/idp/profile/SAML2/POST/SSO",null,null,null,null);request.setAttribute("AssertionConsumerServiceURL",entity+"/sp/acs/0");var old=(Element)request.getElementsByTagNameNS(DS,"Signature").item(0);request.removeChild(old);new XmlSigner().sign(request,suite,(Element)request.getFirstChild().getNextSibling());byte[] body=authnCache.get(trial+"-"+label);if(body==null){body=bytes(request);authnCache.put(trial+"-"+label,body);}request=inner(body);String rq=record(Direction.OUTBOUND,callback+"/idp/profile/SAML2/POST/SSO",null,request.getAttribute("ID"),body,body,Map.of("type","AuthnRequest"));var result=client.send(HttpRequest.newBuilder(URI.create(callback+"/idp/profile/SAML2/POST/SSO")).timeout(Duration.ofSeconds(8)).POST(HttpRequest.BodyPublishers.ofByteArray(body)).build(),HttpResponse.BodyHandlers.ofByteArray());require(result.statusCode()==200);var response=inner(result.body());require(new XmlSignatureVerifier().hasValidEnvelopedSignature(response,target.certificate()));baselines.put(label,record(Direction.INBOUND,entity+"/sp/acs/0",200,request.getAttribute("ID"),result.body(),result.body(),Map.of("type","Response","inResponseTo",request.getAttribute("ID"),"request_transcript",rq)));}
        var session=registered.get("primary");String action=ShibbolethNativeSloContinuationEvidence.originActionId(run,trial);var origin=message("LogoutRequest","_"+action,entity,targetSoap,null,null,session.index(),session.name());byte[] envelope=originCache.get(trial);if(envelope==null){envelope=soap(origin);originCache.put(trial,envelope);}origin=inner(envelope);String rq=record(Direction.OUTBOUND,targetSoap,null,action,envelope,bytes(origin),Map.of("type","LogoutRequest","kind","LOGOUT_PROBE","probe_transport","direct-soap","action_id",action));var result=client.send(HttpRequest.newBuilder(URI.create(targetSoap)).timeout(Duration.ofSeconds(20)).header("Content-Type","text/xml").POST(HttpRequest.BodyPublishers.ofByteArray(envelope)).build(),HttpResponse.BodyHandlers.ofByteArray());require(result.statusCode()==200);var response=inner(result.body());String rs=record(Direction.INBOUND,targetSoap,200,action,result.body(),bytes(response),Map.of("type","SloProbeHttpResponse","saml_message","LogoutResponse","probe_transport","direct-soap","in_response_to",origin.getAttribute("ID"),"request_transcript",rq));
        var rows=new ArrayList<Map<String,Object>>();for(String label:attempted){String file="actor/"+trial+"-"+label+"-metadata.xml";var doc=SecureXml.newDocument();doc.appendChild(doc.importNode(peers.get(label),true));write(file,SecureXml.serialize(doc));rows.add(Map.of("label",label,"requestReference",requestRefs.get(label),"responseReference",responseRefs.get(label),"nativeMetadataFile",file));}
        trials.add(Map.of("trial",trial,"preparedReference",preparedRef,"originRequestReference",rq,"originResponseReference",rs,"participants",rows,"baselines",baselines.entrySet().stream().map(e->Map.of("label",e.getKey(),"responseReference",e.getValue())).toList(),"operationInputFile","actor/"+trial+"-input.json","operationOutputFile","actor/"+trial+"-output.json","operationTraceFile","actor/"+trial+"-trace.xml"));
    }
    void run()throws Exception {byte[] targetBytes=targetMetadata();Files.write(output.resolve("target-metadata.xml"),targetBytes);trial("failure");trial("all-success");write("actor/SoapContinuationActor.java",Files.readAllBytes(source));Path classBase=Path.of(SoapContinuationActor.class.getProtectionDomain().getCodeSource().getLocation().toURI());try(var paths=Files.walk(classBase)){for(var c:paths.filter(Files::isRegularFile).toList())if(c.getFileName().toString().startsWith("SoapContinuationActor")&&c.toString().endsWith(".class"))write("actor/classes/"+c.getFileName(),Files.readAllBytes(c));}write("actor/classes.json",JSON.mapper().writeValueAsBytes(producerClasses()));Files.write(output.resolve("transcript.json"),JSON.mapper().writeValueAsBytes(entries));var rows=new ArrayList<Map<String,Object>>();for(var row:decoded.entrySet()){String file="decoded/"+row.getKey()+".xml";Files.createDirectories(output.resolve("decoded"));Files.write(output.resolve(file),row.getValue());rows.add(Map.of("id",row.getKey(),"file",file,"sha256",hash(row.getValue())));}Files.write(output.resolve("decoded-manifest.json"),JSON.mapper().writeValueAsBytes(rows));var files=new TreeMap<String,String>();try(var paths=Files.walk(receipt)){for(var p:paths.filter(Files::isRegularFile).toList())files.put(receipt.relativize(p).toString(),hash(Files.readAllBytes(p)));}var manifest=new LinkedHashMap<String,Object>();manifest.put("schema","samlscope-suite-actor-soap-continuation-v1");manifest.put("runId",run);manifest.put("planId",plan);manifest.put("targetMetadataSha256",hash(targetBytes));manifest.put("producerSourceFile","actor/SoapContinuationActor.java");manifest.put("producerSourceSha256",hash(Files.readAllBytes(source)));manifest.put("actorClass",continuation.getClass().getName());manifest.put("producerClassesFile","actor/classes.json");manifest.put("publicCallbackBase",callback);manifest.put("trials",trials);manifest.put("files",files);Files.write(receipt.resolve("manifest.json"),JSON.mapper().writeValueAsBytes(manifest));Files.write(output.resolve("operation-counts.json"),JSON.mapper().writeValueAsBytes(Map.of("diagnosticTargetAuthenticationRequests",8,"diagnosticOriginSoapRequests",2,"diagnosticParticipantSoapRequests",requestRefs.size()+(continuation instanceof StopAfterErrorActor?1:3),"productConfigurationWrites",0,"productLogins",0,"personInteractions",0,"credentialsPersisted",false)));}
    public static void main(String[]args)throws Exception {require(args.length==3);var actor=new SoapContinuationActor(Path.of(args[0]),args[1],Path.of(args[2]));try{actor.run();actor.entries.clear();actor.decoded.clear();actor.trials.clear();actor.next=0;actor.continuation=new StopAfterErrorActor();actor.setOutput("mutant");actor.run();}finally{actor.server.stop(0);actor.executor.shutdownNow();}}
}
