package com.samlscope.runner.cases;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.function.BiFunction;

/** Actual archived production JAR first. Native public calibration never enters Recorder or the API. */
public final class VerifyShibbolethSelfContainedTrustEvidence {
 static final ObjectMapper M=new JsonCodec().mapper();static final String CASE="IIP-MD06-c-idp-01";
 static void require(boolean b,String s){if(!b)throw new IllegalArgumentException(s);}
 static String sha(byte[] b)throws Exception{return VerifyNativeRoleKeyConsumption.hash(b);}
 record Data(String run,String plan,byte[] target,List<TranscriptEntry> entries,Map<String,byte[]> decoded,BiFunction<String,String,Optional<PlanCredentials>> keys){}
 static void safe(Path root,Path file){require(file.toAbsolutePath().normalize().startsWith(root.toAbsolutePath().normalize()),"outside public root");for(var p=file;p!=null;p=p.getParent())require(!Files.isSymbolicLink(p),"symlink source");require(Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS),"missing original");}
 static Data load(Path source,Path data,Path role)throws Exception {
  var created=M.readTree(source.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText();require(run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&plan.matches("plan_[0-9A-HJKMNP-TV-Z]{26}"),"foreign Plan/Run");
  safe(data,data.resolve("samlscope.db"));try(var c=DriverManager.getConnection("jdbc:sqlite:file:"+data.resolve("samlscope.db")+"?mode=ro");var q=c.prepareStatement("SELECT plan_id FROM runs WHERE id=?")){q.setString(1,run);try(var r=q.executeQuery()){require(r.next()&&plan.equals(r.getString(1))&&!r.next(),"unknown Run/Plan");}}
  var entries=List.of(M.readValue(source.resolve("transcript.json").toFile(),TranscriptEntry[].class));var decoded=new HashMap<String,byte[]>();for(var row:M.readTree(source.resolve("decoded-manifest.json").toFile())){Path file=source.resolve(row.path("file").asText()).normalize();safe(source,file);require(file.getParent().equals(source.resolve("decoded")),"decoded escaped");byte[] raw=Files.readAllBytes(file);require(sha(raw).equals(row.path("sha256").asText())&&decoded.put(row.path("id").asText(),raw)==null,"decoded changed");}
  var keyRoot=data.resolve("keys").resolve(plan);require(Files.isDirectory(keyRoot,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(keyRoot),"unsafe Plan keys");for(String name:List.of("signing-certificate.der","signing-key.pk8"))safe(data,keyRoot.resolve(name));try(var files=Files.list(keyRoot)){for(var child:files.filter(p->Files.isDirectory(p,LinkOption.NOFOLLOW_LINKS)).toList()){require(child.getFileName().toString().matches("(?:poll-[a-f0-9]{16}|roll[23]-[a-f0-9]{24})"),"unknown polling key");for(String name:List.of("signing-certificate.der","signing-key.pk8"))safe(data,child.resolve(name));}}
  byte[] target=Files.readAllBytes(source.resolve("target-metadata.xml"));VerifyNativeRoleKeyConsumption.baseline(source.resolve("source-role"),run,plan,entries,decoded,target);return new Data(run,plan,target,entries,decoded,VerifyNativeRoleKeyConsumption.keys(run,plan,role));
 }
 static class Fallback implements TestCase,AttestationPrompt {public String id(){return CASE;}public TargetRole role(){return TargetRole.IDP;}public String promptEn(){return "Approved attestation fallback";}public List<AttestationOption>options(){return List.of();}public CaseStep start(CaseContext c){throw new AssertionError("Owned native proof escaped to attestation");}public CaseStep resume(CaseContext c,CaseState s,CaseEvent e){throw new AssertionError("Owned proof escaped");}}
 static CaseOutcome observe(Path trust,Path role,Data d,boolean offline)throws Exception {
  var context=VerifyNativeRoleKeyConsumption.context(d.run,d.entries,true);var leaf=new ShibbolethSelfContainedTrustEvidenceFile(trust,role,e->d.decoded.get(e.id()),r->r.equals(d.run)?d.target:null,d.keys,offline);var expected=leaf.evaluate(context);var wrapper=new SelfContainedMetadataTrustEvidenceTestCase(new Fallback(),leaf::exists,leaf::evaluate,ShibbolethSelfContainedTrustEvidenceFile.ADAPTER,"native-self-contained-trust-evidence",".shibboleth-trust.json",offline);
  require(wrapper.start(context).equals(new CaseStep.Finish(expected)),"start mismatch");for(var event:List.<CaseEvent>of(new CaseEvent.ConfigConfirmed(),new CaseEvent.TranscriptReady(),new CaseEvent.Attested("satisfied","unused"),new CaseEvent.Aborted("finished")))require(wrapper.resume(context,CaseState.initial(),event).equals(new CaseStep.Finish(expected)),"resume mismatch");
  if(expected.outcome()!=Outcome.NOT_VERIFIED){require(wrapper.evidenceStatus(context).ready()&&wrapper.reevaluateRecordedEvidence(context,CaseOutcome.notVerified("pending","case.pending-interaction")).orElseThrow().equals(expected),"recorded mismatch");require(wrapper.reevaluateRecordedEvidence(context,expected).isEmpty(),"conclusive reevaluated");}else require(!wrapper.evidenceStatus(context).ready(),"incomplete proof ready");return expected;
 }
 static void copyPublic(Path from,Path to)throws Exception{try(var paths=Files.walk(from)){for(var p:paths.filter(Files::isRegularFile).toList()){safe(from,p);var dest=to.resolve(from.relativize(p));Files.createDirectories(dest.getParent());if(p.getFileName().toString().endsWith(".jar")){try{Files.createLink(dest,p);}catch(java.io.IOException denied){Files.copy(p,dest);}}else Files.copy(p,dest);}}}
 static Map<String,byte[]> originals(Path folder)throws Exception{var result=new LinkedHashMap<String,byte[]>();try(var paths=Files.walk(folder)){for(var p:paths.filter(Files::isRegularFile).filter(p->!p.getFileName().toString().endsWith(".jar")).toList())result.put(folder.relativize(p).toString(),Files.readAllBytes(p));}return result;}
 static void restore(Path root,Map<String,byte[]> bytes)throws Exception{for(var e:bytes.entrySet())Files.write(root.resolve(e.getKey()),e.getValue());}
 static void editBound(Path payload,ObjectNode receipt,String name,java.util.function.Consumer<ObjectNode> action)throws Exception{var p=payload.resolve(receipt.path(name+"File").asText());var n=(ObjectNode)M.readTree(p.toFile());action.accept(n);byte[] raw=M.writeValueAsBytes(n);Files.write(p,raw);receipt.put(name+"Sha256",sha(raw));}
 static void editRole(Path role,ObjectNode receipt,String file,java.util.function.Consumer<ObjectNode> action)throws Exception{var n=(ObjectNode)M.readTree(role.resolve(file).toFile());action.accept(n);byte[] raw=M.writeValueAsBytes(n);Files.write(role.resolve(file),raw);var m=(ObjectNode)M.readTree(role.resolve("manifest.json").toFile());((ObjectNode)m.path("originals")).put(file,sha(raw));byte[] mr=M.writeValueAsBytes(m);Files.write(role.resolve("manifest.json"),mr);receipt.put("roleReceiptSha256",sha(mr));}
 static void write(Path receipt,ObjectNode m)throws Exception{Files.write(receipt,M.writeValueAsBytes(m));}
 public static void main(String[]args)throws Exception {
  require(args.length==3,"proof-folder data-root output");M.enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);java.util.logging.LogManager.getLogManager().reset();Path source=Path.of(args[0]).toRealPath(),data=Path.of(args[1]).toAbsolutePath().normalize(),output=Path.of(args[2]);require(!Files.exists(output),"immutable report");String run=M.readTree(source.resolve("trust-receipt.json").toFile()).path("runId").asText();Path temp=Files.createTempDirectory("shib-role-trust-replay-");var roleRoot=temp.resolve("metadata-role-key-evidence");var role=roleRoot.resolve(run);var trust=temp.resolve("metadata-trust-evidence");var payload=trust.resolve(run+".shibboleth-trust");var receipt=trust.resolve(run+".shibboleth-trust.json");
  try {
   copyPublic(source.resolve("source-role/receipt"),role);copyPublic(source.resolve("receipt"),payload);Files.write(receipt,Files.readAllBytes(source.resolve("trust-receipt.json")));Data base=load(source,data,role);var tr=originals(trust);var rr=originals(role);byte[] ci=Files.readAllBytes(payload.resolve("calibration-input.json")),co=Files.readAllBytes(payload.resolve("native-calibration-output.json"));Files.delete(payload.resolve("calibration-input.json"));Files.delete(payload.resolve("native-calibration-output.json"));var outcome=observe(trust,roleRoot,base,false);Files.write(payload.resolve("calibration-input.json"),ci);Files.write(payload.resolve("native-calibration-output.json"),co);require(outcome.outcome()==Outcome.SATISFIED,"Actual stock not SAT: "+outcome);var checks=new TreeMap<String,String>();
   for(String name:List.of("wrong-run","wrong-adapter","wrong-case","wrong-campaign","wrong-target","foreign-role-receipt","missing-output","native-source-mismatch","native-class-mismatch","native-input-mismatch","native-own-signature-rejected","extra-stock-trust-input","missing-restoration","omitted-cost","public-diagnostic-user-operation","private-material-claim","unknown-path","calibration-label-mismatch","foreign-history","duplicate-history","foreign-decoded-ref","missing-encrypted-normal","wrong-decryption-key","missing-epoch","missing-negative-control","scope-after-http-start","scope-before-http-end","unknown-property-override","runtime-epoch-changed","restoration-native-identity-changed","missing-original-restoration","foreign-role-native-runtime-projection")){
    restore(trust,tr);restore(role,rr);var m=(ObjectNode)M.readTree(receipt.toFile());var d=base;String variant=MetadataRoleKeyProbeTestCase.VARIANTS.getFirst();var roleM=M.readTree(role.resolve("manifest.json").toFile());var epoch=roleM.path("observations").get(0);var normal=epoch.path("exchanges").get(0);
    switch(name){
     case "wrong-run"->m.put("runId","run_00000000000000000000000000");case "wrong-adapter"->m.put("adapter","unknown");case "wrong-case"->m.put("caseId","IIP-MD06-a-idp-01");case "wrong-campaign"->m.put("campaignId","unrelated");case "wrong-target"->m.put("targetMetadataSha256","0".repeat(64));case "foreign-role-receipt"->m.put("roleReceiptSha256","0".repeat(64));case "missing-output"->m.put("nativeOutputFile","missing.json");case "native-source-mismatch"->m.put("producerSha256","0".repeat(64));
     case "native-class-mismatch"->editBound(payload,m,"nativeOutput",n->((ObjectNode)n.path("selectedNativeClassHashes")).put("org.opensaml.saml.security.impl.MetadataCredentialResolver","0".repeat(64)));
     case "native-input-mismatch"->editBound(payload,m,"input",n->((ObjectNode)n.path("records").get(0)).put("requestSha256","0".repeat(64)));
     case "native-own-signature-rejected","extra-stock-trust-input"->editBound(payload,m,"nativeOutput",n->((ObjectNode)n.path("records").get(0)).put(name.equals("native-own-signature-rejected")?"stockNativeSignatureAccepted":"stockAdditionalTrustInputSupplied",name.equals("extra-stock-trust-input")));
     case "missing-restoration"->editBound(payload,m,"operations",n->n.put("temporarySourceRemoved",false));case "omitted-cost"->editBound(payload,m,"operations",n->n.put("nativePublicJavaCalls",0));case "public-diagnostic-user-operation"->editBound(payload,m,"operations",n->n.put("credentialPosts",1));case "private-material-claim"->editBound(payload,m,"nativeOutput",n->n.put("privateKeyRead",true));case "unknown-path"->m.put("selectedPath","unknown");case "calibration-label-mismatch"->m.put("counterfactualCalibrationOnly",true);
     case "foreign-history","foreign-decoded-ref","duplicate-history"->{var rows=new ArrayList<>(base.entries);if(name.equals("duplicate-history"))rows.add(rows.getFirst());else{int i=0;while(rows.get(i).decodedSamlRef()==null)i++;var e=rows.get(i);rows.set(i,VerifyNativeRoleKeyConsumption.altered(e,name.equals("foreign-history")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-decoded-ref")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef()));}d=new Data(base.run,base.plan,base.target,rows,base.decoded,base.keys);}
     case "missing-encrypted-normal"->{var bytes=new HashMap<>(base.decoded);bytes.remove(normal.path("responseReference").asText());d=new Data(base.run,base.plan,base.target,base.entries,bytes,base.keys);}
     case "wrong-decryption-key"->{var a=base.keys.apply(run,"three-signing-keys-first").orElseThrow();d=new Data(base.run,base.plan,base.target,base.entries,base.decoded,(r,v)->v.equals("three-signing-keys")?Optional.of(a):base.keys.apply(r,v));}
     case "missing-epoch","missing-negative-control"->{var n=(ObjectNode)roleM;if(name.equals("missing-epoch"))((ArrayNode)n.path("observations")).remove(1);else((ArrayNode)n.path("observations").get(0).path("exchanges")).remove(1);byte[] bytes=M.writeValueAsBytes(n);Files.write(role.resolve("manifest.json"),bytes);m.put("roleReceiptSha256",sha(bytes));}
     case "scope-after-http-start","scope-before-http-end"->{String phase=name.equals("scope-after-http-start")?"before":"after";editRole(role,m,"trust-"+variant+"-"+phase+"-observed.json",n->n.put("recordedAt",phase.equals("before")?epoch.path("completedAt").asText():epoch.path("startedAt").asText()));}
     case "unknown-property-override"->editRole(role,m,"trust-"+variant+"-before-selected-properties.json",n->n.put("idp.trust.signatures","custom.PKIX"));case "runtime-epoch-changed"->editRole(role,m,"trust-runtime-protocol-end.json",n->n.put("startedAt","1970-01-01T00:00:00Z"));case "restoration-native-identity-changed"->editRole(role,m,"trust-runtime-final.json",n->n.put("id","other"));case "missing-original-restoration"->editRole(role,m,"trust-product-restoration.json",n->n.put("restored",false));case "foreign-role-native-runtime-projection"->{var manifest=(ObjectNode)M.readTree(role.resolve("manifest.json").toFile());for(String file:List.of("target-container-inspect-start.json","target-container-inspect-end.json")){var n=M.readTree(role.resolve(file).toFile());((ObjectNode)n.get(0).path("State")).put("StartedAt","2026-10-03T08:00:00Z");byte[] raw=M.writeValueAsBytes(n);Files.write(role.resolve(file),raw);((ObjectNode)manifest.path("originals")).put(file,sha(raw));}byte[] raw=M.writeValueAsBytes(manifest);Files.write(role.resolve("manifest.json"),raw);m.put("roleReceiptSha256",sha(raw));}
    }
    write(receipt,m);var result=observe(trust,roleRoot,d,false);require(result.outcome()==Outcome.NOT_VERIFIED,"failed calibration "+name+": "+result);checks.put(name,"NOT_VERIFIED");
   }
   restore(trust,tr);restore(role,rr);var m=(ObjectNode)M.readTree(receipt.toFile());m.put("selectedPath","developer-instrumented-additional-anchor").put("counterfactualCalibrationOnly",true);write(receipt,m);var label=observe(trust,roleRoot,base,true);require(label.outcome()==Outcome.NOT_VERIFIED,"label-only calibration leaked");checks.put("receipt-label-only-mutant","NOT_VERIFIED");m.put("inputFile",m.path("calibrationInputFile").asText()).put("inputSha256",m.path("calibrationInputSha256").asText()).put("nativeOutputFile",m.path("calibrationOutputFile").asText()).put("nativeOutputSha256",m.path("calibrationOutputSha256").asText());write(receipt,m);var productionMutant=observe(trust,roleRoot,base,false);require(productionMutant.outcome()==Outcome.NOT_VERIFIED,"native diagnostic leaked to production");var mutant=observe(trust,roleRoot,base,true);require(mutant.outcome()==Outcome.VIOLATED,"approved additional-anchor mutant missed: "+mutant);
   var report=new TreeMap<String,Object>();report.put("runId",run);report.put("caseId",CASE);report.put("targetMetadataSha256",sha(base.target));report.put("outcome",outcome);report.put("negativeControls",checks);report.put("approvedMutant",mutant);report.put("productionMutantOutcome",productionMutant);report.put("sameReaderPredicateAndExplicitOfflineWrapper",true);report.put("counterfactualAdoptedAsProductFinding",false);report.put("privateKeyExported",false);report.put("plaintextPersisted",false);for(String key:List.of("productConfigurationWrites","protocolOperations","credentialPosts"))report.put(key,0);Files.write(output,M.writerWithDefaultPrettyPrinter().writeValueAsBytes(report));
  }finally{try(var files=Files.walk(temp)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
}
