package com.samlscope.runner.cases;
import com.samlscope.store.JsonCodec;
import com.samlscope.core.transcript.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.evaluation.*;
import com.samlscope.runner.DefaultCaseContext;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.Clock;
import java.util.*;
public final class VerifyKeycloakSubjectConfirmation {
 static final com.fasterxml.jackson.databind.ObjectMapper M=new JsonCodec().mapper();
 static String hash(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
 static void edit(Path folder,ObjectNode receipt,String name,java.util.function.Consumer<ObjectNode> action)throws Exception{var file=folder.resolve(name);var n=(ObjectNode)M.readTree(Files.readAllBytes(file));action.accept(n);var raw=M.writeValueAsBytes(n);Files.write(file,raw);((ObjectNode)receipt.path("files")).put(name,hash(raw));}
 static void body(ObjectNode record,java.util.function.Consumer<ObjectNode> action){try{var n=(ObjectNode)M.readTree(Base64.getDecoder().decode(record.path("response_base64").asText()));action.accept(n);var raw=M.writeValueAsBytes(n);record.put("response_base64",Base64.getEncoder().encodeToString(raw));record.put("response_sha256",hash(raw));}catch(Exception e){throw new IllegalArgumentException(e);}}
 public static void main(String[] args)throws Exception{
  var source=Path.of(args[0]).toAbsolutePath().normalize();var output=Path.of(args[2]);if(Files.exists(output))throw new IllegalArgumentException("Immutable output exists");String run=M.readTree(source.resolve("created.json").toFile()).at("/run/id").asText();var entries=List.of(M.readValue(source.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new HashMap<String,byte[]>();for(var row:M.readTree(source.resolve("decoded-manifest.json").toFile())){var raw=Files.readAllBytes(source.resolve(row.path("file").asText()));if(!hash(raw).equals(row.path("sha256").asText()))throw new IllegalArgumentException("Original changed");bodies.put(row.path("id").asText(),raw);}var receipt=(ObjectNode)M.readTree(source.resolve("qualified-receipt.json").toFile());var target=Files.readAllBytes(source.resolve("target-metadata.xml"));var originals=new LinkedHashMap<String,byte[]>();try(var paths=Files.walk(source.resolve("originals"))){for(var f:paths.filter(Files::isRegularFile).toList())originals.put(source.resolve("originals").relativize(f).toString(),Files.readAllBytes(f));}
  var directory=Files.createTempDirectory("kc-attester-replay-").toRealPath();var folder=Files.createDirectory(directory.resolve(run+".keycloak-subject-confirmation"));var path=directory.resolve(run+".keycloak-subject-confirmation.json");var outcomes=new TreeMap<String,CaseOutcome>();var controls=new TreeMap<String,String>();
  try{reset(folder,originals);Files.write(path,Files.readAllBytes(source.resolve("qualified-receipt.json")));for(String id:List.of(KeycloakSubjectConfirmationEvidence.FR,KeycloakSubjectConfirmationEvidence.GD)){var result=observe(directory,run,id,entries,bodies,target,"browser_sso_idp");if(result.outcome()!=Outcome.SATISFIED_WITH_NOTE)throw new IllegalStateException("Actual stock proof incomplete "+result);outcomes.put(id,result);}
   for(String name:List.of("wrong-run","wrong-campaign","wrong-target","wrong-profile","wrong-peer","missing-restoration","restore-client-remains","native-runtime-changed","classpath-injected","process-injected","unknown-factory","unknown-factory-property","unknown-effective-mapper","client-signature-disabled","foreign-attester-setting","client-before-after-differ","missing-source-jar","native-source-mutated","source-producer-mutated","control-purpose-product","control-target-trust-change","control-signer-in-product-evidence","semantic-positive-swapped","signed-calibration-tampered","duplicate-transcript","foreign-transcript-run","foreign-content-reference","directory-receipt","symlink-receipt")){
    reset(folder,originals);var changed=receipt.deepCopy();var history=new ArrayList<>(entries);var actualBodies=new HashMap<>(bodies);byte[] actualTarget=target;String profile="browser_sso_idp";
    switch(name){
     case "wrong-run"->changed.put("runId","run_00000000000000000000000000");case "wrong-campaign"->changed.put("campaignId","other");case "wrong-target"->changed.put("targetMetadataSha256","0".repeat(64));case "wrong-profile"->profile="metadata_idp";case "wrong-peer"->changed.put("peerEntityId","other");
     case "missing-restoration"->Files.delete(folder.resolve("restoration.json"));case "restore-client-remains"->edit(folder,changed,"restoration.json",n->n.putArray("remaining_clients").addObject().put("id","other"));
     case "native-runtime-changed"->edit(folder,changed,"environment-before.json",n->((ObjectNode)n.path("runtime")).put("image","changed"));
     case "classpath-injected"->{var raw="injected jar".getBytes();Files.write(folder.resolve("before.native-classpath.txt"),raw);((ObjectNode)changed.path("files")).put("before.native-classpath.txt",hash(raw));edit(folder,changed,"environment-before.json",n->{try{n.put("nativeClasspathSha256",hash(raw));}catch(Exception e){throw new IllegalArgumentException(e);}});}
     case "process-injected"->edit(folder,changed,"environment-before.json",n->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("publicProcessArguments")).add("-javaagent:unknown.jar"));
     case "unknown-factory","unknown-factory-property"->edit(folder,changed,"server-info-before.json",n->body(n,b->{var types=(com.fasterxml.jackson.databind.node.ArrayNode)b.path("protocolMapperTypes").path("saml");if(name.equals("unknown-factory"))((ObjectNode)types.get(0)).put("id","custom-attester");else ((com.fasterxml.jackson.databind.node.ArrayNode)types.get(0).path("properties")).addObject().put("name","attesters");}));
     case "unknown-effective-mapper"->edit(folder,changed,"native-scopes-before.json",n->{var rec=(ObjectNode)n.path("clientMappers");try{var raw="[{\"protocol\":\"saml\",\"protocolMapper\":\"custom-attester\"}]".getBytes();rec.put("response_base64",Base64.getEncoder().encodeToString(raw));rec.put("response_sha256",hash(raw));}catch(Exception e){throw new IllegalArgumentException(e);}});
     case "client-signature-disabled","foreign-attester-setting","client-before-after-differ"->edit(folder,changed,"native-client-before.json",n->body(n,b->{var attrs=(ObjectNode)b.path("attributes");if(name.equals("client-signature-disabled"))attrs.put("saml.client.signature","false");else if(name.equals("foreign-attester-setting"))attrs.put("saml.attesting.entity","other");else b.put("enabled",false);}));
     case "missing-source-jar"->Files.delete(folder.resolve("native-runtime/org.keycloak.keycloak-saml-core-26.7.2.jar"));
     case "native-source-mutated"->{var raw="other bytecode".getBytes();Files.write(folder.resolve("native-runtime/org.keycloak.keycloak-services-26.7.2.jar"),raw);((ObjectNode)changed.path("files")).put("native-runtime/org.keycloak.keycloak-services-26.7.2.jar",hash(raw));}
     case "source-producer-mutated"->{var raw="other producer".getBytes();Files.write(folder.resolve("ProduceKeycloakSubjectConfirmationControls.java"),raw);((ObjectNode)changed.path("files")).put("ProduceKeycloakSubjectConfirmationControls.java",hash(raw));}
     case "control-purpose-product"->edit(folder,changed,"calibration/calibration.json",n->n.put("purpose","product-issued"));case "control-target-trust-change"->edit(folder,changed,"calibration/calibration.json",n->n.put("targetTrustChanges",1));
     case "control-signer-in-product-evidence"->{var ref=receipt.path("responseReference").asText();actualBodies.put(ref,originals.get("calibration/foreign-positive.xml"));var e=entries.stream().filter(x->x.id().equals(ref)).findFirst().orElseThrow();var node=(ObjectNode)M.valueToTree(e);node.put("decodedSamlBytes",actualBodies.get(ref).length);history.set(history.indexOf(e),M.treeToValue(node,TranscriptEntry.class));}
     case "semantic-positive-swapped"->{var raw=originals.get("calibration/multiple-packed-identifiers.xml");Files.write(folder.resolve("calibration/multiple-positive.xml"),raw);((ObjectNode)changed.path("files")).put("calibration/multiple-positive.xml",hash(raw));}
     case "signed-calibration-tampered"->{var raw="<Response/>".getBytes();Files.write(folder.resolve("calibration/foreign-positive.xml"),raw);((ObjectNode)changed.path("files")).put("calibration/foreign-positive.xml",hash(raw));}
     case "duplicate-transcript"->history.add(entries.getFirst());case "foreign-transcript-run","foreign-content-reference"->{var e=history.getFirst();var n=(ObjectNode)M.valueToTree(e);n.put(name.equals("foreign-transcript-run")?"runId":"decodedSamlRef",name.equals("foreign-transcript-run")?"run_00000000000000000000000000":"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml");history.set(0,M.treeToValue(n,TranscriptEntry.class));}
     case "directory-receipt","symlink-receipt"->{}default->throw new IllegalArgumentException(name);
    }
    Files.deleteIfExists(path);if(name.equals("directory-receipt"))Files.createDirectory(path);else if(name.equals("symlink-receipt")){var outside=directory.resolve("outside.json");Files.write(outside,M.writeValueAsBytes(changed));Files.createSymbolicLink(path,outside);}else Files.write(path,M.writeValueAsBytes(changed));
    for(String id:outcomes.keySet())if(observe(directory,run,id,history,actualBodies,actualTarget,profile).outcome()!=Outcome.NOT_VERIFIED)throw new IllegalStateException("Altered proof became conclusive "+name+" "+id);controls.put(name,"NOT_VERIFIED");
   }
   Files.write(output,M.writerWithDefaultPrettyPrinter().writeValueAsBytes(Map.of("runId",run,"production_outcomes",outcomes,"negative_controls",controls,"oracle_calibration_controls",4,"calibration_product_evidence",false,"transcriptSha256",hash(Files.readAllBytes(source.resolve("transcript.json"))),"verdict_adopted",false)),StandardOpenOption.CREATE_NEW);
  }finally{try(var paths=Files.walk(directory)){for(var f:paths.sorted(Comparator.reverseOrder()).toList())Files.delete(f);}}
 }
 static void reset(Path folder,Map<String,byte[]> originals)throws Exception{try(var paths=Files.walk(folder)){for(var f:paths.filter(p->!p.equals(folder)).sorted(Comparator.reverseOrder()).toList())Files.delete(f);}for(var row:originals.entrySet()){var f=folder.resolve(row.getKey());Files.createDirectories(f.getParent());Files.write(f,row.getValue());}}
 static CaseOutcome observe(Path directory,String run,String id,List<TranscriptEntry> history,Map<String,byte[]> raw,byte[] target,String profile){var recorder=new TranscriptRecorder(){public List<TranscriptEntry>list(String r){if(!r.equals(run))throw new IllegalArgumentException();return history;}public TranscriptEntry record(TranscriptInput input){throw new UnsupportedOperationException();}public TranscriptEntry updateSamlAnalysis(String r,String c,Map<String,Object>s){throw new UnsupportedOperationException();}};var ctx=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,true);return new KeycloakSubjectConfirmationEvidence(directory,e->raw.get(e.id()),r->profile).evaluate(ctx,id,target).orElseThrow();}
}
