package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.runner.DefaultCaseContext;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.security.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.sql.DriverManager;
import java.time.*;
import java.util.*;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.cert.jcajce.*;
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.w3c.dom.Element;

/** Production replay only: original private keys and semantic-control signers stay in memory. */
public final class VerifyKeycloakPersistentPairwiseEvidence {
 private static final JsonCodec JSON=new JsonCodec();
 private static final String S="urn:oasis:names:tc:SAML:2.0:assertion",P="urn:oasis:names:tc:SAML:2.0:protocol",DS="http://www.w3.org/2000/09/xmldsig#";
 private static void require(boolean yes,String why){if(!yes)throw new IllegalArgumentException(why);}
 private static String sha(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 private record Data(ObjectNode receipt,Map<String,List<TranscriptEntry>> entries,Map<String,byte[]> bodies,Map<String,byte[]> targets,Map<String,PrivateKey> keys){}
 private static void regular(Path data,Path path)throws Exception {require(path.normalize().startsWith(data)&&Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS),"Unsafe key source");for(var p=path;p!=null&&p.startsWith(data);p=p.getParent())require(!Files.isSymbolicLink(p),"Symlink source");}
 private static Data load(Path folder,Path data)throws Exception {
  var receipt=(ObjectNode)JSON.mapper().readTree(folder.resolve("qualified-receipt.json").toFile());var entries=new HashMap<String,List<TranscriptEntry>>();var bodies=new HashMap<String,byte[]>();var targets=new HashMap<String,byte[]>();var keys=new HashMap<String,PrivateKey>();
  for(int i=0;i<2;i++) {var child=folder.resolve(i==0?"primary":"secondary");var peer=receipt.path("peers").get(i);var run=peer.path("runId").asText();require(run.matches("run_[0-9A-HJKMNP-TV-Z]{26}"),"Unsafe Run");
   var history=List.of(JSON.mapper().readValue(child.resolve("transcript.json").toFile(),TranscriptEntry[].class));var by=new HashMap<String,TranscriptEntry>();for(var e:history)require(run.equals(e.runId())&&by.put(e.id(),e)==null,"Ambiguous history");entries.put(run,history);
   for(var row:JSON.mapper().readTree(child.resolve("decoded-manifest.json").toFile())) {var path=child.resolve(row.path("file").asText()).normalize();require(path.getParent().equals(child.resolve("decoded")),"Original path escape");var raw=Files.readAllBytes(path);var e=by.get(row.path("id").asText());require(e!=null&&raw.length==e.decodedSamlBytes()&&sha(raw).equals(row.path("sha256").asText()),"Decoded original changed");require(bodies.put(e.id(),raw)==null,"Cross-Run duplicate content reference");}
   targets.put(run,Files.readAllBytes(child.resolve("target-metadata.xml")));var db=data.resolve("samlscope.db");regular(data,db);String plan;
   try(var connection=DriverManager.getConnection("jdbc:sqlite:file:"+db+"?mode=ro");var query=connection.prepareStatement("SELECT r.plan_id FROM runs r JOIN plans p ON p.id=r.plan_id WHERE r.id=?")){query.setString(1,run);try(var rows=query.executeQuery()){require(rows.next(),"Unknown native Run");plan=rows.getString(1);require(!rows.next()&&plan.matches("plan_[0-9A-HJKMNP-TV-Z]{26}")&&peer.path("entityId").asText().equals("http://localhost:18080/p/"+plan),"Run/Plan scope mismatch");}}
   var file=data.resolve("keys").resolve(plan).resolve("signing-key.pk8");regular(data,file);require(Files.size(file)<=16384,"Key size invalid");var encoded=Files.readAllBytes(file);try{keys.put(run,KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded)));}finally{Arrays.fill(encoded,(byte)0);}
  }return new Data(receipt,entries,bodies,targets,keys);
 }
 private static TranscriptEntry copy(TranscriptEntry e,String run,int length){return new TranscriptEntry(e.id(),run,e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),e.decodedSamlRef(),length,e.contentType(),e.rawQuery(),e.samlSummary());}
 private static CaseOutcome evaluate(Path directory,Data data)throws Exception {
  String run=data.receipt.path("runId").asText();Files.write(directory.resolve(run+".keycloak-pairwise.json"),JSON.mapper().writeValueAsBytes(data.receipt));
  var recorder=new TranscriptRecorder(){public List<TranscriptEntry>list(String r){return data.entries.getOrDefault(r,List.of()).stream().map(e->{var raw=data.bodies.get(e.id());return raw==null?e:copy(e,e.runId(),raw.length);}).toList();}public TranscriptEntry record(TranscriptInput i){throw new UnsupportedOperationException();}public TranscriptEntry updateSamlAnalysis(String id,String c,Map<String,Object>s){throw new UnsupportedOperationException();}};
  var context=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,true);
  return new KeycloakPersistentPairwiseEvidence(directory,e->data.bodies.get(e.id()),data.targets::get,r->Optional.ofNullable(data.keys.get(r))).evaluate(context).orElseGet(()->CaseOutcome.notVerified("absent","absent"));
 }
 private static Data changed(Data d){return new Data(d.receipt.deepCopy(),new HashMap<>(d.entries),new HashMap<>(d.bodies),new HashMap<>(d.targets),new HashMap<>(d.keys));}
 private static void replace(Data data,JsonNode ref,JsonNode original)throws Exception {var raw=JSON.mapper().writeValueAsBytes(original);data.bodies.put(ref.path("reference").asText(),raw);((ObjectNode)ref).put("sha256",sha(raw));}
 private static ObjectNode original(Data d,JsonNode ref)throws Exception {return (ObjectNode)JSON.mapper().readTree(d.bodies.get(ref.path("reference").asText()));}
 private static PlanCredentials credentials()throws Exception {Security.addProvider(new BouncyCastleProvider());var generator=KeyPairGenerator.getInstance("RSA");generator.initialize(2048);var pair=generator.generateKeyPair();var subject=new X500Name("CN=Memory-only NameID control");var now=Instant.now();var cert=new JcaX509v3CertificateBuilder(subject,java.math.BigInteger.ONE,Date.from(now.minusSeconds(86400)),Date.from(now.plusSeconds(86400)),subject,pair.getPublic()).build(new JcaContentSignerBuilder("SHA256withRSA").setProvider("BC").build(pair.getPrivate()));return new PlanCredentials(pair.getPrivate(),new JcaX509CertificateConverter().setProvider("BC").getCertificate(cert));}
 private static Data semantic(Data original,PlanCredentials signer,String mutation)throws Exception {var data=changed(original);String first=null;byte[] target=null;
  for(int index=0;index<2;index++){var peer=data.receipt.path("peers").get(index);var run=peer.path("runId").asText();var targetDoc=SecureXml.parse(original.targets.get(run));var certs=targetDoc.getElementsByTagNameNS(DS,"X509Certificate");for(int j=0;j<certs.getLength();j++)certs.item(j).setTextContent(Base64.getEncoder().encodeToString(signer.certificate().getEncoded()));var targetRaw=SecureXml.serialize(targetDoc);data.targets.put(run,targetRaw);if(target==null)target=targetRaw;
   for(String exchange:List.of("baseline","persistent")){var ref=peer.path(exchange).path("transcript_ids").get(1).asText();var doc=SecureXml.parse(original.bodies.get(ref));var response=doc.getDocumentElement();var encrypted=MetadataAlgorithmEvidence.children(response,S,"EncryptedAssertion");var assertion=new SamlXmlDecrypter().decrypt(encrypted.getFirst(),original.keys.get(run));var clear=(Element)doc.importNode(assertion,true);response.replaceChild(clear,encrypted.getFirst());for(var sig:MetadataAlgorithmEvidence.children(clear,DS,"Signature"))clear.removeChild(sig);for(var sig:MetadataAlgorithmEvidence.children(response,DS,"Signature"))response.removeChild(sig);
    var name=(Element)clear.getElementsByTagNameNS(S,"NameID").item(0);if(exchange.equals("persistent")){if(first==null)first=name.getTextContent();if(index==1)switch(mutation){case "equal-persistent-values"->name.setTextContent(first);case "wrong-name-qualifier"->name.setAttribute("NameQualifier","https://wrong-idp.example");case "wrong-sp-name-qualifier"->name.setAttribute("SPNameQualifier","https://wrong-sp.example");case "unexpected-sp-provided-id"->name.setAttribute("SPProvidedID","never-assigned");case "wrong-principal-attribute"->{var attrs=clear.getElementsByTagNameNS(S,"Attribute");for(int j=0;j<attrs.getLength();j++){var attr=(Element)attrs.item(j);if(attr.getAttribute("Name").equals("samlscope.native.username"))attr.getElementsByTagNameNS(S,"AttributeValue").item(0).setTextContent("another-native-principal");}}}}
    new XmlSigner().sign(response,signer,MetadataAlgorithmEvidence.children(response,P,"Status").getFirst());data.bodies.put(ref,SecureXml.serialize(doc));
   }
  }
  String digest=sha(target);data.receipt.put("targetMetadataSha256",digest);for(var peer:data.receipt.path("peers"))for(String refName:List.of("initial","converter","application","before","after","restoration")){var ref=peer.path(refName);var value=original(data,ref);value.put("targetMetadataSha256",digest);replace(data,ref,value);}return data;
 }
 private static Map<String,CaseOutcome> normalCases(Data data)throws Exception {var peer=data.receipt.path("peers").get(0);String run=peer.path("runId").asText();var history=data.entries.get(run);var refs=peer.path("persistent").path("transcript_ids");var messages=new ArrayList<NormalFlowBrowserObservation.Message>();for(var ref:refs){var e=history.stream().filter(v->v.id().equals(ref.asText())).findFirst().orElseThrow();var raw=data.bodies.get(e.id());if(e.direction()==Direction.INBOUND){var doc=SecureXml.parse(raw);var response=doc.getDocumentElement();var encrypted=MetadataAlgorithmEvidence.children(response,S,"EncryptedAssertion");var assertion=new SamlXmlDecrypter().decrypt(encrypted.getFirst(),data.keys.get(run));response.replaceChild(doc.importNode(assertion,true),encrypted.getFirst());raw=SecureXml.serialize(doc);}messages.add(new NormalFlowBrowserObservation.Message("transcript:"+e.id(),e.method(),e.url(),e.timestamp(),raw,e.direction()==Direction.INBOUND));}var outcomes=new TreeMap<String,CaseOutcome>();for(String id:List.of("IIP-SSO05-a-idp-01","IIP-SSO05-a2-idp-01"))outcomes.put(id,NormalFlowBrowserObservation.evaluate(id,messages).orElseThrow());return outcomes;}
 public static void main(String[] args)throws Exception {require(args.length==3,"folder data report required");java.util.logging.Logger.getLogger("org.apache.xml.security.signature.XMLSignature").setLevel(java.util.logging.Level.SEVERE);var folder=Path.of(args[0]);var data=load(folder,Path.of(args[1]).toAbsolutePath().normalize());var output=Path.of(args[2]);require(!Files.exists(output),"Immutable report exists");String run=data.receipt.path("runId").asText();var temp=Files.createTempDirectory("kc-pairwise-replay-");var source=temp.resolve(run+".keycloak-pairwise");Files.createDirectory(source);
  try {Files.copy(folder.resolve("native-source/before-services.jar"),source.resolve("native-services.jar"));Files.copy(folder.resolve("primary/fixture.xml"),source.resolve("primary.xml"));Files.copy(folder.resolve("secondary/fixture.xml"),source.resolve("secondary.xml"));
   var actual=evaluate(temp,data);boolean mutant=Files.isRegularFile(folder.resolve("campaign.json"))&&JSON.mapper().readTree(folder.resolve("campaign.json").toFile()).path("sameValueNativeMutant").asBoolean();var normal=normalCases(data);if(mutant){require(actual.outcome()==Outcome.VIOLATED,"Native producer mutant not detected: "+actual);require(normal.get("IIP-SSO05-a-idp-01").outcome()==Outcome.SATISFIED&&normal.get("IIP-SSO05-a2-idp-01").outcome()==Outcome.VIOLATED,"Native format/length control not detected");var report=new TreeMap<String,Object>();report.put("runId",run);report.put("outcome",actual);report.put("normalCases",normal);report.put("privateKeyExported",false);report.put("productConfigurationWrites",0);report.put("samlRequests",0);report.put("nativeProducerControl",true);JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(output.toFile(),report);return;}
   require(actual.outcome()==Outcome.SATISFIED,"Native positive rejected: "+actual);require(normal.values().stream().allMatch(v->v.outcome()==Outcome.SATISFIED),"Native format/length positives unproven");var checks=new TreeMap<String,Object>();checks.put("native-positive",actual.outcome().name());var signer=credentials();var baseline=evaluate(temp,semantic(data,signer,"baseline"));require(baseline.outcome()==Outcome.SATISFIED,"Valid semantic baseline rejected: "+baseline);checks.put("signed-semantic-baseline",baseline.outcome().name());
   for(String mutation:List.of("equal-persistent-values","wrong-name-qualifier","wrong-sp-name-qualifier","unexpected-sp-provided-id","wrong-principal-attribute")){var outcome=evaluate(temp,semantic(data,signer,mutation));Outcome expected=mutation.equals("wrong-principal-attribute")?Outcome.NOT_VERIFIED:Outcome.VIOLATED;require(outcome.outcome()==expected,"Semantic control accepted "+mutation+" "+outcome);checks.put(mutation,outcome.outcome().name());}
   for(String mutation:List.of("foreign-history-run","duplicate-transcript-id","wrong-target","wrong-receipt-run","missing-peer","missing-original","wrong-request-hash","wrong-request-reference","wrong-decryption-key","wrong-restoration","late-before-readback","default-scope-mapper-changed","native-nameid-mapper-added","wrong-client-signature-policy","different-native-user","native-runtime-epoch-changed","wrong-native-converter-fixture","wrong-native-application","wrong-source-jar")){
    var d=changed(data);var peer=(ObjectNode)d.receipt.path("peers").get(1);String second=peer.path("runId").asText();byte[] oldSource=null;
    switch(mutation){case "foreign-history-run"->{var h=new ArrayList<>(d.entries.get(second));h.set(0,copy(h.getFirst(),run,h.getFirst().decodedSamlBytes()));d.entries.put(second,h);}case "duplicate-transcript-id"->{var h=new ArrayList<>(d.entries.get(second));h.add(h.getFirst());d.entries.put(second,h);}case "wrong-target"->d.receipt.put("targetMetadataSha256","0".repeat(64));case "wrong-receipt-run"->d.receipt.put("runId","run_00000000000000000000000000");case "missing-peer"->((ArrayNode)d.receipt.path("peers")).remove(1);case "missing-original"->d.bodies.remove(peer.path("before").path("reference").asText());case "wrong-request-hash"->((ObjectNode)peer.path("persistent")).put("requestSha256","0".repeat(64));case "wrong-request-reference"->((ArrayNode)peer.path("persistent").path("transcript_ids")).set(0,d.receipt.path("peers").get(0).path("persistent").path("transcript_ids").get(0));case "wrong-decryption-key"->d.keys.put(second,d.keys.get(run));case "wrong-source-jar"->{oldSource=Files.readAllBytes(source.resolve("native-services.jar"));var corrupt=oldSource.clone();corrupt[100]^=1;Files.write(source.resolve("native-services.jar"),corrupt);}
     default->{String key=switch(mutation){case "wrong-restoration"->"restoration";case "wrong-native-converter-fixture"->"converter";case "wrong-native-application"->"application";default->"before";};var ref=peer.path(key);var record=original(d,ref);switch(mutation){case "wrong-restoration"->((ArrayNode)record.path("users")).add("left-native-user");case "late-before-readback"->record.put("recordedAt","2099-01-01T00:00:00Z");case "default-scope-mapper-changed"->((ObjectNode)record.at("/scope/samlClientScopes/0/protocolMappers/0")).put("protocolMapper","saml-nameid-user-attribute-mapper");case "native-nameid-mapper-added"->((ArrayNode)record.at("/client/protocolMappers")).addObject().put("protocolMapper","saml-nameid-user-attribute-mapper");case "wrong-client-signature-policy"->((ObjectNode)record.at("/client/attributes")).put("saml.client.signature","false");case "different-native-user"->((ObjectNode)record.path("user")).put("id","00000000-0000-0000-0000-000000000000");case "native-runtime-epoch-changed"->((ObjectNode)record.at("/scope/runtime")).put("containerId","0".repeat(64));case "wrong-native-converter-fixture","wrong-native-application"->((ObjectNode)record.path("native")).put("requestSha256","0".repeat(64));default->throw new IllegalArgumentException(mutation);}replace(d,ref,record);}}
    var outcome=evaluate(temp,d);if(oldSource!=null)Files.write(source.resolve("native-services.jar"),oldSource);require(outcome.outcome()==Outcome.NOT_VERIFIED,"Invalid original adopted "+mutation+" "+outcome);checks.put(mutation,outcome.outcome().name());
   }
   var report=new TreeMap<String,Object>();report.put("runId",run);report.put("outcome",actual);report.put("normalCases",normal);report.put("checks",checks);report.put("privateKeyExported",false);report.put("productConfigurationWrites",0);report.put("samlRequests",0);JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(output.toFile(),report);
  } finally{try(var paths=Files.walk(temp)){for(var p:paths.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}
 }
}
