package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.runner.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.security.*;
import java.security.cert.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.*;
import java.util.*;
import java.util.function.BiFunction;

/** Original replay only. No Recorder writes, product actions, or plaintext identifiers are exported. */
public final class VerifyMetadataCertificateRuntime {
 static final JsonCodec JSON=new JsonCodec();static final String CASE="IIP-MD06-a6-idp-01",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#";
 static void require(boolean value){if(!value)throw new IllegalArgumentException("Certificate runtime original replay failed");}
 static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 static void reset(Path folder,Map<String,byte[]> originals)throws Exception{try(var files=Files.list(folder)){for(var p:files.toList())if(!p.getFileName().toString().endsWith(".jar"))Files.delete(p);}for(var row:originals.entrySet()){var p=folder.resolve(row.getKey());if(!p.getFileName().toString().endsWith(".jar")||!Files.exists(p)||!Arrays.equals(row.getValue(),Files.readAllBytes(p)))Files.write(p,row.getValue());}}
 static void change(Path folder,ObjectNode manifest,String file,byte[] bytes)throws Exception{Files.write(folder.resolve(file),bytes);((ObjectNode)manifest.path("originals")).put(file,hash(bytes));}
 static void edit(Path folder,ObjectNode manifest,String file,java.util.function.Consumer<ObjectNode> action)throws Exception{var node=(ObjectNode)JSON.mapper().readTree(folder.resolve(file).toFile());action.accept(node);change(folder,manifest,file,JSON.mapper().writeValueAsBytes(node));}
 static DefaultCaseContext context(String run,List<TranscriptEntry> entries,boolean complete){var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String selected){return entries;}public TranscriptEntry record(TranscriptInput input){throw new AssertionError("Replay submitted an action");}public TranscriptEntry updateSamlAnalysis(String id,String correlation,Map<String,Object> summary){throw new AssertionError("Replay changed an original");}};return new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),new TestPlan.Parameters(180,45,"reference"),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,complete);}
 static CaseOutcome result(Path root,String run,ObjectNode manifest,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,boolean complete)throws Exception{var path=root.resolve(run).resolve("manifest.json");if(!Files.exists(path)||!JSON.mapper().readTree(Files.readAllBytes(path)).equals(manifest))Files.write(path,JSON.mapper().writeValueAsBytes(manifest));return new MetadataCertificateRuntimeEvidence(root,e->bodies.get(e.id()),r->target,keys).evaluate(context(run,entries,complete)).orElse(CaseOutcome.notVerified("unproven","unproven"));}
 static TranscriptEntry altered(TranscriptEntry e,String run,String decoded){return new TranscriptEntry(e.id(),run,e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),decoded,e.decodedSamlBytes(),e.contentType(),e.rawQuery(),e.samlSummary());}
 static BiFunction<String,String,Optional<PlanCredentials>> keys(String run,String plan,Path receipt)throws Exception {
  var result=new HashMap<String,PlanCredentials>();for(var variant:MetadataCertificateRuntimeProbeTestCase.VARIANTS){var peer=SecureXml.parse(Files.readAllBytes(receipt.resolve(variant+"-fixture.xml"))).getDocumentElement();var sp=MetadataAlgorithmEvidence.children(peer,MD,"SPSSODescriptor").getFirst();var bytes=Base64.getMimeDecoder().decode(sp.getElementsByTagNameNS(DS,"X509Certificate").item(0).getTextContent());var publicCertificate=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(bytes));try(var aliases=Files.list(Path.of("/data/keys/"+plan))){for(var alias:aliases.filter(Files::isDirectory).toList()){var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(alias.resolve("signing-certificate.der")));if(Arrays.equals(cert.getPublicKey().getEncoded(),publicCertificate.getPublicKey().getEncoded())){var raw=Files.readAllBytes(alias.resolve("signing-key.pk8"));try{result.put(variant,new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(raw)),cert));}finally{Arrays.fill(raw,(byte)0);}break;}}}require(result.containsKey(variant));}return (selected,variant)->selected.equals(run)?Optional.ofNullable(result.get(variant)):Optional.empty();
 }
 static Map<String,Object> lifecycle(Path root,String run,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,CaseOutcome actual)throws Exception{
  var fallback=new ConfigurationGateTestCase(new AttestedOutcomeTestCase(CASE,TargetRole.IDP,"validity.evidence",Duration.ofMinutes(1),List.of(AttestationOption.of("evidence_satisfies",Outcome.SATISFIED,"declaration.satisfies"))),"validity.config",Duration.ofMinutes(1),ConfigurationFailureSemantics.TEST_PRECONDITION);
  var wrapper=new MetadataCertificateRuntimeProbeTestCase(fallback,r->target,e->bodies.get(e.id()),keys,root);var context=context(run,entries,true);var map=new TreeMap<String,Object>();map.put("start",((CaseStep.Finish)wrapper.start(context)).outcome().equals(actual));var state=new CaseState("configuration",Map.of());
  for(var event:List.of(new CaseEvent.ConfigConfirmed(),new CaseEvent.TranscriptReady(),new CaseEvent.Aborted("operator-ended"),new CaseEvent.TimedOut(Duration.ofMinutes(1))))map.put(event.getClass().getSimpleName(),((CaseStep.Finish)wrapper.resume(context,state,event)).outcome().equals(actual));
  map.put("status-ready",wrapper.evidenceStatus(context).ready());map.put("recorded-not-verified",wrapper.reevaluateRecordedEvidence(context,CaseOutcome.notVerified("before","before")).orElseThrow().equals(actual));map.put("recorded-conclusive",wrapper.reevaluateRecordedEvidence(context,actual).isPresent());map.put("incomplete-history",((CaseStep.Finish)wrapper.start(context(run,entries,false))).outcome().outcome().name());return map;
 }

 static void verifyBaseline(Path input,String run,String plan,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] targetRaw)throws Exception{
  var proof=JSON.mapper().readTree(input.resolve("initial-baseline/baseline-proof.json").toFile());require(run.equals(proof.path("runId").asText())&&proof.path("expiryPairsResent").asInt(-1)==0&&proof.path("protocolSubmissions").asInt(-1)==1);var request=entries.stream().filter(e->e.id().equals(proof.path("requestReference").asText())).findFirst().orElseThrow();var response=entries.stream().filter(e->e.id().equals(proof.path("responseReference").asText())).findFirst().orElseThrow();var req=SecureXml.parse(bodies.get(request.id())).getDocumentElement();var sp=SecureXml.parse(Files.readAllBytes(input.resolve("initial-baseline/fixture.xml"))).getDocumentElement();var target=SecureXml.parse(targetRaw).getDocumentElement();require(run.equals(request.runId())&&run.equals(response.runId())&&request.direction()==Direction.OUTBOUND&&response.direction()==Direction.INBOUND&&"GET".equals(request.method())&&"POST".equals(response.method())&&request.timestamp().isBefore(response.timestamp())&&req.getAttribute("ID").equals(request.correlationId())&&req.getAttribute("ID").equals(response.correlationId())&&Boolean.TRUE.equals(response.samlSummary().get("normalFlowAccepted")));
  var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(Path.of("/data/keys/"+plan+"/signing-certificate.der")));require(new RedirectSignatureVerifier().isValidForMessage(request.rawQuery(),cert,bodies.get(request.id())));var encoded=Files.readAllBytes(Path.of("/data/keys/"+plan+"/signing-key.pk8"));try{var credential=new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded)),cert);VerifiedResponseAssertion.read(SecureXml.parse(bodies.get(response.id())).getDocumentElement(),target.getAttribute("entityID"),MetadataAlgorithmEvidence.signingKeys(target),sp,Optional.of(credential),req.getAttribute("ID"),req.getAttribute("AssertionConsumerServiceURL"));}finally{Arrays.fill(encoded,(byte)0);}
 }
 static ObjectNode refuse(Path folder,ObjectNode m,List<TranscriptEntry> entries,Map<String,byte[]> bodies,String variant)throws Exception{
  ObjectNode exchange=null;for(var row:m.path("observations"))if(variant.equals(row.path("variant").asText()))exchange=(ObjectNode)row.path("exchanges").get(0);require(exchange!=null);String response=exchange.path("responseReference").asText(),request=exchange.path("requestReference").asText(),rid=SecureXml.parse(bodies.get(request)).getDocumentElement().getAttribute("ID");exchange.putNull("responseReference");var h=(ObjectNode)exchange.path("nativeHttp").get(0);var rejected=m.path("observations").get(0).path("exchanges").get(1).path("nativeHttp").get(0);h.put("responseStatus",400).put("samlResponseFormPresent",false).put("nativeMessageSecurityError",true);h.remove("responseSamlSha256");h.put("responseBodyFile",rejected.path("responseBodyFile").asText()).put("responseBodySha256",rejected.path("responseBodySha256").asText());var audit=new StringBuilder();for(var line:Files.readString(folder.resolve("native-request-bound-audit.log")).lines().toList()){var fields=line.split("\\|",-1);if(fields[1].equals(rid)){fields[3]="MessageAuthenticationError";fields[4]="";fields[5]="false";}audit.append(String.join("|",fields)).append("\n");}change(folder,m,"native-request-bound-audit.log",audit.toString().getBytes());entries.removeIf(e->e.id().equals(response));return exchange;
 }
 static void selectPkix(Path folder,ObjectNode m)throws Exception{for(var phase:List.of("before","after"))edit(folder,m,"trust-"+phase+"-selected-properties.json",n->n.put("idp.trust.signatures","shibboleth.PKIXSignatureTrustEngine"));}
 static ObjectNode calibratedCause(Path input,Path folder,ObjectNode m,ObjectNode exchange,String variant,Map<String,byte[]> bodies)throws Exception{
  var diagnostic=JSON.mapper().readTree(input.resolve("pkix-calibration/output/native-pkix-diagnostic.json").toFile());require(!diagnostic.path("controlsAdopted").asBoolean(true));com.fasterxml.jackson.databind.JsonNode row=null;for(var candidate:diagnostic.path("records"))if(variant.equals(candidate.path("variant").asText()))row=candidate;require(row!=null&&!row.path("accepted").asBoolean(true));String requestReference=exchange.path("requestReference").asText();byte[] raw=bodies.get(requestReference);var req=SecureXml.parse(raw).getDocumentElement();var md=SecureXml.parse(Files.readAllBytes(folder.resolve(variant+"-fixture.xml"))).getDocumentElement();var sp=MetadataAlgorithmEvidence.children(md,MD,"SPSSODescriptor").getFirst();var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(sp.getElementsByTagNameNS(DS,"X509Certificate").item(0).getTextContent())));require(hash(raw).equals(row.path("requestSha256").asText())&&req.getAttribute("ID").equals(row.path("requestId").asText())&&hash(cert.getEncoded()).equals(row.path("certificateSha256").asText()));var trace=Files.readAllBytes(input.resolve("pkix-calibration/output/"+row.path("exceptionTraceFile").asText()));require(hash(trace).equals(row.path("exceptionTraceSha256").asText()));String traceFile=variant+"-calibrated-native-exception.txt",causeFile=variant+"-counterfactual-native-cause.json";change(folder,m,traceFile,trace);var cause=JSON.mapper().createObjectNode();cause.put("schema","samlscope-native-certpath-operation-failure-v1").put("source","native-selected-pkix-trust-engine").put("algorithm","PKIX").put("trustEngineBean","shibboleth.PKIXSignatureTrustEngine").put("runId",m.path("runId").asText()).put("targetMetadataSha256",m.path("targetMetadataSha256").asText()).put("requestId",req.getAttribute("ID")).put("requestSha256",hash(raw)).put("certificateSha256",hash(cert.getEncoded())).put("nativeTimestamp",exchange.path("nativeBegin").asText()).put("exceptionClass",row.path("exceptionClass").asText()).put("reason",row.path("reason").asText()).put("exceptionTraceFile",traceFile).put("exceptionTraceSha256",hash(trace)).put("diagnosticNativeExecutedAt",row.path("nativeExecutedAt").asText()).put("counterfactualCalibrationOnly",true);change(folder,m,causeFile,JSON.mapper().writeValueAsBytes(cause));exchange.put("certificateCheckFailureFile",causeFile);return cause;
 }
 public static void main(String[] args)throws Exception {
  require(args.length==2);JSON.mapper().enable(com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);java.util.logging.Logger.getLogger("org.apache.xml.security.signature.XMLSignature").setLevel(java.util.logging.Level.SEVERE);var input=Path.of(args[0]);var receipt=input.resolve("receipt");var created=JSON.mapper().readTree(input.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText();var manifestRaw=Files.readAllBytes(receipt.resolve("manifest.json"));var base=(ObjectNode)JSON.mapper().readTree(manifestRaw);require(run.equals(base.path("runId").asText()));var target=Files.readAllBytes(input.resolve("target-metadata.xml"));var entries=List.of(JSON.mapper().readValue(input.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new HashMap<String,byte[]>();for(var row:JSON.mapper().readTree(input.resolve("decoded-manifest.json").toFile())){var raw=Files.readAllBytes(input.resolve(row.path("file").asText()));require(hash(raw).equals(row.path("sha256").asText())&&bodies.put(row.path("id").asText(),raw)==null);}verifyBaseline(input,run,plan,entries,bodies,target);var credentials=keys(run,plan,receipt);var originals=new LinkedHashMap<String,byte[]>();try(var files=Files.list(receipt)){for(var file:files.toList())originals.put(file.getFileName().toString(),Files.readAllBytes(file));}var tmp=Files.createTempDirectory("certificate-runtime-replay-");var folder=Files.createDirectories(tmp.resolve(run));
  try {
   reset(folder,originals);var actual=result(tmp,run,base,entries,bodies,target,credentials,true);require(actual.outcome()==Outcome.SATISFIED);var negative=new TreeMap<String,String>();
   for(String name:List.of("wrong-run","wrong-target","wrong-adapter","missing-epoch","wrong-native-readback","wrong-source","wrong-provider","wrong-restoration","runtime-changed","query-failed","query-wrong-entity","query-after-probe","missing-negative-control","wrong-audit-request","wrong-native-profile","missing-native-rejection","http-wrong-hash","http-wrong-url","http-outside-epoch","clock-missing-original","clock-outside-native-audit","tampered-request","tampered-response","foreign-run-entry","duplicate-entry","foreign-decoded-reference","wrong-decryption-key","incomplete-history","wrong-trust-profile","custom-trust-engine","missing-native-jar","wrong-native-jar","native-security-changed","unknown-native-override","missing-crl-original","unreachable-network-unproven","unknown-issuer-condition","native-control-rejected","forceauthn-one","ispassive-one","unreachable-stale","restoration-failed","native-readiness-failed","wrong-created-plan")) {
    reset(folder,originals);var m=base.deepCopy();var selected=new ArrayList<>(entries);var raw=new HashMap<>(bodies);var selectedKeys=credentials;boolean complete=true;var epoch=m.path("observations").get(0);var normal=epoch.path("exchanges").get(0);var rejection=epoch.path("exchanges").get(1);String request=normal.path("requestReference").asText(),response=normal.path("responseReference").asText();String variant=epoch.path("variant").asText();
    switch(name){
     case "wrong-run"->m.put("runId","run_00000000000000000000000000");case "wrong-target"->m.put("targetMetadataSha256","0".repeat(64));case "wrong-adapter"->m.put("adapter","parser-only");case "missing-epoch"->((com.fasterxml.jackson.databind.node.ArrayNode)m.path("observations")).remove(1);
     case "wrong-native-readback"->change(folder,m,variant+"-metadata-stdout.txt","<wrong/>".getBytes());case "wrong-source"->change(folder,m,variant+"-after-source.xml","<wrong/>".getBytes());case "wrong-provider"->change(folder,m,variant+"-after-providers.xml","<wrong/>".getBytes());case "wrong-restoration"->change(folder,m,"final-audit.xml","<wrong/>".getBytes());
     case "runtime-changed"->{var n=JSON.mapper().readTree(folder.resolve("target-container-inspect-end.json").toFile());((ObjectNode)n.get(0)).put("Id","other");change(folder,m,"target-container-inspect-end.json",JSON.mapper().writeValueAsBytes(n));}
     case "query-failed"->edit(folder,m,variant+"-metadata-query.json",n->n.put("exitCode",1));case "query-wrong-entity"->edit(folder,m,variant+"-metadata-query.json",n->n.put("entityId","other"));case "query-after-probe"->edit(folder,m,variant+"-metadata-query.json",n->n.put("recordedAt","2099-01-01T00:00:00Z"));case "missing-negative-control"->((com.fasterxml.jackson.databind.node.ArrayNode)epoch.path("exchanges")).remove(1);
     case "wrong-audit-request"->change(folder,m,"native-request-bound-audit.log",new String(originals.get("native-request-bound-audit.log")).replace("|"+SecureXml.parse(raw.get(rejection.path("requestReference").asText())).getDocumentElement().getAttribute("ID")+"|","|_foreign|" ).getBytes());
     case "wrong-native-profile"->change(folder,m,"native-request-bound-audit.log",new String(originals.get("native-request-bound-audit.log")).replace("http://shibboleth.net/ns/profiles/saml2/sso/browser","SAML2.SSO").getBytes());
     case "missing-native-rejection"->((ObjectNode)rejection.path("nativeHttp").get(0)).put("nativeMessageSecurityError",false);case "http-wrong-hash"->((ObjectNode)normal.path("nativeHttp").get(0)).put("requestSha256","0".repeat(64));case "http-wrong-url"->((ObjectNode)normal.path("nativeHttp").get(0)).put("requestUrl","http://wrong.invalid/");case "http-outside-epoch"->((ObjectNode)normal.path("nativeHttp").get(0)).put("startedAt","1970-01-01T00:00:00Z");
     case "clock-missing-original"->{var sample=JSON.mapper().readTree(folder.resolve(normal.path("clockBeforeFile").asText()).toFile());Files.delete(folder.resolve(sample.path("nativeClockFile").asText()));}case "clock-outside-native-audit"->edit(folder,m,normal.path("clockBeforeFile").asText(),n->n.put("nativeInstant","2099-01-01T00:00:00Z"));
     case "tampered-request","tampered-response"->{var ref=name.equals("tampered-request")?request:response;var x=SecureXml.parse(raw.get(ref));x.getDocumentElement().setAttribute("ID","_tampered");raw.put(ref,SecureXml.serialize(x));}
     case "foreign-run-entry","foreign-decoded-reference"->{int index=0;while(!selected.get(index).id().equals(response))index++;var e=selected.get(index);selected.set(index,altered(e,name.equals("foreign-run-entry")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-decoded-reference")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef()));}case "duplicate-entry"->selected.add(selected.getFirst());case "wrong-decryption-key"->{var wrong=new PlanCredentials(KeyPairGenerator.getInstance("RSA").generateKeyPair().getPrivate(),credentials.apply(run,"control").orElseThrow().certificate());selectedKeys=(r,v)->Optional.of(wrong);}case "incomplete-history"->complete=false;
     case "wrong-trust-profile"->edit(folder,m,"trust-before-native-effective-profile.json",n->((ObjectNode)n.path("RelyingPartyConfiguration")).put("securityConfiguration","other"));case "custom-trust-engine"->edit(folder,m,"trust-before-selected-properties.json",n->n.put("idp.trust.signatures","custom.TrustAll"));case "missing-native-jar"->Files.delete(folder.resolve("native-idp-conf-impl.jar"));case "wrong-native-jar"->change(folder,m,"native-idp-conf-impl.jar",new byte[]{0});case "native-security-changed"->change(folder,m,"trust-after-global.xml","<wrong/>".getBytes());case "unknown-native-override"->change(folder,m,"trust-before-override-source-inventory.json","[\"custom.class\"]".getBytes());case "missing-crl-original"->change(folder,m,"certificate-revoked-fixture.xml","<wrong/>".getBytes());case "unreachable-network-unproven"->change(folder,m,"certificate-revocation-unreachable-network.json","[]".getBytes());case "unknown-issuer-condition"->change(folder,m,"certificate-unknown-ca-fixture.xml",originals.get("control-fixture.xml"));case "native-control-rejected"->((ObjectNode)normal).putNull("responseReference");
     case "forceauthn-one","ispassive-one"->{var document=SecureXml.parse(raw.get(request));var req=document.getDocumentElement();req.removeChild(MetadataAlgorithmEvidence.children(req,DS,"Signature").getFirst());req.setAttribute(name.equals("forceauthn-one")?"ForceAuthn":"IsPassive","1");new XmlSigner().sign(req,credentials.apply(run,"control").orElseThrow(),MetadataAlgorithmEvidence.children(req,"urn:oasis:names:tc:SAML:2.0:protocol","NameIDPolicy").getFirst());var bytes=SecureXml.serialize(document);require(new XmlSignatureVerifier().hasValidEnvelopedSignature(req,credentials.apply(run,"control").orElseThrow().certificate()));raw.put(request,bytes);((ObjectNode)normal.path("nativeHttp").get(0)).put("requestSha256",hash(bytes));}
     case "unreachable-stale"->{var rows=JSON.mapper().readTree(folder.resolve("certificate-revocation-unreachable-network.json").toFile());for(var row:rows){((ObjectNode)row).put("startedAt","1970-01-01T00:00:00Z");((ObjectNode)row).put("completedAt","1970-01-01T00:00:01Z");}change(folder,m,"certificate-revocation-unreachable-network.json",JSON.mapper().writeValueAsBytes(rows));}case "restoration-failed"->edit(folder,m,"restoration.json",n->n.put("restored",false));case "native-readiness-failed"->edit(folder,m,"restored-native-readiness.json",n->n.put("status",503));case "wrong-created-plan"->edit(folder,m,"created.json",n->((ObjectNode)n.path("run")).put("planId","plan_00000000000000000000000000"));
    }
    require(result(tmp,run,m,selected,raw,target,selectedKeys,complete).outcome()==Outcome.NOT_VERIFIED);negative.put(name,"NOT_VERIFIED");
   }
   // Generic key rejection cannot establish certificate-check causality, even with PKIX selected.
   for(var name:List.of("generic-key-refusal","pkix-cause-missing","pkix-cause-wrong-request","pkix-cause-wrong-certificate","pkix-cause-wrong-window","pkix-cause-wrong-reason","pkix-cause-missing-trace","pkix-cause-faked-trace")){
    reset(folder,originals);var m=base.deepCopy();var selected=new ArrayList<>(entries);String variant="certificate-unknown-ca";var exchange=refuse(folder,m,selected,bodies,variant);if(!name.equals("generic-key-refusal"))selectPkix(folder,m);
    if(!Set.of("generic-key-refusal","pkix-cause-missing").contains(name)){var cause=calibratedCause(input,folder,m,exchange,variant,bodies);switch(name){case "pkix-cause-wrong-request"->cause.put("requestId","_foreign");case "pkix-cause-wrong-certificate"->cause.put("certificateSha256","0".repeat(64));case "pkix-cause-wrong-window"->cause.put("nativeTimestamp","1970-01-01T00:00:00Z");case "pkix-cause-wrong-reason"->cause.put("reason","REVOKED");case "pkix-cause-missing-trace"->Files.delete(folder.resolve(cause.path("exceptionTraceFile").asText()));case "pkix-cause-faked-trace"->{byte[] trace=("request_id="+cause.path("requestId").asText()+"\nrequest_sha256="+cause.path("requestSha256").asText()+"\ncertificate_sha256="+cause.path("certificateSha256").asText()+"\nreason=NO_TRUST_ANCHOR\n").getBytes();change(folder,m,cause.path("exceptionTraceFile").asText(),trace);cause.put("exceptionTraceSha256",hash(trace));}}change(folder,m,exchange.path("certificateCheckFailureFile").asText(),JSON.mapper().writeValueAsBytes(cause));}
    require(result(tmp,run,m,selected,bodies,target,credentials,true).outcome()==Outcome.NOT_VERIFIED);negative.put(name,"NOT_VERIFIED");
   }
   var mutants=new TreeMap<String,String>();var variantNames=new ArrayList<>(MetadataCertificateRuntimeProbeTestCase.VARIANTS.subList(1,5));variantNames.add("whole-certificate-pkix-enforcement");for(var name:variantNames){
    reset(folder,originals);var m=base.deepCopy();var selected=new ArrayList<>(entries);selectPkix(folder,m);var affected=name.equals("whole-certificate-pkix-enforcement")?MetadataCertificateRuntimeProbeTestCase.VARIANTS.subList(1,5):List.of(name);
    for(var variant:affected){var exchange=refuse(folder,m,selected,bodies,variant);calibratedCause(input,folder,m,exchange,variant,bodies);}
    require(result(tmp,run,m,selected,bodies,target,credentials,true).outcome()==Outcome.VIOLATED);mutants.put(name,"VIOLATED");
   }
   reset(folder,originals);Files.write(folder.resolve("manifest.json"),manifestRaw);var lifecycle=lifecycle(tmp,run,entries,bodies,target,credentials,actual);require(lifecycle.equals(Map.of("start",true,"ConfigConfirmed",true,"TranscriptReady",true,"Aborted",true,"TimedOut",true,"status-ready",true,"recorded-not-verified",true,"recorded-conclusive",false,"incomplete-history","NOT_VERIFIED")));
   var report=new TreeMap<String,Object>();report.put("runId",run);report.put("caseId",CASE);report.put("targetMetadataSha256",hash(target));report.put("outcome",actual);report.put("negativeControls",negative);report.put("approvedMutants",mutants);report.put("controlsAdopted",false);report.put("pkixCounterexamplesAreDiagnosticCalibrationOnly",true);report.put("nativePkixDiagnosticSha256",hash(Files.readAllBytes(input.resolve("pkix-calibration/output/native-pkix-diagnostic.json"))));report.put("wrapperLifecycle",lifecycle);report.put("manifestSha256",hash(manifestRaw));report.put("productOperations",0);report.put("privateCredentialsPersisted",false);JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[1]).toFile(),report);
  }finally{try(var files=Files.walk(tmp)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
 static String hashUnchecked(byte[] raw){try{return hash(raw);}catch(Exception impossible){throw new IllegalStateException(impossible);}}
}
