package com.samlscope.runner.cases;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.runner.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.security.*;
import java.security.cert.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.*;
import java.util.*;
import java.util.function.*;

/** Archived production reader replay. Counterfactual native causes never alter original receipts. */
public final class VerifySimpleSamlPhpCertificateRuntime {
 static final ObjectMapper M=new JsonCodec().mapper();static final String CASE=MetadataCertificateRuntimeProbeTestCase.CASE;
 static void require(boolean b){if(!b)throw new IllegalArgumentException("SSP certificate original replay failed");}
 static String sha(byte[] b)throws Exception{return SimpleSamlPhpMetadataCertificateRuntimeEvidence.hash(b);}
 static class Data {byte[] manifestRaw,target;ObjectNode m;List<TranscriptEntry> entries;Map<String,byte[]> decoded=new HashMap<>();Map<String,PlanCredentials> keys=new HashMap<>();String run,plan;}
 static void write(Path f,Data d,String name,byte[] bytes)throws Exception{var p=f.resolve(name);Files.createDirectories(p.getParent());Files.write(p,bytes);((ObjectNode)d.m.path("files")).put(name,sha(bytes));}
 static Data load(Path folder,Path data,Path temp)throws Exception{
  var d=new Data();d.manifestRaw=Files.readAllBytes(folder.resolve("manifest.json"));d.m=(ObjectNode)M.readTree(d.manifestRaw);d.run=d.m.path("runId").asText();d.plan=d.m.path("planId").asText();d.target=Files.readAllBytes(folder.resolve("target-metadata.xml"));d.entries=new ArrayList<>(List.of(M.readValue(folder.resolve("transcript.json").toFile(),TranscriptEntry[].class)));
  for(var row:M.readTree(folder.resolve("decoded-manifest.json").toFile())){var p=folder.resolve(row.path("file").asText()).normalize();require(p.startsWith(folder)&&!Files.isSymbolicLink(p));var raw=Files.readAllBytes(p);require(sha(raw).equals(row.path("sha256").asText())&&d.decoded.put(row.path("id").asText(),raw)==null);}
  for(var row:M.readTree(folder.resolve("browser-originals-manifest.json").toFile())){var raw=Files.readAllBytes(folder.resolve(row.path("file").asText()));require(sha(raw).equals(row.path("sha256").asText()));var dest=temp.resolve(row.path("reference").asText());require(dest.normalize().startsWith(temp));Files.createDirectories(dest.getParent());Files.write(dest,raw);}
  var aliases=new ArrayList<Path>();var keydir=data.resolve("keys").resolve(d.plan);aliases.add(keydir);try(var files=Files.list(keydir)){aliases.addAll(files.filter(Files::isDirectory).toList());}
  for(var v:MetadataCertificateRuntimeProbeTestCase.VARIANTS){var md=SecureXml.parse(Files.readAllBytes(folder.resolve(v+"-fixture.xml"))).getDocumentElement();var sp=MetadataAlgorithmEvidence.children(md,"urn:oasis:names:tc:SAML:2.0:metadata","SPSSODescriptor").getFirst();var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(sp.getElementsByTagNameNS("http://www.w3.org/2000/09/xmldsig#","X509Certificate").item(0).getTextContent())));for(var alias:aliases){var certpath=alias.resolve("signing-certificate.der");if(!Files.isRegularFile(certpath))continue;var actual=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(certpath));if(Arrays.equals(actual.getPublicKey().getEncoded(),cert.getPublicKey().getEncoded())){var raw=Files.readAllBytes(alias.resolve("signing-key.pk8"));try{d.keys.put(v,new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(raw)),actual));}finally{Arrays.fill(raw,(byte)0);}break;}}require(d.keys.containsKey(v));}
  return d;
 }
 static TranscriptEntry copy(TranscriptEntry e,String id,String run,String ref,int size){return new TranscriptEntry(id,run,e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),ref,size,e.contentType(),e.rawQuery(),e.samlSummary());}
 static CaseContext context(Data d,boolean complete){var recorder=new TranscriptRecorder(){public List<TranscriptEntry>list(String r){return d.entries.stream().map(e->{var b=d.decoded.get(e.id());return b==null?e:copy(e,e.id(),e.runId(),e.decodedSamlRef(),b.length);}).toList();}public TranscriptEntry record(TranscriptInput i){throw new AssertionError("Replay cannot send");}public TranscriptEntry updateSamlAnalysis(String r,String id,Map<String,Object>s){throw new AssertionError("Replay cannot change history");}};return new DefaultCaseContext(d.run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,complete);}
 static MetadataCertificateRuntimeProbeTestCase wrapper(Path root,Data d){var fallback=new ConfigurationGateTestCase(new AttestedOutcomeTestCase(CASE,TargetRole.IDP,"native",Duration.ofMinutes(1),List.of(AttestationOption.of("satisfies",Outcome.SATISFIED,"declared"))),"native",Duration.ofMinutes(1),ConfigurationFailureSemantics.TEST_PRECONDITION);return new MetadataCertificateRuntimeProbeTestCase(fallback,r->d.target,e->d.decoded.get(e.id()),(r,v)->{com.samlscope.saml.metadata.MetadataService.Variant.parse(v);return r.equals(d.run)?Optional.ofNullable(d.keys.get(v)):Optional.empty();},root.resolveSibling("unused-shib-native"),root);}
 static CaseOutcome observe(Path root,Path folder,Data d,boolean complete)throws Exception{Files.write(folder.resolve("manifest.json"),M.readTree(d.manifestRaw).equals(d.m)?d.manifestRaw:M.writeValueAsBytes(d.m));return ((CaseStep.Finish)wrapper(root,d).start(context(d,complete))).outcome();}
 static void originalEdit(Path folder,Data d,String label,Consumer<ObjectNode> edit)throws Exception{var ref=(ObjectNode)d.m.path("originals").path(label);var id=ref.path("reference").asText();var n=(ObjectNode)M.readTree(d.decoded.get(id));edit.accept(n);var raw=M.writeValueAsBytes(n);d.decoded.put(id,raw);ref.put("sha256",sha(raw));write(folder,d,"native-originals/"+label+".json",raw);}
 static void readbackEdit(Path folder,Data d,String label,Consumer<ObjectNode> edit)throws Exception{String name="native-readbacks/"+label+".json";var n=(ObjectNode)M.readTree(folder.resolve(name).toFile());edit.accept(n);var raw=M.writeValueAsBytes(n);write(folder,d,name,raw);originalEdit(folder,d,label,o->{n.fields().forEachRemaining(x->o.set(x.getKey(),x.getValue()));try{o.put("nativeReadbackSha256",sha(raw));}catch(Exception e){throw new IllegalStateException(e);}});}
 static Map<String,Object> lifecycle(Path root,Data d,CaseOutcome actual){var w=wrapper(root,d);var c=context(d,true);var values=new TreeMap<String,Object>();values.put("start",w.start(c).equals(new CaseStep.Finish(actual)));for(var e:List.of(new CaseEvent.ConfigConfirmed(),new CaseEvent.TranscriptReady(),new CaseEvent.Aborted("ended"),new CaseEvent.TimedOut(Duration.ofMinutes(1))))values.put(e.getClass().getSimpleName(),w.resume(c,CaseState.initial(),e).equals(new CaseStep.Finish(actual)));values.put("status-ready",w.evidenceStatus(c).ready());values.put("recorded-not-verified",w.reevaluateRecordedEvidence(c,CaseOutcome.notVerified("before","before")).orElseThrow().equals(actual));values.put("recorded-conclusive",w.reevaluateRecordedEvidence(c,actual).isPresent());values.put("incomplete-history",((CaseStep.Finish)w.start(context(d,false))).outcome().outcome().name());return values;}
 static void reset(Path folder,Map<String,byte[]> backup)throws Exception{try(var paths=Files.walk(folder)){for(var p:paths.sorted(Comparator.reverseOrder()).filter(p->!p.equals(folder)).toList())Files.delete(p);}for(var row:backup.entrySet()){var p=folder.resolve(row.getKey());Files.createDirectories(p.getParent());Files.write(p,row.getValue());}}
 static ObjectNode counterfactual(Path folder,Path temp,Data d,String variant,Path calibration)throws Exception{
  var diagnostic=M.readTree(calibration.resolve("native-openssl-calibration.json").toFile());require(diagnostic.path("counterfactualCalibrationOnly").asBoolean(false)&&!diagnostic.path("controlsAdopted").asBoolean(true)&&!diagnostic.path("actualProductFinding").asBoolean(true));JsonNode nativeRow=null;for(var row:diagnostic.path("records"))if(variant.equals(row.path("variant").asText()))nativeRow=row;require(nativeRow!=null);ObjectNode epoch=null;for(var row:d.m.path("epochs"))if(variant.equals(row.path("variant").asText()))epoch=(ObjectNode)row;require(epoch!=null);var probe=(ObjectNode)epoch.path("probes").get(0);String request=probe.path("requestReference").asText(),response=probe.path("responseReference").asText();var req=d.entries.stream().filter(e->e.id().equals(request)).findFirst().orElseThrow();var rsp=d.entries.stream().filter(e->e.id().equals(response)).findFirst().orElseThrow();var q=SecureXml.parse(d.decoded.get(request)).getDocumentElement();require(q.getAttribute("ID").equals(nativeRow.path("requestId").asText())&&sha(d.decoded.get(request)).equals(nativeRow.path("requestSha256").asText()));
  var invalid=d.m.path("epochs").get(0).path("probes").get(1);var invalidResponse=d.entries.stream().filter(e->e.id().equals(invalid.path("responseReference").asText())).findFirst().orElseThrow();var body=Files.readAllBytes(temp.resolve(invalidResponse.bodyRef()));var newBody="transcripts/"+d.run+"/"+rsp.id()+".body";Files.write(temp.resolve(newBody),body);var httpLabel=probe.path("nativeHttpOriginal").asText();originalEdit(folder,d,httpLabel,n->{try{var h=(ObjectNode)n.path("native");h.put("responseStatus",500).put("responseBodySha256",sha(body)).put("responseBodyBytes",body.length).put("responseUrl",req.url());}catch(Exception failure){throw new IllegalStateException(failure);}});var httpOriginal=M.readTree(d.decoded.get(d.m.path("originals").path(httpLabel).path("reference").asText()));var http=httpOriginal.path("native");
  int index=d.entries.indexOf(rsp);d.entries.set(index,new TranscriptEntry(rsp.id(),d.run,Direction.INBOUND,rsp.timestamp(),req.correlationId(),"BROWSER",req.url(),500,Map.of(),newBody,body.length,null,0,"text/html",null,Map.of("type","BrowserResponseObservation")));d.decoded.remove(rsp.id());
  var check=(ObjectNode)nativeRow.deepCopy();check.put("schema","samlscope-simplesamlphp-openssl-additional-certificate-check-v1").put("source","native-selected-additional-revocation-check").put("checkerSourceFile",diagnostic.path("checkerSourceFile").asText()).put("checkerSourceSha256",diagnostic.path("checkerSourceSha256").asText()).put("operationStartedAt",http.path("startedAt").asText()).put("operationCompletedAt",http.path("finishedAt").asText()).put("diagnosticNativeSignatureVerifiedAt",nativeRow.path("signatureVerifiedAt").asText()).put("nativeProducerOriginalFile",nativeRow.path("nativeProducerReportFile").asText()).put("nativeProducerOriginalSha256",nativeRow.path("nativeProducerReportSha256").asText());
  for(var name:List.of(diagnostic.path("checkerSourceFile").asText(),nativeRow.path("nativeProducerReportFile").asText()))write(folder,d,name,Files.readAllBytes(calibration.resolve(name)));for(String phase:List.of("setup","failure"))for(String stream:List.of("stdout","stderr")){String name=nativeRow.path(phase).path(stream+"File").asText();write(folder,d,name,Files.readAllBytes(calibration.resolve(name)));}for(var network:nativeRow.path("network"))for(var stream:List.of("stdout","stderr")){String name=network.path(stream+"File").asText();write(folder,d,name,Files.readAllBytes(calibration.resolve(name)));}
  String label=variant+"-counterfactual-check",id="tx_00000000000000000000000001";var n=M.createObjectNode().put("schema","samlscope-simplesamlphp-certificate-runtime-original-v1").put("runId",d.run).put("campaignId","native-metadata-certificate-runtime").put("targetMetadataSha256",d.m.path("targetMetadataSha256").asText()).put("kind","native-additional-certificate-check").put("recordedAt",rsp.timestamp().toString()).put("actionId",probe.path("actionId").asText()).put("requestReference",request).put("responseReference",response);n.set("check",check);byte[] bytes=M.writeValueAsBytes(n);write(folder,d,"native-originals/"+label+".json",bytes);d.decoded.put(id,bytes);((ObjectNode)d.m.path("originals")).set(label,M.createObjectNode().put("reference",id).put("sha256",sha(bytes)));probe.put("nativeCertificateCheckOriginal",label);d.entries.add(new TranscriptEntry(id,d.run,Direction.INBOUND,rsp.timestamp().plusNanos(1),null,"POST","http://localhost:18080/p/"+d.plan+"/sp/paos?run="+d.run,204,Map.of(),null,0,"transcripts/"+d.run+"/"+id+".saml.xml",bytes.length,"application/json",null,Map.of()));return check;
 }
 public static void main(String[]args)throws Exception{
  require(args.length==4);boolean primaryRejected=false;try{com.samlscope.saml.metadata.MetadataService.Variant.parse("primary");}catch(IllegalArgumentException expected){primaryRejected=true;}require(primaryRejected);var source=Path.of(args[0]).toRealPath();var data=Path.of(args[1]);var output=Path.of(args[2]);require(!Files.exists(output));var temp=Files.createTempDirectory("ssp-certificate-replay-");var root=temp.resolve("proof");String run=M.readTree(source.resolve("manifest.json").toFile()).path("runId").asText();var folder=root.resolve(run);Files.createDirectories(folder);var backup=new LinkedHashMap<String,byte[]>();try(var files=Files.walk(source)){for(var p:files.filter(Files::isRegularFile).toList())backup.put(source.relativize(p).toString(),Files.readAllBytes(p));}
  try{reset(folder,backup);var actualData=load(folder,data,temp);var actual=observe(root,folder,actualData,true);require(actual.outcome()==Outcome.SATISFIED);var lifecycle=lifecycle(root,actualData,actual);var controls=new TreeMap<String,String>();
   for(var name:List.of("wrong-run","wrong-target","wrong-adapter","missing-epoch","missing-native-source","foreign-operative-class","signature-setting-disabled","missing-configured-key","native-runtime-changed","missing-restoration","wrong-restoration","private-native-original","missing-invalid-control","missing-normal","foreign-history","duplicate-history","foreign-decoded-reference","duplicate-selected-action","wrong-request-bytes","wrong-response-bytes","generic500","http-wrong-request","http-wrong-body","expired-network-probe","missing-revocation-original","cost-forgot-credential","incomplete-history")){
    reset(folder,backup);var d=load(folder,data,temp);var epoch=d.m.path("epochs").get(0);var normal=epoch.path("probes").get(0);var invalid=epoch.path("probes").get(1);String req=normal.path("requestReference").asText(),rsp=normal.path("responseReference").asText();boolean complete=true;
    switch(name){
     case "wrong-run"->d.m.put("runId","run_00000000000000000000000000");case "wrong-target"->d.m.put("targetMetadataSha256","0".repeat(64));case "wrong-adapter"->d.m.put("adapter","parser-only");case "missing-epoch"->((ArrayNode)d.m.path("epochs")).remove(4);case "missing-native-source"->Files.delete(folder.resolve("native-source/native-xml-security-dsig.php"));
     case "foreign-operative-class"->readbackEdit(folder,d,"control-before",n->((ObjectNode)n.path("operativeClasses").path("SAML2\\Utils")).put("path","/custom/check.php"));case "signature-setting-disabled"->readbackEdit(folder,d,"control-before",n->((ObjectNode)n.path("peers").get(0).path("resolvedMetadata")).put("validate.authnrequest",false));case "missing-configured-key"->readbackEdit(folder,d,"control-before",n->((ArrayNode)n.path("peers").get(0).path("signingKeys")).removeAll());case "native-runtime-changed"->originalEdit(folder,d,"control-after",n->((ObjectNode)n.path("runtime")).put("startedAt","other"));case "missing-restoration"->((ObjectNode)d.m.path("originals")).remove("restoration");case "wrong-restoration"->write(folder,d,"final-configuration.php","other".getBytes());case "private-native-original"->readbackEdit(folder,d,"control-before",n->n.put("password","control-only"));case "missing-invalid-control"->((ArrayNode)epoch.path("probes")).remove(1);case "missing-normal"->d.entries.removeIf(e->e.id().equals(rsp));
     case "foreign-history","foreign-decoded-reference"->{var e=d.entries.getFirst();d.entries.set(0,copy(e,e.id(),name.equals("foreign-history")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-decoded-reference")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef(),e.decodedSamlBytes()));}case "duplicate-history"->d.entries.add(d.entries.getFirst());case "duplicate-selected-action"->{var e=d.entries.stream().filter(x->x.id().equals(req)).findFirst().orElseThrow();String id="tx_00000000000000000000000000";d.entries.add(copy(e,id,e.runId(),"transcripts/"+e.runId()+"/"+id+".saml.xml",e.decodedSamlBytes()));d.decoded.put(id,d.decoded.get(req));}
     case "wrong-request-bytes","wrong-response-bytes"->{String id=name.equals("wrong-request-bytes")?req:rsp;var doc=SecureXml.parse(d.decoded.get(id));doc.getDocumentElement().setAttribute("ID","_changed");d.decoded.put(id,SecureXml.serialize(doc));}
     case "generic500"->{String id=invalid.path("responseReference").asText();var e=d.entries.stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();byte[] page="<h1>UNHANDLEDEXCEPTION</h1>".getBytes();Files.write(temp.resolve(e.bodyRef()),page);d.entries.set(d.entries.indexOf(e),new TranscriptEntry(e.id(),e.runId(),e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),page.length,e.decodedSamlRef(),e.decodedSamlBytes(),e.contentType(),e.rawQuery(),e.samlSummary()));originalEdit(folder,d,"control-invalid-signature-http",n->{try{((ObjectNode)n.path("native")).put("responseBodySha256",sha(page)).put("responseBodyBytes",page.length);}catch(Exception failure){throw new IllegalStateException(failure);}});}
     case "http-wrong-request","http-wrong-body"->originalEdit(folder,d,"control-invalid-signature-http",n->((ObjectNode)n.path("native")).put(name.equals("http-wrong-request")?"requestSha256":"responseBodySha256","0".repeat(64)));
     case "expired-network-probe"->{String nameFile="certificate-revocation-unreachable-network.json";var rows=M.readTree(folder.resolve(nameFile).toFile());for(var row:rows){((ObjectNode)row).put("startedAt","1970-01-01T00:00:00Z");((ObjectNode)row).put("completedAt","1970-01-01T00:00:01Z");}write(folder,d,nameFile,M.writeValueAsBytes(rows));}case "missing-revocation-original"->write(folder,d,"certificate-revoked-fixture.xml",Files.readAllBytes(folder.resolve("control-fixture.xml")));case "cost-forgot-credential"->{var n=(ObjectNode)M.readTree(folder.resolve("operation-counts.json").toFile());n.put("credentialPosts",0);write(folder,d,"operation-counts.json",M.writeValueAsBytes(n));}case "incomplete-history"->complete=false;
    }require(observe(root,folder,d,complete).outcome()==Outcome.NOT_VERIFIED);controls.put(name,"NOT_VERIFIED");
   }
   var mutants=new TreeMap<String,String>();for(var variant:List.of("certificate-revoked","certificate-revocation-unreachable")){reset(folder,backup);var d=load(folder,data,temp);counterfactual(folder,temp,d,variant,Path.of(args[3]));require(observe(root,folder,d,true).outcome()==Outcome.VIOLATED);mutants.put(variant,"VIOLATED");}
   for(var name:List.of("additional-cause-missing","additional-cause-wrong-request","additional-cause-wrong-certificate","additional-cause-wrong-time","additional-cause-reason-forged","additional-cause-stderr-forged")){reset(folder,backup);var d=load(folder,data,temp);var check=counterfactual(folder,temp,d,"certificate-revocation-unreachable",Path.of(args[3]));String label="certificate-revocation-unreachable-counterfactual-check";
    switch(name){case "additional-cause-missing"->{for(var row:d.m.path("epochs"))if(row.path("variant").asText().equals("certificate-revocation-unreachable"))((ObjectNode)row.path("probes").get(0)).remove("nativeCertificateCheckOriginal");}case "additional-cause-wrong-request"->originalEdit(folder,d,label,n->((ObjectNode)n.path("check")).put("requestId","_foreign"));case "additional-cause-wrong-certificate"->originalEdit(folder,d,label,n->((ObjectNode)n.path("check")).put("certificateSha256","0".repeat(64)));case "additional-cause-wrong-time"->originalEdit(folder,d,label,n->((ObjectNode)n.path("check")).put("operationStartedAt","1970-01-01T00:00:00Z"));case "additional-cause-reason-forged"->originalEdit(folder,d,label,n->((ObjectNode)n.path("check")).put("reason","CERTIFICATE_REVOKED"));case "additional-cause-stderr-forged"->write(folder,d,check.path("failure").path("stderrFile").asText(),"error 3 at 0 depth lookup: unable to get certificate CRL".getBytes());}require(observe(root,folder,d,true).outcome()==Outcome.NOT_VERIFIED);controls.put(name,"NOT_VERIFIED");}
   reset(folder,backup);var finalData=load(folder,data,temp);require(observe(root,folder,finalData,true).equals(actual));var report=new TreeMap<String,Object>();report.put("outcome",actual);report.put("negativeControls",controls);report.put("approvedMutants",Map.of("mut-iip-md06-a6-idp",mutants.get("certificate-revocation-unreachable")));report.put("additionalRevokedControl",mutants.get("certificate-revoked"));report.put("counterfactualCalibrationOnly",true);report.put("wrapperLifecycle",lifecycle);report.put("manifestSha256",sha(finalData.manifestRaw));report.put("productionProviderAliasesOnly",true);report.put("providerPrimaryAliasRejected",primaryRejected);report.put("privateMaterialExported",false);report.put("additionalProductOperations",0);report.put("controlsAdopted",false);M.writerWithDefaultPrettyPrinter().writeValue(output.toFile(),report);
  }finally{try(var paths=Files.walk(temp)){for(var p:paths.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}
 }
}
