package com.samlscope.runner.cases;
import static com.samlscope.runner.cases.VerifyNativeRoleKeyConsumption.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.TargetRole;
import com.samlscope.core.transcript.*;
import com.samlscope.saml.crypto.PlanCredentials;
import java.nio.file.*;
import java.time.Duration;
import java.util.*;
import java.util.function.BiFunction;

/** Archived production reader + native causal mutant. Does not send, write configuration, or export keys. */
public final class VerifySimpleSamlPhpSelfContainedTrust {
    static final String TRUST_CASE="IIP-MD06-c-idp-01";
    static ObjectNode mutant(ObjectNode base,Path payload)throws Exception{var m=base.deepCopy();m.put("selectedPath","developer-instrumented-additional-anchor").put("counterfactualCalibrationOnly",true).put("inputFile","mutant-input.json").put("inputSha256",hash(Files.readAllBytes(payload.resolve("mutant-input.json")))).put("nativeOutputFile","mutant-native-output.json").put("nativeOutputSha256",hash(Files.readAllBytes(payload.resolve("mutant-native-output.json"))));return m;}
    static CaseOutcome observe(Path trust,Path role,String run,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,
            BiFunction<String,String,Optional<PlanCredentials>> credentials,boolean complete){
        return observe(trust,role,run,entries,bodies,target,credentials,complete,false);
    }
    static CaseOutcome observe(Path trust,Path role,String run,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> credentials,boolean complete,boolean offline){
        return new SimpleSamlPhpSelfContainedTrustEvidenceFile(trust,role,e->bodies.get(e.id()),r->target,credentials,offline).evaluate(context(run,entries,complete));
    }
    static SelfContainedMetadataTrustEvidenceTestCase wrapper(Path trust,Path role,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> credentials){
        return wrapper(trust,role,bodies,target,credentials,false);
    }
    static SelfContainedMetadataTrustEvidenceTestCase wrapper(Path trust,Path role,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> credentials,boolean offline){
        var leaf=new SimpleSamlPhpSelfContainedTrustEvidenceFile(trust,role,e->bodies.get(e.id()),r->target,credentials,offline);
        var fallback=new AttestedOutcomeTestCase(TRUST_CASE,TargetRole.IDP,"approved-trust","Approved trust prompt",Duration.ofMinutes(1),List.of(AttestationOption.of("satisfied",Outcome.SATISFIED,"declaration.satisfied")));
        return new SelfContainedMetadataTrustEvidenceTestCase(fallback,leaf::exists,leaf::evaluate,SimpleSamlPhpSelfContainedTrustEvidenceFile.ADAPTER,"native-self-contained-trust-evidence",".simplesamlphp-trust.json",offline);
    }
    public static void main(String[] args)throws Exception{
        require(args.length==2);JSON.mapper().enable(com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);var input=Path.of(args[0]);var source=input.resolve("source-role");var created=JSON.mapper().readTree(input.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText();var target=Files.readAllBytes(input.resolve("target-metadata.xml"));var entries=List.of(JSON.mapper().readValue(input.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new HashMap<String,byte[]>();for(var row:JSON.mapper().readTree(source.resolve("decoded-manifest.json").toFile())){var bytes=Files.readAllBytes(source.resolve(row.path("file").asText()));require(hash(bytes).equals(row.path("sha256").asText())&&bodies.put(row.path("id").asText(),bytes)==null);}baseline(source,run,plan,entries,bodies,target);var credentials=keys(run,plan,source.resolve("receipt"));var temp=Files.createTempDirectory("ssp-native-trust-proof-");var trust=Files.createDirectory(temp.resolve("trust"));var role=Files.createDirectory(temp.resolve("role"));var nativeRole=Files.createDirectory(role.resolve(run));var payload=Files.createDirectory(trust.resolve(run+".simplesamlphp-trust"));String file=run+".simplesamlphp-trust.json";
        try{
            try(var files=Files.list(source.resolve("receipt"))){for(var p:files.toList())Files.copy(p,nativeRole.resolve(p.getFileName()));}
            var raw=Files.readAllBytes(input.resolve("trust-receipt.json"));var base=(ObjectNode)JSON.mapper().readTree(raw);Files.write(trust.resolve(file),raw);
            try(var files=Files.list(input.resolve("receipt"))){for(var p:files.toList())Files.copy(p,payload.resolve(p.getFileName()));}
            var actual=observe(trust,role,run,entries,bodies,target,credentials,true);require(actual.outcome()==Outcome.SATISFIED);var negatives=new TreeMap<String,String>();
            for(String name:List.of("wrong-run","wrong-peer","wrong-target","wrong-campaign","wrong-role-binding","counterfactual-stock-mismatch","stock-labels-flipped","unknown-selected-path","missing-diagnostic","changed-producer","wrong-native-class","stock-extra-anchor-supplied","stock-signature-rejected","stock-selected-outcome-flipped","mutant-not-rejected","mutant-not-accepted-with-anchor","mutant-wrong-certificate","mutant-math-invalid","diagnostic-wrong-request","diagnostic-wrong-request-hash","diagnostic-wrong-metadata","missing-normal-row","duplicate-normal-row","changed-shared-restoration","extra-shared-key","extra-native-trust","wrong-decryption-key","foreign-history","duplicate-history","incomplete-history")){
                var m=name.startsWith("mutant-")?mutant(base,payload):base.deepCopy();var selected=new ArrayList<>(entries);var key=credentials;boolean complete=true;var nativeFile=payload.resolve(m.path("nativeOutputFile").asText());var nativeBytes=Files.readAllBytes(nativeFile);byte[] restoreRole=null;Path changedRole=null;
                switch(name){
                    case "wrong-run"->m.put("runId","foreign");case "wrong-peer"->m.put("peerEntityId","foreign");case "wrong-target"->m.put("targetMetadataSha256","0".repeat(64));case "wrong-campaign"->m.put("campaignId","foreign");case "wrong-role-binding"->m.put("roleReceiptSha256","0".repeat(64));
                    case "counterfactual-stock-mismatch"->m.put("counterfactualCalibrationOnly",true);case "stock-labels-flipped"->m.put("selectedPath","developer-instrumented-additional-anchor").put("counterfactualCalibrationOnly",true);case "unknown-selected-path"->m.put("selectedPath","declaration");case "missing-diagnostic"->Files.delete(nativeFile);case "changed-producer"->m.put("producerSha256","0".repeat(64));
                    case "wrong-decryption-key"->key=(r,v)->credentials.apply(r,"three-signing-keys-first");case "foreign-history"->{var e=selected.getFirst();selected.set(0,altered(e,"run_00000000000000000000000000",e.decodedSamlRef()));}case "duplicate-history"->selected.add(selected.getFirst());case "incomplete-history"->complete=false;
                    case "changed-shared-restoration","extra-shared-key","extra-native-trust"->{changedRole=nativeRole.resolve(name.equals("changed-shared-restoration")?"final-configuration.php":"native-message.php");restoreRole=Files.readAllBytes(changedRole);Files.writeString(changedRole,"<?php // extra unsupported trust input");}
                    default->{var n=(ObjectNode)JSON.mapper().readTree(nativeBytes);var record=(ObjectNode)n.path("records").get(0);switch(name){case "wrong-native-class"->((ObjectNode)n.at("/selectedNativeClasses/native-message.php")).put("sha256","0".repeat(64));case "stock-extra-anchor-supplied"->record.put("stockAdditionalTrustInputSupplied",true);case "stock-signature-rejected"->record.put("stockNativeSignatureAccepted",false);case "stock-selected-outcome-flipped"->((ObjectNode)record.path("selectedConsumer")).put("accepted",false);case "mutant-not-rejected"->((ObjectNode)record.path("mutant")).put("rejected",false);case "mutant-not-accepted-with-anchor"->((ObjectNode)record.path("mutant")).put("acceptedWithSamePublicAnchorSupplied",false);case "mutant-wrong-certificate"->((ObjectNode)record.path("mutant")).put("exceptionMessage","ExternalTrustInputRequired:foreign");case "mutant-math-invalid"->((ObjectNode)record.path("mutant")).put("mathematicalSignatureAccepted",false);case "diagnostic-wrong-request"->record.put("requestReference","foreign");case "diagnostic-wrong-request-hash"->record.put("requestSha256","0".repeat(64));case "diagnostic-wrong-metadata"->record.put("fixtureSha256","0".repeat(64));case "missing-normal-row"->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("records")).remove(0);case "duplicate-normal-row"->((ObjectNode)n.path("records").get(1)).put("fixtureId",record.path("fixtureId").asText());default->throw new IllegalArgumentException(name);}var bytes=JSON.mapper().writeValueAsBytes(n);Files.write(nativeFile,bytes);m.put("nativeOutputSha256",hash(bytes));}
                }
                Files.write(trust.resolve(file),JSON.mapper().writeValueAsBytes(m));var n=observe(trust,role,run,selected,bodies,target,key,complete);require(n.outcome()==Outcome.NOT_VERIFIED&&observe(trust,role,run,selected,bodies,target,key,complete,true).outcome()==Outcome.NOT_VERIFIED);negatives.put(name,n.outcome().name());if(changedRole!=null)Files.write(changedRole,restoreRole);Files.write(nativeFile,nativeBytes);Files.write(trust.resolve(file),raw);
            }
            var costFile=payload.resolve("operations.json");var originalCosts=Files.readAllBytes(costFile);
            for(String name:List.of("invocation-input-hash","invocation-output-hash","invocation-source-hash","invocation-command","invocation-exit","invocation-mixed-container","missing-invocation")){
                var costs=(ObjectNode)JSON.mapper().readTree(originalCosts);var row=(ObjectNode)costs.path("attempts").get(0);switch(name){case "invocation-input-hash"->row.put("inputSha256","foreign");case "invocation-output-hash"->row.put("outputSha256","foreign");case "invocation-source-hash"->row.put("sourceSha256","foreign");case "invocation-command"->((com.fasterxml.jackson.databind.node.ArrayNode)row.path("command")).set(3,JSON.mapper().getNodeFactory().textNode("different-product"));case "invocation-exit"->row.put("exitCode",1);case "invocation-mixed-container"->((ObjectNode)costs.path("nativeContainerAfter")).put("Id","foreign");case "missing-invocation"->((com.fasterxml.jackson.databind.node.ArrayNode)costs.path("attempts")).remove(0);default->throw new AssertionError(name);}
                var bytes=JSON.mapper().writeValueAsBytes(costs);Files.write(costFile,bytes);var m=base.deepCopy().put("operationsSha256",hash(bytes));Files.write(trust.resolve(file),JSON.mapper().writeValueAsBytes(m));require(observe(trust,role,run,entries,bodies,target,credentials,true).outcome()==Outcome.NOT_VERIFIED&&observe(trust,role,run,entries,bodies,target,credentials,true,true).outcome()==Outcome.NOT_VERIFIED);negatives.put(name,"NOT_VERIFIED");Files.write(costFile,originalCosts);Files.write(trust.resolve(file),raw);
            }
            var mutant=mutant(base,payload);Files.write(trust.resolve(file),JSON.mapper().writeValueAsBytes(mutant));var productionMutant=observe(trust,role,run,entries,bodies,target,credentials,true);var productionMutantWrapper=wrapper(trust,role,bodies,target,credentials);require(productionMutant.outcome()==Outcome.NOT_VERIFIED&&((CaseStep.Finish)productionMutantWrapper.start(context(run,entries,true))).outcome().outcome()==Outcome.NOT_VERIFIED&&!productionMutantWrapper.evidenceStatus(context(run,entries,true)).ready());var violation=observe(trust,role,run,entries,bodies,target,credentials,true,true);require(violation.outcome()==Outcome.VIOLATED&&Boolean.TRUE.equals(violation.details().get("counterfactual_calibration_only")));var fixtureWrapper=wrapper(trust,role,bodies,target,credentials,true);require(((CaseStep.Finish)fixtureWrapper.start(context(run,entries,true))).outcome().equals(violation)&&fixtureWrapper.evidenceStatus(context(run,entries,true)).ready());Files.write(trust.resolve(file),raw);
            var normalWrapper=wrapper(trust,role,bodies,target,credentials);var c=context(run,entries,true);require(((CaseStep.Finish)normalWrapper.start(c)).outcome().equals(actual)&&normalWrapper.evidenceStatus(c).ready()&&normalWrapper.reevaluateRecordedEvidence(c,CaseOutcome.notVerified("previous","previous")).orElseThrow().equals(actual)&&normalWrapper.reevaluateRecordedEvidence(c,actual).isEmpty());for(var event:List.<CaseEvent>of(new CaseEvent.TranscriptReady(),new CaseEvent.Attested("satisfied",""),new CaseEvent.Aborted("cancel")))require(((CaseStep.Finish)normalWrapper.resume(c,null,event)).outcome().equals(actual));
            var result=new TreeMap<String,Object>();result.put("runId",run);result.put("caseId",TRUST_CASE);result.put("outcome",actual);result.put("negativeControls",negatives);result.put("approvedMutant",violation);result.put("sameReaderPredicateAndExplicitOfflineWrapper",true);result.put("productionMutantOutcome",productionMutant);result.put("counterfactualAdoptedAsProductFinding",false);result.put("privateKeyExported",false);result.put("plaintextPersisted",false);result.put("productConfigurationWrites",0);result.put("protocolOperations",0);result.put("credentialPosts",0);JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[1]).toFile(),result);
        }finally{try(var files=Files.walk(temp)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
    }
}
