package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.runner.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.security.*;
import java.security.cert.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.*;
import java.util.*;
import java.util.function.BiFunction;

/** Original replay only. No Recorder writes, product actions, or plaintext identifiers are exported. */
public final class VerifyShibbolethMetadataValidity {
 static final JsonCodec JSON=new JsonCodec();static final String CASE="IIP-MD05-ar-idp-01",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#";
 static void require(boolean value){if(!value)throw new IllegalArgumentException("Validity original replay failed");}
 static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 static void reset(Path folder,Map<String,byte[]> originals)throws Exception{try(var files=Files.list(folder)){for(var p:files.toList())Files.delete(p);}for(var row:originals.entrySet())Files.write(folder.resolve(row.getKey()),row.getValue());}
 static void change(Path folder,ObjectNode manifest,String file,byte[] bytes)throws Exception{Files.write(folder.resolve(file),bytes);((ObjectNode)manifest.path("originals")).put(file,hash(bytes));}
 static void edit(Path folder,ObjectNode manifest,String file,java.util.function.Consumer<ObjectNode> action)throws Exception{var node=(ObjectNode)JSON.mapper().readTree(folder.resolve(file).toFile());action.accept(node);change(folder,manifest,file,JSON.mapper().writeValueAsBytes(node));}
 static DefaultCaseContext context(String run,List<TranscriptEntry> entries,boolean complete){var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String selected){return entries;}public TranscriptEntry record(TranscriptInput input){throw new AssertionError("Replay submitted an action");}public TranscriptEntry updateSamlAnalysis(String id,String correlation,Map<String,Object> summary){throw new AssertionError("Replay changed an original");}};return new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),new TestPlan.Parameters(180,45,"reference"),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,complete);}
 static CaseOutcome result(Path root,String run,ObjectNode manifest,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,boolean complete)throws Exception{var path=root.resolve(run).resolve("manifest.json");if(!Files.exists(path)||!JSON.mapper().readTree(Files.readAllBytes(path)).equals(manifest))Files.write(path,JSON.mapper().writeValueAsBytes(manifest));return new MetadataValidityEvidence(root,e->bodies.get(e.id()),r->target,keys).evaluate(context(run,entries,complete)).orElse(CaseOutcome.notVerified("unproven","unproven"));}
 static TranscriptEntry altered(TranscriptEntry e,String run,String decoded){return new TranscriptEntry(e.id(),run,e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),decoded,e.decodedSamlBytes(),e.contentType(),e.rawQuery(),e.samlSummary());}
 static BiFunction<String,String,Optional<PlanCredentials>> keys(String run,String plan,Path receipt)throws Exception{
  var result=new HashMap<String,PlanCredentials>();for(var variant:List.of("live-validity-root","live-validity-parent","live-validity-child")){var document=SecureXml.parse(Files.readAllBytes(receipt.resolve(variant+"-fixture.xml")));var keys=document.getElementsByTagNameNS(MD,"KeyDescriptor");X509Certificate cert=null;
   for(int i=0;i<keys.getLength();i++){var key=(org.w3c.dom.Element)keys.item(i);if("encryption".equals(key.getAttribute("use"))){var encoded=Base64.getMimeDecoder().decode(key.getElementsByTagNameNS(DS,"X509Certificate").item(0).getTextContent());cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(encoded));}}
   require(cert!=null);try(var aliases=Files.list(Path.of("/data/keys/"+plan))){for(var alias:aliases.filter(Files::isDirectory).toList())if(Arrays.equals(Files.readAllBytes(alias.resolve("signing-certificate.der")),cert.getEncoded())){var raw=Files.readAllBytes(alias.resolve("signing-key.pk8"));try{result.put(variant,new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(raw)),cert));}finally{Arrays.fill(raw,(byte)0);}break;}}require(result.containsKey(variant));
  }return (selected,variant)->selected.equals(run)?Optional.ofNullable(result.get(variant)):Optional.empty();
 }
 static Map<String,Object> lifecycle(Path root,String run,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,CaseOutcome actual)throws Exception{
  var fallback=new ConfigurationGateTestCase(new AttestedOutcomeTestCase(CASE,TargetRole.IDP,"validity.evidence",Duration.ofMinutes(1),List.of(AttestationOption.of("evidence_satisfies",Outcome.SATISFIED,"declaration.satisfies"))),"validity.config",Duration.ofMinutes(1),ConfigurationFailureSemantics.TEST_PRECONDITION);
  var wrapper=new MetadataValidityConfigurationTestCase(fallback,root,e->bodies.get(e.id()),r->target,keys);var context=context(run,entries,true);var map=new TreeMap<String,Object>();map.put("start",((CaseStep.Finish)wrapper.start(context)).outcome().equals(actual));var state=new CaseState("configuration",Map.of());
  for(var event:List.of(new CaseEvent.ConfigConfirmed(),new CaseEvent.TranscriptReady(),new CaseEvent.Aborted("operator-ended"),new CaseEvent.TimedOut(Duration.ofMinutes(1))))map.put(event.getClass().getSimpleName(),((CaseStep.Finish)wrapper.resume(context,state,event)).outcome().equals(actual));
  map.put("status-ready",wrapper.evidenceStatus(context).ready());map.put("recorded-not-verified",wrapper.reevaluateRecordedEvidence(context,CaseOutcome.notVerified("before","before")).orElseThrow().equals(actual));map.put("recorded-conclusive",wrapper.reevaluateRecordedEvidence(context,actual).isPresent());map.put("incomplete-history",((CaseStep.Finish)wrapper.start(context(run,entries,false))).outcome().outcome().name());return map;
 }

 static void verifyBaseline(Path input,String run,String plan,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] targetRaw)throws Exception{
  var proof=JSON.mapper().readTree(input.resolve("baseline-recovery/baseline-proof.json").toFile());require(run.equals(proof.path("runId").asText())&&proof.path("expiryPairsResent").asInt(-1)==0&&proof.path("protocolSubmissions").asInt(-1)==1);var request=entries.stream().filter(e->e.id().equals(proof.path("requestReference").asText())).findFirst().orElseThrow();var response=entries.stream().filter(e->e.id().equals(proof.path("responseReference").asText())).findFirst().orElseThrow();var req=SecureXml.parse(bodies.get(request.id())).getDocumentElement();var sp=SecureXml.parse(Files.readAllBytes(input.resolve("baseline-recovery/fixture.xml"))).getDocumentElement();var target=SecureXml.parse(targetRaw).getDocumentElement();require(run.equals(request.runId())&&run.equals(response.runId())&&request.direction()==Direction.OUTBOUND&&response.direction()==Direction.INBOUND&&"GET".equals(request.method())&&"POST".equals(response.method())&&request.timestamp().isBefore(response.timestamp())&&req.getAttribute("ID").equals(request.correlationId())&&req.getAttribute("ID").equals(response.correlationId())&&Boolean.TRUE.equals(response.samlSummary().get("normalFlowAccepted")));
  var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(Path.of("/data/keys/"+plan+"/signing-certificate.der")));require(new RedirectSignatureVerifier().isValidForMessage(request.rawQuery(),cert,bodies.get(request.id())));var encoded=Files.readAllBytes(Path.of("/data/keys/"+plan+"/signing-key.pk8"));try{var credential=new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded)),cert);VerifiedResponseAssertion.read(SecureXml.parse(bodies.get(response.id())).getDocumentElement(),target.getAttribute("entityID"),MetadataAlgorithmEvidence.signingKeys(target),sp,Optional.of(credential),req.getAttribute("ID"),req.getAttribute("AssertionConsumerServiceURL"));}finally{Arrays.fill(encoded,(byte)0);}
 }
 public static void main(String[] args)throws Exception{
  require(args.length==2);JSON.mapper().enable(com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);java.util.logging.Logger.getLogger("org.apache.xml.security.signature.XMLSignature").setLevel(java.util.logging.Level.SEVERE);var input=Path.of(args[0]);var receipt=input.resolve("receipt");var created=JSON.mapper().readTree(input.resolve("created.json").toFile()).path("run");var run=created.path("id").asText();var plan=created.path("planId").asText();var manifestRaw=Files.readAllBytes(receipt.resolve("manifest.json"));var base=(ObjectNode)JSON.mapper().readTree(manifestRaw);require(run.equals(base.path("runId").asText()));var target=Files.readAllBytes(input.resolve("target-metadata.xml"));var entries=List.of(JSON.mapper().readValue(input.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new HashMap<String,byte[]>();for(var row:JSON.mapper().readTree(input.resolve("decoded-manifest.json").toFile())){var raw=Files.readAllBytes(input.resolve(row.path("file").asText()));require(hash(raw).equals(row.path("sha256").asText())&&bodies.put(row.path("id").asText(),raw)==null);}for(var e:entries)require(run.equals(e.runId())&&(e.decodedSamlRef()==null||("transcripts/"+run+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef())));
  verifyBaseline(input,run,plan,entries,bodies,target);var credentials=keys(run,plan,receipt);var originals=new LinkedHashMap<String,byte[]>();try(var files=Files.list(receipt)){for(var file:files.toList())originals.put(file.getFileName().toString(),Files.readAllBytes(file));}var tmp=Files.createTempDirectory("validity-replay-");var folder=Files.createDirectories(tmp.resolve(run));
  try{
   reset(folder,originals);var actual=result(tmp,run,base,entries,bodies,target,credentials,true);require(actual.outcome()==Outcome.SATISFIED);var negative=new TreeMap<String,String>();
   for(var name:List.of("wrong-run","wrong-target","wrong-adapter","missing-parent","wrong-source","wrong-provider","wrong-restoration","native-runtime-changed","wrong-zero-grace-class","wrong-query-entity","query-not-rejected","query-nonempty","query-after-send","warning-wrong-entity","warning-query-ingress","warning-outside-send","warning-duplicate-range","warning-wrong-range","warning-no-original","historical-offset-claimed","http-wrong-request-hash","http-wrong-url","http-before-clock","http-saml-response-present","missing-control","tampered-control","foreign-run-entry","duplicate-entry","foreign-decoded-reference","tampered-request","tampered-response","wrong-decryption-key","incomplete-history")){
    reset(folder,originals);var m=base.deepCopy();var selected=new ArrayList<>(entries);var raw=new HashMap<>(bodies);var selectedKeys=credentials;boolean complete=true;var parent=m.path("observations").get(1);String request=parent.path("before").path("requestReference").asText(),response=parent.path("before").path("responseReference").asText();
    switch(name){
     case "wrong-run"->m.put("runId","run_00000000000000000000000000");case "wrong-target"->m.put("targetMetadataSha256","0".repeat(64));case "wrong-adapter"->m.put("adapter","parser-only");case "missing-parent"->((com.fasterxml.jackson.databind.node.ArrayNode)m.path("observations")).remove(1);case "wrong-source"->change(folder,m,"live-validity-parent-after-source.xml","<wrong/>".getBytes());case "wrong-provider"->change(folder,m,"live-validity-parent-after-providers.xml","<wrong/>".getBytes());case "wrong-restoration"->change(folder,m,"final-providers.xml","<wrong/>".getBytes());
     case "native-runtime-changed"->{var n=JSON.mapper().readTree(folder.resolve("target-container-inspect-end.json").toFile());((ObjectNode)n.get(0)).put("Id","other");change(folder,m,"target-container-inspect-end.json",JSON.mapper().writeValueAsBytes(n));}case "wrong-zero-grace-class"->change(folder,m,"native-entity-validity.class",new byte[]{1});
     case "wrong-query-entity"->edit(folder,m,"live-validity-parent-after-metadata-query.json",n->n.put("entityId","other"));case "query-not-rejected"->edit(folder,m,"live-validity-parent-after-metadata-query.json",n->n.put("exitCode",0));case "query-nonempty"->{change(folder,m,"live-validity-parent-after-metadata-stdout.txt","<EntityDescriptor/>".getBytes());edit(folder,m,"live-validity-parent-after-metadata-query.json",n->n.put("stdoutSha256",hashUnchecked("<EntityDescriptor/>".getBytes())));}case "query-after-send"->edit(folder,m,"live-validity-parent-after-metadata-query.json",n->n.put("recordedAt","2099-01-01T00:00:00Z"));
     case "warning-wrong-entity","warning-query-ingress","warning-outside-send"->{var file="live-validity-parent-retrospective-native-log-line.txt";var line=new String(originals.get(file));line=name.equals("warning-wrong-entity")?line.replace(base.path("entityId").asText(),"http://other.invalid/entity"):name.equals("warning-query-ingress")?line.replace("172.21.0.1","127.0.0.1"):line.replace("2026-10-02 05:06:37,281","2026-10-02 05:06:00,281");change(folder,m,file,line.getBytes());change(folder,m,"live-validity-parent-after-probe-process.log",line.getBytes());final var changed=line;edit(folder,m,"retrospective-log-range.json",n->{var r=(ObjectNode)n.path("ranges").get(1);r.put("sha256",hashUnchecked(changed.getBytes()));r.put("offsetEnd",r.path("offsetStart").asLong()+changed.getBytes().length);if(name.equals("warning-outside-send"))r.put("nativeInstant","2026-10-02T05:06:00.281Z");});}
     case "warning-duplicate-range"->edit(folder,m,"retrospective-log-range.json",n->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("ranges")).add(n.path("ranges").get(1)));case "warning-wrong-range"->edit(folder,m,"retrospective-log-range.json",n->((ObjectNode)n.path("ranges").get(1)).put("offsetEnd",1));case "warning-no-original"->Files.delete(folder.resolve("live-validity-parent-retrospective-native-log-line.txt"));case "historical-offset-claimed"->edit(folder,m,"retrospective-log-range.json",n->n.put("historicalBeforeOffsetCaptured",true));
     case "http-wrong-request-hash"->((ObjectNode)parent.path("after").path("nativeHttp").get(0)).put("requestSha256","0".repeat(64));case "http-wrong-url"->((ObjectNode)parent.path("after").path("nativeHttp").get(0)).put("requestUrl","http://wrong.invalid/");case "http-before-clock"->((ObjectNode)parent.path("after").path("nativeHttp").get(0)).put("startedAt","1970-01-01T00:00:00Z");case "http-saml-response-present"->((ObjectNode)parent.path("after").path("nativeHttp").get(0)).put("samlResponseFormPresent",true);
     case "missing-control"->m.remove("signatureControl");case "tampered-control"->{var id=m.path("signatureControl").path("requestReference").asText();var x=SecureXml.parse(raw.get(id));x.getDocumentElement().setAttribute("Version","1.1");raw.put(id,SecureXml.serialize(x));}
     case "foreign-run-entry","foreign-decoded-reference"->{var index=0;while(!selected.get(index).id().equals(response))index++;var e=selected.get(index);selected.set(index,altered(e,name.equals("foreign-run-entry")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-decoded-reference")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef()));}case "duplicate-entry"->selected.add(selected.getFirst());
     case "tampered-request","tampered-response"->{var ref=name.equals("tampered-request")?request:response;var x=SecureXml.parse(raw.get(ref));x.getDocumentElement().setAttribute("ID","_tampered");raw.put(ref,SecureXml.serialize(x));}case "wrong-decryption-key"->{var key=new PlanCredentials(KeyPairGenerator.getInstance("RSA").generateKeyPair().getPrivate(),credentials.apply(run,"live-validity-root").orElseThrow().certificate());selectedKeys=(r,v)->Optional.of(key);}case "incomplete-history"->complete=false;
    }
    require(result(tmp,run,m,selected,raw,target,selectedKeys,complete).outcome()==Outcome.NOT_VERIFIED);negative.put(name,"NOT_VERIFIED");
   }
   var mutants=new TreeMap<String,String>();var producer=JSON.mapper().readTree(input.resolve("calibration-r3/producer.json").toFile());require(!producer.path("controlsAdopted").asBoolean(true)&&!producer.path("nativePrivateKeyExported").asBoolean(true));
   for(int i=0;i<3;i++){
    reset(folder,originals);var m=base.deepCopy();var row=m.path("observations").get(i);var variant=row.path("variant").asText();var control=producer.path("controls").get(i);require(variant.equals(control.path("variant").asText()));var bytes=Files.readAllBytes(input.resolve("calibration-r3").resolve(control.path("file").asText()));require(hash(bytes).equals(control.path("sha256").asText()));var x=SecureXml.parse(bytes).getDocumentElement();var id="tx_0000000000000000000000000"+i;String rid=x.getAttribute("InResponseTo");var timestamp=Instant.parse(x.getAttribute("IssueInstant"));var h=(ObjectNode)row.path("after").path("nativeHttp").get(0);h.put("responseStatus",200);h.put("samlResponseFormPresent",true);h.put("responseSamlSha256",hash(bytes));((ObjectNode)row.path("after")).put("responseReference",id);
    var response=new TranscriptEntry(id,run,Direction.INBOUND,timestamp,rid,"POST",x.getAttribute("Destination"),200,Map.of(),"synthetic-calibration",bytes.length,"transcripts/"+run+"/"+id+".saml.xml",bytes.length,"application/saml+xml",null,Map.of("type","Response","inResponseTo",rid,"metadataProbeAccepted",true));var selected=new ArrayList<>(entries);selected.add(response);var raw=new HashMap<>(bodies);raw.put(id,bytes);var audit=new String(originals.get("native-request-bound-audit.log"))+"SAMLscope-signature-v1|"+rid+"|"+base.path("entityId").asText()+"||Success|true|POST|SAML2.SSO|"+timestamp+"\n";change(folder,m,"native-request-bound-audit.log",audit.getBytes());var outcome=result(tmp,run,m,selected,raw,target,credentials,true);require(outcome.outcome()==Outcome.VIOLATED);mutants.put(variant.equals("live-validity-parent")?"ignore-earlier-parent":variant.equals("live-validity-child")?"ignore-earlier-child":"ignore-root-deadline",outcome.outcome().name());
   }
   reset(folder,originals);Files.write(folder.resolve("manifest.json"),manifestRaw);var lifecycle=lifecycle(tmp,run,entries,bodies,target,credentials,actual);require(lifecycle.equals(Map.of("start",true,"ConfigConfirmed",true,"TranscriptReady",true,"Aborted",true,"TimedOut",true,"status-ready",true,"recorded-not-verified",true,"recorded-conclusive",false,"incomplete-history","NOT_VERIFIED")));
   JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[1]).toFile(),Map.of("runId",run,"caseId",CASE,"targetMetadataSha256",hash(target),"outcome",actual,"negativeControls",negative,"approvedMutants",mutants,"wrapperLifecycle",lifecycle,"manifestSha256",hash(manifestRaw),"productOperations",0,"privateCredentialsPersisted",false));
  }finally{try(var files=Files.walk(tmp)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
 static String hashUnchecked(byte[] bytes){try{return hash(bytes);}catch(Exception e){throw new IllegalArgumentException(e);}}
}
