package com.samlscope.runner.cases;
import com.samlscope.store.JsonCodec;
import com.samlscope.core.transcript.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.evaluation.*;
import com.samlscope.runner.DefaultCaseContext;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.file.*;
import java.security.*;
import java.security.cert.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.*;
import java.util.*;

/** Actual production leaf replay: Run credentials and decrypted principals stay in JVM memory. */
public final class VerifyShibbolethTransientAllowCreate {
 static final JsonCodec JSON=new JsonCodec();static final String SUFFIX=".shibboleth-transient-allow-create";
 static void require(boolean v){if(!v)throw new IllegalStateException("Native transient replay incomplete");}
 static String hash(byte[] b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
 static String hashUnchecked(byte[] b){try{return hash(b);}catch(Exception e){throw new IllegalStateException(e);}}
 static CaseOutcome result(Path root,ObjectNode m,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,PrivateKey key,boolean complete)throws Exception{
  var run=m.path("runId").asText();if(!Files.exists(root.resolve(run+SUFFIX+".json"))||!JSON.mapper().readTree(Files.readAllBytes(root.resolve(run+SUFFIX+".json"))).equals(m))Files.write(root.resolve(run+SUFFIX+".json"),JSON.mapper().writeValueAsBytes(m));var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String r){return entries;}public TranscriptEntry record(TranscriptInput i){throw new AssertionError("Replay sent protocol");}public TranscriptEntry updateSamlAnalysis(String i,String c,Map<String,Object>s){throw new AssertionError("Replay changed originals");}};
  var context=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,complete);
  return new ShibbolethTransientAllowCreateEvidence(root,e->bodies.get(e.id()),r->target,r->Optional.ofNullable(key)).evaluate(context).orElse(CaseOutcome.notVerified("unproven","unproven"));
 }
 static Map<String,Object> lifecycle(Path directory,ObjectNode manifest,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,PrivateKey key,CaseOutcome expected)throws Exception{
  var run=manifest.path("runId").asText();if(!Files.exists(directory.resolve(run+SUFFIX+".json"))||!JSON.mapper().readTree(Files.readAllBytes(directory.resolve(run+SUFFIX+".json"))).equals(manifest))Files.write(directory.resolve(run+SUFFIX+".json"),JSON.mapper().writeValueAsBytes(manifest));var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String r){return entries;}public TranscriptEntry record(TranscriptInput i){throw new AssertionError("Native lifecycle sent protocol");}public TranscriptEntry updateSamlAnalysis(String i,String c,Map<String,Object>x){throw new AssertionError("Native lifecycle changed originals");}};
  var context=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,true);
  var test=new TransientAllowCreateScenarioTestCase(r->{throw new AssertionError("Owned proof consulted active configuration");},r->r.equals(run)?Optional.of(key):Optional.empty()).withNativeEvidence(directory,e->bodies.get(e.id()),r->target);
  require(test.start(context).equals(new com.samlscope.core.caseexec.CaseStep.Finish(expected)));for(var event:List.of(new com.samlscope.core.caseexec.CaseEvent.TranscriptReady(),new com.samlscope.core.caseexec.CaseEvent.ConfigConfirmed(),new com.samlscope.core.caseexec.CaseEvent.Aborted("cancelled"),new com.samlscope.core.caseexec.CaseEvent.TimedOut(Duration.ZERO)))require(test.resume(context,com.samlscope.core.caseexec.CaseState.initial(),event).equals(new com.samlscope.core.caseexec.CaseStep.Finish(expected)));
  require(test.queuedEvidenceOutcome(context).equals(expected)&&test.evidenceStatus(context).ready());require(test.reevaluateRecordedEvidence(context,CaseOutcome.notVerified("pending","idp.transient-allow-create.unproven")).orElseThrow().equals(expected)&&test.reevaluateRecordedEvidence(context,CaseOutcome.of(Outcome.SATISFIED,"already-conclusive",List.of())).isEmpty());
  var incomplete=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,false);require(((com.samlscope.core.caseexec.CaseStep.Finish)test.start(incomplete)).outcome().outcome()==Outcome.NOT_VERIFIED&&!test.evidenceStatus(incomplete).ready()&&test.queuedEvidenceOutcome(incomplete).outcome()==Outcome.NOT_VERIFIED&&test.reevaluateRecordedEvidence(incomplete,CaseOutcome.notVerified("pending","idp.transient-allow-create.unproven")).isEmpty());
  var empty=new TransientAllowCreateScenarioTestCase(r->{throw new AssertionError("Owned invalid proof consulted active configuration");},r->Optional.empty()).withNativeEvidence(directory,e->bodies.get(e.id()),r->target);require(((com.samlscope.core.caseexec.CaseStep.Finish)empty.start(context)).outcome().outcome()==Outcome.NOT_VERIFIED);
  return Map.of("startResume","SATISFIED","queued","SATISFIED","recordedUpdate",true,"existingConclusiveUnchanged",true,"statusReady",true,"incompleteHistory","NOT_VERIFIED","emptyKey","NOT_VERIFIED","productOperations",0);
 }
 static void reset(Path folder,Map<String,byte[]> files)throws Exception{try(var list=Files.list(folder)){for(var p:list.toList())Files.delete(p);}for(var e:files.entrySet())Files.write(folder.resolve(e.getKey()),e.getValue());}
 static void change(Path folder,ObjectNode m,String name,byte[] b)throws Exception{Files.write(folder.resolve(name),b);((ObjectNode)m.path("files")).put(name,hash(b));}
 static void edit(Path folder,ObjectNode m,String name,java.util.function.Consumer<ObjectNode> edit)throws Exception{var n=(ObjectNode)JSON.mapper().readTree(folder.resolve(name).toFile());edit.accept(n);change(folder,m,name,JSON.mapper().writeValueAsBytes(n));}
 static TranscriptEntry altered(TranscriptEntry e,String run,String content,String correlation){return new TranscriptEntry(e.id(),run,e.direction(),e.timestamp(),correlation,e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),content,e.decodedSamlBytes(),e.contentType(),e.rawQuery(),e.samlSummary());}
 public static void main(String[]args)throws Exception{
  require(args.length==3);JSON.mapper().enable(com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);java.util.logging.Logger.getLogger("org.apache.xml.security.signature.XMLSignature").setLevel(java.util.logging.Level.SEVERE);
  var original=Path.of(args[0]);var browser=Path.of(args[1]);var output=Path.of(args[2]);var created=JSON.mapper().readTree(browser.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText();require(run.matches("run_[0-9A-HJKMNP-TV-Z]{26}")&&plan.matches("plan_[0-9A-HJKMNP-TV-Z]{26}"));
  var marker=original.getParent().resolve(run+SUFFIX+".json");byte[] markerRaw=Files.readAllBytes(marker);var base=(ObjectNode)JSON.mapper().readTree(markerRaw);var entries=List.of(JSON.mapper().readValue(browser.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new TreeMap<String,byte[]>();for(var e:entries)if(e.decodedSamlRef()!=null){require(run.equals(e.runId())&&("transcripts/"+run+"/"+e.id()+".saml.xml").equals(e.decodedSamlRef()));var b=Files.readAllBytes(Path.of("/data").resolve(e.decodedSamlRef()));require(b.length==e.decodedSamlBytes());bodies.put(e.id(),b);}byte[] target=Files.readAllBytes(Path.of("/data/target-metadata/"+run+".xml"));
  var peer=SecureXml.parse(Files.readAllBytes(original.resolve("matrix-sp-metadata.xml"))).getDocumentElement();var descriptors=MetadataAlgorithmEvidence.children(MetadataAlgorithmEvidence.children(peer,"urn:oasis:names:tc:SAML:2.0:metadata","SPSSODescriptor").getFirst(),"urn:oasis:names:tc:SAML:2.0:metadata","KeyDescriptor");var encryption=descriptors.stream().filter(e->"encryption".equals(e.getAttribute("use"))).findFirst().orElseThrow();var certNode=encryption.getElementsByTagNameNS("http://www.w3.org/2000/09/xmldsig#","X509Certificate");require(certNode.getLength()==1);var wanted=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(Base64.getMimeDecoder().decode(certNode.item(0).getTextContent())));PrivateKey key=null;
  var keyPaths=new ArrayList<Path>();keyPaths.add(Path.of("/data/keys/"+plan));try(var aliases=Files.list(Path.of("/data/keys/"+plan))){keyPaths.addAll(aliases.filter(Files::isDirectory).toList());for(var alias:keyPaths)if(Arrays.equals(Files.readAllBytes(alias.resolve("signing-certificate.der")),wanted.getEncoded())){var raw=Files.readAllBytes(alias.resolve("signing-key.pk8"));key=KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(raw));Arrays.fill(raw,(byte)0);break;}}require(key!=null);
  var tmp=Files.createTempDirectory("shib-fp-replay-");var folder=Files.createDirectories(tmp.resolve(run+SUFFIX));var files=new TreeMap<String,byte[]>();try(var paths=Files.list(original)){for(var p:paths.toList())files.put(p.getFileName().toString(),Files.readAllBytes(p));}var controls=new TreeMap<String,String>();CaseOutcome actual;
  try{
   reset(folder,files);Files.write(tmp.resolve(run+SUFFIX+".json"),markerRaw);actual=result(tmp,base,entries,bodies,target,key,true);require(actual.outcome()==Outcome.SATISFIED);
   for(String name:List.of("wrong-run","wrong-target","wrong-entity","wrong-campaign","native-method-changed","property-override","native-profile-override","unknown-source","wrong-runtime","provider-not-restored","missing-rejection","normal-signature-tampered","matrix-missing","matrix-duplicate","wrong-policy-key","wrong-allow-create","wrong-correlation","foreign-run","duplicate-entry","foreign-reference","tampered-request","tampered-response","wrong-decryption-key","missing-response","missing-original","symlink-original","incomplete-history","producer-signature-tampered","producer-control-swapped","audit-principal-mixed","audit-assertion-id","audit-nameid-digest","audit-session-mixed","audit-authentication-mixed","audit-missing","audit-source")){
    reset(folder,files);var m=base.deepCopy();var selected=new ArrayList<>(entries);var raw=new HashMap<>(bodies);byte[] fixedTarget=target;PrivateKey selectedKey=key;boolean complete=true;String request=m.path("matrix").get(0).path("requestReference").asText(),response=m.path("matrix").get(0).path("responseReference").asText();
    switch(name){
     case "wrong-run"->m.put("runId","run_00000000000000000000000000");case "wrong-target"->fixedTarget=new byte[]{1};case "wrong-entity"->m.put("targetEntityId","other");case "wrong-campaign"->m.put("campaignId","other");case "native-method-changed"->change(folder,m,"native-idp-saml-impl.jar",new byte[]{1});case "property-override"->change(folder,m,"before-matrix-properties-sha256.json","{}".getBytes());case "native-profile-override"->edit(folder,m,"before-matrix-native-effective-profile.json",n->((ObjectNode)n.path("ProfileConfiguration")).put("forceAuthn",true));case "unknown-source"->change(folder,m,"before-matrix-override-source-inventory.json","[\"custom\"]".getBytes());case "wrong-runtime"->{var n=JSON.mapper().readTree(folder.resolve("target-container-inspect-end.json").toFile());((ObjectNode)n.get(0)).put("Id","other");change(folder,m,"target-container-inspect-end.json",JSON.mapper().writeValueAsBytes(n));}case "provider-not-restored"->change(folder,m,"final-providers.xml","<wrong/>".getBytes());case "missing-rejection"->edit(folder,m,"normal-native-http-observations.json",n->((ObjectNode)n.path("records").get(0)).put("nativeMessageSecurityError",false));
     case "matrix-missing"->((com.fasterxml.jackson.databind.node.ArrayNode)m.path("matrix")).remove(0);case "matrix-duplicate"->((ObjectNode)m.path("matrix").get(1)).put("key",m.path("matrix").get(0).path("key").asText());case "wrong-policy-key"->((ObjectNode)m.path("matrix").get(0)).put("key","other");
     case "wrong-allow-create"->{var x=SecureXml.parse(raw.get(request));((org.w3c.dom.Element)x.getElementsByTagNameNS("urn:oasis:names:tc:SAML:2.0:protocol","NameIDPolicy").item(0)).setAttribute("AllowCreate","false");raw.put(request,SecureXml.serialize(x));}
     case "wrong-correlation","foreign-run","foreign-reference"->{int i=0;while(!selected.get(i).id().equals(response))i++;var e=selected.get(i);selected.set(i,altered(e,name.equals("foreign-run")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-reference")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef(),name.equals("wrong-correlation")?"other":e.correlationId()));}
     case "duplicate-entry"->selected.add(selected.getFirst());case "missing-response"->selected.removeIf(e->e.id().equals(response));case "incomplete-history"->complete=false;case "wrong-decryption-key"->selectedKey=KeyPairGenerator.getInstance("RSA").generateKeyPair().getPrivate();
     case "tampered-request","tampered-response","normal-signature-tampered"->{String r=name.equals("normal-signature-tampered")?m.path("positiveRequestReference").asText():name.equals("tampered-request")?request:response;var x=SecureXml.parse(raw.get(r));x.getDocumentElement().setAttribute("ID","_tampered");raw.put(r,SecureXml.serialize(x));}
     case "missing-original"->Files.delete(folder.resolve("matrix-sp-metadata.xml"));case "symlink-original"->{Files.delete(folder.resolve("matrix-sp-metadata.xml"));Files.createSymbolicLink(folder.resolve("matrix-sp-metadata.xml"),original.resolve("matrix-sp-metadata.xml"));}
     case "audit-source"->change(folder,m,"audit-public-collector.py","other".getBytes());
     case "audit-principal-mixed","audit-assertion-id","audit-nameid-digest","audit-session-mixed","audit-authentication-mixed","audit-missing"->{var lines=new ArrayList<>(List.of(new String(files.get("audit-public.log")).split("\\R")));if(name.equals("audit-missing"))lines.remove(1);else {var f=lines.get(1).split("\\|",-1);switch(name){case "audit-principal-mixed"->f[3]="foreign-principal";case "audit-assertion-id"->f[5]="_other";case "audit-nameid-digest"->f[9]="sha256:"+"0".repeat(64);case "audit-session-mixed"->f[19]="sha256:"+"0".repeat(64);case "audit-authentication-mixed"->f[7]="2000-01-01T00:00:00Z";}lines.set(1,String.join("|",f));}var changed=(String.join("\n",lines)+"\n").getBytes();change(folder,m,"audit-public.log",changed);edit(folder,m,"audit-public-observed.json",n->n.put("publicOriginalSha256",hashUnchecked(changed)));}
     case "producer-signature-tampered"->change(folder,m,"transient-positive.xml",new String(files.get("transient-positive.xml")).replace("synthetic-fp-principal","synthetic-fp-tampered").getBytes());case "producer-control-swapped"->{change(folder,m,"transient-positive.xml",files.get("persistent-format.xml"));edit(folder,m,"producer.json",n->((ObjectNode)n.path("files")).put("transient-positive",hashUnchecked(files.get("persistent-format.xml"))));}
    }
    require(result(tmp,m,selected,raw,fixedTarget,selectedKey,complete).outcome()==Outcome.NOT_VERIFIED);controls.put(name,"NOT_VERIFIED");
   }
   reset(folder,files);Files.write(tmp.resolve(run+SUFFIX+".json"),markerRaw);var wrapper=lifecycle(tmp,base,entries,bodies,target,key,actual);
   // The newly shared stock validator must preserve the previously deployed reader's
   // outputs; normal native factory closure is exercised by the current positive too.
   JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(output.toFile(),Map.of("runId",run,"outcome",actual,"negativeControls",controls,"wrapperLifecycle",wrapper,"nativeSignedSemanticControls",4,"manifestSha256",hash(markerRaw),"originalDecodedSha256",bodies.entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey,e->hashUnchecked(e.getValue()))),"productOperations",0,"privateKeyPersisted",false,"decryptedIdentifierPersisted",false));
  }finally{try(var paths=Files.walk(tmp)){for(var p:paths.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
}
