package com.samlscope.runner.cases;
import com.fasterxml.jackson.databind.node.ObjectNode;import com.samlscope.store.JsonCodec;
import com.samlscope.core.transcript.*;import com.samlscope.core.plan.*;import com.samlscope.core.run.Reachability;import com.samlscope.core.evaluation.*;import com.samlscope.core.caseexec.*;import com.samlscope.runner.DefaultCaseContext;import com.samlscope.saml.crypto.*;import com.samlscope.saml.metadata.TargetEncryptionKeys;import com.samlscope.saml.normal.SecureXml;import com.samlscope.runner.BrowserFrontChannelScenario.Binding;
import java.nio.file.*;import java.net.URI;import java.security.*;import java.security.cert.*;import java.security.spec.*;import java.time.*;import java.util.*;
/** Archived actual Reader, native controls and lifecycle. Existing Suite private key only read in memory. */
public final class VerifySimpleSamlPhpEncryptedLogout{
 private static final com.fasterxml.jackson.databind.ObjectMapper M=new JsonCodec().mapper();
 private static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 private static void edit(Path folder,String name,java.util.function.Consumer<ObjectNode> operation)throws Exception{var value=(ObjectNode)M.readTree(Files.readAllBytes(folder.resolve(name)));operation.accept(value);Files.write(folder.resolve(name),M.writeValueAsBytes(value));if(!name.equals("manifest.json")){var manifest=(ObjectNode)M.readTree(Files.readAllBytes(folder.resolve("manifest.json")));((ObjectNode)manifest.path("files")).put(name,hash(Files.readAllBytes(folder.resolve(name))));Files.write(folder.resolve("manifest.json"),M.writeValueAsBytes(manifest));}}
 private static void editArray(Path folder,String name,java.util.function.Consumer<com.fasterxml.jackson.databind.node.ArrayNode> operation)throws Exception{var value=(com.fasterxml.jackson.databind.node.ArrayNode)M.readTree(Files.readAllBytes(folder.resolve(name)));operation.accept(value);Files.write(folder.resolve(name),M.writeValueAsBytes(value));var manifest=(ObjectNode)M.readTree(Files.readAllBytes(folder.resolve("manifest.json")));((ObjectNode)manifest.path("files")).put(name,hash(Files.readAllBytes(folder.resolve(name))));Files.write(folder.resolve("manifest.json"),M.writeValueAsBytes(manifest));}
 private static void reset(Path folder,Map<String,byte[]> originals)throws Exception{for(var row:originals.entrySet()){Files.deleteIfExists(folder.resolve(row.getKey()));Files.write(folder.resolve(row.getKey()),row.getValue());}}
 public static void main(String[] args)throws Exception{
  Path source=Path.of(args[0]),output=Path.of(args[1]),data=Path.of(args[2]);var created=M.readTree(source.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText(),entity="http://localhost:18080/p/"+plan;var privatePath=data.resolve("keys").resolve(plan).resolve("signing-key.pk8");var certificatePath=privatePath.resolveSibling("signing-certificate.der");if(!Files.isRegularFile(privatePath,LinkOption.NOFOLLOW_LINKS)||!Files.isRegularFile(certificatePath,LinkOption.NOFOLLOW_LINKS))throw new IllegalStateException("Existing Suite key unavailable; no generation/export is allowed");
  var credentials=new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(Files.readAllBytes(privatePath))),(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(certificatePath)));
  var entries=List.of(M.readValue(source.resolve("transcript.json").toFile(),TranscriptEntry[].class));var decoded=new HashMap<String,byte[]>();for(var row:M.readTree(source.resolve("decoded-manifest.json").toFile())){byte[] value=Files.readAllBytes(source.resolve(row.path("file").asText()));if(!hash(value).equals(row.path("sha256").asText()))throw new IllegalArgumentException("Decoded original differs");decoded.put(row.path("id").asText(),value);}
  byte[] target=Files.readAllBytes(source.resolve("target-metadata.xml"));var targetXml=SecureXml.parse(target).getDocumentElement();var targetKeys=MetadataAlgorithmEvidence.signingKeys(targetXml);var effective=new ArrayList<>(new TargetEncryptionKeys().rsaKeys(target,"http://localhost:18380/idp",TargetRole.IDP));
  var nativeKeys=M.readTree(source.resolve("originals/baseline-before.decryption-keys.json").toFile()).path("keys");for(var key:nativeKeys){var publicKey=KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(key.path("spkiBase64").asText())));if(effective.stream().noneMatch(k->Arrays.equals(k.getEncoded(),publicKey.getEncoded())))effective.add(publicKey);}if(effective.size()!=2)throw new IllegalArgumentException("Actual effective registered keys unavailable");
  var configuration=new IdpBasicLogoutScenarioTestCase.Configuration(new IdpErrorProbeConfiguration(URI.create("http://localhost:18380/simplesaml/module.php/saml/idp/singleSignOnService"),entity,URI.create(entity+"/sp/acs/0"),Duration.ofSeconds(30),true,true,true),URI.create("http://localhost:18380/simplesaml/module.php/saml/idp/singleLogout"),URI.create(entity+"/sp/slo"),"http://localhost:18380/idp",credentials,targetKeys,Binding.SIGNED_REDIRECT,effective.getFirst(),effective);
  final String[] alteration={""};var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String id){if(!run.equals(id))throw new IllegalArgumentException();if(alteration[0].isBlank())return entries;var changed=new ArrayList<>(entries);if(alteration[0].equals("duplicate-transcript-id")){changed.set(1,entries.getFirst());return changed;}try{var row=(ObjectNode)M.valueToTree(changed.getFirst());row.put("runId","run_00000000000000000000000000");changed.set(0,M.treeToValue(row,TranscriptEntry.class));return changed;}catch(Exception impossible){throw new IllegalStateException(impossible);}}public TranscriptEntry record(TranscriptInput input){throw new AssertionError();}public TranscriptEntry updateSamlAnalysis(String id,String correlation,Map<String,Object> summary){throw new AssertionError();}};
  var context=new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),TestPlan.Parameters.defaults(),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,true);Path directory=Files.createTempDirectory("ssp-encrypted-replay-").toRealPath(),folder=Files.createDirectory(directory.resolve(run));var originals=new LinkedHashMap<String,byte[]>();try(var files=Files.list(source.resolve("originals"))){for(var p:files.toList())originals.put(p.getFileName().toString(),Files.readAllBytes(p));}
  var reader=new SimpleSamlPhpEncryptedLogoutEvidence(directory,e->decoded.get(e.id()),id->target,id->configuration);var controls=new LinkedHashMap<String,String>();try{
   reset(folder,originals);var outcome=reader.evaluate(context).orElseThrow();if(outcome.outcome()!=Outcome.VIOLATED)throw new IllegalStateException("Actual native unknown-key counterexample incomplete: "+outcome.notVerifiedReason());var fallback=new IdpBasicLogoutScenarioTestCase(SimpleSamlPhpEncryptedLogoutEvidence.CASE,id->configuration);var wrapper=new EncryptedLogoutNativeTestCase(fallback,reader);var finished=new CaseStep.Finish(outcome);if(!wrapper.start(context).equals(finished)||!wrapper.resume(context,CaseState.initial(),new CaseEvent.TranscriptReady()).equals(finished)||!wrapper.evidenceStatus(context).ready()||!wrapper.queuedEvidenceOutcome(context).equals(outcome))throw new IllegalStateException("Owned native lifecycle differs");var recorded=wrapper.reevaluateRecordedEvidence(context,CaseOutcome.notVerified("incomplete","slo.encrypted-id.multiple-keys.negative-control-failed")).orElseThrow();if(!recorded.equals(outcome))throw new IllegalStateException("Recorded native result differs");
   var names=List.of("wrong-run","wrong-target","wrong-campaign","wrong-entity","wrong-profile","native-receiver-changed","native-receiver-after-changed","native-decrypt-command-changed","native-signature-command-changed","native-http-client-changed","collector-changed","not-restored","restore-different","missing-original","symlink-original","foreign-transcript-entry","duplicate-transcript-id","missing-matrix","duplicate-matrix","wrong-request-reference","wrong-response-reference","unknown-key-decrypted","registered-key-not-decrypted","native-key-spki-unbound","unknown-request-sha-unbound","response-location-unbound","request-transport-unbound","missing-active-session","wrong-session-nameid","same-nameid-reused","native-http-clock-reversed","missing-second-key-readback","ephemeral-key-not-removed","native-source-unknown","signature-selfcheck-unproven","wrong-operation-count","native-decrypt-invocation-failed","native-decrypt-json-incomplete");
   var matrix=M.readTree(originals.get("manifest.json")).path("matrix");String unknownRequest=matrix.get(1).path("requestReference").asText(),registeredRequest=matrix.get(2).path("requestReference").asText();String unknownId=SecureXml.parse(decoded.get(unknownRequest)).getDocumentElement().getAttribute("ID"),registeredId=SecureXml.parse(decoded.get(registeredRequest)).getDocumentElement().getAttribute("ID");
   for(String name:names){reset(folder,originals);alteration[0]="";switch(name){
    case "wrong-run"->edit(folder,"manifest.json",n->n.put("runId","run_00000000000000000000000000"));case "wrong-target"->edit(folder,"manifest.json",n->n.put("targetMetadataSha256","0".repeat(64)));case "wrong-campaign"->edit(folder,"manifest.json",n->n.put("campaignId","other"));case "wrong-entity"->edit(folder,"manifest.json",n->n.put("targetEntityId","other"));case "wrong-profile"->edit(folder,"plan.json",n->((ObjectNode)n.at("/plan/plan")).put("profile","metadata_idp"));
    case "native-receiver-changed"->Files.writeString(folder.resolve("native-idp-saml2.php"),"other");case "native-receiver-after-changed"->Files.writeString(folder.resolve("native-idp-saml2-after.php"),"other");case "native-decrypt-command-changed"->Files.writeString(folder.resolve("native-decrypt-command.php"),"other");case "native-signature-command-changed"->Files.writeString(folder.resolve("native-verify-command.php"),"other");case "native-http-client-changed"->Files.writeString(folder.resolve("native-http-client.py"),"other");case "collector-changed"->Files.writeString(folder.resolve("collector.py"),"other");
    case "not-restored"->edit(folder,"restoration.json",n->((ObjectNode)n.path("hosted")).put("restored",false));case "restore-different"->Files.writeString(folder.resolve("remote-final.php"),"other");case "missing-original"->Files.delete(folder.resolve("native-session-observations.json"));case "symlink-original"->{Files.delete(folder.resolve("native-session-observations.json"));Files.createSymbolicLink(folder.resolve("native-session-observations.json"),source.resolve("originals/native-session-observations.json"));}case "foreign-transcript-entry","duplicate-transcript-id"->alteration[0]=name;
    case "missing-matrix"->edit(folder,"manifest.json",n->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("matrix")).remove(2));case "duplicate-matrix"->edit(folder,"manifest.json",n->((ObjectNode)n.path("matrix").get(2)).put("fixtureId","slo-basic-logout-control"));case "wrong-request-reference"->edit(folder,"manifest.json",n->((ObjectNode)n.path("matrix").get(2)).put("requestReference",unknownRequest));case "wrong-response-reference"->edit(folder,"manifest.json",n->((ObjectNode)n.path("matrix").get(2)).put("responseReference",n.path("matrix").get(1).path("responseReference").asText()));
    case "unknown-key-decrypted"->edit(folder,"native-decrypt-"+unknownId+".json",n->((ObjectNode)n.path("keysTried").get(0)).put("decrypted",true));case "registered-key-not-decrypted"->edit(folder,"native-decrypt-"+registeredId+".json",n->{for(var tried:n.path("keysTried"))((ObjectNode)tried).put("decrypted",false);});case "native-key-spki-unbound"->edit(folder,"native-decrypt-"+unknownId+".json",n->((ObjectNode)n.path("keysTried").get(0)).put("spkiSha256","0".repeat(64)));case "unknown-request-sha-unbound"->edit(folder,"native-decrypt-"+unknownId+".json",n->n.put("requestSha256","0".repeat(64)));
    case "response-location-unbound"->edit(folder,"native-http-observations.json",n->{for(var r:n.path("records"))if(unknownId.equals(r.path("request_id").asText()))((ObjectNode)r).put("native_signed_response_url","http://localhost:18080/other");});case "request-transport-unbound"->edit(folder,"native-http-observations.json",n->{for(var r:n.path("records"))if(unknownId.equals(r.path("request_id").asText()))((ObjectNode)r).put("request_body_sha256","0".repeat(64));});case "missing-active-session"->edit(folder,"native-session-observations.json",n->{for(var r:n.path("observations"))if(unknownId.equals(r.path("requestId").asText())&&"before-native-dispatch".equals(r.path("phase").asText()))((ObjectNode)r.path("session")).put("authenticated",false);});case "wrong-session-nameid"->edit(folder,"native-session-observations.json",n->{for(var r:n.path("observations"))if(unknownId.equals(r.path("requestId").asText())&&"before-native-dispatch".equals(r.path("phase").asText()))((ObjectNode)r.at("/session/associations/0")).put("nameId","other");});
    case "same-nameid-reused"->edit(folder,"native-session-observations.json",n->{String first=n.at("/observations/0/session/associations/0/nameId").asText();for(var r:n.path("observations"))if(r.at("/session/associations/0").isObject())((ObjectNode)r.at("/session/associations/0")).put("nameId",first);});case "native-http-clock-reversed"->edit(folder,"native-http-observations.json",n->{for(var r:n.path("records"))if(unknownId.equals(r.path("request_id").asText()))((ObjectNode)r).put("started_at","2100-01-01T00:00:00Z");});case "missing-second-key-readback"->edit(folder,"baseline-before.decryption-keys.json",n->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("keys")).remove(1));case "ephemeral-key-not-removed"->edit(folder,"ephemeral-key-cleanup.json",n->n.put("removed",false));case "native-source-unknown"->Files.writeString(folder.resolve("native-message.php"),"other");case "signature-selfcheck-unproven"->edit(folder,"native-signature-selfchecks.json",n->{for(var r:n.path("records")){((ObjectNode)r).put("valid",false);((ObjectNode)r).put("allowInvalidControl",false);}});case "wrong-operation-count"->edit(folder,"operation-counts.json",n->n.put("protocolOperationsAttempted",7));case "native-decrypt-invocation-failed"->editArray(folder,"native-decryption-attempts.json",n->((ObjectNode)n.get(0)).put("returncode",1));case "native-decrypt-json-incomplete"->edit(folder,"native-decrypt-"+unknownId+".json",n->((com.fasterxml.jackson.databind.node.ArrayNode)n.path("keysTried")).remove(1));
   }
   var altered=reader.evaluate(context).orElseThrow();if(altered.outcome()!=Outcome.NOT_VERIFIED)throw new IllegalStateException("Altered native original accepted: "+name);if(!(wrapper.start(context) instanceof CaseStep.Finish f)||f.outcome().outcome()!=Outcome.NOT_VERIFIED||wrapper.evidenceStatus(context).ready())throw new IllegalStateException("Owned invalid original falls back");controls.put(name,"NOT_VERIFIED");}
   reset(folder,originals);alteration[0]="";String diagnostic="native-decrypt-"+unknownId+".json.stderr";Files.writeString(folder.resolve(diagnostic),new String(originals.get(diagnostic),java.nio.charset.StandardCharsets.UTF_8)+"\nNative harmless diagnostic warning\n");var diagnosticManifest=(ObjectNode)M.readTree(Files.readAllBytes(folder.resolve("manifest.json")));((ObjectNode)diagnosticManifest.path("files")).put(diagnostic,hash(Files.readAllBytes(folder.resolve(diagnostic))));Files.write(folder.resolve("manifest.json"),M.writeValueAsBytes(diagnosticManifest));if(!reader.evaluate(context).orElseThrow().equals(outcome))throw new IllegalStateException("Nonsemantic stderr warning changed cryptographic meaning");
   Files.write(output,M.writerWithDefaultPrettyPrinter().writeValueAsBytes(Map.ofEntries(Map.entry("nativeStderrDiagnosticVariationOutcomeIdentical",true),Map.entry("runId",run),Map.entry("production_outcome",outcome),Map.entry("recorded_wrapper_outcome",recorded),Map.entry("negative_controls",controls),Map.entry("shared_native_scenario_lifecycle",true),Map.entry("suitePrivateKeyReadOnlyInMemory",true),Map.entry("privateCredentialsExported",false),Map.entry("manifestSha256",hash(originals.get("manifest.json"))),Map.entry("transcriptSha256",hash(Files.readAllBytes(source.resolve("transcript.json")))),Map.entry("verdict_adopted",false))),StandardOpenOption.CREATE_NEW);
  }finally{try(var files=Files.walk(directory)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
}
