package com.samlscope.runner.cases;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.samlscope.core.caseexec.*;
import com.samlscope.core.evaluation.*;
import com.samlscope.core.plan.*;
import com.samlscope.core.run.Reachability;
import com.samlscope.core.transcript.*;
import com.samlscope.runner.*;
import com.samlscope.saml.crypto.*;
import com.samlscope.saml.normal.SecureXml;
import com.samlscope.saml.binding.RedirectSignatureVerifier;
import com.samlscope.store.JsonCodec;
import java.nio.file.*;
import java.security.*;
import java.security.cert.*;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.*;
import java.util.*;
import java.util.function.BiFunction;

/** Original replay only. No Recorder writes, product actions, or plaintext identifiers are exported. */
public final class VerifyNativeRoleKeyConsumption {
 static final JsonCodec JSON=new JsonCodec();static final String CASE="IIP-MD06-a2-idp-01",MD="urn:oasis:names:tc:SAML:2.0:metadata",DS="http://www.w3.org/2000/09/xmldsig#";
 static void require(boolean value){if(!value)throw new IllegalArgumentException("Validity original replay failed");}
 static String hash(byte[] raw)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
 static void reset(Path folder,Map<String,byte[]> originals)throws Exception{try(var files=Files.list(folder)){for(var p:files.toList())Files.delete(p);}for(var row:originals.entrySet())Files.write(folder.resolve(row.getKey()),row.getValue());}
 static void change(Path folder,ObjectNode manifest,String file,byte[] bytes)throws Exception{Files.write(folder.resolve(file),bytes);((ObjectNode)manifest.path("originals")).put(file,hash(bytes));}
 static void edit(Path folder,ObjectNode manifest,String file,java.util.function.Consumer<ObjectNode> action)throws Exception{var node=(ObjectNode)JSON.mapper().readTree(folder.resolve(file).toFile());action.accept(node);change(folder,manifest,file,JSON.mapper().writeValueAsBytes(node));}
 static DefaultCaseContext context(String run,List<TranscriptEntry> entries,boolean complete){var recorder=new TranscriptRecorder(){public List<TranscriptEntry> list(String selected){return entries;}public TranscriptEntry record(TranscriptInput input){throw new AssertionError("Replay submitted an action");}public TranscriptEntry updateSamlAnalysis(String id,String correlation,Map<String,Object> summary){throw new AssertionError("Replay changed an original");}};return new DefaultCaseContext(run,TargetRole.IDP,Clock.systemUTC(),new TestPlan.Parameters(180,45,"reference"),TestPlan.Interaction.defaults(),Reachability.CONFIRMED,recorder,complete);}
 static CaseOutcome result(Path root,String run,ObjectNode manifest,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,boolean complete)throws Exception{var path=root.resolve(run).resolve("manifest.json");if(!Files.exists(path)||!JSON.mapper().readTree(Files.readAllBytes(path)).equals(manifest))Files.write(path,JSON.mapper().writeValueAsBytes(manifest));return new MetadataRoleKeyEvidence(root,e->bodies.get(e.id()),r->target,keys,new SimpleSamlPhpMetadataRoleKeyNativeAdapter(e->bodies.get(e.id())),new KeycloakMetadataRoleKeyNativeAdapter(e->bodies.get(e.id()))).evaluate(context(run,entries,complete)).orElse(CaseOutcome.notVerified("unproven","unproven"));}
 static TranscriptEntry altered(TranscriptEntry e,String run,String decoded){return new TranscriptEntry(e.id(),run,e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),decoded,e.decodedSamlBytes(),e.contentType(),e.rawQuery(),e.samlSummary());}
 static BiFunction<String,String,Optional<PlanCredentials>> keys(String run,String plan,Path receipt)throws Exception {
  var result=new HashMap<String,PlanCredentials>();var roles=List.of("role-keys-sp-first-explicit-a","role-keys-idp-first-explicit-b");var publicKeys=new LinkedHashMap<String,X509Certificate>();
  for(int i=0;i<roles.size();i++){var peer=SecureXml.parse(Files.readAllBytes(receipt.resolve(roles.get(i)+"-fixture.xml"))).getDocumentElement();var sp=MetadataAlgorithmEvidence.children(peer,MD,"SPSSODescriptor").getFirst();var descriptors=MetadataAlgorithmEvidence.children(sp,MD,"KeyDescriptor");for(var descriptor:descriptors){String alias="signing".equals(descriptor.getAttribute("use"))?(i==0?"three-signing-keys-first":"three-signing-keys-second"):"three-signing-keys";var bytes=Base64.getMimeDecoder().decode(descriptor.getElementsByTagNameNS(DS,"X509Certificate").item(0).getTextContent());var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(new java.io.ByteArrayInputStream(bytes));var prior=publicKeys.putIfAbsent(alias,cert);require(prior==null||Arrays.equals(prior.getEncoded(),cert.getEncoded()));}}
  for(var expected:publicKeys.entrySet()){var cert=expected.getValue();try(var aliases=Files.list(Path.of("/data/keys/"+plan))){for(var alias:aliases.filter(Files::isDirectory).toList())if(Arrays.equals(Files.readAllBytes(alias.resolve("signing-certificate.der")),cert.getEncoded())){var raw=Files.readAllBytes(alias.resolve("signing-key.pk8"));try{result.put(expected.getKey(),new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(raw)),cert));}finally{Arrays.fill(raw,(byte)0);}break;}}require(result.containsKey(expected.getKey()));}require(result.size()==3);return (selected,variant)->selected.equals(run)?Optional.ofNullable(result.get(variant)):Optional.empty();
 }
 static TranscriptEntry decodedLength(TranscriptEntry e,int length){return new TranscriptEntry(e.id(),e.runId(),e.direction(),e.timestamp(),e.correlationId(),e.method(),e.url(),e.status(),e.headers(),e.bodyRef(),e.bodyBytes(),e.decodedSamlRef(),length,e.contentType(),e.rawQuery(),e.samlSummary());}
 static void editNative(Path folder,ObjectNode m,String label,List<TranscriptEntry> entries,Map<String,byte[]> bodies,java.util.function.Consumer<ObjectNode> edit)throws Exception {
  var ref=(ObjectNode)m.path("nativeOriginals").path(label);String id=ref.path("reference").asText(),file=ref.path("file").asText();var n=(ObjectNode)JSON.mapper().readTree(bodies.get(id));edit.accept(n);var bytes=JSON.mapper().writeValueAsBytes(n);bodies.put(id,bytes);ref.put("sha256",hash(bytes));change(folder,m,file,bytes);for(int i=0;i<entries.size();i++)if(entries.get(i).id().equals(id)){entries.set(i,decodedLength(entries.get(i),bytes.length));return;}throw new IllegalArgumentException("Native original not found");
 }
 static Map<String,Object> lifecycle(Path root,String run,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] target,BiFunction<String,String,Optional<PlanCredentials>> keys,CaseOutcome actual)throws Exception {
  var fallback=new ConfigurationGateTestCase(new AttestedOutcomeTestCase(CASE,TargetRole.IDP,"role.evidence",Duration.ofMinutes(1),List.of(AttestationOption.of("evidence_satisfies",Outcome.SATISFIED,"declaration.satisfies"))),"role.config",Duration.ofMinutes(1),ConfigurationFailureSemantics.TEST_PRECONDITION);
  var content=(TranscriptContentReader)(e->bodies.get(e.id()));var wrapper=new MetadataRoleKeyProbeTestCase(fallback,r->target,content,keys,root,new SimpleSamlPhpMetadataRoleKeyNativeAdapter(content),new KeycloakMetadataRoleKeyNativeAdapter(content));var c=context(run,entries,true);var map=new TreeMap<String,Object>();map.put("start",((CaseStep.Finish)wrapper.start(c)).outcome().equals(actual));var state=new CaseState("configuration",Map.of());
  for(var event:List.of(new CaseEvent.ConfigConfirmed(),new CaseEvent.TranscriptReady(),new CaseEvent.Aborted("ended"),new CaseEvent.TimedOut(Duration.ofMinutes(1))))map.put(event.getClass().getSimpleName(),((CaseStep.Finish)wrapper.resume(c,state,event)).outcome().equals(actual));map.put("status-ready",wrapper.evidenceStatus(c).ready());map.put("recorded-not-verified",wrapper.reevaluateRecordedEvidence(c,CaseOutcome.notVerified("before","before")).orElseThrow().equals(actual));map.put("recorded-conclusive",wrapper.reevaluateRecordedEvidence(c,actual).isPresent());map.put("incomplete-history",((CaseStep.Finish)wrapper.start(context(run,entries,false))).outcome().outcome().name());return map;
 }
 static void baseline(Path input,String run,String plan,List<TranscriptEntry> entries,Map<String,byte[]> bodies,byte[] targetRaw)throws Exception {
  var n=JSON.mapper().readTree(input.resolve("receipt/baseline.json").toFile());require(n.path("protocolSubmissions").asInt(-1)==1&&n.path("credentialPosts").asInt(-1)==1&&n.path("outboundReferences").size()==1);String rq=n.path("outboundReferences").get(0).asText();var request=entries.stream().filter(e->e.id().equals(rq)).findFirst().orElseThrow();var response=entries.stream().filter(e->Boolean.TRUE.equals(e.samlSummary().get("normalFlowAccepted"))).toList();require(response.size()==1);var req=SecureXml.parse(bodies.get(request.id())).getDocumentElement();var sp=SecureXml.parse(Files.readAllBytes(input.resolve("receipt/baseline-fixture.xml"))).getDocumentElement();var target=SecureXml.parse(targetRaw).getDocumentElement();var reply=response.getFirst();require(run.equals(request.runId())&&run.equals(reply.runId())&&request.direction()==Direction.OUTBOUND&&reply.direction()==Direction.INBOUND&&"GET".equals(request.method())&&"POST".equals(reply.method())&&request.timestamp().isBefore(reply.timestamp())&&req.getAttribute("ID").equals(request.correlationId())&&req.getAttribute("ID").equals(reply.correlationId()));
  var cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(Files.newInputStream(Path.of("/data/keys/"+plan+"/signing-certificate.der")));require(new RedirectSignatureVerifier().isValidForMessage(request.rawQuery(),cert,bodies.get(request.id())));var encoded=Files.readAllBytes(Path.of("/data/keys/"+plan+"/signing-key.pk8"));try{var credential=new PlanCredentials(KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded)),cert);VerifiedResponseAssertion.read(SecureXml.parse(bodies.get(reply.id())).getDocumentElement(),target.getAttribute("entityID"),MetadataAlgorithmEvidence.signingKeys(target),sp,Optional.of(credential),req.getAttribute("ID"),req.getAttribute("AssertionConsumerServiceURL"));}finally{Arrays.fill(encoded,(byte)0);}
 }
 public static void main(String[] args)throws Exception {
  require(args.length==2||args.length==3);JSON.mapper().enable(com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);java.util.logging.Logger.getLogger("org.apache.xml.security.signature.XMLSignature").setLevel(java.util.logging.Level.SEVERE);var input=Path.of(args[0]);var receipt=input.resolve("receipt");var created=JSON.mapper().readTree(input.resolve("created.json").toFile()).path("run");String run=created.path("id").asText(),plan=created.path("planId").asText();var manifestRaw=Files.readAllBytes(receipt.resolve("manifest.json"));var base=(ObjectNode)JSON.mapper().readTree(manifestRaw);require(run.equals(base.path("runId").asText()));var target=Files.readAllBytes(input.resolve("target-metadata.xml"));var entries=List.of(JSON.mapper().readValue(input.resolve("transcript.json").toFile(),TranscriptEntry[].class));var bodies=new HashMap<String,byte[]>();for(var row:JSON.mapper().readTree(input.resolve("decoded-manifest.json").toFile())){var raw=Files.readAllBytes(input.resolve(row.path("file").asText()));require(hash(raw).equals(row.path("sha256").asText())&&bodies.put(row.path("id").asText(),raw)==null);}baseline(input,run,plan,entries,bodies,target);var credentials=keys(run,plan,receipt);var originals=new LinkedHashMap<String,byte[]>();try(var files=Files.list(receipt)){for(var file:files.toList())originals.put(file.getFileName().toString(),Files.readAllBytes(file));}var tmp=Files.createTempDirectory("native-role-key-replay-");var folder=Files.createDirectories(tmp.resolve(run));
  try {
   reset(folder,originals);var actual=result(tmp,run,base,entries,bodies,target,credentials,true);require(actual.outcome()==Outcome.SATISFIED);
   if(args.length==3){JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[1]).toFile(),Map.of("runId",run,"outcome",actual,"diagnosticOnly",true));return;}
   var negative=new TreeMap<String,String>();
   for(String name:List.of("wrong-run","wrong-target","wrong-adapter","missing-epoch","missing-peer-role","wrong-native-purpose","wrong-source","wrong-restoration","runtime-changed","missing-negative-control","missing-native-rejection","http-wrong-hash","http-wrong-url","http-outside-epoch","native-original-wrong-run","native-original-wrong-request","native-original-wrong-response","native-original-wrong-http","tampered-request","tampered-response","foreign-run-entry","duplicate-entry","foreign-decoded-reference","wrong-decryption-key","incomplete-history")){
    reset(folder,originals);var m=base.deepCopy();var selected=new ArrayList<>(entries);var raw=new HashMap<>(bodies);var selectedKeys=credentials;boolean complete=true;var epoch=m.path("observations").get(1);var normal=epoch.path("exchanges").get(0);var rejection=epoch.path("exchanges").get(1);String request=normal.path("requestReference").asText(),response=normal.path("responseReference").asText(),variant=epoch.path("variant").asText();
    switch(name){
     case "wrong-run"->m.put("runId","run_00000000000000000000000000");case "wrong-target"->m.put("targetMetadataSha256","0".repeat(64));case "wrong-adapter"->m.put("adapter","parser-only");case "missing-epoch"->((com.fasterxml.jackson.databind.node.ArrayNode)m.path("observations")).remove(1);
     case "missing-peer-role"->{var xml=SecureXml.parse(originals.get(variant+"-fixture.xml"));xml.getDocumentElement().removeChild(MetadataAlgorithmEvidence.children(xml.getDocumentElement(),MD,"IDPSSODescriptor").getFirst());change(folder,m,variant+"-fixture.xml",SecureXml.serialize(xml));}
     case "wrong-native-purpose"->editNative(folder,m,variant+"-conversion",selected,raw,n->((ObjectNode)n.at("/parserOutput/nativeSpMetadata/keys/0")).put("encryption",true));
     case "wrong-source"->change(folder,m,"native-message.php","<?php // altered".getBytes());case "wrong-restoration"->change(folder,m,"final-configuration.php","<?php // altered".getBytes());
     case "runtime-changed"->{var n=JSON.mapper().readTree(folder.resolve("target-container-inspect-end.json").toFile());((ObjectNode)n.get(0)).put("Id","other");change(folder,m,"target-container-inspect-end.json",JSON.mapper().writeValueAsBytes(n));}
     case "missing-negative-control"->((com.fasterxml.jackson.databind.node.ArrayNode)epoch.path("exchanges")).remove(1);
     case "missing-native-rejection"->change(folder,m,"browser-"+rejection.path("responseReference").asText()+".body","HTTP 500".getBytes());
     case "http-wrong-hash"->((ObjectNode)normal.path("nativeHttp").get(0)).put("requestSha256","0".repeat(64));case "http-wrong-url"->((ObjectNode)normal.path("nativeHttp").get(0)).put("requestUrl","http://wrong.invalid/");case "http-outside-epoch"->((ObjectNode)normal.path("nativeHttp").get(0)).put("startedAt","1970-01-01T00:00:00Z");
     case "native-original-wrong-run"->editNative(folder,m,normal.path("fixtureId").asText()+"-http",selected,raw,n->n.put("runId","run_00000000000000000000000000"));
     case "native-original-wrong-request"->editNative(folder,m,normal.path("fixtureId").asText()+"-http",selected,raw,n->n.put("requestReference",rejection.path("requestReference").asText()));
     case "native-original-wrong-response"->editNative(folder,m,normal.path("fixtureId").asText()+"-http",selected,raw,n->n.put("responseReference",rejection.path("responseReference").asText()));
     case "native-original-wrong-http"->editNative(folder,m,normal.path("fixtureId").asText()+"-http",selected,raw,n->((ObjectNode)n.path("native")).put("requestSha256","0".repeat(64)));
     case "tampered-request","tampered-response"->{String id=name.equals("tampered-request")?request:response;var x=SecureXml.parse(raw.get(id));x.getDocumentElement().setAttribute("ID","_tampered");raw.put(id,SecureXml.serialize(x));}
     case "foreign-run-entry","foreign-decoded-reference"->{int index=0;while(!selected.get(index).id().equals(response))index++;var e=selected.get(index);selected.set(index,altered(e,name.equals("foreign-run-entry")?"run_00000000000000000000000000":e.runId(),name.equals("foreign-decoded-reference")?"transcripts/run_00000000000000000000000000/"+e.id()+".saml.xml":e.decodedSamlRef()));}
     case "duplicate-entry"->selected.add(selected.getFirst());case "wrong-decryption-key"->{var wrong=new PlanCredentials(KeyPairGenerator.getInstance("RSA").generateKeyPair().getPrivate(),credentials.apply(run,"three-signing-keys").orElseThrow().certificate());selectedKeys=(r,v)->v.equals("three-signing-keys")?Optional.of(wrong):credentials.apply(r,v);}case "incomplete-history"->complete=false;
    }
    require(result(tmp,run,m,selected,raw,target,selectedKeys,complete).outcome()==Outcome.NOT_VERIFIED);negative.put(name,"NOT_VERIFIED");
   }
   var mutants=new TreeMap<String,String>();var purposeControls=new TreeMap<String,String>();var producer=JSON.mapper().readTree(input.resolve("calibration/producer.json").toFile());require(!producer.path("controlsAdopted").asBoolean(true)&&!producer.path("nativePrivateKeyExported").asBoolean(true)&&producer.path("controls").size()==6);
   for(var control:producer.path("controls")){
    reset(folder,originals);var m=base.deepCopy();String fixture=control.path("fixtureId").asText();com.fasterxml.jackson.databind.JsonNode exchange=null;for(var row:m.path("observations"))for(var x:row.path("exchanges"))if(fixture.equals(x.path("fixtureId").asText()))exchange=x;require(exchange!=null);var bytes=Files.readAllBytes(input.resolve("calibration").resolve(control.path("file").asText()));require(hash(bytes).equals(control.path("sha256").asText()));var response=SecureXml.parse(bytes).getDocumentElement();String rid=response.getAttribute("InResponseTo"),id="tx_00000000000000000000000000";Instant at=Instant.parse(response.getAttribute("IssueInstant"));((ObjectNode)exchange).put("responseReference",id);var h=(ObjectNode)exchange.path("nativeHttp").get(0);h.put("responseStatus",200).put("samlResponseFormPresent",true).put("responseSamlSha256",hash(bytes));String form="<form><input name='SAMLResponse' value='"+Base64.getEncoder().encodeToString(bytes)+"'/></form>";h.put("responseBodyBytes",form.getBytes().length).put("responseBodySha256",hash(form.getBytes()));var selected=new ArrayList<>(entries);var raw=new HashMap<>(bodies);var http=h.deepCopy();editNative(folder,m,fixture+"-http",selected,raw,n->{n.put("responseReference",id);n.set("native",http);});selected.add(new TranscriptEntry(id,run,Direction.INBOUND,at,rid,"POST",response.getAttribute("Destination"),200,Map.of(),"synthetic-calibration",bytes.length,"transcripts/"+run+"/"+id+".saml.xml",bytes.length,"application/saml+xml",null,Map.of("type","Response","inResponseTo",rid)));raw.put(id,bytes);var outcome=result(tmp,run,m,selected,raw,target,credentials,true);if(fixture.endsWith("peer-key")){require(outcome.outcome()==Outcome.VIOLATED);mutants.put(fixture,"VIOLATED");}else{require(outcome.outcome()==Outcome.NOT_VERIFIED);purposeControls.put(fixture,"NOT_VERIFIED");}
   }
   reset(folder,originals);Files.write(folder.resolve("manifest.json"),manifestRaw);var lifecycle=lifecycle(tmp,run,entries,bodies,target,credentials,actual);require(lifecycle.equals(Map.of("start",true,"ConfigConfirmed",true,"TranscriptReady",true,"Aborted",true,"TimedOut",true,"status-ready",true,"recorded-not-verified",true,"recorded-conclusive",false,"incomplete-history","NOT_VERIFIED")));
   var report=new TreeMap<String,Object>();report.put("runId",run);report.put("caseId",CASE);report.put("targetMetadataSha256",hash(target));report.put("outcome",actual);report.put("negativeControls",negative);report.put("approvedMutants",mutants);report.put("purposeAcceptanceControls",purposeControls);report.put("wrapperLifecycle",lifecycle);report.put("manifestSha256",hash(manifestRaw));report.put("productOperations",0);report.put("privateCredentialsPersisted",false);report.put("calibrationIsCounterfactualOnly",true);JSON.mapper().writerWithDefaultPrettyPrinter().writeValue(Path.of(args[1]).toFile(),report);
  }finally{try(var files=Files.walk(tmp)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
 }
}
