#!/usr/bin/env python3
"""Adopt the complete certificate runtime consumer proof, using archived production code."""
import argparse,hashlib,json,pathlib,secrets,subprocess,tempfile
from verify_shibboleth_native_ui_acceptance import dependency_classpath
from verify_terminal_http_acceptance import _verify_target_runtime,_verify_suite_runtime,find_case
REPO=pathlib.Path(__file__).resolve().parents[2];FOLDER='shibboleth-certificate-runtime-r1';CASE='IIP-MD06-a6-idp-01';SUITE='samlscope-reference-suite';ARCHIVE='reader-v197'
PINS={'image_id': 'sha256:916a6af4fc3e4c94ec5c6c1cb77b9d78955954682988ae4e220739053461a5e7', 'jars': {'core': '1d6e0020c915f50e78902554c06b61916a3f49e50de78d3bc23c6089d312babe', 'runner': '85f0335c57bef0b8061644ba9c78bab37392ee56e3d677bcdf289db1d3542d5e', 'saml': '43b2cc47bd142956e7f35bd1d906950f64d3f952374db72a2df84f5e3617bec7'}};STORE='c4482cd06f9290a3592f0fceac2c9ec2d7603ea0557d1edc885e1c3d51bd8ece';HELPER='9dfe5dd7a5d0c3d3abcfab036f68972f708fc3f435182a425dbf39c3c1cd4577';STORED_HELPER='b51f4754ed5fced71c6e2451468333f7afe2e2a2e040f3890f2a875a0e941ea3'
SHA=lambda b:hashlib.sha256(b).hexdigest();READ=lambda p:json.loads(pathlib.Path(p).read_bytes())
def require(value,message):
 if not value:raise ValueError(message)
def command(args):return subprocess.run(args,check=True,capture_output=True,timeout=90)
def jars(archive):
 require(PINS is not None,'Actual deployed certificate Reader pins not finalized');runtime=READ(archive/'suite-runtime-terminal-http.json');paths=[]
 for name,digest in PINS['jars'].items():
  path=archive/runtime['jars'][name]['file'];require(SHA(path.read_bytes())==runtime['jars'][name]['sha256']==digest,'Archived production JAR differs');paths.append(path)
 path=archive/'suite-store-0.1.0.jar';require(SHA(path.read_bytes())==STORE,'Archived Store differs');return paths+[path]
def replay(folder,retain=False):
 folder=pathlib.Path(folder);archive=folder/ARCHIVE;project=jars(archive);source=archive/'replay-helper.java';require(HELPER is not None and SHA(source.read_bytes())==HELPER,'Archived certificate helper changed')
 with tempfile.TemporaryDirectory(prefix='certificate-runtime-replay-') as tmp:
  tmp=pathlib.Path(tmp);classes=tmp/'classes';classes.mkdir();named=tmp/'VerifyMetadataCertificateRuntime.java';named.write_bytes(source.read_bytes());cp=':'.join(map(str,project))+':'+dependency_classpath(archive,retain);command(['javac','-cp',cp,'-d',str(classes),str(named)]);require(all(p.name.startswith('VerifyMetadataCertificateRuntime') for p in classes.rglob('*.class')),'Helper shadows production Reader')
  remote='/tmp/certificate-runtime-replay-'+secrets.token_hex(6);command(['docker','exec','-u','0',SUITE,'mkdir',remote]);uid=command(['docker','exec',SUITE,'id','-u']).stdout.decode().strip()
  try:
   for local,name in [(folder/name,name) for name in ['receipt','created.json','target-metadata.xml','initial-baseline','pkix-calibration']]+[(archive/'full-run-originals'/name,name) for name in ['transcript.json','decoded-manifest.json','decoded']]+[(classes,'classes')]+[(p,p.name) for p in project]:command(['docker','cp',str(local),SUITE+':'+remote+'/'+name])
   command(['docker','exec','-u','0',SUITE,'chown','-R',uid+':'+uid,remote]);cp=':'.join(remote+'/'+p.name for p in project)+':'+remote+'/classes:/opt/samlscope/lib/*';result=subprocess.run(['docker','exec',SUITE,'java','-cp',cp,'com.samlscope.runner.cases.VerifyMetadataCertificateRuntime',remote,remote+'/report.json'],capture_output=True,timeout=90);require(result.returncode==0,'Archived production replay failed: '+result.stderr.decode(errors='replace')[-1000:]);command(['docker','cp',SUITE+':'+remote+'/report.json',str(tmp/'report.json')]);raw=(tmp/'report.json').read_bytes()
  finally:command(['docker','exec','-u','0',SUITE,'rm','-rf',remote])
 saved=archive/'production-replay.json'
 if retain:require(not saved.exists(),'Refusing to overwrite actual replay');saved.write_bytes(raw)
 else:require(saved.read_bytes()==raw,'Actual archived Reader replay differs')
 value=json.loads(raw);require(value['outcome']['outcome']=='SATISFIED' and value['outcome']['reasonCode']=='metadata.certificate.runtime-no-pkix-observed','Complete certificate observation differs');require(len(value['negativeControls'])==52 and set(value['negativeControls'].values())=={'NOT_VERIFIED'},'Invalid originals accepted');require(len(value['approvedMutants'])==5 and set(value['approvedMutants'].values())=={'VIOLATED'},'Certificate-check mutant detection incomplete');require(value['controlsAdopted'] is False and value['pkixCounterexamplesAreDiagnosticCalibrationOnly'] is True and SHA((folder/'pkix-calibration/output/native-pkix-diagnostic.json').read_bytes())==value['nativePkixDiagnosticSha256'],'Diagnostic controls adopted or changed');require(value['wrapperLifecycle']=={'start':True,'ConfigConfirmed':True,'TranscriptReady':True,'Aborted':True,'TimedOut':True,'status-ready':True,'recorded-not-verified':True,'recorded-conclusive':False,'incomplete-history':'NOT_VERIFIED'},'Actual wrapper lifecycle differs');require(value['productOperations']==0 and value['privateCredentialsPersisted'] is False,'Replay performed product operations or persisted credentials');return value
def stored(folder,retain=False):
 folder=pathlib.Path(folder);archive=folder/ARCHIVE;project=jars(archive);source=archive/'stored-helper.java';require(STORED_HELPER is not None and SHA(source.read_bytes())==STORED_HELPER,'Stored helper differs')
 with tempfile.TemporaryDirectory(prefix='certificate-runtime-stored-') as tmp:
  tmp=pathlib.Path(tmp);classes=tmp/'classes';classes.mkdir();named=tmp/'ReadMetadataCertificateRuntimeStoredConclusion.java';named.write_bytes(source.read_bytes());cp=':'.join(map(str,project))+':'+dependency_classpath(archive);command(['javac','-cp',cp,'-d',str(classes),str(named)])
  if retain:
   remote='/tmp/certificate-runtime-stored-'+secrets.token_hex(6);command(['docker','exec','-u','0',SUITE,'mkdir',remote]);uid=command(['docker','exec',SUITE,'id','-u']).stdout.decode().strip()
   try:
    command(['docker','cp',str(classes),SUITE+':'+remote+'/classes']);command(['docker','exec','-u','0',SUITE,'chown','-R',uid+':'+uid,remote]);raw=command(['docker','exec',SUITE,'java','-cp',remote+'/classes:/opt/samlscope/lib/*','com.samlscope.runner.cases.ReadMetadataCertificateRuntimeStoredConclusion','capture',READ(folder/'created.json')['run']['id']]).stdout
   finally:command(['docker','exec','-u','0',SUITE,'rm','-rf',remote])
   require(not (archive/'stored-conclusion.json').exists(),'Refusing to overwrite stored original');(archive/'stored-conclusion.json').write_bytes(raw)
  path=archive/'stored-conclusion.json';raw=command(['java','-cp',cp+':'+str(classes),'com.samlscope.runner.cases.ReadMetadataCertificateRuntimeStoredConclusion','offline',str(path.resolve())]).stdout;require(raw==path.read_bytes(),'Archived central Evaluator differs');return json.loads(raw)
def verify(root):
 folder=pathlib.Path(root)/FOLDER;archive=folder/ARCHIVE;require(all(SHA((folder/name).read_bytes())==digest for name,digest in READ(folder/'acceptance-originals.json').items()),'Accepted original bytes changed');old=READ(folder/'preformal-v196/manifest-original.json');new=READ(folder/'receipt/manifest.json');require(len(old['originals'])==151 and len(new['originals'])==153 and all(old['originals'][name]==new['originals'][name]==SHA((folder/'receipt'/name).read_bytes()) for name in old['originals']) and set(new['originals'])-set(old['originals'])=={'target-container-mounts-native-original.json','target-container-mounts-capture.json'},'Historic native originals or supplemental scope changed');supplement=READ(folder/'runtime-mounts-supplement-operation-audit.json');require(supplement['original151Unchanged'] is True and supplement['originalFilesChanged'] is False and supplement['productConfigurationWrites']==supplement['protocolSubmissions']==supplement['credentialPosts']==0 and supplement['immutableNativeContainerSourceReadbacks']==1 and supplement['oldManifestSha256']==SHA((folder/supplement['oldManifestFile']).read_bytes()) and supplement['sourceSha256']==SHA((folder/supplement['sourceFile']).read_bytes()),'Read-only mount supplementation changed or performed product operations');created=READ(folder/'created.json')['run'];run=created['id'];report=replay(folder);require(report['runId']==run,'Foreign replay');_verify_target_runtime(folder/'receipt','shibboleth',float(created['createdAt']))
 # Deployment followed evidence collection. The formal archive is pinned to its real capture;
 # no claim that the stricter Reader was running during the earlier protocol operation is made.
 _verify_suite_runtime(archive,run,float(READ(archive/'formal-lifecycle.json')['runtimeCapturedAtEpoch']),PINS)
 restored=READ(folder/'restoration.json');require(restored['restored'] is True and restored['errors']==[] and restored['original']==restored['final'],'Native settings not exactly restored');receipt=folder/'receipt'
 for kind in ['providers','audit']:require((receipt/('original-'+kind+'.xml')).read_bytes()==(receipt/('final-'+kind+'.xml')).read_bytes(),'Restoration bytes differ')
 ops=READ(folder/'operation-counts.json');require(ops['restored'] is True and ops['personOperations']==0 and ops['credentialPosts']==1 and ops['certificateTargetSubmissions']==6 and ops['ordinaryBaselineSubmissions']==1 and ops['protocolSubmissions']==7 and ops['sameAuthenticatedClient'] is True and ops['additionalLoginBlocked'] is True,'Shared-session operation counts differ');cumulative=READ(folder/'cumulative-operation-audit.json');require(cumulative['cumulative']==dict(productConfigurationWrites=12,metadataReloads=7,productRestarts=2,credentialPosts=1,protocolSubmissions=7,restorationWrites=3,personOperations=0,restored=True) and cumulative['credentialCountsAreSharedObservationNotAdditive'] is True,'Cumulative user/setting work differs');require(all(SHA((folder/name).read_bytes())==digest for name,digest in cumulative['sources'].items()),'Operation count source changed')
 path=archive/'evaluation-terminal-http-v1/result.json';result=READ(path);case=find_case(result,CASE);require(result['run']['id']==run and result['target']['metadata_digest']=='sha256:'+report['targetMetadataSha256'],'Formal Run/target differs');require(case['outcome']=='SATISFIED' and case['verdict']=='PASS' and case['mode']=='CONFIG' and case['attested'] is False and case['evidence_class']=='OPERATOR_ASSISTED' and case['reason_code']==report['outcome']['reasonCode'] and case['evidence']==report['outcome']['evidence'],'Formal central result differs');require(READ(archive/'full-run-originals/transcript.json')==READ(archive/'evaluation-terminal-http-v1/transcript-before.json')==READ(archive/'evaluation-terminal-http-v1/transcript.json'),'Formal evaluation changed transcript');baseline=folder/'initial-baseline';require(READ(baseline/'restoration.json')['restored'] is True and (baseline/'original-providers.xml').read_bytes()==(baseline/'final-providers.xml').read_bytes(),'Initial baseline settings not restored');counts=READ(baseline/'operation-counts-reconciled.json');require(counts['credentialPosts']==1 and counts['actualProtocolSubmissions']==counts['actualNativeProtocolGets']==1 and counts['actualNativeProtocolPosts']==0 and counts['productConfigurationWrites']==3 and counts['metadataReloads']==2 and counts['productRestarts']==counts['personOperations']==0,'Initial shared login operation counts differ');value=stored(folder);item=value['cases'][CASE];prior=READ(archive/'previous-stored-conclusion.json');old=prior['cases'][CASE];observed=dict(item['outcome']);details=dict(observed['details']);history=details.pop('previous_recorded_evidence_result',None);observed['details']=details;require(value['runId']==prior['runId']==run and set(value['cases'])==set(prior['cases'])=={CASE} and item['status']=='FINISHED' and item['verdict']=='PASS','Stored lifecycle differs')
 if old['outcome'] is None:require(history is None and item['revision']==old['revision']+1,'Unconfirmed initial result invented a prior outcome')
 elif old['outcome']['outcome']=='NOT_VERIFIED':require(history is not None and set(history)=={'revision','updated_at','outcome','not_verified_reason','reason_code','reason_message_key','evidence','details'} and item['revision']==old['revision']+1 and history['revision']==old['revision'] and history['updated_at']==old['updatedAt'] and all(history[a]==old['outcome'][b] for a,b in [('outcome','outcome'),('not_verified_reason','notVerifiedReason'),('reason_code','reasonCode'),('reason_message_key','reasonMessageKey'),('evidence','evidence'),('details','details')]),'Complete prior recorded result audit differs')
 else:require(old==item and history is None,'Unexpected conclusive prior result')
 require(observed==report['outcome'],'Stored full CaseOutcome differs');require(READ(archive/'outbox-after-formal.json')==READ(archive/'outbox-before-formal.json') and READ(archive/'outbox-after-formal.json')['count']==6,'Formal evaluation added or changed browser actions');diagnostic=READ(folder/'diagnostic-operation-audit.json');require(diagnostic['nativeProducerInvocations']==1 and diagnostic['nativeCompilerInvocations']==1 and diagnostic['nativeCertPathValidations']==5 and diagnostic['controlsAdopted'] is False and diagnostic['diagnosticIsProductFinding'] is False and diagnostic['productConfigurationWrites']==diagnostic['protocolSubmissions']==diagnostic['credentialPosts']==diagnostic['productRestarts']==0 and all(SHA((folder/name).read_bytes())==digest for name,digest in diagnostic['sources'].items()),'Diagnostic native operations or originals differ');return path,{CASE:case}

def live(folder):
 folder=pathlib.Path(folder);receipt=folder/'receipt';restored=READ(folder/'restoration.json')
 for path,digest in restored['original'].items():require(SHA(command(['docker','exec','samlscope-reference-shibboleth','cat',path]).stdout)==digest,'Live native settings differ from restored original')
 return dict(nativeSettingsRestored=True,productOperations=0)

if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('root',type=pathlib.Path);p.add_argument('--retain-replay',action='store_true');p.add_argument('--capture-stored',action='store_true');p.add_argument('--live',action='store_true');a=p.parse_args();folder=a.root/FOLDER
 if a.live:print(live(folder))
 elif a.retain_replay:print(replay(folder,True)['runId'],'actual production replay retained')
 elif a.capture_stored:print(stored(folder,True)['runId'],'stored original retained')
 else:print(verify(a.root))
