import test from 'node:test';
import assert from 'node:assert/strict';
import {propagationObservation, settlePending} from './slo_propagation_observation.mjs';

const sha = c => c.repeat(64);
function sample(trial = 'failure') {
  const participants = ['fail', 'remain', 'remain2'].map((suffix, i) => ({
    entityId: 'http://localhost:18080/p/plan_test/sp-' + suffix,
    sessionKeySha256: sha(String(i + 1))
  }));
  const resources = participants.flatMap((peer, i) => {
    const request = {id: '_request_' + i, sha256: sha(String(i + 4))};
    const failed = trial === 'failure' && i === 0;
    return [{origin: 'http://localhost:18280', path: '/idp/profile/PropagateLogout',
      status: 200, sessionKeySha256: peer.sessionKeySha256, generatedRequest: {...request}},
    {origin: 'http://localhost:18080', path: failed ? '/sp/slo-fail' : '/sp/slo',
      status: failed ? 500 : 200, sessionKeySha256: peer.sessionKeySha256, samlRequest: {...request}},
    ...(failed ? [] : [{origin: 'http://localhost:18280', path: '/idp/profile/SAML2/POST/SLO',
      status: 200, sessionKeySha256: peer.sessionKeySha256, nativeResult: 'Success'}])];
  });
  return {trial, initiatorCompleted: true, nativeFlowScopes: [sha('a')],
    nativePropagationContext: {flowScopeSha256: sha('a'), participants}, nativeResources: resources,
    nativeDom: {completed: false, participants: participants.map((peer, i) => ({entityId: peer.entityId,
      classes: ['logout', trial === 'failure' && i === 0 ? 'failure' : 'success']}))}};
}

test('all actual participant transports settle independently of initiator and native status heading', () => {
  const actual = propagationObservation(sample());
  assert.equal(actual.settled, true);
  assert.equal(actual.nativeDomCompleted, false);
  assert.equal(actual.affectsVerdict, false);
  assert.equal(propagationObservation(sample('all-success')).settled, true);
});

test('initiator completion or DOM classes alone never stand in for transports', () => {
  const r = sample(); r.nativeResources = [];
  assert.equal(propagationObservation(r).settled, false);
  r.nativeDom.completed = true;
  assert.equal(propagationObservation(r).settled, false);
});

test('every successful participant needs its native response', () => {
  const r = sample(); r.nativeResources = r.nativeResources.filter(row => !row.nativeResult);
  assert.equal(propagationObservation(r).reason, 'native-success-response-unavailable');
});

test('failure must be the actual HTTP500 with native failure DOM', () => {
  const r = sample(); r.nativeResources.find(row => row.status === 500).status = 400;
  assert.equal(propagationObservation(r).settled, false);
  const pending = sample(); pending.nativeDom.participants[0].classes = ['logout', 'pending'];
  assert.equal(propagationObservation(pending).settled, false);
});

test('different generated bytes or duplicate request IDs are ambiguous', () => {
  const r = sample(); r.nativeResources.find(row => row.samlRequest).samlRequest.sha256 = sha('b');
  assert.equal(propagationObservation(r).settled, false);
  const duplicate = sample();
  for (const row of duplicate.nativeResources) {
    if (row.generatedRequest) row.generatedRequest.id = '_same';
    if (row.samlRequest) row.samlRequest.id = '_same';
  }
  assert.equal(propagationObservation(duplicate).settled, false);
});

test('foreign session resource, other native flow, or duplicate peer cannot settle', () => {
  const r = sample(); r.nativeResources.push({sessionKeySha256: sha('c'), nativeResult: 'Success'});
  assert.equal(propagationObservation(r).reason, 'foreign-participant-resource');
  const foreign = sample(); foreign.nativeFlowScopes = [sha('b')];
  assert.equal(propagationObservation(foreign).settled, false);
  const duplicate = sample(); duplicate.nativePropagationContext.participants[2] = duplicate.nativePropagationContext.participants[1];
  assert.equal(propagationObservation(duplicate).settled, false);
});

test('unknown trial, result contradiction, and foreign-origin result fail closed', () => {
  const r = sample(); r.trial = 'unknown'; assert.equal(propagationObservation(r).settled, false);
  const mixed = sample(); mixed.nativeResources.find(row => row.nativeResult).nativeResult = 'Failure';
  assert.equal(propagationObservation(mixed).settled, false);
  const foreign = sample(); foreign.nativeResources.find(row => row.nativeResult).origin = 'https://elsewhere.invalid';
  assert.equal(propagationObservation(foreign).settled, false);
});

test('observer drain includes responses appended while the first promise settles', async () => {
  const observed = [], pending = [];
  pending.push(Promise.resolve().then(() => {
    observed.push(1); pending.push(Promise.resolve().then(() => observed.push(2)));
  }));
  const cursor = await settlePending(pending);
  assert.equal(cursor, 2); assert.deepEqual(observed, [1, 2]);
  pending.push(Promise.resolve().then(() => observed.push(3)));
  assert.equal(await settlePending(pending, cursor), 3);
  assert.deepEqual(observed, [1, 2, 3]);
});
