import type { Plan } from './api'

/** Metadata is generated by the server using the configured Test Peer base URL. */
export function idpRoundTripUrl(plan: Plan, runId: string): string {
  const url = new URL(`/p/${encodeURIComponent(plan.plan.id)}/start/m0-roundtrip`, plan.metadataUrl)
  url.searchParams.set('run', runId)
  return url.toString()
}
