import type { Plan, Run } from './api'

export function idpRoundTripReady(run: Run | undefined): boolean {
  const report = run?.context?.preflight as { checks?: Array<{ code: string; status: string }> } | undefined
  const checks = report?.checks
  return Array.isArray(checks)
    && checks.some(check => check.code === 'target_metadata' && check.status === 'PASS')
    && !checks.some(check => check.status === 'FAIL')
}

/** Metadata is generated by the server using the configured Test Peer base URL. */
export function idpRoundTripUrl(plan: Plan, runId: string): string {
  const url = new URL(`/p/${encodeURIComponent(plan.plan.id)}/start/m0-roundtrip`, plan.metadataUrl)
  url.searchParams.set('run', runId)
  return url.toString()
}
